### PR TITLE
fix: remaining locked amount error

### LINKED ISSUE #5413: Vested transfers. Add cliff transfers
https://novasama-technologies.atlassian.net/wiki/spaces/S/pages/190742529/Cliff+vesting

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Add locked amount tooltip.
Add error for small remaining locked amount left after start block unlock.

## Related Issues
Resolves https://github.com/novasamatech/nova-spektr/issues/5413

## Screenshots/Recordings
Screenshot 2026-01-14 at 1 32 12 PM
Screenshot 2026-01-14 at 1 33 36 PM

## Checklist

- [X] I have performed a self-review of my own code
- [X] I have tested the changes and verified the happy path works as expected
- [X] I have provided screenshot of the working feature (if applicable)
- [X] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [X] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/entities/vesting/ui/VestingFieldErrorRenderer.tsx [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+import { type ValidationIssue, VestingFieldError } from '../lib/types';
+
+type RenderVestingFieldErrorOptions = {
+  issue: ValidationIssue;
+  asset: Asset | null;
+  minVestedTransfer?: BN | null;
+  remainingLockedAmount?: string | null;
+};
+
+export function renderVestingFieldError({
```
Comment (johnthecat) [inline src/renderer/entities/vesting/ui/VestingFieldErrorRenderer.tsx]: why is in named as simple function?

Comment (savvyer) [reply src/renderer/entities/vesting/ui/VestingFieldErrorRenderer.tsx]: replaced it with two separate react component

File: src/renderer/features/vested-transfer/components/VestedTransferForm.tsx [hunk 2]
```diff
@@ -269,28 +276,35 @@ const ValidationsAlert = () => {
...
+
     const isMinVestedTransferError =
       issue.message === VestingFieldError.MIN_VESTED_TRANSFER && nonNullable(minVestedTransfer) && nonNullable(asset);
 
-    if (isMinVestedTransferError) {
+    const isCliffMinVestedTransferError =
+      issue.message === VestingFieldError.CLIFF_MIN_VESTED_TRANSFER &&
+      nonNullable(minVestedTransfer) &&
+      nonNullable(asset) &&
+      nonNullable(remainingLockedAmount);
```
Comment (aaa123eee) [inline src/renderer/features/vested-transfer/components/VestedTransferForm.tsx:292]: these don't seem to be related to the error itself, maybe they can be placed closer to the rendering

**Review by aaa123eee — APPROVED** [review]

**Review by cuteWarmFrog — APPROVED** [review]
