### PR TITLE
Display flex multisig on Staking page, fix markup BondNominate

### LINKED ISSUE #4746: Flexiblle multisig. Staking page - broken state
## Description

Broken state for Staking page on Flexible multisig

Image

## Test database
[spektr-database (20).json](https://github.com/user-attachments/files/22532070/spektr-database.20.json)

## Expected result

Shows pure proxied to interact with

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
Broken state for Staking page on Flexible multisig
Incorrect markup on BondNominate modal

## Related Issues
Closes #4746

## Changes Made
Flexible multisig accounts now appear on Staking page
Fixed BondNominate modal layout

## Screenshots/Recordings
Снимок экрана 2025-09-25 в 13 36 22
Снимок экрана 2025-09-25 в 13 37 19
Снимок экрана 2025-09-25 в 13 37 32

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/widgets/Staking/BondNominate/default/model/form-model.ts [hunk 1]
```diff
@@ -206,22 +206,27 @@ const $coreTx = combine(
...
+        return null;
+      }
+    }
 
     return transactionBuilder.buildBondNominate({
       chain: chain,
       asset: networkStore.asset,
       accountId: signatory.accountId,
       amount: amount,
-      destination: destination,
```
Comment (valentunn) [inline src/renderer/widgets/Staking/BondNominate/default/model/form-model.ts:224]: Could you please explain what was the issue here?
One thing that concerns me, is that we skip the `validateAddress(destination )` check if destination is `RESTAKE`. However, we then do `destination: toAddress(destination!)`. It looks like this line may break if `destination` is invalid?

Comment (Yanaty) [reply src/renderer/widgets/Staking/BondNominate/default/model/form-model.ts:224]: Fixed a little bit.
The issue was that `nullable(destination)` check prevented transaction creation when RESTAKE was selected (since no address is needed for RESTAKE).

Fixed by adding destination type condition:
- RESTAKE: send empty string to destination (becomes `payee: "Staked"`)
- Non-RESTAKE: validate address and pass it to destination

Comment (valentunn) [reply src/renderer/widgets/Staking/BondNominate/default/model/form-model.ts:224]: Maybe we could change `destination` from `string` to 
```ts
type Staked = "Staked"
type Payout = { destination: Address }
type RewardDestination = Staked | Payout
```
?
This way we would be very explicit about what we are doing and avoid implicitly using `' '` to indicate that it is `Staked`

File: src/renderer/widgets/Staking/BondNominate/default/ui/BondNominate.tsx [hunk 2]
```diff
@@ -51,7 +51,7 @@ export const BondNominate = () => {
   return (
     <Modal
       isOpen={isModalOpen}
-      size="md"
+      size="fit"
```
Comment (johnthecat) [inline src/renderer/widgets/Staking/BondNominate/default/ui/BondNominate.tsx]: Please use dynamic value based on step, only step with validators should have 'fit' size, overwise modal will explode if any validation error appears

Comment (Yanaty) [reply src/renderer/widgets/Staking/BondNominate/default/ui/BondNominate.tsx]: fixed

File: src/renderer/widgets/Staking/BondNominate/default/model/form-model.ts (hunk 1 above)
Comment (Yanaty) [reply src/renderer/widgets/Staking/BondNominate/default/model/form-model.ts:224]: good idea, done

File: src/renderer/entities/transaction/lib/transactionBuilder.ts [hunk 3]
```diff
@@ -141,7 +145,7 @@ function buildBond({ chain, asset, accountId, destination, amount }: BondParams)
     args: {
       value: formatAmount(amount, asset.precision),
       controller: accountId,
-      payee: destination === '' ? 'Staked' : { Account: destination },
+      payee: destination === 'Staked' ? destination : { Account: destination.destination },
```
Comment (valentunn) [inline src/renderer/entities/transaction/lib/transactionBuilder.ts]: There seems to be an error: when it is `Staked`, we should use `Staked` in `payee` (you can see that from the old logic) Otherwise there will be an encoding error

Comment (Yanaty) [reply src/renderer/entities/transaction/lib/transactionBuilder.ts]: done

**Review by valentunn — APPROVED** [review]
