### PR TITLE
fix: proxy with multisig operation details

### LINKED ISSUE #3055: Proxy. Multisig operations via pure proxy parses wrong
## Description

operation proxy(batch_all) parses wrong:

Image

https://westend.subscan.io/multisig_extrinsic/24529359-2?call_hash=0xdd5ae87b219737bb6d4346e40ad46d4a158c3338cbc296347245264d63dc3e27

## Environment
https://github.com/novasamatech/nova-spektr/commit/f81dc81edb3ccfbe598fbd73b86fe345c04db62c

### PR DESCRIPTION
**Pull request by sokolova-an**
Closes https://github.com/novasamatech/nova-spektr/issues/3055

### CODE REVIEW

File: src/renderer/features/governance-operation-details/governance-operation-details-model.tsx [hunk 1]
```diff
@@ -12,13 +12,37 @@ export const governanceOperationDetailFeature = createFeature({
...
+    const transaction = getTransactionFromMultisigTx(operation);
+
+    if (
+      transaction?.type &&
+      [TransactionType.UNLOCK, TransactionType.VOTE, TransactionType.REVOTE, TransactionType.REMOVE_VOTE].includes(
+        transaction.type,
+      )
+    ) {
+      return <GovernanceVoteDetails operation={operation} />;
+    }
```
Comment (Asmadek) [inline src/renderer/features/governance-operation-details/governance-operation-details-model.tsx:25]: In case when we check tx, maybe delete duplication from GovernanceVoteDetails component?

File: src/renderer/features/governance-operation-details/governance-operation-details-model.tsx [hunk 2]
```diff
@@ -12,13 +12,37 @@ export const governanceOperationDetailFeature = createFeature({
...
-  order: 1,
+  render: ({ operation }) => {
+    const transaction = getTransactionFromMultisigTx(operation);
+
+    if (
+      transaction?.type &&
+      [TransactionType.DELEGATE, TransactionType.UNDELEGATE, TransactionType.EDIT_DELEGATION].includes(transaction.type)
+    ) {
+      return <GovernanceDelegateDetails operation={operation} />;
+    }
```
Comment (Asmadek) [inline src/renderer/features/governance-operation-details/governance-operation-details-model.tsx:41]: Same here

**Review by Asmadek — APPROVED** [review]
