### PR TITLE
fix: order events by duration

### LINKED ISSUE #3786: Fellowship. All events. Oldest sorting does not work
## Description

When user try to sort all events on Fellowship by "Oldest" nothing happened

## Actual Behavior

https://github.com/user-attachments/assets/c93be33b-f67c-4bea-b4fa-05fff0d8c318

## Environment
DEV

### PR DESCRIPTION
**Pull request by aaa123eee**
## Description

Fix sort by duration

## Related Issues

closes #3786

## Changes Made

- keep fields extraction on higher level to reduce recalc & for sorting purposes

## Screenshots/Recordings

image

### CODE REVIEW

File: src/renderer/features/fellowship-activity-feed/components/ActivityList.tsx [hunk 1]
```diff
@@ -1,16 +1,39 @@
...
 
+import { useI18n } from '@/shared/i18n';
+import { identityService } from '@/domains/network';
+import { identityModel } from '../model/identity';
 import { activityFeed } from '../model/list';
 
 import { ActivityListView } from './ActivityListView';
+import { getDescription } from './utils';
+
+const now = Date.now();
```
Comment (savvyer) [inline src/renderer/features/fellowship-activity-feed/components/ActivityList.tsx]: Are you sure about this?

Date will be evaluated once at module load time. It won’t reflect the current time on re-renders or user interactions.

`now` could have Date from yesterday or week ago when the user first time opened the app

File: src/renderer/features/fellowship-activity-feed/components/ActivityModal.tsx [hunk 2]
```diff
@@ -23,6 +23,8 @@ const orderVariants: Record<OrderKey, { field: string; direction: 'asc' | 'desc'
   'name-desc': { field: 'name', direction: 'desc' },
 };
 
+const now = Date.now();
```
Comment (savvyer) [inline src/renderer/features/fellowship-activity-feed/components/ActivityModal.tsx]: Same question here

File: src/renderer/features/fellowship-activity-feed/components/ActivityList.tsx (hunk 1 above)
Comment (aaa123eee) [reply src/renderer/features/fellowship-activity-feed/components/ActivityList.tsx]: copy pasted from another component

I put it to the component scope

Comment (aaa123eee) [reply src/renderer/features/fellowship-activity-feed/components/ActivityList.tsx]: I got it now

We usually use the Countdown component so I relied on that, then it would be not necessary because of countdown logic, but here is just Duration. TY!

**Review by johnthecat — APPROVED** [review]

**Review by sokolova-an — APPROVED** [review]
