### PR TITLE
fix: timelineValue in the Retention widget

### LINKED ISSUE #5196: Fellowship. Retention timeline shows working period as completed while it's still ongoing
## Description

In the Fellowship retention timeline, the first part of the retention cycle (working period) is visually marked as completed, even though the tooltip for this segment shows a different completion date that has not yet been reached.

As a result, the timeline suggests that the working period is already over, while the underlying data indicates it is still ongoing.

Can be reproduced on the account: 12HWjfYxi7xt7EvpTxUis7JoNWF7YCqa19JXmuiwizfwJZY2

Image

## Time goes by:

Image

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
In the Fellowship retention timeline, the first part of the retention cycle (working period) is visually marked as completed, even though the tooltip for this segment shows a different completion date that has not yet been reached.

As a result, the timeline suggests that the working period is already over, while the underlying data indicates it is still ongoing.

## Related Issues
Closes #5196

## Changes Made
Fixed timelineValue calculation for the retention widget

## Screenshots/Recordings
Снимок экрана 2025-12-11 в 13 37 10
Снимок экрана 2025-12-11 в 13 36 30

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [ ] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [ ] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx [hunk 1]
```diff
@@ -369,21 +372,45 @@ const useRetentionData = () => {
     ];
   }, [t, retentionPeriodDates, fromDateFormatted, toDateFormatted]);
 
-  // Calculate timeline position directly from elapsed time
   const timelineValue = useMemo(() => {
-    if (nullable(retentionPeriodDates) || nullable(retentionPeriodDates.from) || nullable(retentionPeriodDates.to))
-      return 0;
+    if (nullable(api) || nullable(retentionPeriod) || nullable(currentBlock)) return 0;
```
Comment (aaa123eee) [inline src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx]: maybe better null than fake 0 value?

**Review by aaa123eee — DISMISSED** [review]

File: src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx [hunk 2]
```diff
@@ -369,21 +372,45 @@ const useRetentionData = () => {
...
 
-    const now = new Date();
-    const totalDuration = differenceInMilliseconds(retentionPeriodDates.to, retentionPeriodDates.from);
+    const blockTimeMs = getExpectedBlockTime(api).toNumber();
```
Comment (johnthecat) [inline src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx]: plz use `useBlockTime` hook instead

File: src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx (hunk 1 above)
Comment (Yanaty) [reply src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx]: Better keep a number, because the component only accepts a number.

File: src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx (hunk 2 above)
Comment (Yanaty) [reply src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx]: fixed

**Review by aaa123eee — APPROVED** [review]
