### PR TITLE
Fix/flexible multisig notify

### LINKED ISSUE #5391: Notifications. Flex multisig notifications are decoded as regular multisig “Proxy: Proxy”
## Description

Notifications about flex multisig operations are currently parsed as regular multisig operations, but displayed as a generic wrapper: “Proxy: Proxy”.
Because of this, the operation in the notification is not recognized as a flex multisig operation, is not linked to the corresponding flex multisig wallet, and does not show the actual underlying action (e.g., Transfer) in the operations list.

Notifications about flex multisig operations should be parsed as flex multisig operations, resolved to their underlying call, and shown as proper operation types.

[spektr-database (70).json](https://github.com/user-attachments/files/24231367/spektr-database.70.json)

## Steps to Reproduce

1. Trigger any flex multisig operation that generates a notification (e.g., a transfer via flex multisig).
2. Open the Notifications list.
3. Locate the notification related to that flex multisig operation.
4. Check the action/type shown on the notification card.

## Expected Behavior

- The notification should be recognized as a flex multisig operation notification.
- The action in the notification should reflect the unwrapped underlying call (e.g.: “Transfer …”)
- Notification should not be labeled as a generic “Proxy: Proxy call” unless the underlying call is truly unknown.

## Actual Behavior

- Flex multisig operation notifications are displayed as regular multisig notifications.
- The action shown is “Proxy: Proxy”, hiding the real operation type.

## Screenshots

Image

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Smart logic for guessing whether it's a flexible trasnaction or not

## Related Issues
Closes #5391 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/entities/multisig-accounts/api/multisigsService.ts [hunk 1]
```diff
@@ -118,3 +120,26 @@ async function findFlexibleMultisigs(
...
+  if (isProxyTx) return true;
+
+  // Nova Wallet wraps proxy calls inside utility.batchAll transactions instead of sending direct proxy.proxy calls.
+  const transactions = operation.transaction?.args.transactions;
+
+  return (
+    operation.method === 'batchAll' &&
+    operation.section === 'utility' &&
+    Array.isArray(transactions) &&
+    transactions.every((t: DecodedTransaction) => flexibleMultisigAccountId === toAccountId(t.args.real))
```
Comment (johnthecat) [inline src/renderer/entities/multisig-accounts/api/multisigsService.ts]: will crash in `toAccountId(t.args.real)` if t is not proxy.proxy call

**Review by johnthecat — APPROVED** [review]

**Review by kalininilya — APPROVED** [review]
