### PR TITLE
Fix: Multishard migration

### LINKED ISSUE #3541: Polkadot Vault. Multiple root wallet to many multishard wallets perform wrong
## Description

When user with multi root wallet migrate to many multishard wallets has some collisions.

## Steps to Reproduce

1. Clean the app
2. `git checkout release/1.14.5`
3. Build app
4. Import database
5. Update app to actual dev
6. Build app
7. Run and waiting for migrations

## Expected Behavior

All wallets with a few roots were split on different single root multishards

## Actual Behavior

Error when startup the app

## Environment
https://github.com/novasamatech/nova-spektr/commit/f62cd23c1f3f280c5dbb83b7a40dd807bf3ca80f

Test database before migration:
- [before_migration.json](https://github.com/user-attachments/files/19683369/before_migration.json)

Image

### PR DESCRIPTION
**Pull request by tuul-wq**
## Related Issues
closes #3541 

## Changes Made
- Updated `migration-6.ts`
- Now it better handles pre-migration-5 multishards
- Increased readability
- Updated `Account` types, removed `BaseAccount` from PV
- Updated mocks accounts factories, now can be more parameterized than before
- **Tests !!!** (can be used in further migrations, hope they'll never happen 😄)

### CODE REVIEW

File: src/renderer/entities/proxy/lib/__tests__/mocks/proxy-mocks.ts [hunk 1]
```diff
@@ -44,7 +38,7 @@ const wallets: Wallet[] = [
         accountId: TEST_ACCOUNTS[0],
         signingType: SigningType.MULTISIG,
         cryptoType: CryptoType.SR25519,
-      } satisfies VaultBaseAccount,
+      } satisfies BaseAccount,
```
Comment (tuul-wq) [inline src/renderer/entities/proxy/lib/__tests__/mocks/proxy-mocks.ts]: PV contains only 2 types of accounts - `VaultChainAccount` & `VaultShardAccount`
`BaseAccount` appears only in WO & SingleShard

File: src/renderer/features/wallets/RenameWallet/model/__tests__/mocks/wallet-mock.ts [hunk 2]
```diff
@@ -1,10 +1,10 @@
-import { AccountType, CryptoType, SigningType, type VaultBaseAccount, WalletType } from '@/shared/core';
+import { AccountType, type BaseAccount, CryptoType, SigningType, WalletType } from '@/shared/core';
 
 const wallet1 = {
   id: 1,
   accounts: [
     { walletId: 1, cryptoType: CryptoType.SR25519, type: 'universal', accountType: AccountType.BASE },
-  ] as VaultBaseAccount[],
```
Comment (aaa123eee) [inline src/renderer/features/wallets/RenameWallet/model/__tests__/mocks/wallet-mock.ts:7]: maybe we can use `satisfies`?

File: src/renderer/features/wallets/RenameWallet/model/__tests__/mocks/wallet-mock.ts [hunk 3]
```diff
@@ -15,7 +15,7 @@ const wallet2 = {
   id: 2,
   accounts: [
     { walletId: 2, cryptoType: CryptoType.SR25519, type: 'universal', accountType: AccountType.BASE },
-  ] as VaultBaseAccount[],
+  ] as BaseAccount[],
```
Comment (aaa123eee) [inline src/renderer/features/wallets/RenameWallet/model/__tests__/mocks/wallet-mock.ts]: maybe we can use `satisfies`?

File: src/renderer/features/wallets/RenameWallet/model/__tests__/rename-wallet-model.test.ts [hunk 4]
```diff
@@ -42,7 +42,7 @@ describe('entities/wallet/model/wallet-model', () => {
       name: newName,
       accounts: [
         { cryptoType: 0, name: 'New wallet name', accountType: AccountType.BASE, type: 'universal', walletId: 1 },
-      ] as VaultBaseAccount[],
+      ] as BaseAccount[],
```
Comment (aaa123eee) [inline src/renderer/features/wallets/RenameWallet/model/__tests__/rename-wallet-model.test.ts]: maybe we can use `satisfies`?

File: src/renderer/shared/api/storage/migration/migration-6.ts [hunk 5]
```diff
@@ -1,99 +1,188 @@
...
+      toRegroup.set(accountId, chainAccounts);
+    } else {
+      toRegroup.set(accountId, {
+        name: baseAccounts[0].name ?? 'Base Account',
+        accountId: baseAccounts[0].accountId,
+        cryptoType: baseAccounts[0].cryptoType,
+        type: 'universal',
+        accountType: AccountType.BASE,
+        signingType: SigningType.POLKADOT_VAULT,
+      } as BaseAccount);
```
Comment (aaa123eee) [inline src/renderer/shared/api/storage/migration/migration-6.ts]: same

File: src/renderer/shared/api/storage/migration/migration-6.ts [hunk 6]
```diff
@@ -1,99 +1,188 @@
...
+  for (const [accountId, account] of toWalletDraft.entries()) {
+    // Polkadot Vault
+    if (Array.isArray(toRegroup.get(accountId))) {
+      toWallet.set(accountId, {
+        name: account.name ?? 'Polkadot Vault',
+        type: WalletType.POLKADOT_VAULT,
+        rootAccountId: account.accountId,
+        signingType: SigningType.POLKADOT_VAULT,
+        isActive: false,
+      } as PolkadotVaultWallet);
```
Comment (aaa123eee) [inline src/renderer/shared/api/storage/migration/migration-6.ts]: and same 😂

**Review by aaa123eee — APPROVED** [review]
I'd suggest to use `satisfies` as much as possible for type safety

File: src/renderer/entities/wallet/lib/account-utils.ts [hunk 7]
```diff
@@ -70,7 +72,7 @@ function isWatchOnlyAccount(account: Partial<AnyAccount>): account is WatchOnlyA
   );
 }
 
-function isVaultBaseAccount(account: Partial<AnyAccount>): account is VaultBaseAccount {
+function isBaseAccount(account: Partial<AnyAccount>): account is BaseAccount {
```
Comment (johnthecat) [inline src/renderer/entities/wallet/lib/account-utils.ts]: Why did you changed name of interface to `BaseAccount`? It exists only in PV

**Review by johnthecat — CHANGES_REQUESTED** [review]

File: src/renderer/entities/wallet/lib/account-utils.ts (hunk 7 above)
Comment (tuul-wq) [reply src/renderer/entities/wallet/lib/account-utils.ts]: > PV contains only 2 types of accounts - VaultChainAccount & VaultShardAccount
BaseAccount appears only in WO & SingleShard

So there is no point in saving `Vault` prefix

Comment (johnthecat) [reply src/renderer/entities/wallet/lib/account-utils.ts]: Without Vault prefix it harder to get context of this account. Also there is a huge affected area because of this small change. Let's roll it back

File: .github/workflows/install-pnpm/action.yaml [hunk 8]
```diff
@@ -8,12 +8,8 @@ runs:
...
         run_install: false
 
-    - name: 🤞 Install Node.js
+    - name: 🤞 Use Node.js
       uses: actions/setup-node@v4
       with:
         cache: pnpm
         node-version: 21
-
-    - name: ⚙️ Install dependencies
```
Comment (johnthecat) [inline .github/workflows/install-pnpm/action.yaml:17]: Why do you remove dependency install from this action. If you need to install pnpm separately - create new action "install pnpm" and reuse it here

**Review by johnthecat — CHANGES_REQUESTED** [review]

**Review by johnthecat — APPROVED** [review]
