### PR TITLE
fix: filter chains for add proxy by accounts

### LINKED ISSUE #1612: Regular proxy creation. EVM networks are available for wallet without EVM accounts
## Description
For "Add delegated authority (proxy)" is available EVM networks for wallet without EVM accounts

## Steps to Reproduce

1. Create wallet without EVM accounts
2. Go to Wallet details
3. Select Delegated authorities
4. Select any EVM network

## Expected Behavior
User can't select EVM networks for wallets without EVM accounts

## Actual Behavior
User can select, error does not show clear info what is wrong

## Environment
https://github.com/novasamatech/nova-spektr/commit/7275d804570096a1947b02062b51524e5daa6066

## Screenshots
Screenshot 2024-04-01 at 12 25 39
Screenshot 2024-04-01 at 12 25 26

Not clear error what is wrong:
Screenshot 2024-04-01 at 12 30 43

### PR DESCRIPTION
**Pull request by Asmadek**
closes #1612

### CODE REVIEW

File: src/renderer/widgets/AddProxyModal/model/form-model.ts [hunk 1]
```diff
@@ -271,9 +271,24 @@ const $proxyWallet = combine(
   { skipVoid: false },
 );
 
-const $proxyChains = combine(networkModel.$chains, (chains) => {
-  return Object.values(chains).filter(proxiesUtils.isRegularProxy);
-});
+const $proxyChains = combine(
+  { chains: networkModel.$chains, accounts: walletModel.$accounts, wallet: walletSelectModel.$walletForDetails },
```
Comment (tuul-wq) [inline src/renderer/widgets/AddProxyModal/model/form-model.ts]: For readability
```suggestion
  {
    chains: networkModel.$chains,
    accounts: walletModel.$accounts,
    wallet: walletSelectModel.$walletForDetails,
  },
```

File: src/renderer/widgets/AddPureProxiedModal/model/form-model.ts [hunk 2]
```diff
@@ -213,9 +213,24 @@ const $proxyWallet = combine(
   { skipVoid: false },
 );
 
-const $proxyChains = combine(networkModel.$chains, (chains) => {
-  return Object.values(chains).filter(proxiesUtils.isRegularProxy);
-});
+const $proxyChains = combine(
+  { chains: networkModel.$chains, accounts: walletModel.$accounts, wallet: walletSelectModel.$walletForDetails },
```
Comment (tuul-wq) [inline src/renderer/widgets/AddPureProxiedModal/model/form-model.ts]: Same comment here

**Review by tuul-wq — APPROVED** [review]
