### PR TITLE
fix: add-proxy modal step state

### LINKED ISSUE #1683: Add delegated authority. Widget state may be broken
## Description
When user create "Add delegated authority operation" the state of widget may be broken

<details>
  <summary>🍿Example🍿</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/a0658994-9774-4b1a-bb62-369d52d7a801

</details>

## Steps to Reproduce

1. Add a few delegated authorities one by one

## Actual Behavior
Regular proxy widget is stuck and can't be open

## Environment
https://github.com/novasamatech/nova-spektr/commit/683af3e412c17bea7781600b5882375b01b7f632

### PR DESCRIPTION
**Pull request by sokolova-an**
Add step state on flowClosed

### CODE REVIEW

**Review by Asmadek — APPROVED** [review]

File: src/renderer/widgets/AddProxyModal/model/add-proxy-model.ts [hunk 1]
```diff
@@ -156,6 +156,12 @@ sample({
   target: stepChanged,
 });
 
+sample({
+  clock: flowClosed,
+  fn: () => Step.NONE,
+  target: stepChanged,
+});
```
Comment (tuul-wq) [inline src/renderer/widgets/AddProxyModal/model/add-proxy-model.ts]:
```suggestion
sample({
  clock: [flowFinished, flowClosed],
  fn: () => Step.NONE,
  target: stepChanged,
});
```

**Review by tuul-wq — APPROVED** [review]
Approved with comment

**Review by Asmadek — APPROVED** [review]
