### PR TITLE
Fix: Identities

### LINKED ISSUE #1707: Validator list is not displayed on Kusama
Validator list is not displayed on Kusama.

The scenario:
1. Open the Staking page
2. Select nominator
3. Click "Show Validators"

Expected result:
1. The list of selected validator is shown

Actual result:
1. Empty list is shown

Reproduced for start staking, change validators flows.

Image

### PR DESCRIPTION
**Pull request by tuul-wq**
- Fixed Identities for runtime > 1.4.0
- Increased performance of validators mapping

closes #1707

### CODE REVIEW

File: src/renderer/entities/staking/api/validatorsService.ts [hunk 1]
```diff
@@ -111,12 +113,16 @@ async function getValidatorsStake(api: ApiPromise, era: EraIndex): Promise<Recor
...
-  return data.reduce((acc, [storageKey, type]) => {
+  return data.reduce<ValidatorMap>((acc, [storageKey, type]) => {
     const address = storageKey.args[1].toString();
-    const commission = parseFloat(type.commission.toHuman() as string);
-    const payload = { address, commission, blocked: type.blocked.toHuman() };
 
-    return { ...acc, [address]: payload };
+    acc[address] = {
+      address,
+      commission: parseFloat(type.commission.toHuman() as string),
```
Comment (Asmadek) [inline src/renderer/entities/staking/api/validatorsService.ts:121]: why not use `toString` and not use `as string`?

File: src/renderer/entities/staking/api/validatorsService.ts [hunk 2]
```diff
@@ -222,22 +243,24 @@ async function getParentIdentities(
...
+    const { display, web, email, twitter } = data.info; // { data also includes: judgements, deposit }
 
-    const payload: Identity = {
+    acc[sub] = {
       subName,
       email: email.isRaw ? u8aToString(email.asRaw) : email.value.toString(),
-      riot: riot.isRaw ? u8aToString(riot.asRaw) : riot.value.toString(),
       twitter: twitter.isRaw ? u8aToString(twitter.asRaw) : twitter.value.toString(),
       website: web.isRaw ? u8aToString(web.asRaw) : web.value.toString(),
+      // riot: riot.isRaw ? u8aToString(riot.asRaw) : riot.value.toString(),
```
Comment (Asmadek) [inline src/renderer/entities/staking/api/validatorsService.ts]: what reason to comment this code and not to delete ?

File: src/renderer/entities/staking/api/validatorsService.ts [hunk 3]
```diff
@@ -307,13 +330,14 @@ async function getSlashingSpans(
...
   }
 
-  return slashingSpans.reduce((acc, span, index) => {
+  return slashingSpans.reduce<Record<Address, { slashed: boolean }>>((acc, span, index) => {
     let validatorIsSlashed = false;
-    if (!span.isNone) {
-      const { lastNonzeroSlash } = span.unwrap();
-      validatorIsSlashed = era - lastNonzeroSlash.toNumber() < slashDeferDuration;
+    if (span.isSome) {
+      validatorIsSlashed = era - span.unwrap().lastNonzeroSlash.toNumber() < slashDeferDuration;
```
Comment (Asmadek) [inline src/renderer/entities/staking/api/validatorsService.ts:335]: what do you think to use BN here?

File: src/renderer/shared/core/types/identity.ts [hunk 4]
```diff
@@ -5,8 +5,8 @@ export type Identity = {
   email: string;
   website: string;
   twitter: string;
-  riot: string;
   parent: ParentIdentity;
+  // riot: string;
```
Comment (Asmadek) [inline src/renderer/shared/core/types/identity.ts]: same comment as for another commented code

**Review by Asmadek — APPROVED** [review]

**Review by sokolova-an — APPROVED** [review]

File: src/renderer/entities/staking/api/validatorsService.ts (hunk 2 above)
Comment (tuul-wq) [reply src/renderer/entities/staking/api/validatorsService.ts]: Hm, I agree, we can safely remove it, because we don't show riot/matrix anyway

Comment (Tbaut) [reply src/renderer/entities/staking/api/validatorsService.ts]: why not keep it, and actually show it? (I know it's not here, could be in another PR) I find it useful at times for actual real time messaging, rather than the other platforms.

Comment (tuul-wq) [reply src/renderer/entities/staking/api/validatorsService.ts]: > why not keep it, and actually show it? (I know it's not here, could be in another PR) I find it useful at times for actual real time messaging, rather than the other platforms.

In current design we don't show `riot/matrix` and don't have any plans to do so
