### PR TITLE
fix: delegation modal height 

### LINKED ISSUE #2117: Governance. Delegation. Track page does not fit the frame
## Expected Behavior

image

## Actual Behavior

Screenshot 2024-08-16 at 13 19 39

## Environment
https://github.com/novasamatech/nova-spektr/commit/ddfa3266133bcb8670bfd51587f837e691145df4

### LINKED ISSUE #2118: Governance. Delegation. Crash when try to open delegator card.
## Description

Crash when open delegator card.

https://github.com/novasamatech/nova-spektr/blob/ddfa3266133bcb8670bfd51587f837e691145df4/src/renderer/widgets/DelegateDetails/ui/YourDelegations.tsx#L74

https://github.com/user-attachments/assets/fb6ea073-9df8-4b31-98a9-aa77b013ebd3

## Steps to Reproduce

1. Delegate
2. Remove delegation
3. Go to Governance page
4. Click "Add delegation"
5. Open delegator card

## Expected Behavior
Show add delegation button

## Actual Behavior
Crash with TypeError: Cannot read properties of undefined (reading 'balance')

## Environment
https://github.com/novasamatech/nova-spektr/commit/c8a8e989a58c4798deb402b449e7f8cc50721236

### PR DESCRIPTION
**Pull request by Asmadek**
* fix: delegation modal height
* fix: calculate active accounts on active delegations for your delegations

### CODE REVIEW

File: src/renderer/widgets/DelegateDetails/model/delegate-details-model.ts [hunk 1]
```diff
@@ -29,10 +29,8 @@ const $activeTracks = votingAggregate.$activeWalletVotes.map((activeVotes) => {
   return activeTracks;
 });
 
-const $activeAccounts = votingAggregate.$activeWalletVotes.map((activeVotes) => {
-  return Object.entries(activeVotes)
-    .filter(([_, delegations]) => Object.keys(delegations).length > 0)
-    .map(([address]) => address);
+const $activeAccounts = delegationAggregate.$activeDelegations.map((activeVotes) => {
+  return Object.entries(activeVotes).map(([address]) => address);
```
Comment (johnthecat) [inline src/renderer/widgets/DelegateDetails/model/delegate-details-model.ts]:
```suggestion
  return Object.keys(activeVotes);
```

File: src/renderer/widgets/DelegateDetails/ui/YourDelegation.tsx [hunk 2]
```diff
@@ -61,10 +61,10 @@ export const YourDelegation = () => {
                   components={{
                     votes: (
                       <AssetBalance
-                        value={activeDelegations[activeAccounts[0]]?.balance
+                        value={activeDelegations[activeAccounts[0]].balance
```
Comment (johnthecat) [inline src/renderer/widgets/DelegateDetails/ui/YourDelegation.tsx]: Looks unsafe
You need to check if active account and active delegation exists before getting balance

File: src/renderer/widgets/DelegateDetails/ui/YourDelegation.tsx [hunk 3]
```diff
@@ -61,10 +61,10 @@ export const YourDelegation = () => {
...
                           .mul(
                             new BN(
-                              votingService.getConvictionMultiplier(activeDelegations[activeAccounts[0]]?.conviction),
+                              votingService.getConvictionMultiplier(activeDelegations[activeAccounts[0]].conviction),
```
Comment (johnthecat) [inline src/renderer/widgets/DelegateDetails/ui/YourDelegation.tsx]: Looks unsafe

File: src/renderer/widgets/DelegateDetails/ui/YourDelegations.tsx [hunk 4]
```diff
@@ -26,9 +26,9 @@ export const YourDelegations = () => {
   return (
     <BaseModal
       closeButton
-      headerClass="px-5 py-3"
-      panelClass="w-[784px] h-[672px] bg-white"
-      contentClass="min-h-0 h-full w-full bg-white py-4 flex flex-col gap-6 overflow-y-auto scrollbar-stable"
+      headerClass={cnTw('px-5 py-3')}
```
Comment (johnthecat) [inline src/renderer/widgets/DelegateDetails/ui/YourDelegations.tsx]: Why do you add `cnTw` into static classNames?

File: src/renderer/widgets/DelegateDetails/ui/YourDelegations.tsx [hunk 5]
```diff
@@ -71,7 +77,7 @@ export const YourDelegations = () => {
                     components={{
                       votes: (
                         <AssetBalance
-                          value={new BN(activeDelegations[address].balance).mul(
+                          value={activeDelegations[address].balance.mul(
```
Comment (johnthecat) [inline src/renderer/widgets/DelegateDetails/ui/YourDelegations.tsx]: Looks unsafe

File: src/renderer/widgets/DelegateModal/ui/DelegateForm.tsx [hunk 6]
```diff
@@ -48,9 +48,9 @@ export const DelegateForm = ({ isOpen, onClose, onGoBack }: Props) => {
   return (
     <BaseModal
       closeButton
-      headerClass="px-5 py-3"
-      panelClass="flex flex-col w-modal h-[738px] gap-4 bg-white"
-      contentClass="min-h-0 h-full w-full bg-card-background py-4"
+      headerClass={cnTw('px-5 py-3')}
```
Comment (johnthecat) [inline src/renderer/widgets/DelegateModal/ui/DelegateForm.tsx]: Why do you add cnTw into static classNames?

File: src/renderer/widgets/DelegateModal/ui/SelectTracksForm.tsx [hunk 7]
```diff
@@ -25,9 +25,9 @@ export const SelectTrackForm = ({ isOpen, onClose }: Props) => {
   return (
     <BaseModal
       closeButton
-      headerClass="px-5 py-3"
-      panelClass="w-[896px] h-[738px] bg-white"
-      contentClass="min-h-0 h-full w-full bg-card-background py-4 flex flex-col gap-6"
+      headerClass={cnTw('px-5 py-3')}
```
Comment (johnthecat) [inline src/renderer/widgets/DelegateModal/ui/SelectTracksForm.tsx]: Why do you add cnTw into static classNames?

**Review by johnthecat — CHANGES_REQUESTED** [review]

**Review by johnthecat — APPROVED** [review]
