### PR TITLE
Fix: show proposer address if no identity is found

### LINKED ISSUE #2055: Governance. Referendum data. Proposer without identity is missed.
## Description
Proposer is not shown in referenda details if he has no identity

Screenshot 2024-08-09 at 09 46 38

## Steps to Reproduce

1. Go to Governance
2. Find 1061 referenda
3. Open it

## Expected Behavior
As a proposer is shown address, because identity is not available

## Actual Behavior
Empty place for proposer

## Environment
https://github.com/novasamatech/nova-spektr/commit/769e2c447f837eea9cdc8d946a1bd416cacb1fc2

### PR DESCRIPTION
**Pull request by Tbaut**
closes #2055 
image

### CODE REVIEW

File: src/renderer/features/governance/components/ReferendumDetails/Timeline.tsx [hunk 1]
```diff
@@ -48,7 +48,7 @@ export const Timeline = ({ referendumId }: Props) => {
 
       {!isLoading &&
         timeline.map((status) => (
-          <div key={status.date.toLocaleString()} className="flex items-center justify-between">
+          <div key={`${status.status}-${status.date.toLocaleString()}`} className="flex items-center justify-between">
```
Comment (Tbaut) [inline src/renderer/features/governance/components/ReferendumDetails/Timeline.tsx:51]: I figured that 2 statuses were actually posted at the exact same time (the starting ones) resulting in an error in the console. Since it's a small one I added the fix in this PR.

**Review by pgolovkin — APPROVED** [review]

File: src/renderer/features/governance/components/ReferendumDetails/ProposerName.tsx [hunk 2]
```diff
@@ -30,21 +31,26 @@ export const ProposerName = ({ referendum }: Props) => {
...
-
-  const proposerName = proposer ? (
+  const proposerName = proposer?.parent ? (
     <AccountAddress
       addressFont="text-text-secondary"
       size={16}
       address={proposer.parent.address}
       name={proposer.parent.name || proposer.email || proposer.twitter || proposer.parent.address}
     />
+  ) : (referendum as OngoingReferendum)?.submissionDeposit?.who ? (
```
Comment (johnthecat) [inline src/renderer/features/governance/components/ReferendumDetails/ProposerName.tsx]: let's check if it's really ongoing referendum by `referendumService.isOngoing`

File: src/renderer/features/governance/components/ReferendumDetails/ProposerName.tsx [hunk 3]
```diff
@@ -30,21 +31,26 @@ export const ProposerName = ({ referendum }: Props) => {
...
+    <AccountAddress
+      addressFont="text-text-secondary"
+      size={16}
+      address={(referendum as OngoingReferendum).submissionDeposit!.who}
+      name={toAddress((referendum as OngoingReferendum).submissionDeposit!.who, { chunk: 6 })}
```
Comment (johnthecat) [inline src/renderer/features/governance/components/ReferendumDetails/ProposerName.tsx]: can you pass chain prop and add correct `addressPrefix` please?

File: src/renderer/features/governance/components/ReferendumDetails/ProposerName.tsx (hunk 2 above)
Comment (Tbaut) [reply src/renderer/features/governance/components/ReferendumDetails/ProposerName.tsx]: Much better, thanks.

File: src/renderer/features/governance/components/ReferendumDetails/ProposerName.tsx (hunk 3 above)
Comment (Tbaut) [reply src/renderer/features/governance/components/ReferendumDetails/ProposerName.tsx]: Sure, I passed it through the props since we had no chain related info in this component.

File: src/renderer/features/governance/components/ReferendumDetails/ProposalDescription.tsx [hunk 4]
```diff
@@ -15,6 +16,8 @@ type Props = {
 
 export const ProposalDescription = ({ chainId, referendum }: Props) => {
   const isDescriptionLoading = useUnit(detailsAggregate.$isDescriptionLoading);
+  const addressPrefix = useUnit(networkModel.$chains)[chainId]?.addressPrefix;
```
Comment (johnthecat) [inline src/renderer/features/governance/components/ReferendumDetails/ProposalDescription.tsx]: In governance we have `networkSelectorModel.$governanceChain`, can you use it instead?

Comment (Tbaut) [reply src/renderer/features/governance/components/ReferendumDetails/ProposalDescription.tsx]: absolutely, thanks.

**Review by johnthecat — APPROVED** [review]

**Review by Asmadek — APPROVED** [review]
