### PR TITLE
fix: polkadot vault keys details modals

### LINKED ISSUE #4926: Multishard vault. Edited keys in multishard Vault wallet not updated immediately after saving
## Description

When editing keys of a multishard Polkadot Vault wallet, the updated key configuration is not displayed immediately after saving.
The user must close the wallet details view and reopen it to see the changes.

## Steps to Reproduce

1. Open a multishard Vault wallet.
2. Click Edit keys.
3. Modify one or more derivation paths or shard configurations.
4. Click Save.
5. Observe the wallet details view after saving.

## Expected Behavior

The updated keys and shard configuration should appear immediately in the wallet details after saving.

## Actual Behavior

Wallet details still show the old key configuration until the user closes and reopens the wallet details.

## Screenshots

https://github.com/user-attachments/assets/c8014a45-f446-40cb-b465-6b81e29abfc1

### LINKED ISSUE #4927: Reopening a multishard Vault wallet details after editing keys opens Edit Keys modal
## Description

After editing and saving keys for a multishard Polkadot Vault wallet, reopening the wallet details results in the Edit keys modal being displayed automatically instead of the expected wallet details view.

## Steps to Reproduce

1. Open a multishard Vault wallet.
2. Click Edit keys.
3. Modify and save the key configuration.
4. Close the wallet details view.
5. Reopen the same Vault wallet.

## Expected Behavior

Reopening the wallet should display the wallet details view by default.

## Actual Behavior

The app opens the Edit keys modal immediately upon reopening the wallet.

## Screenshots

https://github.com/user-attachments/assets/39bb2852-e32c-4e9c-ad0a-e2b518d28857

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Fixes bug: Edited keys in Polkadot Vault wallet not updated immediately after saving
Fixes bug: Reopening a Polkadot Vault wallet details after editing keys opens Edit Keys modal

## Related Issues
Closes #4926 
Closes #4927

## Checklist

- [X] I have performed a self-review of my own code
- [X] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [X] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [X] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/wallet-details/ui/wallets/VaultWalletDetails.tsx [hunk 1]
```diff
@@ -68,30 +68,30 @@ export const VaultWalletDetails = ({ wallet, onClose }: Props) => {
...
   const [chains, setChains] = useState<Chain[]>([]);
 
-  const accountsMap = useMemo(() => {
-    const accountsMap = walletDetailsUtils.getVaultAccountsMap(wallet.accounts);
-    //todo sort these accounts
+  const walletAccounts = useStoreMap({
+    store: accounts.$list,
+    keys: [wallet.id],
+    fn: (accounts, [walletId]) =>
+      accountService.filterAccountsByWallet(accounts, walletId) as (VaultChainAccount | VaultShardAccount)[],
```
Comment (johnthecat) [inline src/renderer/features/wallet-details/ui/wallets/VaultWalletDetails.tsx]: let's remove this type assumption, use `.filter(a => accountUtils.is...)` instead

File: src/renderer/features/wallet-details/ui/wallets/VaultWalletDetails.tsx [hunk 2]
```diff
@@ -68,30 +68,30 @@ export const VaultWalletDetails = ({ wallet, onClose }: Props) => {
...
-    return accountsMap;
-  }, [wallet.accounts]);
+  const accountsMap = useMemo(() => walletDetailsUtils.getVaultAccountsMap(walletAccounts), [walletAccounts]);
 
   useEffect(() => {
     const filteredChains = Object.values(allChains).filter(c => {
-      const accounts = Object.values(accountsMap).flat(2);
-
-      return accounts.some(a => accountUtils.isChainAndCryptoMatch(a, c));
+      return walletAccounts.some(a => accountUtils.isChainAndCryptoMatch(a, c));
```
Comment (johnthecat) [inline src/renderer/features/wallet-details/ui/wallets/VaultWalletDetails.tsx]: use `accountService.isAccountAvailableOnChain` instead

**Review by aaa123eee — APPROVED** [review]
