### PR TITLE
fix: exclude duplicated authorities

### LINKED ISSUE #1655: Delegated authority. Has duplicates in the tab.
## Description
There is a case, when delegated authority shows proxy duplicates

## Steps to Reproduce

1. Create regular proxy
2. Restart the app

## Expected Behavior
Show only one regular proxy

## Actual Behavior
a list of duplicates of regular proxy is shown

## Environment
https://github.com/novasamatech/nova-spektr/commit/ca555571245870d28cad4cd0c3ea42cb09c3d98d

logs:
[nova-spektr.log](https://github.com/novasamatech/nova-spektr/files/14918892/nova-spektr.log)

Screenshot 2024-04-09 at 16 03 57

address:
5FxYHLTBomNhZVnbfWVJvNKBraMfe4ejvr51UDadGRaRCYk9

### PR DESCRIPTION
**Pull request by Asmadek**
* add temp solution for it

### CODE REVIEW

File: src/renderer/widgets/WalletDetails/model/wc-details-model.ts [hunk 1]
```diff
@@ -147,6 +147,8 @@ sample({
 
 sample({
   clock: walletModel.events.walletRemovedSuccess,
+  source: { forgetStep: $forgetStep },
```
Comment (tuul-wq) [inline src/renderer/widgets/WalletDetails/model/wc-details-model.ts:150]: Mm?
`source: $forgetStep`

**Review by tuul-wq — APPROVED** [review]
