### PR TITLE
fix: handle batch for flex msig operation

### LINKED ISSUE #5047: Flexible multisig. Parsing operation. Can't parse operation from the Nova Wallet as a flexible multisig
## Description

We can't parse operation sent from Nova Wallet as a flexible multisig operation

## Steps to Reproduce

1. Import test database - [spektr-database (5).json](https://github.com/user-attachments/files/23485343/spektr-database.5.json)
2. Multisig 0x7fef594e78bd3623a7de237144653ab3765faf41 has operation

## Expected Behavior

Should parse as a flexible multisig operation in 0xc561d1e07b24349004546d0d26d92ebef8c4ae62 wallet

## Actual Behavior

Operation wrapped into proxy calls inside batch, it can't parse as a flexible multisig operations

Example of flow:

https://github.com/user-attachments/assets/d40061fa-96b3-40bc-99b5-7fc3c0d1aeda

### PR DESCRIPTION
**Pull request by aaa123eee**
## Description

add a check for batch operation

## Related Issues

closes #5047 

## Screenshots/Recordings

image

image

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

**Review by johnthecat — APPROVED** [review]

File: src/renderer/aggregates/selected-wallet-multisig-operations/model.ts [hunk 1]
```diff
@@ -24,9 +25,16 @@ const $list = combine(
...
 
       return accountOperations.filter(tx => {
-        return (
-          tx.method === 'proxy' && tx.section === 'proxy' && proxiedAccountId === toAccountId(tx.transaction?.args.real)
-        );
+        const isProxyTx =
+          tx.method === 'proxy' &&
+          tx.section === 'proxy' &&
+          proxiedAccountId === toAccountId(tx.transaction?.args.real);
+        const isBatchAllTx =
```
Comment (johnthecat) [inline src/renderer/aggregates/selected-wallet-multisig-operations/model.ts:36]: Add comment please. It should be about nova wallet case
