### PR TITLE
Fix: Light clients

### LINKED ISSUE #3300: Networking. Light client stuck in connecting state
## Description

When user change connection to the light client it is stuck in connecting state

## Steps to Reproduce

1. Go to Settings
2. Open networking
3. Switch polkadot connection to the Light client

## Expected Behavior

Successfully connect via light client

## Actual Behavior

Stuck in connecting state

Image

[localhost-1741337825875.log](https://github.com/user-attachments/files/19123428/localhost-1741337825875.log)

## Environment
https://github.com/novasamatech/nova-spektr/commit/1d618d3e353db00129b5875c54573657f358d66c

## Additional information
Tried to update smoldot to the latest version"@substrate/connect": "2.1.4",

### PR DESCRIPTION
**Pull request by tuul-wq**
- Rollback `@substrate/connect` > 1.3.1
- Use `createApiFx` to notify about `api` readiness
- Use new `Accordion` in `NetworkList`

closes #3300 

Screenshot 2025-03-18 at 12 57 01 PM

### CODE REVIEW

File: src/renderer/features/network/NetworkList/ui/NetworkList.tsx [hunk 1]
```diff
@@ -31,21 +29,23 @@ export const NetworkList = ({ title, query, networkList, children }: Props) => {
...
-            {title}
-          </CaptionText>
-          <Counter variant="waiting">{networkList.length}</Counter>
-
-          <div className="ml-auto flex items-center gap-x-1.5">
-            {success > 0 && <Counter variant="success">{success}</Counter>}
-            {connecting > 0 && <Counter variant="waiting">{connecting}</Counter>}
-            {error > 0 && <Counter variant="error">{error}</Counter>}
+    <Accordion initialOpen={isListOpen} onToggle={toggleList}>
+      <Box padding={[1.5, 2, 1.5, 2]}>
```
Comment (johnthecat) [inline src/renderer/features/network/NetworkList/ui/NetworkList.tsx]:
```suggestion
      <Box padding={[1.5, 2]}>
```

**Review by johnthecat — APPROVED** [review]
