### PR TITLE
Fix: Connections number

### LINKED ISSUE #1456: The amount of connections isn't equal to the amount of success + connecting + error
## Description
image
An image sums it up. It is weird that the amount of the left isn't equal to the sum of the amounts on the right.
## Steps to Reproduce

1. go to settings>networks
2. see the issue

## Expected Behavior
Have the sum of the numbers on the right equal to the number on the left

## Actual Behavior
They are not equal

## Screenshots
See above

## Possible Solution
I looked into it and realized that we do not take into account the connections with the status `isDisconnectedStatus`. Also in the list we mark them as "Connecting..." which is misleading.

### PR DESCRIPTION
**Pull request by tuul-wq**
- Consistent network status

closes #1456

### CODE REVIEW

File: src/renderer/features/network/NetworkList/lib/networks-list-utils.ts [hunk 1]
```diff
@@ -21,17 +21,18 @@ function getExtendedChain(
...
+
+  for (const network of networkList) {
+    if (networkUtils.isDisabledConnection(network.connection)) continue;
 
-      if (networkUtils.isConnectedStatus(network.connectionStatus)) acc.success += 1;
-      if (networkUtils.isConnectingStatus(network.connectionStatus)) acc.connecting += 1;
-      if (networkUtils.isErrorStatus(network.connectionStatus)) acc.error += 1;
+    if (networkUtils.isConnectedStatus(network.connectionStatus)) metrics.success += 1;
+    if (networkUtils.isConnectingStatus(network.connectionStatus)) metrics.connecting += 1;
+    if (networkUtils.isDisconnectedStatus(network.connectionStatus)) metrics.connecting += 1;
```
Comment (tuul-wq) [inline src/renderer/features/network/NetworkList/lib/networks-list-utils.ts:33]: It's a state when connection is running but node tries to reconnect, which is similar to `connecting`
but is being invoked on `provider.disconnect` event

**Review by johnthecat — APPROVED** [review]

**Review by sokolova-an — APPROVED** [review]
