### PR TITLE
fix(proxy): show delegates & total deposit

### LINKED ISSUE #4271: 'Delegated to' tab in proxy account wallet details shows counter but no accounts
## Description

When viewing the wallet details of a proxy account, the 'Delegated to' tab displays a numeric counter indicating that one or more proxy accounts exist. However, upon opening the tab, no accounts are rendered - only a blank 'Accounts' section is visible.

## Steps to Reproduce

1. Open a proxy account and delegate authority to some accounts.
2. Reopen the proxy account from Step 1 and click on the 'Delegated to' tab.
3. Observe that the tab counter (e.g. '1') shows at least one proxied account.

## Expected Behavior

The 'Delegated to' tab should display a list of proxied accounts corresponding to the count in the tab label.

## Actual Behavior

The tab shows a non-zero counter but does not render any proxied accounts, leaving the section blank.

Image

### PR DESCRIPTION
**Pull request by aaa123eee**
## Description

Derive the list of delegations from the proxied accounts.
Remove an excessive proxy groups DB field

## Related Issues

closes #4271

## Changes Made

- removed ProxyGroup entity
- deposits are now pulled from the deposits store instead
- proxy connections now derrived from proxied accounts instead

## Screenshots/Recordings

image

### CODE REVIEW

File: src/renderer/features/wallet-details/model/wallet-details-model.ts [hunk 1]
```diff
@@ -36,28 +37,22 @@ const $chainsProxies = combine(
...
+    return wallet.accounts.filter(accountUtils.isProxiedAccount).map(account => {
+      const chainDeposits = deposits.find(d => d.chainId === account.chainId);
+      const deposit = chainDeposits?.deposits[account.accountId] || '0';
+
+      return {
+        chainId: account.chainId,
+        proxiedAccountId: account.accountId,
+        walletId: account.walletId,
+        totalDeposit: deposit,
+      };
```
Comment (aaa123eee) [inline src/renderer/features/wallet-details/model/wallet-details-model.ts]: deposit can be saved in the account model

**Review by johnthecat — APPROVED** [review]
