### PR TITLE
fix: now advanced dialog has correct deposit

### LINKED ISSUE #2170: Governance. Advanced info. Shows wrong deposit amount
## Description
Deposit amount is shown as submissionDeposit, but it should show decisionDeposit.

Referenda details example:
```js
{
  Ongoing: {
    track: 10
    origin: {
      Origins: StakingAdmin
    }
    proposal: {
      Lookup: {
        hash_: 0x002c390837cb103126cccd213f61c1a5fa16061336e59bf36b326da58d690235
        len: 36
      }
    }
    enactment: {
      After: 10
    }
    submitted: 422,453
    submissionDeposit: {
      who: 5EpsavEfPSZC8X2E4zHdJdepzpzfSccqNP5RUVyAU9Hyi3z4
      amount: 30,000,000,000
    }
    decisionDeposit: {
      who: 5EpsavEfPSZC8X2E4zHdJdepzpzfSccqNP5RUVyAU9Hyi3z4
      amount: 5,000,000,000,000,000
    }
    deciding: {
      since: 422,533
      confirming: null
    }
    tally: {
      ayes: 0
      nays: 0
      support: 0
    }
    inQueue: false
    alarm: [
      422,733
      [
        422,733
        0
      ]
    ]
  }
}
```

Screenshot 2024-08-21 at 17 14 32

## Steps to Reproduce

1. Create referenda
2. Place decision deposit
3. Find it in Spektr
4. Check Advanced

## Expected Behavior
In Advanced should be shown decisionDeposit if it haven't placed yet - shows 0 or didn't placed.

## Actual Behavior
Shows submission deposit, which is not interested for user

## Environment
https://github.com/novasamatech/nova-spektr/commit/64f12ff7746cb19024e2df0b6009cec5e6e2cf17

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #2170

### CODE REVIEW

File: src/renderer/features/governance/components/ReferendumDetails/AdvancedDialog.tsx [hunk 1]
```diff
@@ -16,21 +16,13 @@ export const AdvancedDialog = ({ asset, referendum, onClose }: Props) => {
...
-
-  const turnoutBalance = supportThreshold
-    ? formatBalance(supportThreshold.value.sub(tally.support), asset.precision)
-    : null;
-  const turnout = `${turnoutBalance?.formatted ?? 0} ${asset.symbol}`;
-
-  const deposit = submissionDeposit
-    ? `${formatBalance(submissionDeposit.amount, asset.precision).formatted} ${asset.symbol}`
-    : null;
+  const electrorate = formatAsset(tally.ayes.add(tally.nays).add(tally.support), asset);
```
Comment (Asmadek) [inline src/renderer/features/governance/components/ReferendumDetails/AdvancedDialog.tsx]: typo `electorate`

**Review by Asmadek — APPROVED** [review]
