### PR TITLE
fix: using relay parent block nubmer for pure proxieds

### LINKED ISSUE #4758: Kill pure proxy. Wrong spawner is used for flexible multisig.
## Description

Wrong spawner accountId is used for pure proxy kill flow.

Example of operation:
https://kusama.subscan.io/multisig_extrinsic/30252229-2?call_hash=0x1e08778c3469dd1d87343874b580f68ebc9e228c83f463dc88e6993d49071e8e

is used:
spawner: 0x14f0c4e9195004ab0be6fe37c18f430e2a1a8e922e7f8fee11d131d9fd29b878

expected:
spawner: 0x7a28037947ecebe0dd86dc0e910911cb33185fd0714b37b75943f67dcf9b6e7c

For pure proxy - GWz6yTEq8rQfQKk8MHWtcU5sjiVFPSRqqWtKKfQWQurZb64

## Test database:

[spektr-database (21).json](https://github.com/user-attachments/files/22536436/spektr-database.21.json)

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Reverted how we decide pure or not pure is proxy
filling block number to relay if its parachain

## Related Issues
Closes #4758 #4609

## Screenshots/Recordings
https://assethub-kusama.subscan.io/multisig_extrinsic/11617229-2?call_hash=0x7f046cbf92b83a67c1024345c58a89acc2377a9baa129d983a040fd5dabbcc4f

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/proxied-add-pure/model/add-pure-proxied-model.ts [hunk 1]
```diff
@@ -61,7 +61,22 @@ type GetPureProxyResult = {
...
+    const apiAtBlockHash = await api.rpc.chain.getBlockHash(timepoint.height);
+
+    const apiAt = await api.at(apiAtBlockHash);
+
+    const validationData = await apiAt.query?.['parachainSystem']?.['validationData']?.();
+
+    if (validationData) {
+      const validationDataJson = validationData.toJSON() as { relayParentNumber: number };
+      if (Number.isInteger(validationDataJson.relayParentNumber)) {
+        blockNumber = validationDataJson.relayParentNumber;
```
Comment (aaa123eee) [inline src/renderer/features/proxied-add-pure/model/add-pure-proxied-model.ts]: mb `try { z.object({ relayParentNumber: z.number() }).parse( validationData.toJSON() ) }`

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/features/proxied-add-pure/model/add-pure-proxied-model.ts [hunk 2]
```diff
@@ -52,33 +54,65 @@ const $initiatorWallet = combine(
...
+      disambiguationIndex: pureCreated.disambiguationIndex,
+      extrinsicIndex: timepoint.index,
+    });
+
+    return {
+      pure: pureCreated.pure,
+      blockNumber,
+      pendingBlockNumber: timepoint.height,
+      extrinsicIndex: pureCreated.extrinsicIndex,
+    };
```
Comment (valentunn) [inline src/renderer/features/proxied-add-pure/model/add-pure-proxied-model.ts]: This is dublicated across two flows. I suggest to extract and reuse it

File: src/renderer/shared/core/types/account.ts [hunk 3]
```diff
@@ -75,7 +75,8 @@ export interface ProxiedAccount extends ChainAccount {
   connections: ProxiedConnection[];
   proxyVariant: ProxyVariant;
   deposit: string;
-  blockNumber: number;
+  blockNumber: number; // timeline chain blockNumber;
```
Comment (valentunn) [inline src/renderer/shared/core/types/account.ts]: Maybe we can name it more specifically? E.g. `entropyBlockNumber` to indicate that this is what we used to create an entropy for account id => to call kill_pure

**Review by valentunn — APPROVED** [review]

**Review by johnthecat — APPROVED** [review]
