### PR TITLE
fix: added removed from basket message

### LINKED ISSUE #5108: Fellowship. Adding to basket from salary widget shows misleading “Added” success message while actually removing the task
## Description

From the Salary widget, clicking “Add to basket” the activate salary action always shows a success alert with the text “Added to the basket”, regardless of the current state.

However, when the task is already in the basket, the behavior is incorrect:

The UI still shows “Added to the basket”.
In reality, clicking Add to basket in this state removes the task from the basket.
There is no indication in the modal that the task is already in the basket, nor an option to explicitly remove it.

So the button behaves like a toggle, but the text and UX always pretend it’s an “Add” action, which is misleading.

## Steps to Reproduce

1. Open the Fellowship profile with the Salary widget visible.
2. Click Add to basket (e.g. Activate salary) from the Salary widget.
3. Observe: success alert “Added to the basket”.
4. Without clearing the basket, click Add to basket again from the same widget.

## Expected Behavior

If the task is **_not_** in the basket:

- Clicking Add to basket should add it and show “Added to the basket”.

If the task is already in the basket:

- The UI should indicate this state (e.g., different button text like “Remove from basket”).

Clicking the button while the task is in the basket, should either:

- Remove it and show “Removed from the basket”

In any case, the alert text must match the actual action (add vs remove).

## Actual Behavior

Clicking Add to basket when the task is already in the basket:

- Removes the task from the basket.
- Still shows success alert “Added to the basket”, which is incorrect.

## Database
Select fellowship3 account

[fellowship.json](https://github.com/user-attachments/files/23605500/fellowship.json)

### PR DESCRIPTION
**Pull request by Yanaty**
## Description

From the Salary widget, clicking “Add to basket” the activate salary action always shows a success alert with the text “Added to the basket”, regardless of the current state.

However, when the task is already in the basket, the behavior is incorrect:

The UI still shows “Added to the basket”.
In reality, clicking Add to basket in this state removes the task from the basket.
There is no indication in the modal that the task is already in the basket, nor an option to explicitly remove it.

So the button behaves like a toggle, but the text and UX always pretend it’s an “Add” action, which is misleading.

## Related Issues
Closes #5108

## Changes Made
Added removed from basket message

## Screenshots/Recordings

https://github.com/user-attachments/assets/75d92928-9c9b-4655-aa54-d6b1fc98470f

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/fellowship-salary/components/SalaryPayoutModal.tsx [hunk 1]
```diff
@@ -36,6 +37,8 @@ export const SalaryPayoutModal = ({ disabled, children }: Props) => {
   const account = useUnit(salaryPayout.$account);
   const wallet = useUnit(salaryPayout.$wallet);
   const fee = useUnit(salaryPayout.$fee);
+  const inBasket = useUnit(salaryInduct.$inBasket);
+
```
Comment (cuteWarmFrog) [inline src/renderer/features/fellowship-salary/components/SalaryPayoutModal.tsx]: Are you sure that slaryInduct and not salaryPayout model should be used?

File: src/renderer/features/fellowship-salary/components/SalaryRegisterModal.tsx [hunk 2]
```diff
@@ -33,6 +34,8 @@ export const SalaryRegisterModal = ({ disabled, children }: Props) => {
   const account = useUnit(salaryRequest.$account);
   const wallet = useUnit(salaryRequest.$wallet);
   const fee = useUnit(salaryRequest.$fee);
+  const inBasket = useUnit(salaryInduct.$inBasket);
+
```
Comment (cuteWarmFrog) [inline src/renderer/features/fellowship-salary/components/SalaryRegisterModal.tsx]: Again, induct was already used in the Induct component

File: src/renderer/features/fellowship-salary/components/SalaryPayoutModal.tsx (hunk 1 above)
Comment (Yanaty) [reply src/renderer/features/fellowship-salary/components/SalaryPayoutModal.tsx]: You’re right, thanks for noticing

File: src/renderer/features/fellowship-salary/components/SalaryRegisterModal.tsx (hunk 2 above)
Comment (Yanaty) [reply src/renderer/features/fellowship-salary/components/SalaryRegisterModal.tsx]: You’re right, thanks for noticing

**Review by cuteWarmFrog — APPROVED** [review]
лгтм
