### PR TITLE
fix: use local config even if fetch request fails

### LINKED ISSUE #4116: Update config management approach.
We want to get chains and tokens configs from the GitHub:
https://github.com/novasamatech/nova-spektr-utils/tree/main/chains/v1
https://github.com/novasamatech/nova-spektr-utils/tree/main/tokens/v1

### PR DESCRIPTION
**Pull request by savvyer**
## Description
If request to fetch remote chains/tokens configs fails we should not crash the app and load the available config from the local storage.

## Related Issues
Closes https://github.com/novasamatech/nova-spektr/issues/4116

### CODE REVIEW

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/entities/network/model/network-model.ts [hunk 1]
```diff
@@ -69,6 +64,11 @@ const getDefaultStatusesFx = createEffect((chains: Record<ChainId, Chain>): Reco
   return dictionary(Object.values(chains), 'chainId', () => ConnectionStatus.DISCONNECTED);
 });
 
+persist({
+  key: 'chains_map',
+  store: $chains,
```
Comment (johnthecat) [inline src/renderer/entities/network/model/network-model.ts:69]: why did you removed sync flag? it indicates that lib should load local storage value on startup, i didn't found any related logic in new code

Comment (savvyer) [reply src/renderer/entities/network/model/network-model.ts:69]: `sync: true` is the default state of the flag in the library.

But I pushed the update that sets this flag explicitly as it was before.

**Review by johnthecat — APPROVED** [review]
