### PR TITLE
Fix: Arbitrary signatory address

### LINKED ISSUE #2892: Multisig creation. Signatory selector - can't enter any wallet address
## Description

Can't enter any wallet address into second signatory

https://github.com/user-attachments/assets/feaac19c-1320-47e3-8bd6-af01c4cab200

## Environment
https://github.com/novasamatech/nova-spektr/commit/2c4fce1386e54459188aa5381f2ebde21bb427d7

### PR DESCRIPTION
**Pull request by tuul-wq**
- Arbitrary signatory address
- Fake rollback improvements

closes #2892

### CODE REVIEW

File: src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx [hunk 1]
```diff
@@ -60,11 +60,9 @@ export const Confirmation = ({ api, tx, account, chain, signAccount, feeTx, onSi
     store: networkModel.$apis,
     keys: [transaction],
     fn: (apis, [transaction]) => {
-      if (transaction && isXcmTransaction(transaction)) {
```
Comment (johnthecat) [inline src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx]: Revert this change please, it will conflict with #2772

**Review by johnthecat — APPROVED** [review]
