### PR TITLE
fix: edit flexible multisig operation

### LINKED ISSUE #4784: Flex multisig. Edit flexible shows for unlock operation
## Description

Image
Image

### PR DESCRIPTION
**Pull request by stepanLav**
## Related Issues

Closes #4784

## Screenshots/Recordings

Before:
Screenshot 2025-09-29 at 10 36 55
Screenshot 2025-09-29 at 10 37 00

After:
Screenshot 2025-09-29 at 10 49 03

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [x] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/entities/transaction/lib/common/utils.ts [hunk 1]
```diff
@@ -106,16 +106,14 @@ export const isEditFlexibleTransaction = (transaction?: Transaction | DecodedTra
...
-    const removeProxyTransaction = transaction.args.transactions.at(0);
-    const addProxyTransaction = transaction.args.transactions.at(1);
-
-    if (isRemoveProxyTransaction(removeProxyTransaction) && isAddProxyTransaction(addProxyTransaction)) {
-      if (addProxyTransaction.args.proxyType === 'Any') {
-        return true;
-      }
-    }
-
-    return true;
```
Comment (stepanLav) [inline src/renderer/entities/transaction/lib/common/utils.ts:118]: this is first bug

File: src/renderer/entities/transaction/lib/common/utils.ts [hunk 2]
```diff
@@ -106,16 +106,14 @@ export const isEditFlexibleTransaction = (transaction?: Transaction | DecodedTra
       return false;
     }
 
-    const removeProxyTransaction = transaction.args.transactions.at(0);
-    const addProxyTransaction = transaction.args.transactions.at(1);
```
Comment (stepanLav) [inline src/renderer/entities/transaction/lib/common/utils.ts:110]: this is second bug, first operation - add proxy, second - remove

File: src/renderer/entities/transaction/lib/common/utils.ts [hunk 3]
```diff
@@ -106,16 +106,14 @@ export const isEditFlexibleTransaction = (transaction?: Transaction | DecodedTra
       return false;
     }
 
-    const removeProxyTransaction = transaction.args.transactions.at(0);
```
Comment (valentunn) [inline src/renderer/entities/transaction/lib/common/utils.ts:109]: I suggest to do early return when checking for BATCH_ALL so there will be one less nested layer:

```ts
if (transaction?.type !== TransactionType.BATCH_ALL) {
return false;
}

// The rest
``

**Review by valentunn — APPROVED** [review]

**Review by Yanaty — APPROVED** [review]
