### PR TITLE
fix: initial loading state for referendum list, refactored referendum subscription

### LINKED ISSUE #2002: Governance. Loading state. There is no loading state for referenda list
## Description

When user open referenda list with connection troubles - there is no loading state for referenda list.

## Steps to Reproduce

1. Switch the Internet off
2. Go to Governance page

## Expected Behavior
Loading state for referenda list:
image
https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=101-11101&t=XU9wnC9WAmdozaBB-4
ongoing number should have loading state too

## Actual Behavior
There is empty page:
Screenshot 2024-07-30 at 10 30 11

## Environment
https://github.com/novasamatech/nova-spektr/commit/a326b27a5828e9884515bb7740a62fb3630fd886

### PR DESCRIPTION
**Pull request by johnthecat**

### CODE REVIEW

File: src/renderer/entities/governance/model/referendum.ts [hunk 1]
```diff
@@ -1,74 +1,77 @@
...
+import { createSubscriber } from '../utils/createSubscriber';
+
+const mergeReferendums = (a: Referendum[], b: Referendum[]) => {
+  return merge(
+    a,
+    b,
+    (x) => x.referendumId,
+    (a, b) => parseInt(a.referendumId) - parseInt(b.referendumId),
+  );
 };
```
Comment (sokolova-an) [inline src/renderer/entities/governance/model/referendum.ts:18]: Are you sure we need to merge them? We receive a full new updated list from the network anyway. In the case of merging, it can be a situation when the `referendum.id` is the same but `referendum.status` for example is different. In that case referendum list won't be updated when the `ongoing` referendum becomes `completed`

File: src/renderer/entities/governance/model/referendum.ts [hunk 2]
```diff
@@ -1,74 +1,77 @@
...
+import { merge, nonNullable } from '@shared/lib/utils';
 import { governanceService } from '../lib/governanceService';
-
-type RequestListParams = {
-  chain: Chain;
-  api: ApiPromise;
+import { governanceSubscribeService } from '../lib/governanceSubscribeService';
+import { createSubscriber } from '../utils/createSubscriber';
+
+const mergeReferendums = (a: Referendum[], b: Referendum[]) => {
```
Comment (Asmadek) [inline src/renderer/entities/governance/model/referendum.ts:11]: what do you think to move it so referendum or governance service?

**Review by Asmadek — APPROVED** [review]

File: src/renderer/entities/governance/lib/governanceSubscribeService.ts [hunk 3]
```diff
@@ -138,3 +144,24 @@ function subscribeVotingFor(
...
   };
 }
+
+/**
+ * TODO move to chain helpers
+ */
+function subscribeBlockWithInterval(api: ApiPromise, ttl: number, callback: (header: Header) => unknown) {
+  const throttled = throttle(callback, ttl);
+  const unsubscribe = api.rpc.chain.subscribeNewHeads((header) => {
+    throttled(header);
```
Comment (sokolova-an) [inline src/renderer/entities/governance/lib/governanceSubscribeService.ts:154]: Trying to understand, why do we need to pass `header` into `throttled`?

File: src/renderer/entities/governance/lib/governanceSubscribeService.ts [hunk 4]
```diff
@@ -138,3 +144,24 @@ function subscribeVotingFor(
...
+  });
+
+  return () => {
+    throttled.cancel();
+    unsubscribe.then((x) => x());
```
Comment (sokolova-an) [inline src/renderer/entities/governance/lib/governanceSubscribeService.ts]: let's use `fn` for these calls

File: src/renderer/entities/governance/model/referendum.ts (hunk 2 above)
Comment (johnthecat) [reply src/renderer/entities/governance/model/referendum.ts:11]: services holds mostly business logic, not transport-level mappings. I don't think that this is a good idea

File: src/renderer/features/governance/aggregates/list.ts [hunk 5]
```diff
@@ -64,24 +65,13 @@ const $referendums = combine(
...
-    chain: networkSelectorModel.$governanceChain,
-  },
-  filter: ({ chain }, api) => !!api && !!chain,
-  fn: ({ chain }, api) => ({ api: api!, chain: chain! }),
-  target: referendumModel.events.updateReferendums,
+  source: networkSelectorModel.$governanceChain,
+  filter: (chain, api) => nonNullable(api) && nonNullable(chain),
+  fn: (chain, api) => ({ chain: chain!, api: api! }),
+  target: referendumModel.events.subscribeReferendums,
 });
```
Comment (sokolova-an) [inline src/renderer/features/governance/aggregates/list.ts:72]: In which place now will we update/resubscribe the referendum list when we change the network?

File: src/renderer/entities/governance/model/referendum.ts (hunk 1 above)
Comment (johnthecat) [reply src/renderer/entities/governance/model/referendum.ts:18]: Merging lists is safer option regardless of current implementation of subscribe method. Merge method overrides record by key (`referendumId` in this case), so it shouldn't be a problem.

File: src/renderer/entities/governance/lib/governanceSubscribeService.ts (hunk 3 above)
Comment (johnthecat) [reply src/renderer/entities/governance/lib/governanceSubscribeService.ts:154]: It can be useful, when this helper became shared

File: src/renderer/features/governance/aggregates/list.ts (hunk 5 above)
Comment (johnthecat) [reply src/renderer/features/governance/aggregates/list.ts:72]: in current implementation subscribe method reinit subscription with new parameters
