### PR TITLE
fix: comments after evm tests

### LINKED ISSUE #1558: EVM. Is not shown an Identicon for old multishard creation flow and accounts menu.
## Description
Does not show Identicon for EVM accounts in a few places:

Old multishard
Screenshot 2024-03-12 at 15 57 46

Your accounts:
Screenshot 2024-03-12 at 15 58 10

### LINKED ISSUE #1559: EVM. XCMs to EVM network - can't calculate fee.
## Description
Can't calculate network fee when user use EVM address in recipient for non EVM networks, example - Acala -> Moonbeam

## Steps to Reproduce
- User has as substrate, as EVM accounts in his wallet

1. Go to assets tab
2. Find Acala network
3. Click Transfer
4. Select Moonbeam
5. Click "Myself"

## Expected Behavior
XCM for Acala -> Moonbeam works right

## Actual Behavior
Problem with fee calculation
Screenshot 2024-03-12 at 16 07 21

error:
```
2024/03/12 16:06:55.183 [development#1.5.0]-renderer [info] > Error getting fee -  Error: createType(Call):: Call: failed decoding xTokens.transferMultiasset:: Struct: failed on args: {"asset":"{\"_enum\":{\"__Unused0\":\"Null\",\"V2\":\"XcmV2MultiAsset\",\"__Unused2\":\"Null\",\"V3\":\"XcmV3MultiAsset\"}}","dest":"{\"_enum\":{\"__Unused0\":\"Null\",\"V2\":\"XcmV2MultiLocation\",\"__Unused2\":\"Null\",\"V3\":\"StagingXcmV3MultiLocation\"}}","dest_weight_limit":"{\"_enum\":{\"Unlimited\":\"Null\",\"Limited\":\"SpWeightsWeightV2Weight\"}}"}:: Struct: failed on dest: {"_enum":{"__Unused0":"Null","V2":"XcmV2MultiLocation","__Unused2":"Null","V3":"StagingXcmV3MultiLocation"}}:: Enum(V2):: Struct: failed on interior: {"_enum":{"Here":"Null","X1":"XcmV2Junction","X2":"(XcmV2Junction,XcmV2Junction)","X3":"(XcmV2Junction,XcmV2Junction,XcmV2Junction)","X4":"(XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction)","X5":"(XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction)","X6":"(XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction)","X7":"(XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction)","X8":"(XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction,XcmV2Junction)"}}:: Enum(X2):: Tuple: failed on 1:: Enum(AccountId32):: Struct: failed on id: [u8;32]:: Expected input with 32 bytes (256 bits), found 20 bytes
```

## Environment

- Version: https://github.com/novasamatech/nova-spektr/commit/39582c09745bd2ae548ba6edb25e897672bdce3c

### LINKED ISSUE #1560: EVM. Signle chain Multisig creation. Can assign substrate address from contacts list
## Description
Contact list with substrate addresses are available for multisig creation

## Steps to Reproduce
- user has contacts with substrate addresses

1. Go to single chain multisig creation flow
2. Select EVM chain
3. Go to Contacts tab

## Expected Behavior
For EVM chain are available only contacts with EVM address

## Actual Behavior
Can select contact with substrate address
Screenshot 2024-03-12 at 15 55 52

## Environment

- Version: https://github.com/novasamatech/nova-spektr/commit/39582c09745bd2ae548ba6edb25e897672bdce3c

### LINKED ISSUE #1561: EVM. For wallets without EVM accounts in the list, EVM networks still available.
## Description
For wallets without EVM accounts in the list, EVM networks still available and receive feature shows wrong address, also there is a way to transfer assets from unexistence wallet

## Steps to Reproduce

1. Create Polkadot Vault wallet with all addresses
2. Go to Assets tab
3. Find Moonbeam
4. Click transfer \ receive

## Expected Behavior
Moonbeam is not available on Assets tab, if wallet does not have address for it

## Actual Behavior
User can click on Receive and Transfer for Moonbeam network

## Environment

- Version: https://github.com/novasamatech/nova-spektr/commit/39582c09745bd2ae548ba6edb25e897672bdce3c

## Screenshots
Screenshot 2024-03-12 at 15 54 08
Screenshot 2024-03-12 at 15 50 43

### PR DESCRIPTION
**Pull request by Asmadek**
* show myself button for multiaccounts wallets 
* correct list of accounts

### CODE REVIEW

File: src/renderer/features/wallets/ShardSelectorModal/ui/SelectableShard.tsx [hunk 1]
```diff
@@ -35,15 +35,11 @@ export const SelectableShard = ({
   const isSharded = isShard || isChain;
   const address = toAddress(account.accountId, { prefix: addressPrefix });
 
+  const theme = isBase && walletUtils.isPolkadotVault(wallet) ? 'jdenticon' : undefined;
```
Comment (tuul-wq) [inline src/renderer/features/wallets/ShardSelectorModal/ui/SelectableShard.tsx:38]: Let's pass `polkadot` instead of `undefined`, otherwise it looks awkward

File: src/renderer/shared/api/xcm/xcmService.ts [hunk 2]
```diff
@@ -316,27 +323,46 @@ export const getVersionedAccountLocation = (
 };
 
 export const getAccountLocation = (accountId?: AccountId): Object | undefined => {
-  return {
-    parents: 0,
-    interior: {
-      X1: {
+  const isEthereum = isEthereumAccountId(accountId);
```
Comment (tuul-wq) [inline src/renderer/shared/api/xcm/xcmService.ts:326]: I would not introduce standalone variable, utility method name is super clear

File: src/renderer/shared/api/xcm/xcmService.ts [hunk 3]
```diff
@@ -316,27 +323,46 @@ export const getVersionedAccountLocation = (
...
   const location: Record<string, any> = { parachainId };
+  const isEthereum = isEthereumAccountId(accountId);
 
   if (accountId) {
-    location.accountId = {
-      network: 'Any',
-      id: accountId,
-    };
+    if (isEthereum) {
+      location.accountKey = {
```
Comment (tuul-wq) [inline src/renderer/shared/api/xcm/xcmService.ts]: You could inline condition with property destructuring 
`...(isEth ? {key: accountId} : {id: accountId})`
Or this one
`[isEth ? 'key' : 'id']: accountId`

File: src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/SelectAccountSignatories.tsx [hunk 4]
```diff
@@ -25,6 +25,7 @@ import { EmptyContactList } from '@entities/contact';
 import { type Contact, type Account, ShardAccount, Wallet, Chain } from '@shared/core';
 import { ContactItem, ExplorersPopover, WalletCardMd } from '@entities/wallet';
 import { matrixModel } from '@entities/matrix';
+import { networkUtils } from '@/src/renderer/entities/network';
```
Comment (tuul-wq) [inline src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/SelectAccountSignatories.tsx]: Import

File: src/renderer/shared/api/xcm/xcmService.ts (hunk 3 above)
Comment (Asmadek) [reply src/renderer/shared/api/xcm/xcmService.ts:356]: I can't do this, because we have not only `key` and `id` differance, but `accountKey` and `accountId` on higher level

File: src/renderer/features/wallets/ShardSelectorModal/ui/SelectableShard.tsx (hunk 1 above)
Comment (Asmadek) [reply src/renderer/features/wallets/ShardSelectorModal/ui/SelectableShard.tsx:38]: In that case we need not only `polkadot` but `ethereum` too. `Identicon` component already can select default theme. I can't see any reasons to check it twice.

File: src/renderer/shared/api/xcm/xcmService.ts [hunk 5]
```diff
@@ -347,12 +364,20 @@ const getChildLocation = (parachainId: number, accountId?: AccountId): Object =>
...
   const location: Record<string, any> = {};
+  const isEthereum = isEthereumAccountId(accountId);
 
   if (accountId) {
-    location.accountId = {
-      network: 'Any',
-      id: accountId,
-    };
+    if (isEthereum) {
+      location.accountKey = {
```
Comment (tuul-wq) [inline src/renderer/shared/api/xcm/xcmService.ts]: Same destructuring can be applied here

**Review by tuul-wq — APPROVED** [review]
