### PR TITLE
Fix: Use accountId

### LINKED ISSUE #3295: Governance. Votes for multishard wallet does not show
## Description

Vote state for multishard won't update after actual voting.

## Test data

[spektr-database.json](https://github.com/user-attachments/files/19103709/spektr-database.json)

Example:

https://github.com/user-attachments/assets/39234001-0ff2-47a6-826c-1f6ff8a96905

## Steps to Reproduce

1. Select multishard
2. Go to governance page
3. Select referenda and vote from one of shard

## Expected Behavior
Referenda state will be updated

## Actual Behavior
Nothing happened

actually voted - https://kusama.subscan.io/extrinsic/27367392-2

## Environment
https://github.com/novasamatech/nova-spektr/commit/57262d9fc7fb031e6fc71ef04c876f1c12a5f9a8

### PR DESCRIPTION
**Pull request by tuul-wq**
- Use `accountId` instead of `address`

closes #3295

### CODE REVIEW

File: src/renderer/features/governance/aggregates/voting.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ const $activeWalletVotes = combine(
       return {};
     }
 
-    const addresses = accountUtils.getAddressesForWallet(wallet, chain);
+    const addresses = accountUtils.getAccountsIdsForWallet(wallet, chain);
```
Comment (Asmadek) [inline src/renderer/features/governance/aggregates/voting.ts]: Mybe rename `addresses` to `accountIds`?

**Review by Asmadek — APPROVED** [review]

**Review by johnthecat — APPROVED** [review]
