### PR TITLE
fix: proper chain for xcm destination account

### LINKED ISSUE #3093: XCM. Wrong address is shown on confirmation page
## Description

When a user make an XCM transfer from EVM to Substrate network, Recipient address will be shown in EVM format

Image

Image

## Steps to Reproduce

1. Make a transfer from Mythos to Polkadot Asset Hub

## Expected Behavior

Confirmation screen shows recipient address in Substrate format

## Actual Behavior

Confirmation screen shows recipient address in EVM format

## Environment
https://github.com/novasamatech/nova-spektr/commit/718ca6be2e2fd2455460acb1c72f51b04fd947b7

### PR DESCRIPTION
**Pull request by aaa123eee**
## Description

Show proper chain for destination address on XCM confirmarion

## Related Issues

closes #3093

## Changes Made

- added a check for xcmChain

## Screenshots/Recordings

image

### CODE REVIEW

File: src/renderer/features/operations/OperationsConfirm/Transfer/ui/Confirmation.tsx [hunk 1]
```diff
@@ -99,7 +99,11 @@ export const Confirmation = ({ id = 0, secondaryActionButton, hideSignButton, on
         )}
 
         <DetailRow label={t('operation.details.recipient')} className="text-text-secondary">
-          <Account accountId={toAccountId(confirmStore.destination)} chain={confirmStore.chain} variant="short" />
+          <Account
+            accountId={toAccountId(confirmStore.destination)}
+            chain={confirmStore.xcmChain || confirmStore.chain}
```
Comment (aaa123eee) [inline src/renderer/features/operations/OperationsConfirm/Transfer/ui/Confirmation.tsx:104]: this is a simple fix

I also suggest refactoring it to have a dedicated `destinationChain` field in the store instead of xcmChain. This should be relatively safe since currently `xcmChain` is actually a destination chain

**Review by johnthecat — APPROVED** [review]
