### PR TITLE
Fix/pure proxieds check

### LINKED ISSUE #4597: Sync service fails to add related pure proxies and flex multisigs - indexer returns 'pure: false' for linked pure proxies
## Description

When a user manually adds an account to Spektr, the sync service should pull in all related accounts, including any linked flex multisigs and their components (the regular multisig and the pure proxy).

Currently, for accounts that are part of flex multisigs, the indexer (SubQuery) returns 'pure: false' for the pure proxy entries during sync. As a result, the sync logic does not recognize these as pure proxies and doesn’t add the corresponding pure proxies and flex multisigs to the wallet list.

## Steps to Reproduce

1. Manually add an account that participates in one or more flex multisigs.
2. Trigger Sync.
3. Observe the related accounts that get added.
4. Check the indexer response for proxy entries tied to this account - note pure: false.
5. Verify that pure proxies and flex multisigs are missing or misclassified in the UI.

## Expected Behavior

- Sync detects that the manually added account has linked flex multisigs.
- Sync adds all related accounts:
The regular multisig
The pure proxy (correctly identified as pure: true)
The flex multisig wrapper
- UI shows all three entities, with correct types and links.

## Actual Behavior

- Indexer returns proxy entries with 'pure: false' for what are actually pure proxies.
- Sync fails to add the pure proxy (only proxied) and therefore does not add the flex multisig (adds just a regular proxy).

## Database

[spektr-database (10).json](https://github.com/user-attachments/files/22301875/spektr-database.10.json)

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Temporary fix for checking if proxied is pure from table PureProxy

## Related Issues
Closes #4597 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/domains/network/account-sync/resource.ts [hunk 1]
```diff
@@ -56,13 +72,25 @@ export const proxyAccountsProvider: AccountProvider<SyncedProxyAccount> = {
...
+
+    const parsed = proxiedResponse.proxieds.nodes.map(x => proxySchema.parse(x));
+
+    const accountIds = parsed.map(x => x.accountId);
+
+    const pureProxiesResponse = await client.request<{ pureProxies: { nodes: unknown[] } }, { accounts: AccountId[] }>(
+      PURE_PROXY_QUERY,
+      { accounts: accountIds },
+    );
+    //todo remove when reindexing is done
```
Comment (kalininilya) [inline src/renderer/domains/network/account-sync/resource.ts:89]: Is there a ticket for this?

**Review by kalininilya — APPROVED** [review]

File: src/renderer/domains/network/account-sync/resource.ts [hunk 2]
```diff
@@ -105,6 +133,9 @@ export const proxyAccountsProvider: AccountProvider<SyncedProxyAccount> = {
           });
           if (nullable(proxyFromIndexer)) continue;
 
+          // Check if this account is a pure proxy using the PureProxy table data
+          const isPureProxy = pureProxyLookup.has(`${accountId}:${chainId}`);
```
Comment (aaa123eee) [inline src/renderer/domains/network/account-sync/resource.ts]: maybe we can keep the old check too
```suggestion
          const isPureProxy = proxyFromIndexer.isPureProxy || pureProxyLookup.has(`${accountId}:${chainId}`);
```

File: src/renderer/domains/network/account-sync/resource.ts (hunk 1 above)
Comment (cuteWarmFrog) [reply src/renderer/domains/network/account-sync/resource.ts:89]: https://github.com/novasamatech/nova-spektr/issues/4609
