### PR TITLE
fix: warning validation

### LINKED ISSUE #1631: Revoke delegated authority (pure proxy). Validation problem on Attention dialogue.
## Description
There is some problems for `Revoke delegated authority (pure proxy)` screen:

1. Revoke authority button become active, after click only on one check-box
Screenshot 2024-04-04 at 10 09 38
----------->
Screenshot 2024-04-04 at 10 09 51

2. There is no way to understand that user has typo in the string, button become just unavailable, without any explanations.
Screenshot 2024-04-04 at 10 11 44
----------->
Screenshot 2024-04-04 at 10 11 59

3. Back button lead to empty page with network fee:

https://github.com/novasamatech/nova-spektr/assets/40560660/78217f38-3911-4b59-9a13-0d2c0edc3423

### PR DESCRIPTION
**Pull request by Asmadek**
* fix warning validation
* add invalid state for warning input
* don't show init form on go back if don't needed

### CODE REVIEW

File: src/renderer/widgets/RemovePureProxyModal/model/warning-model.ts [hunk 1]
```diff
@@ -66,7 +66,7 @@ const $warningForm = createForm<FormParams>({
       ],
     },
   },
-  validateOn: ['submit'],
+  validateOn: ['change', 'submit'],
```
Comment (tuul-wq) [inline src/renderer/widgets/RemovePureProxyModal/model/warning-model.ts]: On every key press use will see invalid field state
Why `onSubmit` doesn't work here?

File: src/renderer/widgets/RemovePureProxyModal/ui/RemovePureProxy.tsx [hunk 2]
```diff
@@ -46,7 +47,9 @@ export const RemovePureProxy = () => {
       {removePureProxyUtils.isWarningStep(step) && <Warning onGoBack={closeModal} />}
       {removePureProxyUtils.isInitStep(step) && <RemovePureProxyForm onGoBack={closeModal} />}
       {removePureProxyUtils.isConfirmStep(step) && (
-        <Confirmation onGoBack={() => removePureProxyModel.events.stepChanged(Step.INIT)} />
+        <Confirmation
+          onGoBack={() => (isMultisig ? removePureProxyModel.events.stepChanged(Step.INIT) : closeModal())}
```
Comment (tuul-wq) [inline src/renderer/widgets/RemovePureProxyModal/ui/RemovePureProxy.tsx]: This should happen in model
check out `split`
closeModal() is just `removePureProxyModel.output.flowFinished` in terms of model

File: src/renderer/widgets/RemovePureProxyModal/model/warning-model.ts [hunk 3]
```diff
@@ -80,14 +80,19 @@ sample({
   target: formSubmitted,
 });
 
+sample({
+  clock: formInitiated,
+  target: $warningForm.validate,
```
Comment (tuul-wq) [inline src/renderer/widgets/RemovePureProxyModal/model/warning-model.ts:85]: If I get this right, when I open the form it will validate and highlight all the fields right away?
It's required by UI mockups or it's something else?

File: src/renderer/widgets/RemoveProxyModal/ui/RemoveProxy.tsx [hunk 4]
```diff
@@ -35,7 +36,7 @@ export const RemoveProxy = () => {
     <BaseModal closeButton contentClass="" isOpen={isModalOpen} title={getModalTitle(step, chain)} onClose={closeModal}>
       {removeProxyUtils.isInitStep(step) && <RemoveProxyForm onGoBack={closeModal} />}
       {removeProxyUtils.isConfirmStep(step) && (
-        <Confirmation onGoBack={() => removeProxyModel.events.stepChanged(Step.INIT)} />
+        <Confirmation onGoBack={() => (isMultisig ? removeProxyModel.events.stepChanged(Step.INIT) : closeModal())} />
```
Comment (tuul-wq) [inline src/renderer/widgets/RemoveProxyModal/ui/RemoveProxy.tsx]: This should happen in model
check out split
closeModal() is just removePureProxyModel.output.flowFinished in terms of model

**Review by tuul-wq — CHANGES_REQUESTED** [review]

File: src/renderer/widgets/RemovePureProxyModal/model/warning-model.ts (hunk 3 above)
Comment (Asmadek) [reply src/renderer/widgets/RemovePureProxyModal/model/warning-model.ts:85]: Without this trigger boolean values mark as valid if it not touched. What your suggestions for it? It not highlight fields, but needed for submit button

File: src/renderer/widgets/RemovePureProxyModal/ui/RemovePureProxy.tsx (hunk 2 above)
Comment (Asmadek) [reply src/renderer/widgets/RemovePureProxyModal/ui/RemovePureProxy.tsx]: To realise it in model we should add new event for go back, change `removePureProxyModel.events.stepChanged` to this new event, add check that it's `Step.INIT` and  `isMultisig`. Of somehow detect that it was change form `CONFIRM` to `INIT`.  Are you sure that it's better than simple ternary operator?

File: src/renderer/widgets/RemoveProxyModal/model/remove-proxy-model.ts [hunk 5]
```diff
@@ -168,6 +170,18 @@ sample({
...
 sample({ clock: stepChanged, target: $step });
 
+split({
+  clock: wentBackFromConfirm,
+  source: $isMultisig,
+  match: {
+    multisigWallet: (isMultisig) => isMultisig,
+  },
+  cases: {
+    multisigWallet: stepChangedToInit,
```
Comment (tuul-wq) [inline src/renderer/widgets/RemoveProxyModal/model/remove-proxy-model.ts:180]: Maybe declare prepended event just in place?
`multisigWallet: stepChanged.prepend(() => Step.INIT),`

File: src/renderer/widgets/RemovePureProxyModal/model/remove-pure-proxy-model.ts [hunk 6]
```diff
@@ -170,6 +172,18 @@ const $shouldRemovePureProxy = combine(
...
 sample({ clock: stepChanged, target: $step });
 
+split({
+  clock: wentBackFromConfirm,
+  source: $isMultisig,
+  match: {
+    multisigWallet: (isMultisig) => isMultisig,
+  },
+  cases: {
+    multisigWallet: stepChangedToInit,
```
Comment (tuul-wq) [inline src/renderer/widgets/RemovePureProxyModal/model/remove-pure-proxy-model.ts:182]: Same suggestion here

**Review by tuul-wq — APPROVED** [review]
