### PR TITLE
fix: multisig show available signatory

### LINKED ISSUE #2890: Multisig. Create wallet. Does not show available signatory
## Description

When user try to create multsig wallet it should show available signatories

## Steps to Reproduce

1. Add some wallets with Westend (or any other network)
2. Go to multisig creation flow
3. Select Westend
4. Click into signatory field

## Expected Behavior
Shows available signatories list

## Actual Behavior
Nothing happens

https://github.com/user-attachments/assets/bdf15f40-0b8c-4125-9170-c61863e09cb4

## Environment
https://github.com/novasamatech/nova-spektr/commit/2c4fce1386e54459188aa5381f2ebde21bb427d7

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Deprecated `Combobox` didn't show available signatories on input click. Replaced it with a new `Combobox` from ui-kit.

## Related Issues
Closes #2890 

## Changes Made
New `Combobox` supports only `string` type value and renders groups/options differently. So I had to do some adjustments to how we store options and handle changes to selected option.

### CODE REVIEW

File: src/renderer/features/multisig-wallet-pairing/components/components/Signatory.tsx [hunk 1]
```diff
@@ -100,40 +111,36 @@ export const Signatory = ({
...
+            label: <Address showIcon title={account.name} address={address} />,
           });
         }
       }
 
-      walletsOptions.push(
-        {
-          id: walletFamily,
-          value: undefined,
-          disabled: true,
```
Comment (sokolova-an) [inline src/renderer/features/multisig-wallet-pairing/components/components/Signatory.tsx:125]: There was a disabled prop previously, don't we need it?

**Review by sokolova-an — APPROVED** [review]

File: src/renderer/features/multisig-wallet-pairing/components/components/Signatory.tsx (hunk 1 above)
Comment (savvyer) [reply src/renderer/features/multisig-wallet-pairing/components/components/Signatory.tsx:125]: nope, we dont need it anymore.

It was used to show wallets as group separator in options. Disabled means its not a real value that can be selected.
New Combobox component supports real grouping. So I changed the implementation a bit

File: src/renderer/features/multisig-wallet-pairing/components/components/Signatory.tsx [hunk 2]
```diff
@@ -143,20 +150,37 @@ export const Signatory = ({
...
+      addressOptions.push({
         id: contact.id.toString(),
-        element: <Address showIcon title={contact.name} address={displayAddress} />,
+        label: <Address showIcon title={contact.name} address={displayAddress} />,
         value: { address: displayAddress },
       });
     }
 
+    if (validateAddress(query, chain)) {
+      const displayAddress = toAddress(query, { prefix: chain.addressPrefix });
```
Comment (aaa123eee) [inline src/renderer/features/multisig-wallet-pairing/components/components/Signatory.tsx]:
```suggestion
      const displayedAddress = toAddress(query, { prefix: chain.addressPrefix });
```

otherwise sounds like a boolean condition

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/features/multisig-wallet-pairing/components/components/Signatory.tsx (hunk 2 above)
Comment (savvyer) [reply src/renderer/features/multisig-wallet-pairing/components/components/Signatory.tsx]: This is why I prefer to name boolean values like isSomething, hasSomething, shouldShomething.
Would be nice to have this rule in spektr codebase
