### PR TITLE
fix: race condition + simplified logic

### LINKED ISSUE #4611: Regular multisig creation flow. Wrong network fee
## Description

When user swap between evm based accounts and substrate based it shows wrong network fee. Things become worst, when add signatory before swap account

Example:

https://github.com/user-attachments/assets/663746ec-2158-4221-b564-5ac213f9243b

## Test database
[spektr-database (9).json](https://github.com/user-attachments/files/22337257/spektr-database.9.json)

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
1. fixing race condition for fee calculator
2. refactor fee selector

## Related Issues
Closes #4611

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/multisig-wallet-create/multisig-wallet/model/chain-model.ts [hunk 1]
```diff
@@ -21,63 +20,67 @@ type ChainWithFeeAndBalance = {
...
       return { chain, fee };
     } catch {
       return { chain, fee: null };
     }
   },
 );
 
-const calculateFeesSeriesFx = series(calculateFeeForChainFx, { parallel: true });
+// Calculate fees for all chains in series
+const calculateAllFeesFx = series(calculateChainFeeFx, { parallel: true });
```
Comment (johnthecat) [inline src/renderer/features/multisig-wallet-create/multisig-wallet/model/chain-model.ts]: also add `skipErrors: true` here

**Review by johnthecat — APPROVED** [review]
