### PR TITLE
fix: multisig networks list with fees

### LINKED ISSUE #5361: [Flaky] Regular multisig creation: network list is empty in fee-token network selector
## Description

In the regular multisig creation flow, when selecting the network/token to pay the network fee, the network selector modal intermittently opens with an empty list of networks.

Connections are shown as established in Network Settings, but the selector remains empty and only populates after a long delay (2–3 minutes) while the modal stays open but without a loading state indicator, or after reloading the app.

## Steps to Reproduce (intermittent)

1. Start the regular multisig creation flow.
2. Open the network selector modal (to choose token/network for fee payment).
3. Observe: fees are in loading state.
4. Close the modal.
5. Open Network settings and verify connections are established.
6. Return to multisig creation and open the network selector modal again.
7. Observe the list content.

## Expected Behavior

- The network selector should always display the available networks immediately (or show a clear loading indicator and then populate quickly).
- Established connections should result in a non-empty list.
- The list should not require minutes of waiting or an app reload to appear.

## Actual Behavior

- The network list is empty on modal open.
- Networks appear only:

After keeping the modal open for 2–3 minutes, or
After reloading the app.

## Screenshots

https://github.com/user-attachments/assets/bc13b8a0-321f-408c-bd93-0d35ad0b7bc7

## Additional Information

[spektr-database (64).json](https://github.com/user-attachments/files/24191187/spektr-database.64.json)

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Fix network loading fee or empty screen by handling fee requests separately.

The problem was that one of the `getTransactionFee` requests was hanging for very long time, preventing the whole calculateChainFeeFx to finish and render results.

## Related Issues
Closes https://github.com/novasamatech/nova-spektr/issues/5361

## Screenshots/Recordings
https://github.com/user-attachments/assets/0214e7ce-ed42-4e52-b233-43c7d9610f59

## Checklist

- [X] I have performed a self-review of my own code
- [X] I have tested the changes and verified the happy path works as expected
- [X] I have provided screenshot of the working feature (if applicable)
- [X] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [X] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/multisig-wallet-create/multisig-wallet/model/chain-model.ts [hunk 1]
```diff
@@ -46,7 +46,11 @@ const calculateChainFeeFx = createEffect(
         signatories: [TEST_ACCOUNTS[0], TEST_ACCOUNTS[1]],
       });
 
-      const fee = await transactionService.getTransactionFee(fakeTx, api);
+      const fee = await withTimeout(transactionService.getTransactionFee(fakeTx, api), 5000, null);
```
Comment (johnthecat) [inline src/renderer/features/multisig-wallet-create/multisig-wallet/model/chain-model.ts]: Fee should be calculated if chain is active and connected. Timeout works really bad in case of fees calc because usually it's required data for user

**Review by johnthecat — CHANGES_REQUESTED** [review]

**Review by cuteWarmFrog — APPROVED** [review]

**Review by johnthecat — APPROVED** [review]
