### PR TITLE
fix: default chain for evm and non evm based

### LINKED ISSUE #4557: Regular multisig creation flow for EVM accounts is working wrong
## Description

There is a problem with regular multisig and EVM account selection. Basically algorithm should work:
1. My account field is responsible for which network will be used in multisig creation flow
- If in My account is selected EVM address: 
  - network fee will be filtered by only evm based networks
  - as a signatories is available only evm based addresses
  - contacts and my accounts contains only evm based variants, if lenght == 0 shows nothing in a group, if there is no suggestion, do not show drop down at all
- If in My account is selected Substrate address:
  - network fee will be filtered by only substrate based networks
  - as a signatories is available only substrate based addresses
  - contacts and my accounts contains only substrate based variants, if lenght == 0 shows nothing in a group, if there is no suggestion, do not show drop down at all

2. Network fee selection is connected to available balances
- Try to pay network fee on Polkadot with DOT
  - if there is no DOT on polkadot, check next network
  - if there is no available balance on any available network in network selector - shows an error that there is no available balance to pay network fee in Polkadot for substrate based account, in mythos for EVM based accounts

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Setting chain to default corresponding chain if there is no available 

## Related Issues
Closes #4557 

## Screenshots/Recordings
image

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/multisig-wallet-create/multisig-wallet/model/form-model.ts [hunk 1]
```diff
@@ -10,7 +10,8 @@ import { accountUtils, walletModel, walletUtils } from '@/entities/wallet';
 import { signatoryModel } from './signatory-model';
 
 const MIN_THRESHOLD = 2;
-const DEFAULT_CHAIN: ChainId = '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'; // Polkadot
+export const DEFAULT_CHAIN: ChainId = '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'; // Polkadot
```
Comment (valentunn) [inline src/renderer/features/multisig-wallet-create/multisig-wallet/model/form-model.ts]: I suggest to rename it to `DEFAULT_SUBSTRATE_CHAIN` to make the distinction more clear

File: src/renderer/features/multisig-wallet-create/multisig-wallet/model/chain-model.ts [hunk 2]
```diff
@@ -184,6 +185,27 @@ sample({
   target: formModel.form.fields.chainId.change,
 });
 
+sample({
```
Comment (valentunn) [inline src/renderer/features/multisig-wallet-create/multisig-wallet/model/chain-model.ts:188]: We also have this sample above:

image

It looks like `availableChains.at(0)!.chain.chainId` might still emit Polkadot when user no more has the balance on the `currentChainId`. Maybe we should also change it here to`availableChains.find(chain => check that chain address scheme matches the selected account)`?

**Review by valentunn — APPROVED** [review]
