### PR TITLE
Fix: Filter accounts for Vote/Revote

### LINKED ISSUE #3307: Governance. Multishard. Revote lead to wrong balance state.
## Description

When user try to revote or vote on multishard wallet it leads to wrong state.

## Test data

https://github.com/user-attachments/files/19160261/spektr-database.json

## Steps to Reproduce

1. Go to Governance page
2. Select Referenda 1426
3. Try to Vote or Revote

## Expected Behavior
When user Vote he will be able to select any address, from which he has **not voted yet**
When user Revote he will be able to select any address, from which he has **already voted**

## Actual Behavior
When user opens Revote - available balance and existing votes are null

https://github.com/user-attachments/assets/4439ab2c-b4c1-4c6a-9c36-a65a06961d7f

## Environment
https://github.com/novasamatech/nova-spektr/commit/ff1c99c626c8021baac273f983986f9396416084

### PR DESCRIPTION
**Pull request by tuul-wq**
- Use `AccountId` instead of `Address`
- Filter available accounts on Vote and Revote forms

closes #3307

### CODE REVIEW

File: src/renderer/entities/operations/model/operations-model.ts [hunk 1]
```diff
@@ -21,7 +21,7 @@ export const operationsModel = {
     changeFilteredTxs,
   },
 
-  gate: {
+  gates: {
```
Comment (tuul-wq) [inline src/renderer/entities/operations/model/operations-model.ts:24]: Now everywhere is `gates`

File: src/renderer/widgets/VoteModal/aggregates/voteModal.ts [hunk 2]
```diff
@@ -141,19 +143,39 @@ sample({
...
+    const voters = referendum!.voting.votes.map((vote) =>
+      toAddress(vote.voter, { prefix: network?.chain.addressPrefix }),
+    );
+
+    return { type, referendum, voters };
+  },
+  target: spread({
+    type: voteFormAggregate.$type,
+    referendum: voteFormAggregate.$referendum,
+    voters: voteFormAggregate.$voters,
```
Comment (tuul-wq) [inline src/renderer/widgets/VoteModal/aggregates/voteModal.ts:160]: Was completely missing when `form` appears

**Review by aaa123eee — APPROVED** [review]
