### PR TITLE
fix: account overview state

### LINKED ISSUE #5496: Wallet overview are available from the multisig operation

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Fixes account overview modal that preserved the state of previously opened account.

## Related Issues
Fixes https://github.com/novasamatech/nova-spektr/issues/5496

## Screenshots/Recordings

https://github.com/user-attachments/assets/3dadb34f-1a47-46e3-8216-c18af48e89df

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/features/accounts-structure/components/AccountsStructureModal.tsx [hunk 1]
```diff
@@ -29,11 +29,15 @@ export const AccountsStructureModal = ({ walletAccounts, trigger, onClose }: Pro
...
+      accountsStructureModel.setAccounts(walletAccounts);
+    }
     return () => {
-      accountsStructureModel.setAccounts(null);
+      if (isOpen) {
+        accountsStructureModel.setAccounts(null);
+      }
     };
-  }, [walletAccounts]);
+  }, [walletAccounts, isOpen]);
```
Comment (cuteWarmFrog) [inline src/renderer/features/accounts-structure/components/AccountsStructureModal.tsx:40]: let's useGate

**Review by cuteWarmFrog — APPROVED** [review]
