### PR TITLE
fix: fellowship referendum details modal

### LINKED ISSUE #3634: Fellowship. Update design comments
Update the fellowship page according to the new design comments

### LINKED ISSUE #3654: Fellowship. Update activity\agreement
Make activity and agreement 100\100% if this metric is not applicable for the member in promotion or retention referendums, or  there were no referendums, this member could vote for

### PR DESCRIPTION
**Pull request by sokolova-an**
## Description
Update the fellowship referendum details modal and activity/agreement
## Related Issues
Closes #3634 Closes #3654
## Changes Made

- Moved `EvidenceDetailsModal` in `fellowship-referendum-details` feature
- Changed the way we call for details modal - no URL for details 
- Added member activity\agreemnet stats to promote\retain referendum details
- Split description and evidence 

## Screenshots/Recordings
image

### CODE REVIEW

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/domains/collectives/member/service.ts [hunk 1]
```diff
@@ -87,14 +87,37 @@ function isSetActiveTransaction(transaction: Transaction): transaction is SetAct
   return transaction.type === TransactionType.COLLECTIVE_SET_ACTIVE;
 }
 
+interface RankActivityThreshold {
```
Comment (tuul-wq) [inline src/renderer/domains/collectives/member/service.ts]: Let's make it a `type`

File: src/renderer/features/fellowship-tasks/components/Tasks.tsx [hunk 2]
```diff
@@ -14,11 +13,7 @@ import { Basket } from './Basket';
 import { TasksGroup } from './TasksGroup';
 import { Title } from './Title';
 
-type Props = {
-  onReferendumSelect(referendum: Referendum): void;
-};
-
-export const Tasks = memo(({ onReferendumSelect }: Props) => {
+export const Tasks = memo(() => {
```
Comment (tuul-wq) [inline src/renderer/features/fellowship-tasks/components/Tasks.tsx]: Does `memo` have any effect without props?

**Review by tuul-wq — APPROVED** [review]

File: src/renderer/features/fellowship-tasks/components/Tasks.tsx (hunk 2 above)
Comment (sokolova-an) [reply src/renderer/features/fellowship-tasks/components/Tasks.tsx]: no, it's not!
