### PR TITLE
fix: hidden retention referendums proposed by rank 0

### LINKED ISSUE #5168: Fellowship. Retention widget is enabled for users with Rank 0
## Description

Fellowship members with Rank 0 do not need to create retention referenda. Now, Members with Rank 0 can see retention widgets in their My profile modal.
Also all the users can see retention referenda created for users with Rank 0.

What needs to be fixed:

- [ ] 1. Retention widgets should be hidden for members with Rank 0 in their My profile modals
- [ ] 2. Retentions referenda created for members with Rank 0 (to retain such members at Rank 0) should be hidden for all the users.

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
Fellowship members with Rank 0 do not need to create retention referenda. Now, Members with Rank 0 can see retention widgets in their My profile modal.
Also all the users can see retention referenda created for users with Rank 0.

What needs to be fixed:
1. Retention widgets should be hidden for members with Rank 0 in their My profile modals
2. Retentions referenda created for members with Rank 0 (to retain such members at Rank 0) should be hidden for all the users.

## Related Issues
Closes #5168

## Changes Made
For rank = 0 hidden:
1) The retention widget
2) The submit evidence task
3) The pre-referendum retention tasks
4) The ongoing retention referendum tasks 

## Screenshots/Recordings
Снимок экрана 2025-11-24 в 18 35 39

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/aggregates/fellowship-retention/hooks.ts [hunk 1]
```diff
@@ -167,3 +167,19 @@ export const useRetentionWidgetState = () => {
...
+
+  if (nullable(retentionState)) {
+    return { data: false, pending };
+  }
+
+  return {
+    data:
+      retentionState === RetentionWidgetState.WARNING_APPROACHING ||
+      retentionState === RetentionWidgetState.WARNING_URGENT ||
+      retentionState === RetentionWidgetState.CRITICAL_LAST_CALL,
```
Comment (aaa123eee) [inline src/renderer/aggregates/fellowship-retention/hooks.ts:182]: in `data` I expect a data but this one looks like a boolean flag

Comment (johnthecat) [reply src/renderer/aggregates/fellowship-retention/hooks.ts:182]: I think it's ok, data/pending interface is just generic wrapper

File: src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx [hunk 2]
```diff
@@ -52,7 +52,7 @@ export const RetentionWidget = memo(({ member }: Props) => {
   const { data: state, pending } = useRetentionWidgetState();
   const { fromDateFormatted, toDateFormatted, retentionPeriod, timelineSteps, timelineValue } = useRetentionData();
 
-  if (!memberService.shouldProve(member)) return null;
+  if (!memberService.shouldProve(member) || member.rank === 0) return null;
```
Comment (johnthecat) [inline src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx]: maybe zero rank check should be included inside shouldProve method?

File: src/renderer/features/fellowship-tasks/hooks/useEvidenceTasks.ts [hunk 3]
```diff
@@ -80,6 +80,8 @@ export const useEvidenceTasks = () => {
       const proposer = members.find(m => m.accountId === evidence.accountId);
       if (nullable(proposer)) continue;
 
+      if (evidence.wish === 'Retention' && proposer.rank === 0) continue;
```
Comment (johnthecat) [inline src/renderer/features/fellowship-tasks/hooks/useEvidenceTasks.ts]: So we basically cut out evidence tasks for proposers with zero rank? is it correct?

File: src/renderer/features/fellowship-tasks/service.ts [hunk 4]
```diff
@@ -249,10 +250,35 @@ function cutMarkdown(markdown: string) {
...
+  if (!proposerAccountId) {
+    return true;
+  }
+
+  const proposerMember = members.find(member => member.accountId === proposerAccountId);
+  if (!proposerMember) {
+    return true;
+  }
+
+  if (proposerMember.rank === 0 && trackService.isRetentionTrack(referendum.track)) {
```
Comment (johnthecat) [inline src/renderer/features/fellowship-tasks/service.ts]: I saw similar logic inside useEvidenceTasks hook, let's make a generic method for it.

**Review by johnthecat — DISMISSED** [review]

File: src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx (hunk 2 above)
Comment (Yanaty) [reply src/renderer/features/fellowship-retention/ui/RetentionWidget.tsx]: done

File: src/renderer/features/fellowship-tasks/hooks/useEvidenceTasks.ts (hunk 3 above)
Comment (Yanaty) [reply src/renderer/features/fellowship-tasks/hooks/useEvidenceTasks.ts]: yes, it's correct

File: src/renderer/features/fellowship-tasks/service.ts (hunk 4 above)
Comment (Yanaty) [reply src/renderer/features/fellowship-tasks/service.ts]: fixed

**Review by aaa123eee — APPROVED** [review]
