### PR TITLE
Fix/flexbile sync

### LINKED ISSUE #5095: Syncservice. Incorrect proxied account handling and excessive duplicate SubQuery requests
## Description

SyncService shows inconsistent behavior when syncing proxied accounts:

1. Polkadot Asset Hub: SubQuery returns a proxied account, but SyncService does not add this proxied wallet to the local list.
2. Polkadot Collectives: SubQuery returns no proxied accounts at all.
3. Duplicate requests: SyncService sends many identical SubQuery requests with the same payload, causing unnecessary load and slower sync.

## Screenshots

Image

## Database

[gav_proxies.json](https://github.com/user-attachments/files/23587276/gav_proxies.json)

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Using pendingBlockNumber for sync
renamed proxy to proxied

## Related Issues
Closes #5095 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

**Comment by cuteWarmFrog** [comment]
https://github.com/user-attachments/assets/9b642c95-1409-45a2-bfc2-a6d0ca1a007f

File: src/renderer/features/account-sync/model/sync.ts [hunk 1]
```diff
@@ -453,17 +453,17 @@ export const syncFlexibleMultisigs = ({
         return false;
       }
 
-      if (!account.entropyBlockNumber) {
+      if (!account.pendingBlockNumber) {
         return true;
       } else {
         const lastIndexedBlock = syncResult.indexedBlocks.get(account.chainId);
-        return !lastIndexedBlock || lastIndexedBlock >= account.entropyBlockNumber;
+        return !lastIndexedBlock || lastIndexedBlock >= account.pendingBlockNumber;
```
Comment (cuteWarmFrog) [inline src/renderer/features/account-sync/model/sync.ts:460]: fix is here, other is renaming

**Review by johnthecat — APPROVED** [review]
