### PR TITLE
refactor: fix issues on activity modal

### LINKED ISSUE #3489: Fellowship. View list. Redundant symbol on loading state
## Description

Image

### LINKED ISSUE #3490: Fellowship. Events list. Search rules
## Description

Search should work by address and by identity

## Steps to Reproduce

1. Open Fellowship
2. Open Last events - View list
3. Enter into search field seadanda
 - List filtered by seadanda
4. Enter into search field seadanda's address - 142zGifFwRrDbFLJD7LvbyoHQAqDaXeHjkxJbUVwmDYBD7Gf

## Expected Behavior

List filtered by seadanda

## Actual Behavior

Empty list

Image

### LINKED ISSUE #3491: Fellowship. View list page - Empty state looks wrong
Image

### PR DESCRIPTION
**Pull request by aaa123eee**
## Description

small bugs fixes

## Related Issues

closes #3489
closes #3490
closes #3491

## Changes Made

- prevent 0 in template
- search by accountId
- truncate presentation of long queries

## Screenshots

image

### CODE REVIEW

File: src/renderer/features/fellowship-activity-feed/components/ActivityModal.tsx [hunk 1]
```diff
@@ -50,6 +50,8 @@ export const ActivityModal = ({ children }: PropsWithChildren) => {
     };
   });
 
+  console.log({ records });
```
Comment (johnthecat) [inline src/renderer/features/fellowship-activity-feed/components/ActivityModal.tsx]: Remove plz

**Review by johnthecat — APPROVED** [review]

File: src/renderer/features/fellowship-activity-feed/components/ActivityModal.tsx (hunk 1 above)
Comment (aaa123eee) [inline src/renderer/features/fellowship-activity-feed/components/ActivityModal.tsx]:
```suggestion
```

File: src/renderer/features/fellowship-activity-feed/components/ActivityModal.tsx [hunk 2]
```diff
@@ -50,6 +50,7 @@ export const ActivityModal = ({ children }: PropsWithChildren) => {
     };
   });
 
+
```
Comment (aaa123eee) [inline src/renderer/features/fellowship-activity-feed/components/ActivityModal.tsx]:
```suggestion
```
