### PR TITLE
Fix: show previous conviction on edit delegation from basket

### LINKED ISSUE #3025: Basket. Crash when open transaction
## Description

When user open basket operation - crash the app

```
Uncaught RangeError: Invalid time value
```

## Test data:

[spektr-database.json](https://github.com/user-attachments/files/18516695/spektr-database.json)

## Steps to Reproduce

1. Add governance operation to the Basket
2. Go to the basket
3. Try to sign operations

## Expected Behavior

Can be signed

## Actual Behavior

Error

Image

https://github.com/user-attachments/assets/cd3d3d85-3a8f-4982-9004-40803688b6d7

## Environment
https://github.com/novasamatech/nova-spektr/commit/b445163ad4a06b84a8cf4f40d57dff76118bf65f

### PR DESCRIPTION
**Pull request by Asmadek**
fix: save data about previous conviction to basket tx

### CODE REVIEW

File: src/renderer/widgets/EditDelegationModal/model/edit-delegation-model.ts [hunk 1]
```diff
@@ -218,6 +218,7 @@ sample({
         accountId: shard.accountId,
         balance: amount || '0',
         conviction: conviction || 'None',
+        previousConviction: activeDelegations[address].conviction || 'None',
```
Comment (johnthecat) [inline src/renderer/widgets/EditDelegationModal/model/edit-delegation-model.ts:221]: What if there is no active delegation for this address? It will crash

**Review by johnthecat — APPROVED** [review]

File: src/renderer/widgets/EditDelegationModal/model/edit-delegation-model.ts (hunk 1 above)
Comment (Asmadek) [reply src/renderer/widgets/EditDelegationModal/model/edit-delegation-model.ts:221]: For `edit delegation operation` active delegation always exists. If it doesn't exist it will be `delegate operation`
