### PR TITLE
Removed duplicate price requests

### LINKED ISSUE #2011: Multisig. Every time, when opens Operations page it send request to coingecko
## Description
When user opens Operations page it sends request to coingeko. That lead to block by request limits with 429 error

https://github.com/user-attachments/assets/3a735ec9-7611-4b24-99aa-b365c578a499

## Steps to Reproduce

1. Open dev-tools
2. Go to Network tab
3. Open Operations page in the app several times

## Expected Behavior
Use coingeko prices from local storage

## Actual Behavior
Request to coingeko is sent for each transfer on Operations page

## Environment
https://github.com/novasamatech/nova-spektr/commit/285a866ace2a82902e4c1017492b05e98a657e6f

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
When user opens Operations page it sends request to coingeko. That lead to block by request limits with 429 error

## Related Issues
Closes #2011

## Changes Made
Removed duplicate price requests. Prices now fetch once when activeCurrency loads.

### CODE REVIEW

File: src/renderer/entities/price/model/price-provider-model.ts [hunk 1]
```diff
@@ -62,6 +61,24 @@ sample({
...
+    return {
+      chains: Object.values(chains),
+      provider: provider!,
+      currencies: [currency!.coingeckoId],
+      includeRates: true,
+    };
+  },
+  target: fetchAssetsPricesFx,
+});
+
```
Comment (cuteWarmFrog) [inline src/renderer/entities/price/model/price-provider-model.ts]:
```
sample({
  clock: currencyModel.$activeCurrency,
  source: { chains: networkModel.$chains, provider: $priceProvider },
  filter: ({ provider }, currency) => {
    return provider !== null && currency !== null;
  },
  fn: ({ chains, provider }, currency) => {
    return {
      chains: Object.values(chains),
      provider: provider!,
      currencies: [currency!.coingeckoId],
      includeRates: true,
    };
  },
  target: fetchAssetsPricesFx,
});

```

Comment (cuteWarmFrog) [reply src/renderer/entities/price/model/price-provider-model.ts]: you don't need typings in such callbacks, ts can infer them

Comment (Yanaty) [reply src/renderer/entities/price/model/price-provider-model.ts]: fixed

File: src/renderer/entities/price/model/price-provider-model.ts [hunk 2]
```diff
@@ -62,6 +61,23 @@ sample({
   target: [getFiatFlagFx, getPriceProviderFx, getAssetsPricesFx],
 });
 
+sample({
+  clock: currencyModel.$activeCurrency,
+  source: { chains: networkModel.$chains, provider: $priceProvider },
+  filter: ({ provider }, currency) => {
+    return provider !== null && currency !== null;
+  },
```
Comment (aaa123eee) [inline src/renderer/entities/price/model/price-provider-model.ts]:
```suggestion
  filter: ({ provider }, currency) => nonNullable(provider) && nonNullable(currency),
```

**Review by aaa123eee — APPROVED** [review]

**Review by cuteWarmFrog — APPROVED** [review]

File: src/renderer/entities/price/model/price-provider-model.ts (hunk 2 above)
Comment (Yanaty) [reply src/renderer/entities/price/model/price-provider-model.ts]: fixed
