### PR TITLE
Fix: multisig update delete flow and fix bugs

### LINKED ISSUE #2495: Multisig. Signatories does not match with address book\wallets
## Description

If user add someone to Address Book, there is no changes in Multisig signatories.

Example:

https://github.com/user-attachments/assets/59be5d6f-1caa-40d5-a7c9-091766fa0ed2

## Steps to Reproduce

1. Add to Address book someone from your signatories list in one of the Multisigs
2. Open Multisig details again

## Expected Behavior
Shows name and address from Address Book

## Actual Behavior
There is no changes

## Environment
https://github.com/novasamatech/nova-spektr/commit/6ca515af94bd4d44ea25ada390bcc01455cd4bc4

### LINKED ISSUE #2532: Multisig. Previously selected network is left on reopen
## Description

Example:

https://github.com/user-attachments/assets/1a034fe8-3771-4df1-adb7-7d8bb7cbe629

**Expected result:**

reset to default network

## Environment
https://github.com/novasamatech/nova-spektr/pull/2523

### PR DESCRIPTION
**Pull request by sokolova-an**
Updated delete flow as discussed 
Closes https://github.com/novasamatech/nova-spektr/issues/2495
Closes https://github.com/novasamatech/nova-spektr/issues/2532

### CODE REVIEW

**Comment by pgolovkin** [comment]
@sokolova-an Works well, thanks!

File: src/renderer/widgets/CreateWallet/model/flow-model.ts [hunk 1]
```diff
@@ -373,6 +381,20 @@ sample({
...
+sample({
+  clock: submitModel.output.formSubmitted,
+  source: {
+    step: $step,
+    hiddenMultisig: formModel.$hiddenMultisig,
+  },
+  filter: ({ step }, results) =>
+    isStep(step, Step.SUBMIT) &&
+    nonNullable(formModel.$hiddenMultisig) &&
+    results[0]?.result === ExtrinsicResult.SUCCESS,
```
Comment (Asmadek) [inline src/renderer/widgets/CreateWallet/model/flow-model.ts]:
```suggestion
  filter: ({ step }, results) => {
    const isSubmitStep = isStep(step, Step.SUBMIT);
    const isNonNullable = nonNullable(formModel.$hiddenMultisig);
    const isSuccessResult = results[0]?.result === ExtrinsicResult.SUCCESS;
    
    return isSubmitStep && isNonNullable && isSuccessResult;
  },
```

**Review by Asmadek — APPROVED** [review]

File: src/renderer/entities/wallet/model/wallet-model.ts [hunk 2]
```diff
@@ -297,6 +292,8 @@ export const walletModel = {
   $hiddenWallets,
   $activeWallet,
   $isLoadingWallets: fetchAllWalletsFx.pending,
+  // for tests
+  $allWallets,
```
Comment (tuul-wq) [inline src/renderer/entities/wallet/model/wallet-model.ts]: Can define `_test` property, special for model testing
```javascript
_test: {
  $allWallets,
},
```

File: src/renderer/features/wallets/ForgetWallet/model/__tests__/forget-wallet-model.test.ts [hunk 3]
```diff
@@ -114,14 +114,14 @@ describe('features/wallets/ForgetModel', () => {
...
-      values: new Map().set(walletModel.$wallets, [wallet]),
+      values: new Map().set(walletModel.$allWallets, [wallet]),
     });
 
     await allSettled(forgetWalletModel.events.callbacksChanged, { scope, params: { onDeleteFinished: () => {} } });
     await allSettled(forgetWalletModel.events.forgetWallet, { scope, params: wallet });
 
-    expect(spyDeleteWallet).toBeCalledWith(1);
-    expect(spyDeleteAccounts).toBeCalledWith([1, 2]);
+    expect(spyDeleteWallet).toHaveBeenCalledWith(1);
```
Comment (tuul-wq) [inline src/renderer/features/wallets/ForgetWallet/model/__tests__/forget-wallet-model.test.ts:123]: Viva correct grammar 🙌

File: src/renderer/entities/wallet/model/wallet-model.ts [hunk 4]
```diff
@@ -38,6 +38,7 @@ const walletsRemoved = createEvent<ID[]>();
 
 const $wallets = createStore<Wallet[]>([]);
 const $hiddenWallets = createStore<Wallet[]>([]);
+const $allWallets = createStore<Wallet[]>([]);
```
Comment (tuul-wq) [inline src/renderer/entities/wallet/model/wallet-model.ts:41]: Could you please describe for a "new comer" why do we have 2 similar stores?
Taking into account that I was pretty confused by the naming, maybe we should consider different explicit naming for this store?

File: src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts [hunk 5]
```diff
@@ -62,17 +63,27 @@ const $signatoryContacts = combine(
   {
     wallet: walletSelectModel.$walletForDetails,
     wallets: walletModel.$wallets,
+    contacts: contactModel.$contacts,
   },
-  ({ wallet, wallets }): Signatory[] => {
+  ({ wallet, wallets, contacts }): Signatory[] => {
```
Comment (tuul-wq) [inline src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts:68]: We can make this `combine` even better:
```javascript
const $signatoryContacts = combine(
  {
    wallet: walletSelectModel.$walletForDetails,
    wallets: walletModel.$wallets,
    contacts: contactModel.$contacts,
  },
  ({ wallet, wallets, contacts }): Signatory[] => {
    if (!wallet || !walletUtils.isMultisig(wallet)) return [];

    const contactsMap = dictionary(contacts, 'accountId');
    const signatoriesMap = dictionary(wallet.accounts[0].signatories, 'accountId');
    const allSignatories = walletUtils.getAccountsBy(wallets, ({ accountId }) => signatoriesMap[accountId]);
    const signatoriesSet = new Set(allSignatories.map((signatory) => signatory.accountId));

    return wallet.accounts[0].signatories
      .filter((signatory) => !signatoriesSet.has(signatory.accountId))
      .map((signatory) => ({ ...signatory, name: contactsMap[signatory.accountId]?.name }));
  },
);
```

File: src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts [hunk 6]
```diff
@@ -108,9 +119,14 @@ const $signatoryAccounts = combine(
     const allSignatories = walletUtils.getAccountsBy(wallets, ({ accountId }) => signatoriesMap[accountId]);
     const uniqueSignatories = uniqBy(allSignatories, 'accountId');
 
-    return wallet.accounts[0].signatories.filter((signatory) => {
-      return uniqueSignatories.some((s) => s.accountId === signatory.accountId);
-    });
+    return wallet.accounts[0].signatories.reduce<Signatory[]>((acc, signatory) => {
+      const matchingSignatory = uniqueSignatories.find((s) => s.accountId === signatory.accountId);
```
Comment (tuul-wq) [inline src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts]: Can use `dictionary` for `signatoriesMap` and replace `reduce` with `filter > map`

**Review by tuul-wq — COMMENTED** [review]
A couple of suggestions

File: src/renderer/entities/wallet/model/wallet-model.ts (hunk 4 above)
Comment (sokolova-an) [reply src/renderer/entities/wallet/model/wallet-model.ts:41]: It's an abstraction that is used only in this file to combine hidden and visible wallets (can't use combine tho, since it's used as a target in samples) 
The reason is actions that happen with wallets can happen to all of them (deleting, updating, etc) so instead of having 2 separate samples for each case (for hidden and regular wallets) or using spread every time I added this store.
When we separate wallets from logic and will use them only as an abstraction - the rest of the stores can be only a map\combine from this one

**Review by johnthecat — APPROVED** [review]
