### PR TITLE
fix: hide networks for switched off accounts (Polkadot Vault wallet)

### LINKED ISSUE #1860: Polkadot Vault. wallet_pv networks with switched off accounts shows in loading state
## Description
When user import Polkadot Vault wallet (dynamic derivation one) with default setup (polkadot/kusama/westend) and switch off one of accounts on assets page - it will show with unending shimmering state.

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/48f4d4ab-00e6-4853-9994-c8126bb9eb8e

</details>

## Steps to Reproduce

1. Add Polkadot Vault wallet (wallet_pv type)
2. Go to portfolio
3. Disable any account

## Expected Behavior
Networks does not show for disabled accounts

## Actual Behavior
Networks with disabled accounts are shown with shimmering

Screenshot 2024-06-12 at 16 49 48

### PR DESCRIPTION
**Pull request by savvyer**
## Description
I thought it would make sense to do tokens filtering inside the effector portfolio-model.ts instead of react component useEffect like its done for `AssetsChainView`.

## Related Issues
Closes https://github.com/novasamatech/nova-spektr/issues/1860

## Changes Made
Added `$activeShards` store to portfolio-model.ts to filter out switched off Polkadot Vault wallet accounts by `ShardSelectorModal`.

### CODE REVIEW

File: src/renderer/features/assets/AssetsPortfolioView/model/portfolio-model.ts [hunk 1]
```diff
@@ -27,6 +28,18 @@ const $query = restore<string>(queryChanged, '');
 
 const $defaultTokens = createStore(tokensService.getTokensData());
 
+const $activeShards = createStore<AnyAccount[]>([]);
```
Comment (aaa123eee) [inline src/renderer/features/assets/AssetsPortfolioView/model/portfolio-model.ts]: maybe default is null? that's how we can distinguish a pending state

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/features/assets/AssetsPortfolioView/model/portfolio-model.ts (hunk 1 above)
Comment (savvyer) [reply src/renderer/features/assets/AssetsPortfolioView/model/portfolio-model.ts]: Good point. Pushed an update https://github.com/novasamatech/nova-spektr/pull/3620/commits/568b8c90c363171f03614f6f333274920a8e128c

**Review by sokolova-an — APPROVED** [review]

**Review by johnthecat — APPROVED** [review]

**Review by tuul-wq — APPROVED** [review]
This is probably not a big issue, but let's name branches less verbose 😄
