### PR TITLE
fix: tracks field in operations

### LINKED ISSUE #2303: Governance. Multisig. Unlock operations contains redundant parameter.
## Description

Unlock contains "Tracks" param:

Screenshot 2024-09-06 at 13 47 38

## Environment
v1.10.0

### PR DESCRIPTION
**Pull request by sokolova-an**

### CODE REVIEW

**Review by Asmadek — APPROVED** [review]

File: src/renderer/pages/Operations/common/utils.ts [hunk 1]
```diff
@@ -225,6 +225,8 @@ export const getDelegationTracks = (tx: MultisigTransaction): string[] | undefin
     coreTxs = [tx.transaction];
   }
 
+  if (!coreTxs.length) return;
+
   return coreTxs?.map((tx: Transaction) => tx.args.track.toString());
```
Comment (johnthecat) [inline src/renderer/pages/Operations/common/utils.ts]: Remove nullish check for `coreTxs` please
