### PR TITLE
Fix/wc connection UI glitch

### LINKED ISSUE #4687: Wallet Connect. Connection UI glitch
## Description

When connect to the wallet connect for a few milliseconds appear a glitch

Example:

https://github.com/user-attachments/assets/803398ee-31ec-453a-b55c-e8008d308e83

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
Fix UI glitch occurring during WalletConnect connection

## Related Issues
Closes #4687.

## Changes Made
The issue was with incorrect height and positioning of the block

## Screenshots/Recordings

https://github.com/user-attachments/assets/8d423f3f-af7c-4827-b830-48fa6cd68bda

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/wallet-connect-wallet-pairing/components/PairingModal.tsx [hunk 1]
```diff
@@ -103,44 +103,46 @@ export const PairingModal = memo(({ variant, children }: Props) => {
...
-        <Carousel item={step.toString()} fixedHeight>
-          <Carousel.Item id={Step.SCAN.toString()} index={0}>
-            <div className="flex h-full w-full">
-              <div className="flex w-full max-w-[472px] min-w-96 flex-col rounded-l-lg bg-white px-5 py-4">
-                <HeaderTitleText className="mb-10">{header}</HeaderTitleText>
-                <SmallTitleText className="mb-6">{scanTitle}</SmallTitleText>
-
-                <div className="py-7">
-                  <WalletConnectQrCode uri={uri} type={variant} />
+        <div className="relative min-h-[600px]">
```
Comment (johnthecat) [inline src/renderer/features/wallet-connect-wallet-pairing/components/PairingModal.tsx]: let's move relative class to Modal.Content itself, i think it will be reasonable

**Review by johnthecat — APPROVED** [review]

**Review by cuteWarmFrog — APPROVED** [review]

File: src/renderer/features/wallet-connect-wallet-pairing/components/PairingModal.tsx (hunk 1 above)
Comment (Yanaty) [reply src/renderer/features/wallet-connect-wallet-pairing/components/PairingModal.tsx]: moved
