### PR TITLE
fix: delegation tracks modal

### LINKED ISSUE #2127: Governance. Tracks. Tooltip should'n be hardcoded DOT
## Description

There is hardcoded "DOT" text in tooltips:
https://github.com/novasamatech/nova-spektr/blob/b3dfe1e8998b804a7576a620007ea616f19c2b4f/src/renderer/shared/api/translation/locales/en.json#L403-L413

## Environment
https://github.com/novasamatech/nova-spektr/commit/b684d4d72c57f1886b1f49125131fafe6db13165

### LINKED ISSUE #2130: Governance. Add delegation has wrong width
## Description

Screenshot 2024-08-19 at 11 50 29

## Environment
https://github.com/novasamatech/nova-spektr/commit/b684d4d72c57f1886b1f49125131fafe6db13165

### PR DESCRIPTION
**Pull request by sokolova-an**
- Changed the order of delegation tracks according to the design
- Fixed tooltip text
- Fixed modal width

### CODE REVIEW

File: src/renderer/widgets/DelegateModal/lib/helpers.ts [hunk 1]
```diff
@@ -1 +1,13 @@
-export const helpers = {};
+import { type TFunction } from 'i18next';
+
+import { type Asset } from '@/shared/core';
+
+import { treasurySpendsDescription } from './constants';
+
+export const getTreasuryTrackDescription = (asset: Asset | null, description: string, t: TFunction) => {
+  if (asset && treasurySpendsDescription[description][asset.symbol]) {
```
Comment (johnthecat) [inline src/renderer/widgets/DelegateModal/lib/helpers.ts]: This check may crash, add nullish coalescing here

**Review by johnthecat — APPROVED** [review]

**Review by Asmadek — APPROVED** [review]
