### PR TITLE
Fix: warning message show

### LINKED ISSUE #1921: Basket. Staking. Can't return to stake.
## Description
`Insufficient balance to pay network fee` for Return to stake operation, but account has available balance.

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/1a3a6ee6-5771-4df2-9fab-64fe684381e3

</details>

## Test data:
[accounts.json](https://github.com/user-attachments/files/16078799/accounts.json)
[balances.json](https://github.com/user-attachments/files/16078800/balances.json)
[basketTransactions.json](https://github.com/user-attachments/files/16078802/basketTransactions.json)
[wallets.json](https://github.com/user-attachments/files/16078803/wallets.json)

## Steps to Reproduce

1. Go to Staking page
2. Make operation to Unstake
3. Add operation to Return to stake to the Basket
4. Go to Basket page

## Expected Behavior
Can successfully sign operation

## Actual Behavior
Insufficient balance to pay network fee

## Environment
https://github.com/novasamatech/nova-spektr/commit/1ae131716001a9ac28e5f27e92928f57cc78bff0

### LINKED ISSUE #1923: Basket. Revoke delegated authority. Not enough tokens.
## Description
When user wants to remove delegated authority via basket that shows - Not enough tokens

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/e36847b9-42f8-429b-9e1e-f2dab1babd81

</details>

## Test data:
[accounts.json](https://github.com/user-attachments/files/16080705/accounts.json)
[balances.json](https://github.com/user-attachments/files/16080706/balances.json)
[basketTransactions.json](https://github.com/user-attachments/files/16080707/basketTransactions.json)
[wallets.json](https://github.com/user-attachments/files/16080709/wallets.json)

## Steps to Reproduce

1. Go to wallet details
2. Create remove delegated authority operation
3. Add it to the basket
4. Go to basket

## Expected Behavior
Operation can be submitted from the Basket

## Actual Behavior
Can't submit operation due to validation error

## Environment
https://github.com/novasamatech/nova-spektr/commit/26375fd5c68dbf6348f26b4c69bfa75e97fee650

### LINKED ISSUE #1926: Basket. Validations. Wrong validation for Stake more
## Description
Shows `Not enough funds to complete operation`, but actually account has that founds

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/550d3651-52ce-4110-88e8-e0b77a11f5b1

</details>

## Test data:
[accounts.json](https://github.com/user-attachments/files/16085818/accounts.json)
[balances.json](https://github.com/user-attachments/files/16085821/balances.json)
[basketTransactions.json](https://github.com/user-attachments/files/16085822/basketTransactions.json)
[wallets.json](https://github.com/user-attachments/files/16085823/wallets.json)

## Steps to Reproduce

1. Go to staking page with wallet from test data
2. Create operation for Stake more 0.1 WND
3. Add this operation to the basket
4. Go to the basket

## Expected Behavior
Can successfully sign the operation

## Actual Behavior
`Not enough funds to complete operation` validation error

## Environment
https://github.com/novasamatech/nova-spektr/commit/36c791f377a0a3f16c7fca5cc1945b59428d328c

### LINKED ISSUE #1939: Basket. After trigger error "operations has not been executed" will show that error again, even if operation was success
## Description
Triggers "operations has not been executed" each time after trigger it once.

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/709e3ef7-f835-4aad-9a84-6851c7a32e53

</details>

## Steps to Reproduce

1. Add to basket two transfer operations with amount: transfer_amount *2 > transferable_balance
2. Sign both operations
3. Will trigger "1 of 2 operations has not been executed"
Screenshot 2024-07-10 at 10 02 11

4. Add amount on account
5. Sign failed operations again

## Expected Behavior
Successfully sign, show success pop-up

## Actual Behavior
Will show "operations has not been executed" again, but operation was sent

## Environment
https://github.com/novasamatech/nova-spektr/commit/c9856170c6b6cb10cf36f0332e6bb1da8f7ee4de

### PR DESCRIPTION
**Pull request by Asmadek**
* reset results for submit
* wait confirm store will be created
* use get balance function instead do it manually 
* validate txs on change wallet

### CODE REVIEW

File: src/renderer/features/operations/OperationsValidation/model/unstake-validate-model.ts [hunk 1]
```diff
@@ -29,9 +29,7 @@ const validateFx = createEffect(
     const accountId = toAccountId(transaction.address);
     const fee = await transactionService.getTransactionFee(transaction, api, signerOptions);
 
-    const shardBalance = balances.find(
-      (balance) => balance.accountId === accountId && balance.assetId === asset.assetId.toString(),
-    );
+    const shardBalance = balanceUtils.getBalance(balances, accountId, chain.chainId, asset.assetId.toString());
```
Comment (johnthecat) [inline src/renderer/features/operations/OperationsValidation/model/unstake-validate-model.ts:32]: Can you use `balanceUtils.getBalance` function here?

**Review by johnthecat — APPROVED** [review]
