### PR TITLE
fix: refactored portfolio model, now all values are derived

### LINKED ISSUE #2770: Portfolio view. Token balance doesn't match sum of token balances in networks
Token balance doesn't match sum of token balances in networks.

Image

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #2770

### CODE REVIEW

**Review by antonkhvorov — APPROVED** [review]

File: src/renderer/features/assets/AssetsPortfolioView/lib/tokensService.ts [hunk 1]
```diff
@@ -80,28 +75,38 @@ function getChainWithBalance(
...
-  return [chainsWithBalance, totalBalance];
+  return chainsWithBalance;
+}
+
+function calculateTotalBalance(assets: AssetChain[]) {
+  let totalBalance: AssetBalance = {};
+
+  for (const asset of assets) {
+    totalBalance = sumTokenBalances(totalBalance, asset.balance);
+  }
```
Comment (Asmadek) [inline src/renderer/features/assets/AssetsPortfolioView/lib/tokensService.ts]: Maybe? 

```suggestion
  for (const { balance } of assets) {
    totalBalance = sumTokenBalances(totalBalance, balance);
  }
```

File: src/renderer/features/assets/AssetsPortfolioView/model/portfolio-model.ts [hunk 2]
```diff
@@ -21,97 +23,54 @@ const $hideZeroBalances = restore(hideZeroBalancesChanged, false);
...
-  for (const token of tokens) {
-    const filteredChains = token.chains.filter((chain) => {
-      return activeWallet?.accounts.some((account) => {
-        return (
-          accountUtils.isNonBaseVaultAccount(account, activeWallet) &&
-          accountUtils.isChainAndCryptoMatch(account, chains[chain.chainId])
-        );
-      });
-    });
+const $basicTokens = createStore(tokensService.getTokensData());
```
Comment (Asmadek) [inline src/renderer/features/assets/AssetsPortfolioView/model/portfolio-model.ts]: I am not clearly understand after first view what `basicTokens` means. Maybe call it `defaultTokens`?

**Review by Asmadek — APPROVED** [review]
