### PR TITLE
fix: correct available calculation in transfer form

### LINKED ISSUE #4904: MAX button. Shows a validation error for MAX button usage
## Description

User see validation error for MAX button usage

## Steps to Reproduce

[spektr-database.json](https://github.com/user-attachments/files/22999835/spektr-database.json)

1. Import test database
2. Select test_account
3. Go to DOT transfer on Polkadot
4. Click MAX

## Expected Behavior

There is no validation error

## Actual Behavior

Validation error is shown:

Image

Image

### LINKED ISSUE #4908: Max button. Incorrect validation logic for available balance with “Max” button and ED toggle
## Description

The transfer form uses wrong conditions when calculating available balance and deciding when to show the Max button, the ED (keep-alive) toggle, and the ED warning alert.

Correct logic should be:

- Show “Max” button when available > 0.
- Show ED toggle (Keep alive / Allow death) when keepAliveAvailable != allowDeathAvailable (keepAliveAvailable > allowDeathAvailable).
- Show ED alert when 0 < (countedTowardsED - amount) < ED (note the strict inequalities).

## Steps to Reproduce

- Open the transfer form for an account named 'test' from the attached db.
- Open transfer MYTH tokens.
- Switch between on-chain and xcm-transfer using Max button.
- Observe that visibility of Max, ED toggle, and ED alert does not match the expected rules above.

## Expected Behavior

- Max is visible only if available > 0.
- ED toggle is visible only when the computed sendable amounts differ between keep-alive and allow-death paths.
- ED alert appears only when the sent amount would reduce the ED cushion such that 0 < (countedTowardsED - amount) < ED.

## Actual Behavior

UI controls/alerts appear or disappear at incorrect times due to wrong comparison logic.

## Database

[max_ed_test.json](https://github.com/user-attachments/files/23015290/max_ed_test.json)

### PR DESCRIPTION
**Pull request by aaa123eee**
## Related Issues

closes #4908
closes #4904

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [x] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/shared/transactions/createTxValidationStore.ts [hunk 1]
```diff
@@ -37,6 +45,22 @@ export const createTxValidationStore = <Validator extends AnyValidator>({ params
...
+    const { $: $localAvailable } = createStoreFromEffect({
+      params: {
+        ...params,
+        excludeActions: createStore(calculateAvailable.exclude),
+      },
+      defaultValue: { errors: [], balanceValidationResults: [], available: [] },
+      fn: validator,
+    });
+
+    $available = $localAvailable.map((v) => v.available);
```
Comment (aaa123eee) [inline src/renderer/shared/transactions/createTxValidationStore.ts:59]: @johnthecat can't we just reuse the one from line 30 with conditional `excludeActions` param?

File: src/renderer/widgets/Transfer/default/model/form-model.ts [hunk 2]
```diff
@@ -425,36 +428,28 @@ sample({
...
-    totalFee: $totalFee,
-    isExistentialDepositEnabled: $isExistentialDepositEnabled,
+    balance: $availableBalance,
+    balancePreservationStrategy: $balancePreservationStrategy,
   },
-  filter: ({ balance, totalFee }) => nonNullable(balance) && nonNullable(totalFee),
-  fn: ({ balance, totalFee, isExistentialDepositEnabled }) => {
-    return getAvailableAmount({ balance: balance!, totalFee: totalFee!, includeED: isExistentialDepositEnabled });
+  fn: ({ balance, balancePreservationStrategy }) => {
+    if (nullable(balance)) return BN_ZERO;
```
Comment (aaa123eee) [inline src/renderer/widgets/Transfer/default/model/form-model.ts:450]: @johnthecat sometimes we face issues because of syntetic (and incorrect) zero fallbacks

maybe filtering was a good approach?

**Review by aaa123eee — COMMENTED** [review]
tested, looks good overall

we can merge

**Review by johnthecat — APPROVED** [review]

**Review by johnthecat — APPROVED** [review]
