### PR TITLE
fix: flexible change signatories proxy deposit for pure proxied

### LINKED ISSUE #4700: Flexible multisig. Edit flow. Wrong validation for proxy deposit
## Description

There is a wrong validation for proxy deposit.

Image

In Edit flow we need to check:
- Signatory
1. He can pay network fee
2. He can pay for the multisig deposit

- Flexible multisig account (actual pure proxy)
1. He can pay for add_proxy connection

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Validator flexible change signatories proxy deposit for pure proxied

## Related Issues
Closes #4700

## Screenshots/Recordings
image
image

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/flexible-change-signatories/model/change-signatories-model.ts [hunk 1]
```diff
@@ -179,7 +181,29 @@ const { $tx, $fee, $pendingFee } = createComplexTxStore({
...
+  additionalBalanceRules: [
+    ({ route, getBalance, asset, api }) => {
+      const initiator = accountService.findInitiator(route);
+      if (!initiator || !accountUtils.isFlexibleMultisigAccount(initiator)) return;
+
+      const balance = getBalance(initiator.accountId, initiator.chainId, asset.assetId);
+
+      if (nullable(balance)) return;
+
+      const deposit = proxyService.getProxyDeposit(api, '0', 1);
```
Comment (valentunn) [inline src/renderer/features/flexible-change-signatories/model/change-signatories-model.ts]: This is not correct - at this point, there is already a proxy deposit made, so the runtime wont charge use the full `deposit + factor` bur rather just `factor`

This can be accounted by passing already existing deposit instead of `'0'` here
Also we should use `proxyNumber + 1` here since we cannot guarantee this flex msig has just 1 proxy, not to mentioned it will be 2 not 1, since we are adding second proxy in the simplest case

File: src/renderer/features/operations/OperationsValidation/lib/add-proxy-rules.ts [hunk 2]
```diff
@@ -74,4 +76,26 @@ export const AddProxyRules = {
...
+      const initiator = accountService.findInitiator(route);
+      if (!initiator) return;
+
+      const chainId = api.genesisHash.toHex();
+
+      const balance = getBalance(initiator.accountId, chainId, asset.assetId);
+
+      if (nullable(balance)) return;
+
+      const deposit = proxyService.getProxyDeposit(api, '0', proxyNumber + 1);
```
Comment (valentunn) [inline src/renderer/features/operations/OperationsValidation/lib/add-proxy-rules.ts]: Same here. We should use existing deposit here instead of '0'. Overall, '0' can only be used if it is the very `first` proxy being created

**Review by valentunn — CHANGES_REQUESTED** [review]

**Review by valentunn — APPROVED** [review]
