### PR TITLE
fix: changed old popover for custom new one

### LINKED ISSUE #4194: Info popover layout is broken on 'Delegated authorities' tab of Wallet details modal
## Description

In the Wallet details modal, on the Delegated authorities tab, the layout of the info popover (triggered by the Open info button in ellipsis menu) is incorrect.

## Steps to Reproduce

1. Open the Wallet Info modal for any account with delegated authority.
2. Navigate to the Delegated authorities tab.
3. Open the ellipsis menu (three horizontal dots)
4. Click on the Open info button to open the info popover.

## Expected Behavior

The popover should be properly aligned, styled with consistent padding, background, and width.

## Actual Behavior

The popover is visually broken

Image

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Instead of PopoverExporers using castom layout

## Related Issues
closes #4194

### CODE REVIEW

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/features/wallet-details/ui/components/ProxyAccountWithActions.tsx [hunk 1]
```diff
@@ -40,25 +35,50 @@ export const ProxyAccountWithActions = ({ account, chain, canCreateProxy, onRemo
...
+                        {t('walletDetails.common.openInfoAction')}
+                      </FootnoteText>
+                    </button>
+                  </Popover.Trigger>
+                  <Popover.Content>
+                    <Box width="230px" gap={2} padding={4}>
+                      <FootnoteText className="text-text-tertiary">{t('general.explorers.addressTitle')}</FootnoteText>
+                      <Box direction="row" verticalAlign="center" gap={3}>
+                        <HelpText className="text-text-secondary">
+                          <Hash value={proxyAddress} variant="full" />
```
Comment (johnthecat) [inline src/renderer/features/wallet-details/ui/components/ProxyAccountWithActions.tsx]: Use Address component instead

**Review by johnthecat — APPROVED** [review]
