### PR TITLE
fix: avoid closed state for modal

### LINKED ISSUE #3194: Governance. Referendum interactions can be broken
## Description

When user interact with referendums it may broke and stop open new referenda details

Example:

https://github.com/user-attachments/assets/e5eb7bf6-d04e-4a99-8590-e657bb472f32

## Steps to Reproduce

1. Go to governance page
2. Open a fiew referendums

## Actual Behavior
View may broke and stop open new referendums

## Environment
v1.14.4

### PR DESCRIPTION
**Pull request by aaa123eee**
## Description

We use modal style for page but it can never be closed until navigated out. It only causes race condition bugs

closes #3194

### CODE REVIEW

**Review by johnthecat — APPROVED** [review]

File: src/renderer/features/governance/components/ReferendumDetails/ReferendumDetailsModal.tsx [hunk 1]
```diff
@@ -58,16 +58,17 @@ export const ReferendumDetailsModal = ({
...
     store: proposerIdentityAggregate.$proposers,
     keys: [referendum.votedByDelegate?.delegateId],
     fn: (proposers, [delegateId]) => (delegateId ? (proposers[delegateId] ?? null) : null),
   });
 
+  const closeModal = (open: boolean) => !open && onClose();
+
   return (
-    <Modal isOpen={isModalOpen} size="xl" onToggle={closeModal}>
+    <Modal isOpen={true} size="xl" onToggle={closeModal}>
```
Comment (tuul-wq) [inline src/renderer/features/governance/components/ReferendumDetails/ReferendumDetailsModal.tsx]:
```suggestion
    <Modal isOpen size="xl" onToggle={closeModal}>
```

File: src/renderer/features/governance/components/ReferendumDetails/ReferendumDetailsModal.tsx [hunk 2]
```diff
@@ -58,16 +58,17 @@ export const ReferendumDetailsModal = ({
...
   const [showAdvanced, toggleShowAdvanced] = useToggle();
-  const [isModalOpen, closeModal] = useModalClose(true, onClose);
 
   const voter = useStoreMap({
     store: proposerIdentityAggregate.$proposers,
     keys: [referendum.votedByDelegate?.delegateId],
     fn: (proposers, [delegateId]) => (delegateId ? (proposers[delegateId] ?? null) : null),
   });
 
+  const closeModal = (open: boolean) => !open && onClose();
```
Comment (tuul-wq) [inline src/renderer/features/governance/components/ReferendumDetails/ReferendumDetailsModal.tsx]: Let's stick to verbose style when calling functions depending on condition

```suggestion
  const closeModal = (open: boolean) => {
    if (open) return;
    onClose();
  };
```

**Review by tuul-wq — APPROVED** [review]
Little suggestions
