### PR TITLE
fix(operations): parse account id for proxy wraps

### LINKED ISSUE #5543: Operations created from regular multisig are incorrectly classified as flex multisig operations
## Description

When creating an operation directly from a regular multisig of any flex multisig, it is incorrectly shown in the operations list as a flex multisig operation.

https://github.com/user-attachments/assets/1d0ade18-9543-4550-88cc-93b63a0eaf72

### PR DESCRIPTION
**Pull request by aaa123eee**
## Description

Return proxied account id instead of multisig account if for flex operations

## Related Issues

closes #5543

## Changes Made

- find proxied id in proxy wraps
- find proxied id in batches (because of nova wallet)

## Screenshots/Recordings

image

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

**Review by cuteWarmFrog — DISMISSED** [review]

File: src/renderer/features/multisig-operations/model/context.ts [hunk 1]
```diff
@@ -152,8 +151,7 @@ const $multisigAccountsMap = accounts.$list.map(accs => {
   const record: Record<string, MultisigAccount | FlexibleMultisigAccount> = {};
 
   for (const account of multisigAccounts) {
-    const multisigAccountId = multisigService.getMultisigAccountId(account);
-    record[multisigAccountId] = account;
```
Comment (savvyer) [inline src/renderer/features/multisig-operations/model/context.ts:180]: I guess we need to update the OperationsFilter.tsx,
from:
```
      id: multisigService.getMultisigAccountId(multisigAccount),
      value: multisigService.getMultisigAccountId(multisigAccount),
```
to:
```
id: multisigAccount.accountId,
value: multisigAccount.accountId,
```

**Review by savvyer — APPROVED** [review]
