### PR TITLE
fix: correct proxy usage for multisig

### LINKED ISSUE #2647: Multisig. Correct Proxy usage
## Description

To avoid confusing the user the Proxy wallets should be hide by using [isValidSignatory](https://github.com/novasamatech/nova-spektr/blob/9f3b822eef231f452fc92943e3db1ff97dff261c/src/renderer/entities/wallet/lib/wallet-utils.ts#L90) in order to filter which wallets can be used as a signatory to sign. Places were it should be updated:

- Create multisig
- Approve/Reject operations
- Operation's details

Screenshot 2024-11-14 at 11 45 43

- Wallet details

Screenshot 2024-11-14 at 11 44 11

## Environment
https://github.com/novasamatech/nova-spektr/commit/9f3b822eef231f452fc92943e3db1ff97dff261c

### PR DESCRIPTION
**Pull request by sokolova-an**

### CODE REVIEW

File: src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts [hunk 1]
```diff
@@ -67,10 +66,12 @@ const $signatoryContacts = combine(
   },
   ({ wallet, wallets, contacts }): Signatory[] => {
     if (!wallet || !walletUtils.isMultisig(wallet)) return [];
+    //TODO: remove it when sign with proxy is supported
+    const filtredWallets = wallets.filter((w) => !walletUtils.isWatchOnly(w) && !walletUtils.isProxied(w));
 
     const contactsMap = dictionary(contacts, 'accountId');
     const signatoriesMap = dictionary(wallet.accounts[0].signatories, 'accountId');
-    const allSignatories = walletUtils.getAccountsBy(wallets, ({ accountId }) => signatoriesMap[accountId]);
+    const allSignatories = walletUtils.getAccountsBy(filtredWallets, ({ accountId }) => signatoriesMap[accountId]);
```
Comment (johnthecat) [inline src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts]: `filtredWallets` to
`filteredWallets`

File: src/renderer/widgets/WalletDetails/ui/wallets/MultisigWalletDetails.tsx [hunk 2]
```diff
@@ -152,10 +152,10 @@ export const MultisigWalletDetails = ({
               </FootnoteText>
 
               <ul className="flex flex-col gap-y-2 px-3">
-                {signatoryWallets.map(([accountId, wallet]) => (
+                {signatoryWallets.map((wallet) => (
                   <li key={wallet.id} className="flex items-center gap-x-2 py-1.5">
                     <ExplorersPopover
-                      address={accountId}
+                      address={wallet.accounts[0].accountId}
```
Comment (johnthecat) [inline src/renderer/widgets/WalletDetails/ui/wallets/MultisigWalletDetails.tsx]: `accounts[0]` can be empty

**Review by johnthecat — APPROVED** [review]

**Review by tuul-wq — APPROVED** [review]
