### PR TITLE
fix: improve XCM transfer fees validation and error handling

### LINKED ISSUE #5320: DryRun. Destination network fee is added to transfer amount in validation error alert
## Description

When trying to make an xcm transfer, the destination network fee is mistakenly added to the transfer amount in the validation alert.
The bug is reproduced when the available amount is slightly less than the transfer amount. 

## Steps to Reproduce

Can be checked on account:
142j7Ept69naVC7r3igHbRowYiZzcB83mYK9mYh49rhnRNL4

1. Initiate transfer of 1DOT from Polkadot Relay to PAH
2. Check the validation error (transfer amount) + dry run validation error
3. Change transfer amount from 1 Dot to 10 DOT
4. Check the validation error (transfer amount)

## Screenshots

https://github.com/user-attachments/assets/10808297-f057-413e-9a0d-8f912ee218e5

### PR DESCRIPTION
**Pull request by kalininilya**
Closes #5320 #5349

## Description
Enhances balance validation for XCM transfers with more accurate fee checks, adds network error handling, and prevents redundant error messages in the transfer form.

## Validations
- Validations now follow the following logic:
tryWithdraw(origin fee, "keepAlive"), origin fee =  submission fee + delivery fee (it comes this way from paraspell getXcmFees SDK method)
tryWithdraw(amount, "keepAlive")
tryWithdraw(destination fee, "keepAlive")

## Error Handling
- Added network error handling with `TransactionValidationNetworkError` type
- Refactored alerts: removed separate `AlertForDryRunError`, integrated into unified `TransactionValidationError`
- Dry run errors only display when no form/balance validation errors exist
- Added `dryRunRules` support to `createTxValidator` for XCM dry run failures

## UI Improvements
- Added `$isPreparingTransaction` state for loading indicator on Continue button
- Improved error display with dynamic titles and better XCM error formatting

## Screenshots/Recordings
Screenshot 2025-12-15 at 16 20 12

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts [hunk 1]
```diff
@@ -259,10 +259,17 @@ export const transferValidator = createTxValidator<{
       const isXcm = destinationChain.chainId !== sourceChain.chainId;
       const totalAmount = isXcm && destinationFee && !destinationFee.isZero() ? amount.add(destinationFee) : amount;
       const preservation = isXcm ? 'keepAlive' : balancePreservation;
+      const withdrawalResult = balanceService.tryWithdraw(balance, totalAmount, preservation);
 
       return {
         account: initiator,
-        balance: balanceService.tryWithdraw(balance, totalAmount, preservation),
+        balance:
+          isXcm && destinationFee && !destinationFee.isZero()
```
Comment (aaa123eee) [inline src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts]:
```suggestion
          isXcm && destinationFee?.gtn(0)
```

File: src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts [hunk 2]
```diff
@@ -259,10 +259,17 @@ export const transferValidator = createTxValidator<{
...
+            ? {
+                ...withdrawalResult,
+                required: amount,
+              }
```
Comment (aaa123eee) [inline src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts]: we should think twice if we missed any scenario with this withdrawal result editing

and why the `balanceService.tryWithdraw(balance, amount, preservation)` would be incorrect?

Comment (aaa123eee) [reply src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts]: @johnthecat this is the place I was talking about

Comment (kalininilya) [reply src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts]: refactored to 3 separate validations:

withdraw(origin.fee, keepAlive)
withdraw(userAmount,keepAlive)
withdraw(destination.fee, keepAlive)

File: src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts (hunk 1 above)
Comment (kalininilya) [reply src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts]: Removed

File: src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts [hunk 3]
```diff
@@ -234,38 +242,59 @@ export const transferValidator = createTxValidator<{
...
 
       const balance = getBalance(initiator.accountId, sourceChain.chainId, sourceAsset.assetId);
       assert(balance, `Balance for account ${initiator.accountId} not found`);
-
-      // For XCM transfers, combine amount + destination fee with keepAlive
-      // For same-chain transfers, use only amount with user's balancePreservation choice
       const isXcm = destinationChain.chainId !== sourceChain.chainId;
-      const totalAmount = isXcm && destinationFee && !destinationFee.isZero() ? amount.add(destinationFee) : amount;
-      const preservation = isXcm ? 'keepAlive' : balancePreservation;
+      const strategy = isXcm ? 'keepAlive' : balancePreservation;
```
Comment (aaa123eee) [inline src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts]:
```suggestion
      const preservation = isXcm ? 'keepAlive' : balancePreservation;
```

Comment (kalininilya) [reply src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts]: Reverted the rename, agreed that preserving the original name is the better option

File: src/renderer/shared/ui-entities/TransactionValidationError/TransactionValidationError.tsx [hunk 4]
```diff
@@ -134,6 +183,55 @@ const TransactionPermissionError = ({
...
+        <Trans
+          t={t}
+          i18nKey={cleanReason ? 'transfer.dryRunError.descriptionWithReason' : 'transfer.dryRunError.description'}
+          values={{
+            reason: cleanReason,
+            chain: chainName,
+          }}
+        />
+      )}
+    </FootnoteText>
```
Comment (aaa123eee) [inline src/renderer/shared/ui-entities/TransactionValidationError/TransactionValidationError.tsx:218]: I think it can be shortened down to key derivation and one Trans usage

**Review by aaa123eee — DISMISSED** [review]
LGTM overall

File: src/renderer/shared/ui-entities/TransactionValidationError/TransactionValidationError.tsx (hunk 4 above)
Comment (kalininilya) [reply src/renderer/shared/ui-entities/TransactionValidationError/TransactionValidationError.tsx:218]: Done

**Review by aaa123eee — APPROVED** [review]
