### PR TITLE
Fix: operation counter for multisig proxies

### LINKED ISSUE #1611: Proxy for multisig wallet. Operations count is shown.
## Description
For a multsig wallets's proxied account is shown Operations count.

## Steps to Reproduce

1. Create proxy from multisig on one of your wallet
2. Select created proxied account as active

## Expected Behavior
Operations counter does not show any active operations

## Actual Behavior
Operations counter is showing counter equal multisig's counter

## Environment
https://github.com/novasamatech/nova-spektr/commit/7275d804570096a1947b02062b51524e5daa6066

## Screenshots
Screenshot 2024-04-01 at 12 21 38

### LINKED ISSUE #1614: Calling undefined in SignatorySelector.
## Description
May call undefined toString in SignatorySelector. need to add check for signer existence
https://github.com/novasamatech/nova-spektr/blob/7275d804570096a1947b02062b51524e5daa6066/src/renderer/widgets/AddProxyModal/ui/AddProxyForm.tsx#L152

### LINKED ISSUE #1615: Add delegated authority is available for WOW
## Description
For WOW is available add delegated authority.

## Steps to Reproduce

1. Add WOW
2. Go to wallet details
3. Try to Add delegated authorities

## Expected Behavior
Should be forbidden, as that wallet can't sign operations

## Actual Behavior
Can add delegated authority for WOW

Screenshot 2024-04-01 at 13 59 31

### PR DESCRIPTION
**Pull request by Asmadek**
fix: operation count for multisig proxies
fix: use permission utils for add proxy buttons
fix: calling undefined in SignatorySelector

### CODE REVIEW

File: src/renderer/features/navigation/ui/Navigation.tsx [hunk 1]
```diff
@@ -5,18 +5,21 @@ import { MultisigTxInitStatus } from '@entities/transaction';
...
   const chains = useUnit(networkModel.$chains);
   const activeAccounts = useUnit(walletModel.$activeAccounts);
+  const activeWallet = useUnit(walletModel.$activeWallet);
 
   const { getLiveAccountMultisigTxs } = useMultisigTx({});
 
-  const txs = getLiveAccountMultisigTxs(activeAccounts.map((a) => a.accountId)).filter(
-    (tx) => tx.status === MultisigTxInitStatus.SIGNING && chains[tx.chainId],
-  );
+  const txs = walletUtils.isMultisig(activeWallet)
```
Comment (tuul-wq) [inline src/renderer/features/navigation/ui/Navigation.tsx]: ⚠️ Inner `useEffect` under condition ⚠️

File: src/renderer/widgets/AddProxyModal/ui/AddProxyForm.tsx [hunk 2]
```diff
@@ -144,11 +145,13 @@ const SignatorySelector = () => {
 
   if (!isMultisig) return null;
 
-  const options = signatories.map(({ signer, balance }) => {
+  const options = signatories.reduce<DropdownOption[]>((acc, { signer, balance }) => {
+    if (!signer?.id) return acc;
```
Comment (tuul-wq) [inline src/renderer/widgets/AddProxyModal/ui/AddProxyForm.tsx:149]: What kind of problem is solved here?

Comment (Asmadek) [reply src/renderer/widgets/AddProxyModal/ui/AddProxyForm.tsx:149]: https://github.com/novasamatech/nova-spektr/issues/1614

**Review by tuul-wq — APPROVED** [review]
