### PR TITLE
fix: show ready for promotion text when left to promotion is zero

### LINKED ISSUE #5235: Fellowship. Overview widget - show ranks always
we need to show ranks always, by hover -> change colour
Image

### PR DESCRIPTION
**Pull request by kalininilya**
Closes [#5235](https://github.com/novasamatech/nova-spektr/issues/5235)
## Description

This PR fixes issues with the Fellowship promotion progress display

## Changes Made
- Fixed progress bar to display 100% when `leftToPromotion === 0`
- Fixed time-to-next-rank to show "Ready for promotion" instead of null
- Changed falsy check `if (leftToPromotion && ...)` to explicit null check `if (leftToPromotion !== null && leftToPromotion !== undefined && ...)`
- Added condition to force `progressPercentage = 100` when ready for promotion

## Screenshots/Recordings

Screenshot 2025-11-27 at 12 22 45 PM

Screenshot 2025-11-27 at 12 44 50 PM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/fellowship-overview/components/FellowshipOverview.tsx [hunk 1]
```diff
@@ -43,12 +43,12 @@ const useTimeToNextRank = () => {
...
 
   useEffect(() => {
-    if (promotionProgress && promotionProgress.progressPercentage >= 100) {
+    if ((promotionProgress && promotionProgress.progressPercentage >= 100) || leftToPromotion === 0) {
       setTimeToNextRank(READY_FOR_PROMOTION);
       return;
     }
 
-    if (leftToPromotion && currentBlock && api) {
+    if (leftToPromotion !== null && leftToPromotion !== undefined && currentBlock && api) {
```
Comment (johnthecat) [inline src/renderer/features/fellowship-overview/components/FellowshipOverview.tsx]: nonNullable(leftToPromotion)

**Review by johnthecat — DISMISSED** [review]

File: src/renderer/features/fellowship-overview/components/FellowshipOverview.tsx (hunk 1 above)
Comment (kalininilya) [reply src/renderer/features/fellowship-overview/components/FellowshipOverview.tsx]: Fixed

**Review by cuteWarmFrog — APPROVED** [review]
