### PR TITLE
Fix/address book fixes

### LINKED ISSUE #5282: Address book. Name resolution for search
## Description

When user added contact to address book - he can't search by this changed name.

Example:

https://github.com/user-attachments/assets/7e7387c2-0a05-4fe4-86aa-c759426bfc11

using `account.name` in search filters:
- `src/renderer/widgets/Transfer/default/ui/TransferForm.tsx` (Line 302)
- `src/renderer/widgets/Staking/BondNominate/default/model/form-model.ts` (Line 160)
- `src/renderer/widgets/Staking/Payee/default/model/form-model.ts` (Line 105)
- `src/renderer/features/assets-transaction/components/SelectAccount.tsx` (Line 45)

**Impact**: Search functionality searches raw names, missing contact/identity names

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
When user added contact to address book - he can't search by this changed name.

## Related Issues
Closes #5282

## Changes Made
Fixed name resolution in wallet search and other places across the app.

## Screenshots/Recordings
Снимок экрана 2025-12-08 в 15 04 05

Снимок экрана 2025-12-08 в 15 04 44

Снимок экрана 2025-12-08 в 15 04 19

Снимок экрана 2025-12-08 в 15 02 14

Снимок экрана 2025-12-08 в 15 02 31

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/domains/network/account/hooks.ts [hunk 1]
```diff
@@ -1,44 +1,114 @@
...
+        });
+        result[key] = cache[key] ?? account.name;
+      }
+      return result;
+    },
+  });
+
+  if (nullable(accounts) || accounts.length === 0) {
+    return accounts || [];
+  }
```
Comment (savvyer) [inline src/renderer/domains/network/account/hooks.ts]: lets move this check before the `useResource(accountsNameResource` then we can early return without calling useResource and simplify useResource params

Comment (savvyer) [reply src/renderer/domains/network/account/hooks.ts]: can return `[]` only

File: src/renderer/domains/network/account/hooks.ts [hunk 2]
```diff
@@ -1,44 +1,114 @@
...
+
+  return accounts.map(account => {
+    const key = createAccountNameCacheKey({
+      accountId: account.accountId,
+      chain,
+      title: undefined,
```
Comment (savvyer) [inline src/renderer/domains/network/account/hooks.ts]: is there any reason to specify title as undefined explicitly?

File: src/renderer/domains/network/account/hooks.ts [hunk 3]
```diff
@@ -1,44 +1,114 @@
...
 type UseAccountNameParams = {
   accountId: AccountId | null | undefined;
   chain?: Chain | null;
   title?: string;
+  accounts?: AnyAccount[];
 };
 
-export const useAccountName = ({ accountId, chain, title }: UseAccountNameParams) => {
-  const params: AccountNameParams | null = accountId ? { accountId, chain, title } : null;
+export const useAccountsName = (accounts: AnyAccount[], chain?: Chain | null) => {
```
Comment (savvyer) [inline src/renderer/domains/network/account/hooks.ts]: can we rename it to `useAccountNames` or `useAccountsNames`?

File: src/renderer/domains/network/account/hooks.ts [hunk 4]
```diff
@@ -1,44 +1,114 @@
...
+  });
+};
+
+export const useAccountName = ({ accountId, chain, title, accounts: externalAccounts }: UseAccountNameParams) => {
+  if (!accountId) {
+    return title;
+  }
+
+  const account =
+    externalAccounts?.length && accountId ? (externalAccounts.find(a => a.accountId === accountId) ?? null) : null;
```
Comment (savvyer) [inline src/renderer/domains/network/account/hooks.ts]: Can be simplified:
```
const account = externalAccounts?.find(a => a.accountId === accountId) ?? null;
```

what do you think?

File: src/renderer/domains/network/account/hooks.ts [hunk 5]
```diff
@@ -1,44 +1,114 @@
...
+        result[key] = cache[key] ?? wallet.name;
+      }
+      return result;
     },
   });
 
-  return data;
+  if (nullable(wallets) || wallets.length === 0) {
+    return wallets || [];
+  }
```
Comment (savvyer) [inline src/renderer/domains/network/account/hooks.ts]: Same thing. Lets move it above `useResource(walletsNameResource` and simplify params

File: src/renderer/domains/network/account/hooks.ts [hunk 6]
```diff
@@ -1,44 +1,114 @@
...
 
-export const useWalletName = (wallet: Wallet | null | undefined) => {
-  const params: WalletNameParams | null = wallet ? { wallet } : null;
-  const { data } = useResource(walletNameResource, {
-    params,
-    defaultValue: undefined,
-    map: (cache, params) => {
-      return cache[createWalletNameCacheKey(params)] ?? '';
+export const useWalletsName = (wallets: Wallet[]) => {
+  const { data: walletNames } = useResource(walletsNameResource, {
```
Comment (savvyer) [inline src/renderer/domains/network/account/hooks.ts]: what about `useWalletNames` naming for clarity?

File: src/renderer/features/polkadot-vault-wallet/components/WalletGroup.tsx [hunk 7]
```diff
@@ -52,8 +56,9 @@ export const WalletGroup = memo(({ wallets, walletType, query, title, onSelect }
       <Accordion.Content>
         <Box gap={1} padding={[1, 0, 0]}>
           {filteredWallets.map(wallet => {
-            const isSingleAccount = wallet.accounts.length === 1;
-            const accountId = isSingleAccount ? wallet.accounts[0]?.accountId : wallet.rootAccountId;
+            const vaultWallet = wallet as PolkadotVaultGroup;
```
Comment (savvyer) [inline src/renderer/features/polkadot-vault-wallet/components/WalletGroup.tsx]: lets use `isPolkadotVaultGroup` instead of direct typecasting

File: src/renderer/shared/ui-entities/TransactionDetails/TransactionDetails.tsx [hunk 8]
```diff
@@ -46,8 +46,22 @@ export const TransactionDetails = memo(({ wallets, chain, initiators, signatory,
   const initiatorMeta = useTransformer(accountNodeConfigTransformer, { account: firstInitiator || signatory, t });
   const initiatorWalletType = initiatorMeta ? initiatorMeta.title.toLowerCase() : '';
   const isComplexAccountStructure = nullable(initiators.find(i => i === signatory));
-  const firstInitiatorName = useAccountName({ accountId: firstInitiator?.accountId ?? null, chain });
-  const signatoryName = useAccountName({ accountId: signatory?.accountId ?? null, chain });
+  const resolvedAccounts = useMemo(() => {
+    const list: AnyAccount[] = [];
+    if (signatory) list.push(signatory);
+    return [...list, ...initiators];
+  }, [initiators, signatory]);
```
Comment (savvyer) [inline src/renderer/shared/ui-entities/TransactionDetails/TransactionDetails.tsx]: why do you use `initiators` here instead of `firstInitiator` only?

**Review by savvyer — CHANGES_REQUESTED** [review]

File: src/renderer/domains/network/account/hooks.ts (hunk 1 above)
Comment (Yanaty) [reply src/renderer/domains/network/account/hooks.ts]: done

File: src/renderer/domains/network/account/hooks.ts (hunk 2 above)
Comment (Yanaty) [reply src/renderer/domains/network/account/hooks.ts]: no, deleted title

File: src/renderer/domains/network/account/hooks.ts (hunk 3 above)
Comment (Yanaty) [reply src/renderer/domains/network/account/hooks.ts]: renamed to useAccountsNames

File: src/renderer/domains/network/account/hooks.ts (hunk 4 above)
Comment (Yanaty) [reply src/renderer/domains/network/account/hooks.ts]: yes, fixed

File: src/renderer/domains/network/account/hooks.ts (hunk 5 above)
Comment (Yanaty) [reply src/renderer/domains/network/account/hooks.ts]: done

File: src/renderer/domains/network/account/hooks.ts (hunk 6 above)
Comment (Yanaty) [reply src/renderer/domains/network/account/hooks.ts]: renamed to useWalletsNames

File: src/renderer/features/polkadot-vault-wallet/components/WalletGroup.tsx (hunk 7 above)
Comment (Yanaty) [reply src/renderer/features/polkadot-vault-wallet/components/WalletGroup.tsx]: fixed

File: src/renderer/shared/ui-entities/TransactionDetails/TransactionDetails.tsx (hunk 8 above)
Comment (Yanaty) [reply src/renderer/shared/ui-entities/TransactionDetails/TransactionDetails.tsx]: removed this code as unnecessary

File: src/renderer/domains/network/account/hooks.ts [hunk 9]
```diff
@@ -1,22 +1,59 @@
...
+          accountId: account.accountId,
+          chain,
+        });
+        result[key] = cache[key] ?? account.name;
+      }
+      return result;
+    },
+  });
+
+  if (nullable(accounts) || accounts.length === 0) {
```
Comment (savvyer) [inline src/renderer/domains/network/account/hooks.ts]: Did you forget to remove it ?

Comment (Yanaty) [reply src/renderer/domains/network/account/hooks.ts]: removed, thanks

**Review by savvyer — APPROVED** [review]
