### PR TITLE
fix: network requests optimisation

### LINKED ISSUE #1932: Basket. Many similar requests via websoket.
## Description
When user submit batch of operations via Basket it sends many similar requests for each operation:
- {"id":1,"jsonrpc":"2.0","method":"chain_getHeader","params":[]}
- {"id":1,"jsonrpc":"2.0","method":"chain_getFinalizedHead","params":[]}

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/d9cfae4e-1852-483f-89e5-6a15d78d118b

</details>

## Steps to Reproduce

1. Add in the Basket many operations
2. Try to send it all in a row

## Expected Behavior
Optimal network usage

## Actual Behavior
Send a lot of similar requests

## Environment
https://github.com/novasamatech/nova-spektr/commit/36c791f377a0a3f16c7fca5cc1945b59428d328c

### PR DESCRIPTION
**Pull request by Asmadek**
* optimize tx metadata creation
* optimaize paymentInfo usage

### CODE REVIEW

File: src/renderer/entities/transaction/ui/Scanning/ScanMultiframeQr.tsx [hunk 1]
```diff
@@ -48,7 +48,9 @@ export const ScanMultiframeQr = ({
   }, []);
 
   const setupTransactions = async (): Promise<void> => {
-    const transactionPromises = signingPayloads.map((signingPayload, index) => {
+    const metadataMap = {} as Record<Address, Record<ChainId, TxMetadata>>;
```
Comment (johnthecat) [inline src/renderer/entities/transaction/ui/Scanning/ScanMultiframeQr.tsx]: Maybe?
```suggestion
    const metadataMap: Record<Address, Record<ChainId, TxMetadata>> = {};
```

**Review by johnthecat — APPROVED** [review]
