### PR TITLE
fix: multishard voting and etc.

### LINKED ISSUE #2272: Governance. Governance. Does not show in Available balance tokens, locked into staking.
## Description
Does not count staking locks for Available balance in Governance operations.

## Steps to Reproduce

1. Add account - 5EpsavEfPSZC8X2E4zHdJdepzpzfSccqNP5RUVyAU9Hyi3z4
2. Go to Governance
3. Try to Vote on Polkadot

## Expected Behavior
Available balance include free + governance lock and staking lock

<details>
  <summary>NovaWallet state</summary>

IMG_22E14112AFBF-2

</details>

## Actual Behavior
Available balance include freee + governance lock

<details>
  <summary>Spektr state</summary>

Screenshot 2024-09-02 at 19 11 59

</details>

## Environment
https://github.com/novasamatech/nova-spektr/commit/4284a633ab2af77c790ee66bde279a1b74677e0c

### LINKED ISSUE #2407: Governance. Vote history. Search may lead to broken state.
## Description

When user try to search any split votes in the votes history it will lead to make copies of the recording.

Example:

https://github.com/user-attachments/assets/2a0d5634-78ab-43b6-84aa-9b22f5dabfd7

## Steps to Reproduce

1. Vote with split 1\1 for any referenda
2. Find this referenda
3. Go to votes history
4. Try to find votes by address

## Expected Behavior
Shows 1 vote in Aye, 1 vote in Nay

## Actual Behavior
make copies of the recording for each search try, only for ayes

## Environment
https://github.com/novasamatech/nova-spektr/commit/af3f15ee5b9e094633be37a1aa25d70ad285171a

### LINKED ISSUE #2421: Governance. Multishard wallet. Voted info contains the latest voted account, instead of list of accounts
## Description

When user voted as a multishard wallet from a few accounts - voted info shows only the last one.
That updates if restart the app.

## Steps to Reproduce

1. Select multishard wallet
2. Vote for referenda from account_a
3. Vote for referenda from account_b

## Expected Behavior
Voted info shows both accounts

## Actual Behavior
Shows only the last one, updates if restart the app.

https://github.com/user-attachments/assets/670aed77-d175-4aca-bac9-a6030d0b0cc9

## Environment
https://github.com/novasamatech/nova-spektr/commit/f2b5fa27de10af054b2d8239bf5c8049eb7fb5c0

### LINKED ISSUE #2423: Governance. Multishard wallet. Remove vote will create transaction for all voted accounts
## Description

When user try to remove votes - shows both account selector and create transaction for each account.

## Steps to Reproduce

1. Select Multishard wallet
2. Vote from a few accounts of that wallet
3. Try to remove votes

## Expected Behavior
Shows address selector, create one transaction after selection
https://www.figma.com/design/ylvl7Ox25UuZj73Rn85DK7/OpenGov-voting?node-id=4115-126421&t=uyOGVIU2KhtxZqLO-4

## Actual Behavior
Appears account selector, but will create transaction for all accounts

https://github.com/user-attachments/assets/b4da7eac-ea3a-4df8-a3e1-78eee1c3de01

## Environment
https://github.com/novasamatech/nova-spektr/commit/f2b5fa27de10af054b2d8239bf5c8049eb7fb5c0

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #2423 
Closes #2421 
Closes #2407
Closes #2272

### CODE REVIEW

File: src/renderer/pages/Governance/ui/Governance.tsx [hunk 1]
```diff
@@ -183,6 +183,7 @@ export const Governance = () => {
         nonNullable(network) &&
         referendumService.isOngoing(selectedReferendum) && (
           <RemoveVotesModal
+            single
```
Comment (sokolova-an) [inline src/renderer/pages/Governance/ui/Governance.tsx:186]: will this prop be needed only here and not in other places where RemoveVotesModal is called?

**Review by sokolova-an — APPROVED** [review]

File: src/renderer/pages/Governance/ui/Governance.tsx (hunk 1 above)
Comment (johnthecat) [reply src/renderer/pages/Governance/ui/Governance.tsx:186]: comment added 🫡
