### PR TITLE
Fix/promotion widget bugs

### LINKED ISSUE #5132: Fellowship. Wrong promotion states across the app
## Description

Promotion states are being generated incorrectly:
1. Awaiting opportunity state while the indicated promotion eligibility start date is in the past.
2. Wrong submit promotion evidence action on the dashboard with the deadline in the past, while the widget says that the evidence had been submitted.
3. Promotion evidence submitted state in the widget, when no evidence has been submitted yet (new test account).
4. Promotion evidence submitted state in the widget, while the referendum is completed (widget doesn't mention the referendum).

## Steps to Reproduce

For items 1:
Check user 'bkontur' from the attached db on the Polkadot Collectives net.

For items 2:
Check user 'andre' from the attached db on the Polkadot Collectives net.

For item 3:
Check user 'fellow_test1' from the attached db on the Novasama Collectives net.

For item 4:
Check user 'ext-1' from the attached db on the Novasama Collectives net.

## Screenshots

1.

Image

2. 

Image
Image

3. 

Image

4. 

Image

## Database

[promotion.json](https://github.com/user-attachments/files/23650243/promotion.json)

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
Promotion states are being generated incorrectly:

Awaiting opportunity state while the indicated promotion eligibility start date is in the past.
Wrong submit promotion evidence action on the dashboard with the deadline in the past, while the widget says that the evidence had been submitted.
Promotion evidence submitted state in the widget, when no evidence has been submitted yet (new test account).
Promotion evidence submitted state in the widget, while the referendum is completed (widget doesn't mention the referendum).

## Related Issues
Closes #5132

## Changes Made
Fixed calculating promotion period
Fixed error in calculation when member.lastPromotion = 0
Fixed promotion widget state showing “Evidence submitted”

## Screenshots/Recordings
Снимок экрана 2025-11-21 в 10 21 34
Снимок экрана 2025-11-21 в 10 22 01
Снимок экрана 2025-11-21 в 10 22 24
Снимок экрана 2025-11-21 в 11 40 51
Снимок экрана 2025-11-21 в 11 41 04

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/fellowship-tasks/components/tasks/RequestPromotion.tsx [hunk 1]
```diff
@@ -14,7 +14,7 @@ export const requestPromotionTaskActionSlot = createSlot();
 
 export const RequestPromotion = () => {
   const { t, formatDate } = useI18n();
-  const [periodEnd, setPeriodEnd] = useState(0);
+  const [periodEnd, setPeriodEnd] = useState<number>(0);
```
Comment (aaa123eee) [inline src/renderer/features/fellowship-tasks/components/tasks/RequestPromotion.tsx:17]: maybe null is a better indicator of empty state?

**Review by aaa123eee — APPROVED** [review]

**Review by kalininilya — APPROVED** [review]

**Review by cuteWarmFrog — APPROVED** [review]
