### PR TITLE
fix: flexible multisigs subtitle

### LINKED ISSUE #3957: Flexible multisig. Update wallet details
Need to be done:
- Remove "..." component
- Add icons instead of parameters in "..." menu
- Change wallet details page size
- Add new button for Flexible multisig - Edit multisig

https://www.figma.com/design/ZTrGE0r8cD1X7oBZcUzMRu/Flexible-multisig-2.0?node-id=381-111295&m=dev

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Fixed subtitle 

## Related Issues
closes #3957

### CODE REVIEW

File: src/renderer/features/wallet-details/ui/wallets/FlexibleWalletDetails.tsx [hunk 1]
```diff
@@ -1,19 +1,18 @@
 import { useGate, useUnit } from 'effector-react';
+import noop from 'lodash/noop';
```
Comment (johnthecat) [inline src/renderer/features/wallet-details/ui/wallets/FlexibleWalletDetails.tsx]: import { noop } from 'lodash'

**Review by johnthecat — APPROVED** [review]
