### PR TITLE
Fix: Laggy validators

### LINKED ISSUE #1711: Staking. Validator list operates with delays
## Description
For the Kusama network validator list operates with delays

<details>
  <summary>🍿 Example 🍿</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/cf9d4248-5463-4b24-8363-feeee31c1a93

</details>

## Steps to Reproduce

1. Go to staking page
2. Initiate start staking \ change validators operation
3. Go to the validator list
4. Try to select validators

## Actual Behavior
UI is lagging, selection process too long

## Environment
https://github.com/novasamatech/nova-spektr/commit/34bc8d02b705548c958d21b2a6fd32d2ecb3a151

### PR DESCRIPTION
**Pull request by tuul-wq**
- Fixed laggy validators with `React.memo` for `RowItem`
- Moved Validators to a dedicated feature

closes #1711

### CODE REVIEW

File: src/renderer/features/staking/Validators/model/validators-model.ts [hunk 1]
```diff
@@ -65,11 +67,11 @@ const $filteredValidators = combine(
     if (!query) return validators;
 
     return validators.filter((validator) => {
-      return isStringsMatchQuery(query, [
-        validator.address,
-        validator.identity?.subName || '',
-        validator.identity?.parent.name || '',
-      ]);
+      const address = validator.address.toLowerCase();
```
Comment (tuul-wq) [inline src/renderer/features/staking/Validators/model/validators-model.ts:70]: A bit simpler and faster search

**Review by pgolovkin — APPROVED** [review]

**Review by stepanLav — APPROVED** [review]
