### PR TITLE
Fix/transfer_all_tx

### LINKED ISSUE #4995: MAX button. Case when transfer all with Include Existential Deposit on currency pallet leads to error - sends balances.transferAll

### PR DESCRIPTION
**Pull request by stepanLav**
## Description

There is a problem with transaction type selection, based on input mode and balance preservation

## Related Issues

closed #4995 

### Core Changes

1. **`transactionBuilder.ts`**:
   - `isTransferAllSupported()` now returns `true` only for `AssetType.NATIVE` (removed `ORML`)
   - `getTransactionType()`: `TRANSFER_ALLOW_DEATH` only for NATIVE assets
   - `buildTransfer()`: adds `keepAlive` parameter to `TRANSFER_ALL` transaction args based on `balancePreservation`

2. **`extrinsicService.ts`**:
   - `TRANSFER_ALL` handler now uses `keepAlive` from args instead of hardcoded `false`

### Test Coverage

3. **Added comprehensive tests** (`transactionBuilder.test.ts`):
   - 21 tests covering all asset types and input modes
   - Mock data extracted to `mocks.ts` for reusability

### Behavior

- `TRANSFER_ALL` with `keepAlive` parameter:
  - `keepAlive: true` when `balancePreservation === 'keepAlive'`
  - `keepAlive: false` when `balancePreservation === 'allowDeath'`
- `transfer_all` now only supported for NATIVE assets
- ORML and STATEMINE assets always use regular transfers (even with `inputMode === 'max'`)
- `TRANSFER_ALLOW_DEATH` only for NATIVE assets

Fixes issue where `transfer_all` was incorrectly used for ORML assets and didn't respect `balancePreservation` for the `keepAlive` parameter.

## Summary Table

| Asset Type | Input Mode | Balance Preservation | Transaction Type | keepAlive Parameter |
|------------|------------|---------------------|------------------|---------------------|
| **NATIVE** | `regular` | `keepAlive` | `TRANSFER` | `true` |
| **NATIVE** | `regular` | `allowDeath` | `TRANSFER_ALLOW_DEATH` | `false` |
| **NATIVE** | `max` | `keepAlive` | `TRANSFER_ALL` | `true` |
| **NATIVE** | `max` | `allowDeath` | `TRANSFER_ALL` | `false` |
| **ORML** | `regular` | `keepAlive` | `ORML_TRANSFER` | `true` |
| **ORML** | `regular` | `allowDeath` | `ORML_TRANSFER` | `false` |
| **ORML** | `max` | `keepAlive` | `ORML_TRANSFER` | `true` |
| **ORML** | `max` | `allowDeath` | `ORML_TRANSFER` | `false` |
| **STATEMINE** | `regular` | `keepAlive` | `ASSET_TRANSFER` | `true` |
| **STATEMINE** | `regular` | `allowDeath` | `ASSET_TRANSFER` | `false` |
| **STATEMINE** | `max` | `keepAlive` | `ASSET_TRANSFER` | `true` |
| **STATEMINE** | `max` | `allowDeath` | `ASSET_TRANSFER` | `false` |

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [x] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/entities/transaction/lib/transactionBuilder.ts [hunk 1]
```diff
@@ -77,19 +77,20 @@ type TransferParams = {
...
+  if (isNativeAsset(asset)) {
+    const allowDeath = inputMode === 'regular' && balancePreservation === 'allowDeath';
+    if (allowDeath) {
+      return TransactionType.TRANSFER_ALLOW_DEATH;
+    }
 
-  const transferAll = inputMode === 'max' && balancePreservation === 'allowDeath';
-  if (isTransferAllSupported(asset) && transferAll) {
-    return TransactionType.TRANSFER_ALL;
+    if (inputMode === 'max' && isNativeAsset(asset)) {
```
Comment (aaa123eee) [inline src/renderer/entities/transaction/lib/transactionBuilder.ts]:
```suggestion
    if (inputMode === 'max') {
```

Comment (aaa123eee) [reply src/renderer/entities/transaction/lib/transactionBuilder.ts]: already checked above

**Review by aaa123eee — APPROVED** [review]
