### PR TITLE
fix: removed auto-close on error

### LINKED ISSUE #5034: Submit process. Error state - disappear after 1 second
## Description

```
Also, the (invalid) error message disappears after like 1 second which is pretty infuriating.
```

need to change that approach

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
Need to remove auto-close when the submit process ends in an error state.

## Related Issues
Closes #5034

## Changes Made
Remove auto-close on error 

## Screenshots/Recordings
Снимок экрана 2025-11-11 в 13 07 02

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

**Review by cuteWarmFrog — APPROVED** [review]

File: src/renderer/features/operations/OperationSubmit/ui/OperationSubmit.tsx [hunk 1]
```diff
@@ -21,14 +21,26 @@ type Props = {
...
-export const OperationSubmit = ({ autoCloseTimeout = 2000, isOpen, onSuccess, onFail, onClose }: Props) => {
+export const OperationSubmit = ({ autoCloseTimeout, isOpen, onSuccess, onFail, onClose }: Props) => {
   const { t } = useI18n();
 
   const submitStore = useUnit(submitModel.$submitStore);
   const failedTxs = useUnit(submitModel.$failedTxs);
   const succeedTxs = useUnit(submitModel.$succeedTxs);
   const { step, message } = useUnit(submitModel.$submitStep);
 
+  const resolvedAutoCloseTimeout = useMemo(() => {
```
Comment (kalininilya) [inline src/renderer/features/operations/OperationSubmit/ui/OperationSubmit.tsx]: Maybe we should name it `computedAutoCloseTimeout` to make it clear that it’s derived locally, not something received from a network or a promise?

**Review by kalininilya — APPROVED** [review]

File: src/renderer/features/operations/OperationSubmit/ui/OperationSubmit.tsx [hunk 2]
```diff
@@ -75,10 +87,14 @@ export const OperationSubmit = ({ autoCloseTimeout = 2000, isOpen, onSuccess, on
...
       {...getResultProps(step, message)}
-      autoCloseTimeout={!submitUtils.isLoadingStep(step) ? autoCloseTimeout : 0}
+      autoCloseTimeout={resolvedAutoCloseTimeout}
       onClose={handleModalClose}
     >
-      {submitUtils.isErrorStep(step) && <Button onClick={onClose}>{t('operation.submitErrorButton')}</Button>}
+      {submitUtils.isErrorStep(step) && (
+        <Button size="sm" onClick={onClose}>
+          {t('operation.submitErrorButton')}
+        </Button>
```
Comment (savvyer) [inline src/renderer/features/operations/OperationSubmit/ui/OperationSubmit.tsx:96]: did you discuss this? maybe its better to add a default modal close button in the top right corner?

**Review by savvyer — COMMENTED** [review]
checklist in the PR description is empty. check the checkboxes pls

File: src/renderer/features/operations/OperationSubmit/ui/OperationSubmit.tsx (hunk 1 above)
Comment (Yanaty) [reply src/renderer/features/operations/OperationSubmit/ui/OperationSubmit.tsx]: sure, fixed

File: src/renderer/features/operations/OperationSubmit/ui/OperationSubmit.tsx (hunk 2 above)
Comment (Yanaty) [reply src/renderer/features/operations/OperationSubmit/ui/OperationSubmit.tsx:96]: There was a button here, I’ve just added the sm variant

Comment (savvyer) [reply src/renderer/features/operations/OperationSubmit/ui/OperationSubmit.tsx:96]: yep!
Sorry, didn't notice that

**Review by savvyer — APPROVED** [review]
