### PR TITLE
fix: filtering general that user voted from actions required

### LINKED ISSUE #4601: Fellowship. Problem with update Actions required list
## Description

There is a bug, when "Actions required" list won't update after submit transactions

https://github.com/novasamatech/nova-spektr/blob/9fbf47e9f5ae805f181c2ec85c3474001f332190/src/renderer/features/fellowship-tasks/components/Tasks.tsx#L33-L34

## Steps to Reproduce

1. User has a few actions to do
2. Complete some of them, keep at least 1

## Expected Behavior

Actions required list updates reactively

## Actual Behavior

counter will show not updated info

## Environment
PROD

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Filtering general referendas from action required

## Related Issues
Closes #4601

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/fellowship-tasks/components/Tasks.tsx [hunk 1]
```diff
@@ -22,6 +22,12 @@ export const Tasks = () => {
 
   const groups = useMemo(() => groupBy(activeTasks, task => task.group), [activeTasks]);
 
+  const tasksCount = useMemo(() => {
+    const personalCount = groups.personal?.length ?? 0;
+    const generalCount = groups.general?.filter(task => !task.hasVoted).length ?? 0;
```
Comment (aaa123eee) [inline src/renderer/features/fellowship-tasks/components/Tasks.tsx:27]: are we sure they're zero and not pending?

Comment (aaa123eee) [reply src/renderer/features/fellowship-tasks/components/Tasks.tsx:27]: if pending state is possible then 0 can mislead

**Review by aaa123eee — APPROVED** [review]
