### PR TITLE
Fix: Empty signatories

### LINKED ISSUE #3302: Multisig. Signatory selector shows empty list
## Description

When user try to create multisig operation - signatory picker is empty

Example:

https://github.com/user-attachments/assets/d2f95176-8aa4-44d3-be53-d3932debe92b

## Test data

[spektr-database.json](https://github.com/user-attachments/files/19124148/spektr-database.json)

## Steps to Reproduce

1. Load test data
2. Select wallet - 14BGc...3DN53
3. Try to transfer DOT on Polkadot

## Expected Behavior
Can select signatory

## Actual Behavior
Signatory list is empty

## Environment
https://github.com/novasamatech/nova-spektr/commit/1b221d03f0ea20781009eca524824727be3d98bc

### PR DESCRIPTION
**Pull request by tuul-wq**
- Removed redundant account filter for PV
- Updated `SignatorySelector` style

closes #3302

### CODE REVIEW

File: src/renderer/widgets/Transfer/ui/TransferForm.tsx [hunk 1]
```diff
@@ -115,9 +115,10 @@ const AccountSelector = () => {
 
           return (
             <Select.Item key={account.id} value={account.id}>
-              <div className="flex w-full justify-between">
+              <div className="flex w-full items-center justify-between">
```
Comment (tuul-wq) [inline src/renderer/widgets/Transfer/ui/TransferForm.tsx:118]: Was not centered by vertical axis. Should display only 1 line - name or address

File: src/renderer/entities/operations/ui/SignatorySelector.tsx [hunk 2]
```diff
@@ -54,7 +54,8 @@ export const SignatorySelector = ({
               <div className="flex w-full items-center justify-between">
                 <Address
                   showIcon
-                  variant="short"
+                  hideAddress
```
Comment (aaa123eee) [inline src/renderer/entities/operations/ui/SignatorySelector.tsx]: it reverts recent update https://github.com/novasamatech/nova-spektr/pull/3291/files

File: src/renderer/widgets/Transfer/ui/TransferForm.tsx [hunk 3]
```diff
@@ -115,9 +115,10 @@ const AccountSelector = () => {
...
                 <AccountAddress
                   showIcon
+                  hideAddress
```
Comment (aaa123eee) [inline src/renderer/widgets/Transfer/ui/TransferForm.tsx]: is it related to the empty list bug?

**Review by johnthecat — APPROVED** [review]

**Review by aaa123eee — APPROVED** [review]
