### PR TITLE
fix: referendum search state

### LINKED ISSUE #2017: Governance. Search filter shows empty page, while off-chain data is processing.
## Description
While the app is fetching off-chain data, search should show loading state

## Steps to Reproduce

1. Run the app
2. Go to governance page
3. Try to find referenda by "lol" immediatelly, while getting off-chain data in process

## Expected Behavior
Loading state is shown, while off-chain data is loading, then show found result or empty page

## Actual Behavior
Empty page will be shown utnil off-chain data will be loaded, then will be shown found results

https://github.com/user-attachments/assets/5fea9eff-87ba-4d38-9e70-63cf2cf361d0

## Environment
https://github.com/novasamatech/nova-spektr/commit/40e6791613bfe00a5887ff92a9bde304cfb03ccc

### PR DESCRIPTION
**Pull request by johnthecat**
Add new loading + search state in referendums list

### CODE REVIEW

File: src/renderer/features/governance/components/ReferendumList/CompletedReferendums.tsx [hunk 1]
```diff
@@ -1,54 +1,64 @@
...
+  ({ referendums, isLoading, isTitlesLoading, mixLoadingWithData, onSelect }) => {
+    const { t } = useI18n();
+
+    const { isLoading: shouldRenderLoadingState, list: deferredReferendums } = useDeferredList({
+      isLoading,
+      list: referendums,
+    });
+
+    const placeholdersCount = shouldRenderLoadingState
+      ? Math.max(referendums.length || 4, 50)
```
Comment (sokolova-an) [inline src/renderer/features/governance/components/ReferendumList/CompletedReferendums.tsx]: why are these numbers? Why not just `Math.max(referendums.length, 50)`

File: src/renderer/features/governance/components/ReferendumList/OngoingReferendums.tsx [hunk 2]
```diff
@@ -1,53 +1,54 @@
...
-          {isLoading ? (
-            <Shimmering width={25} height={12} />
-          ) : (
-            <CaptionText className="font-semibold text-text-tertiary">{referendums.length.toString()}</CaptionText>
-          )}
-        </div>
-      </Accordion.Button>
-      <Accordion.Content as="ul" className="flex flex-col gap-y-2">
-        {!!isLoading && placeholder}
+    const placeholdersCount = isLoading ? Math.max(referendums.length || 4, 20) : Math.max(1, 4 - referendums.length);
```
Comment (sokolova-an) [inline src/renderer/features/governance/components/ReferendumList/OngoingReferendums.tsx]: and here

**Review by sokolova-an — APPROVED** [review]

File: src/renderer/features/governance/components/ReferendumList/CompletedReferendums.tsx (hunk 1 above)
Comment (johnthecat) [reply src/renderer/features/governance/components/ReferendumList/CompletedReferendums.tsx]: It should be `min`, i'll fix it
