### PR TITLE
Fix: Show current delegated tracks

### LINKED ISSUE #2916: OpegGov delegation. Delegated tracks are not selected when editing delegation
https://github.com/user-attachments/assets/e0c5455d-626f-4177-a7bb-444631d3eb9d

### PR DESCRIPTION
**Pull request by tuul-wq**
- Show already selected (for current delegate) tracks
- Minor code style refactoring

closes #2916

### CODE REVIEW

File: src/renderer/widgets/EditDelegationModal/ui/EditDelegation.tsx [hunk 1]
```diff
@@ -32,12 +32,18 @@ export const EditDelegation = () => {
     editDelegationModel.output.flowFinished,
   );
 
-  if (!walletData) {
```
Comment (tuul-wq) [inline src/renderer/widgets/EditDelegationModal/ui/EditDelegation.tsx:35]: Always `defined`

File: src/renderer/widgets/DelegateDetails/model/delegate-details-model.ts [hunk 2]
```diff
@@ -157,13 +157,11 @@ export const delegateDetailsModel = {
...
   $activeTracks,
-  $uniqueTracks: $activeTracks.map((tracks) =>
-    uniq(
-      Object.values(tracks)
-        .map((tracks) => [...tracks])
-        .flat(),
-    ),
-  ),
+  $uniqueTracks: $activeTracks.map((tracks) => {
+    const flatTracks = Object.values(tracks).flatMap((tracks) => [...tracks]);
```
Comment (johnthecat) [inline src/renderer/widgets/DelegateDetails/model/delegate-details-model.ts]:
```suggestion
    const flatTracks = Object.values(tracks).flat();
```

**Review by johnthecat — APPROVED** [review]

**Review by sokolova-an — APPROVED** [review]

**Review by pgolovkin — APPROVED** [review]
