### PR TITLE
Fix: run proxy workers

### LINKED ISSUE #1604: Run proxy-worker when the user adds, removes the wallet or adds, removes account in the Polkadot Vault wallet
Run proxy-worker when the user adds, removes the wallet or adds, removes account in the Polkadot Vault wallet in order to update the list of delegated to you wallets and proxy accounts.

### PR DESCRIPTION
**Pull request by sokolova-an**
Run proxy worker on add/delete wallet or account and on add/delete delegated proxy

### CODE REVIEW

File: src/renderer/entities/wallet/model/wallet-model.ts [hunk 1]
```diff
@@ -264,4 +259,5 @@ export const walletModel = {
     walletRemovedSuccess: removeWalletFx.done,
     walletsRemoved,
   },
+  output: { workerDataStarted: merge([walletCreatedFx.doneData, multishardCreatedFx.doneData]) },
```
Comment (tuul-wq) [inline src/renderer/entities/wallet/model/wallet-model.ts]:
```suggestion
  output: {
    workerDataStarted: merge([walletCreatedFx.doneData, multishardCreatedFx.doneData]),
  },
```

File: src/renderer/widgets/CreateWallet/ui/CreateWalletProvider.tsx [hunk 2]
```diff
@@ -38,7 +39,14 @@ export const CreateWalletProvider = () => {
 
   const props: ModalProps = {
     onClose: walletPairingModel.events.walletTypeCleared,
-    onComplete: walletProviderModel.events.completed,
+    onComplete: () => {
+      if (walletType !== WalletType.WATCH_ONLY) {
```
Comment (tuul-wq) [inline src/renderer/widgets/CreateWallet/ui/CreateWalletProvider.tsx:43]: Nice workaround 👍

File: src/renderer/entities/proxy/model/proxy-model.ts [hunk 3]
```diff
@@ -191,4 +191,7 @@ export const proxyModel = {
     proxyGroupsUpdated,
     proxyGroupsRemoved,
   },
+  output: {
+    proxyStatusUpdated: merge([addProxiesFx, removeProxiesFx]),
```
Comment (tuul-wq) [inline src/renderer/entities/proxy/model/proxy-model.ts]: I see handling for adding wallets/accounts + remove accounts but nothing for removing the wallet
This part of code is trying to cover that case of wallet deletion?
Explicit worker call after wallet deletion causes problems?

Comment (sokolova-an) [reply src/renderer/entities/proxy/model/proxy-model.ts]: This one should cover a case when we add or remove a proxy from an existing wallet. Otherwise, if we don't run a proxy worker after that - the list of proxies won't change

Comment (tuul-wq) [reply src/renderer/entities/proxy/model/proxy-model.ts]: Actually when we add proxy through details we manually add it into the store/db
This was done to avoid running worker
Maybe it's bugged, I'll take a look

**Review by Asmadek — APPROVED** [review]

**Review by tuul-wq — APPROVED** [review]
