### PR TITLE
fix: revoke authority flow bugs

### LINKED ISSUE #4789: Revoke authority flow - incorrect validations and broken back button
## Description

The revoke authority flow has multiple issues that affect both regular and flex multisig accounts:

- [x] 1. Cannot revoke authority for a regular account - the system shows a wrong validation error about a missing address on the network, even though the account exists. The validation doesn't parses the wallet's name/address.

https://github.com/user-attachments/assets/a54101f3-3f1d-4934-b9eb-b04382d19121

- [x] 2. Outdated validation about token balance - the flow still shows an old error message about insufficient tokens to revoke authority, which should no longer apply.

Image

- [x] 3. Back button not working - when revoking authority from a flex multisig account, the back button on the confirmation modal does nothing, leaving the user stuck.

https://github.com/user-attachments/assets/0daaa1a1-8d34-40aa-a356-bba3852a0746

## Steps to Reproduce

1. Attempt to revoke authority from a regular account ('nova3' in db) → observe the incorrect missing address validation.
2. Attempt to revoke authority when the account has enough balance ('Nova2 - low balance' in db) → observe the outdated insufficient tokens validation.
3. From a flex multisig account, trigger revoke authority ('Flex for Back button' in db) → on the confirmation modal, click Back → observe that nothing happens.

## Expected Behavior

- Regular account revocation should proceed without false validation errors.
- Token balance validation should be updated/removed to reflect current requirements.
- Back button should work properly and return the user to the previous step.

## Actual Behavior

- Regular account revocation fails with incorrect “missing address” validation.
- Old validation message about insufficient tokens is still shown.
- Back button on flex multisig revoke confirmation modal is broken.

## Database

[spektr-database (37).json](https://github.com/user-attachments/files/22595300/spektr-database.37.json)

### PR DESCRIPTION
**Pull request by kalininilya**
Resolves [#4789](https://github.com/novasamatech/nova-spektr/issues/4789)

## Description
Fixes three issues in the proxy revocation flow:
- Wrong validation error for the nova wallet
- Outdated token balance validation
- Back button not working in the confirmation modal

## Changes Made

- Fixed account validation: Added `accountService.isAccountAvailableOnChain()` in ProxiesList.tsx to validate accounts on the target chain
- Removed redundant fee error: Removed FeeError in RemoveProxyForm.tsx; TransactionValidationError already handles this
- Fixed back button: Replaced `wentBackFromConfirm` with `closeModal` in RemoveProxy.tsx to close the modal

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/proxy-remove/ui/RemoveProxy.tsx [hunk 1]
```diff
@@ -96,7 +96,7 @@ export const RemoveProxy = ({ wallet }: Props) => {
                 </Button>
               )
             }
-            onGoBack={removeProxyModel.wentBackFromConfirm}
+            onGoBack={closeModal}
```
Comment (aaa123eee) [inline src/renderer/features/proxy-remove/ui/RemoveProxy.tsx]: why close instead of step back?

**Review by johnthecat — APPROVED** [review]

File: src/renderer/features/proxy-remove/ui/RemoveProxy.tsx (hunk 1 above)
Comment (kalininilya) [reply src/renderer/features/proxy-remove/ui/RemoveProxy.tsx]: After examining the code again I noticed that there is actually a step we can go back to, pushed another fix to actually only close the modal only when the number of signatories is 1 and we can't go back to signatories select modal:

```
  source: combine({
    isMultisig: $isMultisig,
    signatories: $signatories,
  }),
  match: {
    multisigWallet: ({ isMultisig, signatories }) => isMultisig && signatories.length !== 1,
  },
```
