### PR TITLE
fix: doubling of flows when both retention and pomotion modals are rendered

### LINKED ISSUE #5172: Fellowship. Evidence submission triggers repeated confirmation modals in a loop (retention ↔ promotion)
## Description

After submitting evidence in the Fellowship flow, the app repeatedly opens confirmation modals as if the user needs to submit evidence again.

Observed behavior:

1. After submitting retention evidence (via IPFS or file upload), a confirmation modal to submit evidence one more time automatically opens.
2. After confirming/submitting retention evidence, a confirmation to submit promotion evidence opens.
3. After completing promotion, the retention evidence confirmation appears again.

This creates a loop between retention and promotion submission confirmations. The user is effectively stuck being prompted to “submit again” even though the previous submission was already completed.

## Screenshots

https://github.com/user-attachments/assets/3b88333b-9260-4bea-a258-39c98fba5462

### PR DESCRIPTION
**Pull request by kalininilya**
Closes #5172 

## Description
Fixed a bug where submitting evidence reports with IPFS uploads triggered duplicate toasts and confirmation modals. The issue occurred because multiple instances of the evidence submission modals (Promotion and Retention) were mounted simultaneously, and all instances subscribed to the same global Effector stores, causing them to react to state changes even when they weren't the active flow.

## Changes Made

- SubmitEvidencePopover: Only render upload/preview modals when they match the active flow (activeWish === wish)
- SubmitEvidencePopover: Explicitly start flow when clicking "Upload from IPFS"
- MarkdownPreviewModal: Register with flow using useFlow to properly participate in lifecycle
- evidencePost: Filter submit modal opening to only trigger during active preview step

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/fellowship-evidence/components/MarkdownPreviewModal.tsx [hunk 1]
```diff
@@ -29,16 +31,24 @@ export const MarkdownPreviewModal = ({
   const { toast } = useNotification();
   const toastIdRef = useRef<string | number | undefined>(undefined);
 
+  const isViewingSubmittedEvidence = !!evidenceContent;
```
Comment (aaa123eee) [inline src/renderer/features/fellowship-evidence/components/MarkdownPreviewModal.tsx]:
```suggestion
  const isViewingSubmittedEvidence = nonNullable(evidenceContent);
```

**Review by aaa123eee — DISMISSED** [review]

File: src/renderer/features/fellowship-evidence/components/MarkdownPreviewModal.tsx [hunk 2]
```diff
@@ -1,9 +1,12 @@
 import { useUnit } from 'effector-react';
 import { type PropsWithChildren, useEffect, useRef } from 'react';
 
+import { useFlow } from '@/shared/effector';
```
Comment (johnthecat) [inline src/renderer/features/fellowship-evidence/components/MarkdownPreviewModal.tsx]: please use Gate instead

**Review by cuteWarmFrog — DISMISSED** [review]

File: src/renderer/features/fellowship-evidence/components/MarkdownPreviewModal.tsx (hunk 2 above)
Comment (kalininilya) [reply src/renderer/features/fellowship-evidence/components/MarkdownPreviewModal.tsx]: Replaced with useGate

**Review by cuteWarmFrog — APPROVED** [review]
