### PR TITLE
fix: delivery fee

### LINKED ISSUE #1552: Add support delivery fee for XCMs
Fix on Android for delivery fee:
A message sending chain now can deduct delivery fee. In recent Kusama upgrade exponential delivery fee is introduced calculated using formula:

`F * (B + encoded_msg_len * M)`

where F is a factor that depends on the queue load: dmp.deliveryFactor, xcmpQueue.deliveryFactor

B - base fee constant in xcm config: https://github.com/polkadot-fellows/runtimes/blob/v1.1.0/relay/kusama/src/xcm_config.rs#L116C12-L116C27

M - TransactionByteFee constant in the config: https://github.com/polkadot-fellows/runtimes/blob/v1.1.0/relay/kusama/src/lib.rs#L414

For example, if one is sending KSM: Kusama ➝ Asset Hub. It will now pay:

fee for teleport extrinsic on Kusama
delivery fee on Kusama (by xcm pallet)
xcm execution fee on Asset Hub

Note that xcm-pallet widthraws fee not from the holding but from the sender's balance before sending message to the destination chain.

Android fix PR https://github.com/novasamatech/nova-wallet-android/pull/1411/files

Should be done after ED validation implementation.

### LINKED ISSUE #2850: Multisig. Cross-chain fee calculates wrong on Operations page
## Description

Polkadot Asset Hub -> Mythos XCM shows cross-chain fee in DOT and shows 0 from Operations page, when approve multisig.

Screenshot 2024-12-12 at 11 21 37

## Environment
https://github.com/novasamatech/nova-spektr/commit/261ea0fb3861522933e5b3f05330309a7775f339

### LINKED ISSUE #2871: XCM. PAH to Mythos - can't bypass Recipient check with EVM address
## Description

Screenshot 2024-12-18 at 10 03 16

Address example:
0x4c2ab98b646ce36df6a4a4407ab9fcee1c90549a

## Environment
https://github.com/novasamatech/nova-spektr/commit/aec2ef298e5061fd22d29d7a05c6a2029fc6adab

### PR DESCRIPTION
**Pull request by Asmadek**
* fix delivery fee calculation
* fix reserve fee calculation
* fix address validation

### CODE REVIEW

File: src/renderer/widgets/Transfer/model/xcm-transfer-model.ts [hunk 1]
```diff
@@ -281,12 +266,12 @@ sample({
 export const xcmTransferModel = {
   $config,
   $apiDestination,
-  $parentChainApi,
   $xcmData,
   $xcmFee,
   $isXcmFeeLoading,
   $transferDirections,
   $xcmParaId,
+  $xcmChainId: $xcmChain,
```
Comment (sokolova-an) [inline src/renderer/widgets/Transfer/model/xcm-transfer-model.ts]: why do we name it `$xcmChainId` if we pass `$xcmChain`?

**Review by sokolova-an — APPROVED** [review]

File: src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx [hunk 2]
```diff
@@ -69,8 +69,11 @@ export const Confirmation = ({ api, tx, account, chain, signAccount, feeTx, onSi
   });
 
   useEffect(() => {
-    xcmTransferModel.events.xcmConfigLoaded();
-  }, []);
+    xcmTransferModel.events.xcmStarted({
+      chain,
+      asset,
+    });
+  }, [chain, asset, xcmApi]);
```
Comment (tuul-wq) [inline src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx]:
```suggestion
    xcmTransferModel.events.xcmStarted({ chain, asset });
  }, [chain, asset, xcmApi]);
```

File: src/renderer/pages/Operations/components/TransactionAmount.tsx [hunk 3]
```diff
@@ -11,7 +11,8 @@ type Props = {
 };
 
 export const TransactionAmount = ({ tx, className }: Props) => {
-  const asset = tx && getAssetById(tx.args.asset, chainsService.getChainById(tx.chainId)?.assets);
+  const assetId = tx && (tx.args.assetId || tx.args.asset);
```
Comment (tuul-wq) [inline src/renderer/pages/Operations/components/TransactionAmount.tsx]: This should work
```suggestion
  const assetId = tx?.args.assetId || tx?.args.asset;
```

**Review by tuul-wq — APPROVED** [review]
