### PR TITLE
fix: Beneficiary fixes

### LINKED ISSUE #4800: My profile. Beneficiary widget

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
Need to fix some bugs:
1) Selected beneficiary applies to all added accounts. It is expected that beneficiary accounts will be linked to their owners by accountId + chainId.

2) If both proxied and proxy accounts are added to spektr, selecting a proxied account as beneficiary displays the proxied wallet instead of the selected account

## Related Issues
Closes #4800

## Changes Made
Fixed saving beneficiary to localStorage with key including accountId and chainId

## Screenshots
Снимок экрана 2025-10-28 в 17 02 52

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/fellowship-salary/model/beneficiary.ts [hunk 1]
```diff
@@ -1,18 +1,50 @@
...
-  key: 'fellowship-salary-beneficiary',
+sample({
+  clock: $beneficiaryKey,
+  target: populateBeneficiaryFx,
+});
+
+sample({
+  clock: $beneficiary,
+  source: $beneficiaryKey,
+  filter: beneficiary => beneficiary !== null,
```
Comment (cuteWarmFrog) [inline src/renderer/features/fellowship-salary/model/beneficiary.ts]: just use nonNullable

**Review by cuteWarmFrog — APPROVED** [review]

**Review by cuteWarmFrog — APPROVED** [review]

File: src/renderer/features/fellowship-salary/model/beneficiary.ts (hunk 1 above)
Comment (Yanaty) [reply src/renderer/features/fellowship-salary/model/beneficiary.ts]: fixed
