### PR TITLE
fix: update wc pairing

### LINKED ISSUE #2354: WalletConnect. Refresh won't update the list of accounts
## Description

When user refresh walletconnect wallet it will request old list of accounts.

## Steps to Reproduce

1. Connect to WalletConnect
2. Add new network to the config
3. Refresh wallet 

## Expected Behavior
Wallet connect will be requested with updated network list

## Actual Behavior
Refresh will request old list of networks

## Environment
https://github.com/novasamatech/nova-spektr/commit/b3a381d4e43fe8ca1218e07e785f903d5eda47a4

### LINKED ISSUE #2691: WalletConnect. Refresh lead to duplicates in database
## Description

When user perform a reconnect for WalletConnect added wallet it may lead to duplicates in database.

Example:

https://github.com/user-attachments/assets/d6b24470-0fed-4928-93d0-d86dcfbbc198

## Steps to Reproduce

1. Add WalletConnect wallet via NovaWallet
2. Perform Reconnect flow a multiple times
  - Check database accounts table 

## Expected Behavior
After reconnect all accounts will be updated

## Actual Behavior
Some times reconnect will lead to duplications in the table

## Environment
https://github.com/novasamatech/nova-spektr/commit/3f0353542615436e4922356d1e6697cec74edcd5

### PR DESCRIPTION
**Pull request by Asmadek**
* use provider instead client
* new component for wc connect qr code
* update reconnect flow for old accounts

### CODE REVIEW

File: src/renderer/widgets/WalletDetails/model/wc-details-model.ts [hunk 1]
```diff
@@ -57,7 +57,11 @@ sample({
     session: walletConnectModel.$session,
   },
   filter: ({ step, wallet, session }) => {
-    return step === ReconnectStep.RECONNECTING && Boolean(wallet) && Boolean(session?.topic);
+    return (
+      (step === ReconnectStep.RECONNECTING || step === ReconnectStep.REFRESH_ACCOUNTS) &&
+      Boolean(wallet) &&
```
Comment (johnthecat) [inline src/renderer/widgets/WalletDetails/model/wc-details-model.ts]: `nonNullable`?

**Review by johnthecat — APPROVED** [review]
