### PR TITLE
fix: multiple address book rows on wallet rename

### LINKED ISSUE #5284: Wallet rename flow. Nova wallet - will create multiple rows
## Description

When user rename Nova Wallet it will create multiple rows in address book.

## Steps to Reproduce

1. Add Nova Wallet
2. Rename that wallet

## Expected Behavior

Add row in address book

## Actual Behavior

Add row in address book for each address

Example:

https://github.com/user-attachments/assets/e5715c44-3bb8-4628-a1aa-5580419bed12

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
When user rename Nova Wallet it will create multiple rows in address book.

## Related Issues
Closes #5284

## Changes Made
Fixed the creation of multiple rows in the address book

## Screenshots/Recordings

https://github.com/user-attachments/assets/5d518781-4615-4c82-b2da-1b6a48f42913

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/domains/network/account/service.ts [hunk 1]
```diff
@@ -196,20 +197,17 @@ function getAccountAddressPrefix(
...
     (wallet.type === WalletType.POLKADOT_VAULT || wallet.type === WalletType.SINGLE_PARITY_SIGNER) &&
     'rootAccountId' in wallet
   ) {
     return wallet.rootAccountId as AccountId;
   }
 
-  return null;
+  const walletAccounts = filterAccountsByWallet(accounts, wallet.id);
+
+  const universalAccount = walletAccounts.find(acc => acc.type === 'universal');
```
Comment (johnthecat) [inline src/renderer/domains/network/account/service.ts]: accountUtils.isUniversalAccount

File: src/renderer/domains/network/account/service.ts [hunk 2]
```diff
@@ -285,7 +283,13 @@ function resolveAccountName({
       return accountChain?.addressPrefix;
     })();
 
-  return toShortAddress(toAddress(accountId, { prefix }), 5);
+  const isShardAccount =
```
Comment (johnthecat) [inline src/renderer/domains/network/account/service.ts]: let's remove this logic completely

**Review by johnthecat — DISMISSED** [review]

**Review by aaa123eee — DISMISSED** [review]

File: src/renderer/domains/network/account/service.ts (hunk 1 above)
Comment (Yanaty) [reply src/renderer/domains/network/account/service.ts]: fixed

File: src/renderer/domains/network/account/service.ts (hunk 2 above)
Comment (Yanaty) [reply src/renderer/domains/network/account/service.ts]: fixed

**Review by aaa123eee — APPROVED** [review]
