### PR TITLE
Fix: add custom delegate validation

### LINKED ISSUE #2133: Governance. Your delegation. Voting power shows 0.
## Description
Voting power in your delegation shows 0, when its actually a number.

## Steps to Reproduce

1. Delegate to all tracks via NovaWallet
2. Open delegations for the same wallet on Spektr

## Expected Behavior
Shows delegated Voting power
screen

## Actual Behavior
Shows 0
Screenshot 2024-08-19 at 13 26 57

## Environment
https://github.com/novasamatech/nova-spektr/commit/a1e90ef296095ad76870c380166686644a2b55d7

### LINKED ISSUE #2136: Governance. Tracks. Can interact with read-only tracks via "chips"
## Description
When there is some read-only tracks it still be activate\deactivate by "chips"

https://github.com/user-attachments/assets/2f9ccf0a-8c09-4305-adf5-55422f787a5b

## Environment
https://github.com/novasamatech/nova-spektr/commit/a1e90ef296095ad76870c380166686644a2b55d7

### LINKED ISSUE #2138: Governance. Delegation. Add custom still works with error state
## Description
User can create operation with delegation to himself

https://github.com/user-attachments/assets/f80cadbf-2bc1-4ac1-8ebb-9c9f58a6c77f

## Expected Behavior
If an error occurs, Continue is not available.

## Actual Behavior
Can move forward despite any errors

## Environment
https://github.com/novasamatech/nova-spektr/commit/a1e90ef296095ad76870c380166686644a2b55d7

### PR DESCRIPTION
**Pull request by Asmadek**
Fix: add custom delegate validation
fix: show correct voting power
fix: don't select disabled tracks

### CODE REVIEW

File: src/renderer/widgets/DelegateModal/lib/helpers.ts [hunk 1]
```diff
@@ -12,3 +13,7 @@ export const getTreasuryTrackDescription = (asset: Asset | null, description: st
 
   return t(`${description}General`);
 };
+
+export const getTrackIds = (tracks: Track[], votedTracks: string[]): number[] => {
+  return tracks.filter((t) => !votedTracks.includes(t.id)).map((track) => Number(track.id));
+};
```
Comment (sokolova-an) [inline src/renderer/widgets/DelegateModal/lib/helpers.ts:19]: This check for voting is already covered by this sample in the model. Don't need for another filtering function here

```
sample({
  clock: tracksSelected,
  source: { tracks: $tracks, votedTracks: $votedTracks },
  fn: ({ tracks, votedTracks }, newTracks) => {
    const resultArray = newTracks.filter((num) => !votedTracks.includes(num.toString()));

    if (resultArray.every((t) => tracks.includes(t))) {
      return removeItemsFromCollection(tracks, resultArray);
    }

    return addUniqueItems(tracks, resultArray);
  },
  target: $tracks,
});
```

**Review by sokolova-an — CHANGES_REQUESTED** [review]

File: src/renderer/widgets/DelegateModal/lib/helpers.ts (hunk 1 above)
Comment (Asmadek) [reply src/renderer/widgets/DelegateModal/lib/helpers.ts:19]: Only this checking isn't enough, because we should show chips as selected when select all available tracks

**Review by sokolova-an — APPROVED** [review]
