### PR TITLE
fix: polkadot vault edit sharded keys

### LINKED ISSUE #4974: Multishard vault. Shard range pattern (//0...5) is not parsed when creating or editing Vault derivation paths
## Description

When adding or editing derivation paths for a Vault account, Spektr should support shard range creation using the pattern //0...5, automatically generating all shard derivations within the specified range.
Currently, this pattern is not recognized - the user must manually create each shard one by one (e.g., //0, //1, //2, etc.), which is inefficient and error-prone.

## Screenshots

Image

### LINKED ISSUE #5010: Polkadot Vault multishard export generates incorrect shard range (/0...3 instead of /0...2 for 3 shards)
## Description

When exporting multishard Polkadot Vault keys, the export service incorrectly calculates the shard range.
For wallets containing 3 shards, the expected derivation range should be /0...2, but the system currently generates /0...3, adding one extra shard index.

## Steps to Reproduce

1. Create or pair a multishard Polkadot Vault wallet with 3 shards.
2. Click Export keys to generate the keyset.
3. Inspect the path range in the generated exported file.

## Expected Behavior

- The export correctly represents the shard range as /0...2 for 3 shards (0, 1, 2).
- The exported data matches the actual number of shards in the wallet.

## Actual Behavior

The export incorrectly outputs /0...3, implying 4 shards instead of 3.

### LINKED ISSUE #5011: Polkadot Vault import does not accept .txt version of the old-format keyset file
## Description

The Polkadot Vault import feature incorrectly rejects old-versioned keyset files in .txt format.
Currently, the import process only accepts the same legacy keyset structure if it has a .yaml extension.
When the exact same old-versioned keyset is provided as a .txt file (downloaded from the import template), the system displays an error and refuses to import it.

## Steps to Reproduce

1. Download the old-versioned import template in .txt format.
2. Fill out with proper addresses
3. Open Import keyset in a Vault wallet.
4. Select the .txt file and confirm import.

## Expected Behavior

The system recognizes the .txt file as a valid old-format keyset and imports it successfully, same as .yaml.

## Actual Behavior

The .txt file is rejected with an unsupported format error, even though the content is identical to the accepted .yaml version.

### LINKED ISSUE #5013: Polkadot vault. EVM derivations incorrectly allow soft paths (/) during import
## Description

EVM derivations in Polkadot Vault only support hard paths (//), not soft ones (/).
However, when importing a keyset that includes soft path derivations for EVM accounts, the system does not perform any validation or show an error during import.
The issue only becomes visible later, when attempting to scan the generated QR code with the Polkadot Vault app, which fails to parse the invalid derivations.

## Steps to Reproduce

1. Prepare or import a Vault keyset file containing EVM derivations using soft paths (e.g., //myths/public).
2. Import the keyset into Spektr.
3. Observe that no validation errors appear during import.
4. Attempt to sign using the Polkadot Vault app by scanning the generated QR.

## Expected Behavior

- The import process should detect and reject soft paths in EVM derivations.
- Validation error should appear immediately during import, preventing invalid configuration from being saved.

## Actual Behavior

- Import completes successfully with no warnings or errors.
- The issue surfaces only when scanning the QR with the Vault app - parsing fails due to unsupported soft paths.

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Add sharded derivations through the pattern: `//0...5`
Reconcile the accounts creation for key constructor and file import.
Derivations parser and improved validation.
Fixes various bugs related to the file imports.

## Related Issues
Closes https://github.com/novasamatech/nova-spektr/issues/4974
Closes [#5013](https://github.com/novasamatech/nova-spektr/issues/5013)
Closes https://github.com/novasamatech/nova-spektr/issues/5010
Closes https://github.com/novasamatech/nova-spektr/issues/5011

## Screenshots/Recordings
Screenshot 2025-10-31 at 9 32 25 PM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/polkadot-vault-wallet/service.ts [hunk 1]
```diff
@@ -9,38 +11,88 @@ import {
...
+  return pickBy(grouped, items => items.length > 1);
+}
 
-function populateDraftAccounts(draftKeys: DerivationKeyDraft[], chains: Record<ChainId, Chain>) {
-  const shardedKeyGroups = groupShardedDerivations(draftKeys);
+function buildDerivationToGroupIdMap(
+  draftAccounts: Pick<VaultChainAccount, 'chainId' | 'derivationPath'>[],
+  existingAccounts: (VaultChainAccount | VaultShardAccount)[],
+): Map<string, string> {
+  const draftGroups = groupShardedDerivations(draftAccounts);
```
Comment (johnthecat) [inline src/renderer/features/polkadot-vault-wallet/service.ts]: We discussed it 3 or 4 times, also there is special mark in the task about new form
`we need to implement correct derivation parser, string -> Token[]`
There is no any derivation parser here so you need to make a lot of work around merging/unmerging/validation/autocomplete. Why did you skip this part?

**Review by johnthecat — CHANGES_REQUESTED** [review]

File: src/renderer/features/polkadot-vault-wallet/service.ts (hunk 1 above)
Comment (savvyer) [reply src/renderer/features/polkadot-vault-wallet/service.ts]: There was no need for a parser for the version I implemented at first without a sharded pattern `0...5`
Now, yes, it is a lot of code around merging/unmerging shards. and it sucks

Comment (savvyer) [reply src/renderer/features/polkadot-vault-wallet/service.ts]: Implemented a derivation parser, its a bit more helpful, but you still have to do some work around merging/unmerging/validation/autocomplete.

File: src/renderer/features/wallets/KeyConstructor/model/constructor-model.ts [hunk 2]
```diff
@@ -31,30 +40,73 @@ const $keys = createStore<Record<string, DerivationKeyDraft>>({});
...
+  keys: Record<string, DerivationKeyDraft>,
+  chains: Record<ChainId, Chain>,
+) {
+  return Object.entries(keys)
+    .filter(([otherKeyId]) => otherKeyId !== keyId)
+    .filter(([, otherKey]) => {
+      const otherChain = chains[otherKey.chainId];
+      return isEthereumBased
+        ? networkUtils.isEthereumBased(otherChain.options)
+        : (otherChain.parentId ?? otherChain.chainId) === relayChainId;
```
Comment (kalininilya) [inline src/renderer/features/wallets/KeyConstructor/model/constructor-model.ts]: Maybe this part would be easier to follow if we rewrote it using a couple of if statements, right now it’s a bit hard to read

**Review by kalininilya — APPROVED** [review]

**Review by johnthecat — APPROVED** [review]

File: src/renderer/features/wallets/KeyConstructor/model/constructor-model.ts (hunk 2 above)
Comment (savvyer) [reply src/renderer/features/wallets/KeyConstructor/model/constructor-model.ts]: Agree, its a bit confusing
