### PR TITLE
fix: portfolio chain centric view

### LINKED ISSUE #4883: Polkadot Vault. Update logic on Portfolio view
Since we are merging PV keys to consensus based, we would like to show all tokens available in relaychain + parachains on Portfolio view. When user has a key in Kusama, he will be able to use all tokens from porfolio page, which is available in Kusama and it's parachains

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Fixes portfolio chain-centric view. Correctly filter all available chains for accounts that user picked in the modal selector.

## Related Issues
Closes https://github.com/novasamatech/nova-spektr/issues/4883

## Screenshots/Recordings
Screenshot 2025-10-22 at 4 07 54 PM
Screenshot 2025-10-22 at 4 08 27 PM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/assets/AssetsChainView/ui/AssetsChainView.tsx [hunk 1]
```diff
@@ -39,31 +40,30 @@ export const AssetsChainView = ({ query, activeShards, hideZeroBalances, assetsV
...
-          continue;
+      return activeWalletAccounts.some((account) => {
+        if (!visibleAccountIds.has(account.accountId)) return false;
 
-        if (!isMultisig || networkUtils.isMultisigSupported(chain.options)) {
-          filteredChains.push(chain);
-          break;
+        if (!accountService.isAccountAvailableOnChain(account, chain)) return false;
+
+        if (isMultisig && !networkUtils.isMultisigSupported(chain.options)) {
```
Comment (johnthecat) [inline src/renderer/features/assets/AssetsChainView/ui/AssetsChainView.tsx]: Did you checked this statement? What does it do? Let's remove

Comment (savvyer) [reply src/renderer/features/assets/AssetsChainView/ui/AssetsChainView.tsx]: yeah, it seems it doesn't do anything. should be safe to remove

File: src/renderer/features/assets/AssetsChainView/ui/AssetsChainView.tsx [hunk 2]
```diff
@@ -39,31 +39,25 @@ export const AssetsChainView = ({ query, activeShards, hideZeroBalances, assetsV
...
 
-        if (!isMultisig || networkUtils.isMultisigSupported(chain.options)) {
-          filteredChains.push(chain);
-          break;
-        }
-      }
-    }
+        if (!accountService.isAccountAvailableOnChain(account, chain)) return false;
+
+        return true;
```
Comment (johnthecat) [inline src/renderer/features/assets/AssetsChainView/ui/AssetsChainView.tsx]: ?
```suggestion
        return accountService.isAccountAvailableOnChain(account, chain);
```

Comment (savvyer) [reply src/renderer/features/assets/AssetsChainView/ui/AssetsChainView.tsx]: good! updated this part

File: src/renderer/pages/Assets/Assets/model/assets-model.ts [hunk 3]
```diff
@@ -1,16 +1,13 @@
...
 import { type AnyAccount } from '@/domains/network';
-import { accountUtils, walletUtils } from '@/entities/wallet';
 import { walletSelect } from '@/aggregates/wallet-select';
 import { assetsSearchModel, assetsSettingsModel, portfolioModel } from '@/features/assets';
 
-const activeShardsSet = createEvent<AnyAccount[]>();
+const setVisibleAccounts = createEvent<AnyAccount[]>();
 
-const $activeShards = createStore<AnyAccount[]>([]);
+const $visibleAccounts = createStore<AnyAccount[]>([]);
```
Comment (aaa123eee) [inline src/renderer/pages/Assets/Assets/model/assets-model.ts:10]: why not 

```typescript 
createStore().on(setVisibleAccounts, (state, update) => {...})
```

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/pages/Assets/Assets/model/assets-model.ts (hunk 3 above)
Comment (savvyer) [reply src/renderer/pages/Assets/Assets/model/assets-model.ts:10]: I thought its cleaner to just use sample below for two events
