### PR TITLE
fix: add proxy

### LINKED ISSUE #4208: Proxy. Broken layout in 'Add delegated authority (proxy)' modal - large empty space at bottom
## Description

When opening the modal to create a proxy (delegate authority), a large portion of the modal remains empty below the form content. 

## Steps to Reproduce

1. Open Wallet details
2. Click Add delegated authority
3. Observe the layout of the modal, especially the area beneath the action buttons

## Expected Behavior

No large empty areas should remain unused, especially beneath interactive elements.

## Actual Behavior

The modal has a large, unused empty space at the bottom, well below the input fields and buttons.

Image

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Fix AddProxy modal height. Use transaction builder. Use fake tx to calculate fee before all form fields are filled.

## Related Issues
Closes #4208

## Changes Made
- Fixed modal height to fit content
- Transaction fee calculation
- Refactored coreTx by using existing transactionBuilder function
- Refactored buildAddProxy. `toAddress` function is made for use in UI only

### CODE REVIEW

**Review by cuteWarmFrog — APPROVED** [review]
Nice

File: src/renderer/entities/transaction/lib/transactionBuilder.ts [hunk 1]
```diff
@@ -571,7 +572,7 @@ function buildCreatePureProxy({ chain, accountId }: CreateProxyPureParams): Tran
 type AddProxyParams = {
   chain: Chain;
   accountId: AccountId;
-  delegateAccountId: AccountId;
+  delegateAccountId: AccountId | Address;
```
Comment (cuteWarmFrog) [inline src/renderer/entities/transaction/lib/transactionBuilder.ts:574]: why?

File: src/renderer/features/proxy-add/model/form-model.ts [hunk 2]
```diff
@@ -325,26 +320,22 @@ const $api = combine(
...
+    chain: form.fields.chain.$value,
+    isConnected: $isChainConnected,
+  },
+  ({ isConnected, chain }): Transaction | null => {
+    if (!chain || !isConnected) return null;
+
+    return transactionBuilder.buildAddProxy({
+      chain: chain,
+      accountId: TEST_ACCOUNTS[0],
+      delegateAccountId: toAddress(TEST_ACCOUNTS[0], { prefix: chain.addressPrefix }),
```
Comment (johnthecat) [inline src/renderer/features/proxy-add/model/form-model.ts]: can be just account id, pjs will transform in inside extrinsic anyway

File: src/renderer/entities/transaction/lib/transactionBuilder.ts (hunk 1 above)
Comment (savvyer) [reply src/renderer/entities/transaction/lib/transactionBuilder.ts:574]: Because we can pass in both AccountId | Address
Some multisig related code passes AccountId and Add Proxy modal passes Address

**Review by sokolova-an — APPROVED** [review]
