### PR TITLE
fix: signatories for multisig

### LINKED ISSUE #1461: Wallet details. Single wallet multisig. Signatories tab shows same lines.
## Description
For the signle wallet multisig wallet details, tab with signatories shows the same wallets.

## Steps to Reproduce

1. Create sinlge multisig wallet
2. Go to multisig wallet details
3. Select Signatories tab

## Expected Behavior
Addresses for different signatories is shown

## Actual Behavior
The same wallets repeat a few times

## Environment

- Operating system: macOS
- Version:  Nova-Spektr-Stage-1.4.4-3-arm64.dmg

## Screenshots
Screenshot 2024-02-15 at 13 08 59

### PR DESCRIPTION
**Pull request by Asmadek**
closes #1461 

* filter signatory accounts by existed accounts

### CODE REVIEW

File: src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts [hunk 1]
```diff
@@ -145,6 +145,29 @@ const $signatoryWallets = combine(
...
+  ({ walletAccounts, accounts }): Signatory[] => {
+    const multisigAccount = walletAccounts[0];
+    if (!multisigAccount || !accountUtils.isMultisigAccount(multisigAccount)) return [];
+
+    const accountsMap = dictionary(accounts, 'accountId');
+
+    return multisigAccount.signatories.reduce<Signatory[]>((acc, signatory) => {
+      const account = accountsMap[signatory.accountId];
+
+      if (account) {
```
Comment (tuul-wq) [inline src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts:162]:
```suggestion
      if (accountsMap[signatory.accountId]) {
```

**Review by tuul-wq — APPROVED** [review]
