### PR TITLE
fix: correct multisig find flow

### LINKED ISSUE #3018: Onboarding. Creates duplicates of Multisig wallets
## Description

Onboarding flow has a few problems:
- Can't interact with the app while adding new wallets (moved to separate issue - https://github.com/novasamatech/nova-spektr/issues/3021)
- May create duplicates of multisig wallets
- Proxy-worker won't start after adding a wallet (moved to separate issue - https://github.com/novasamatech/nova-spektr/issues/3022)

Example of onboarding:

https://github.com/user-attachments/assets/bab352d2-3f77-4180-b9c7-4bc9995d1080

## Test data

[spektr-database.json](https://github.com/user-attachments/files/18501013/spektr-database.json)

## Steps to Reproduce

1. Import test data
2. Reload the app
3. Go to Governance page
4. Wait for adding multisigs

## Expected Behavior

Added 71 multisig wallets, in results has no duplications

## Actual Behavior

Added different numbers of multisig wallets on each try, there is duplications in wallets

## Environment
https://github.com/novasamatech/nova-spektr/commit/6d80603758b1695c859886205bf337ae7acdeac7

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #3018

### CODE REVIEW

File: src/renderer/entities/multisig/model/multisigs-model.ts [hunk 1]
```diff
@@ -32,27 +31,34 @@ import { multisigUtils } from '../lib/mulitisigs-utils';
...
-  fn: (wallets) => {
-    const filteredWallets =
-      walletUtils.getWalletsFilteredAccounts(wallets, {
-        walletFn: (w) => !walletUtils.isWatchOnly(w) && !walletUtils.isProxied(w) && !walletUtils.isMultisig(w),
-      }) ?? [];
-
-    return walletUtils.getAllAccounts(filteredWallets);
+  clock: [pollingRequest, readyToRequest],
+  source: walletModel.$availableAccounts,
+  fn(accounts) {
```
Comment (Asmadek) [inline src/renderer/entities/multisig/model/multisigs-model.ts:56]: Any reasons for such style? In some places you use arrow function

**Review by Asmadek — APPROVED** [review]

File: src/renderer/entities/multisig/model/multisigs-model.ts (hunk 1 above)
Comment (johnthecat) [reply src/renderer/entities/multisig/model/multisigs-model.ts:56]: I'm experimenting with code style right now and this is one of the latest iteration. I think it's better to add eslint warning.
