### PR TITLE
fix: vested transfer UI

### LINKED ISSUE #5075: Add Validations. Warnings \ Errors

### LINKED ISSUE #5076: Apply new design

### LINKED ISSUE #5121: Vested transfer. Can't sign operation
## Description

There is an empty confirm

tested on - 51f8a0e052e685edcb95606dca3007d5d4606cd4 ( feat/vested-transfers)

Test database:

[spektr-database (11).json](https://github.com/user-attachments/files/23622353/spektr-database.11.json)

Test file:

[vested-transfer-with-errors (2).csv](https://github.com/user-attachments/files/23622360/vested-transfer-with-errors.2.csv)

Example:

https://github.com/user-attachments/assets/bd6db468-06e3-4a11-82aa-9a4389225bc0

Based on logs, fee is null:

Image

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Group call data and vested transfers under `custom operation` nav button.
Update vested transfer operation icons.
Update csv validations. Show errors and warnings.
Show target account identity.

Updated `Table` component:
Allowed to pass react components to table header. Removed hardcoded styles for table header cells.

## Related Issues
Closes https://github.com/novasamatech/nova-spektr/issues/5076
Closes https://github.com/novasamatech/nova-spektr/issues/5121
Closes [#5075](https://github.com/novasamatech/nova-spektr/issues/5075)

## Screenshots/Recordings
valid:
Screenshot 2025-11-24 at 9 36 16 PM

warnings:
Screenshot 2025-11-24 at 9 37 02 PM
Screenshot 2025-11-24 at 9 37 12 PM

errors:
Screenshot 2025-11-24 at 9 48 56 PM
Screenshot 2025-11-24 at 9 46 16 PM

custom operation dropdown:
Screenshot 2025-11-25 at 9 36 21 AM

target address identity:
Screenshot 2025-11-25 at 9 36 47 AM

## Checklist

- [X] I have performed a self-review of my own code
- [X] I have tested the changes and verified the happy path works as expected
- [X] I have provided screenshot of the working feature (if applicable)
- [X] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [X] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/vested-transfer/model/form.ts [hunk 1]
```diff
@@ -220,36 +227,38 @@ sample({
...
-      minVestedTransfer,
-      maxVestingSchedules,
-      existingVestingSchedules,
-    });
+  const validated = vestedTransferUtils.validateCSV(params.parsedFile, schema);
 
-    const validatedData = vestedTransferUtils.validateCSV(parsedFile, schema);
+  if (validated.success) {
+    const transformSchema = vestedTransferUtils.createTransformSchema();
+    const validatedData = params.parsedFile.map((record) => transformSchema.parse(record));
```
Comment (aaa123eee) [inline src/renderer/features/vested-transfer/model/form.ts:261]: shall we wrap this parsing for safety?

**Review by aaa123eee — DISMISSED** [review]

File: src/renderer/features/vested-transfer-operation-details/components/VestedTransferOperationDetails.tsx [hunk 2]
```diff
@@ -16,45 +16,44 @@ type Props = {
...
 
+  const timelineChainId = chain.additional?.timelineChain;
+  const timelineApi = (timelineChainId && apis[timelineChainId]) ?? apis[chain.chainId] ?? null;
   const asset = getNativeAsset(chain.assets);
 
-  const vestingSchedule: VestingSchedule[] =
+  const vestingSchedule: VestingScheduleRaw[] =
     transaction.type === TransactionType.BATCH_ALL
       ? transaction.args.transactions.map(extractVestingSchedule)
       : [extractVestingSchedule(transaction)];
```
Comment (cuteWarmFrog) [inline src/renderer/features/vested-transfer-operation-details/components/VestedTransferOperationDetails.tsx:34]: Imagine that there is a proxy as well on top. Check how I fixed this case in the branch about proxy that you just mentioned

File: src/renderer/features/app-shell/components/Navigation.tsx [hunk 3]
```diff
@@ -24,7 +31,20 @@ export const Navigation = memo(() => {
         {upperItems.map(({ icon, title, link, badge }) => (
           <NavItem key={link} icon={icon} title={title} link={link} badge={badge} />
         ))}
-        <div className="flex flex-col gap-2">{actions}</div>
+
+        <Dropdown width="trigger" align="center" keepOpen open={isActionsOpen} onToggle={toggleIsActionsOpen}>
```
Comment (johnthecat) [inline src/renderer/features/app-shell/components/Navigation.tsx]: Should be in separated feature as well
app-custom-operations

**Review by cuteWarmFrog — DISMISSED** [review]

File: src/renderer/features/multisig-operations/model/approve-model.ts [hunk 4]
```diff
@@ -226,6 +223,15 @@ const { $errors, $valid } = createTxValidationStore({
   },
 });
 
+const { $: $multisigDeposit, $pending: $isDepositLoading } = createStoreFromEffect({
```
Comment (johnthecat) [inline src/renderer/features/multisig-operations/model/approve-model.ts]: why not combine?

Comment (savvyer) [reply src/renderer/features/multisig-operations/model/approve-model.ts]: createStoreFromEffect already provides $pending store. Seems like a perfect fit for the use case.

File: src/renderer/features/vested-transfer-operation-details/components/VestedTransferOperationDetails.tsx (hunk 2 above)
Comment (savvyer) [reply src/renderer/features/vested-transfer-operation-details/components/VestedTransferOperationDetails.tsx:34]: yep, it is handled above via `const transaction = operationDetailsUtils.getCoreTx(operation);`

File: src/renderer/features/multisig-operations/model/approve-model.ts (hunk 4 above)
Comment (johnthecat) [reply src/renderer/features/multisig-operations/model/approve-model.ts]: but it's sync, you don't need any pending state

Comment (savvyer) [reply src/renderer/features/multisig-operations/model/approve-model.ts]: yeah, good point. let me fix it up

**Review by stepanLav — APPROVED** [review]
