### PR TITLE
fix: added explorers for multisig events using blocknumber and index

### LINKED ISSUE #4699: Multisig operations. Log shows not all events
## Description

Some events is not shown in multisig operations log

Image

## Expected Behavior

All sign extrinsic is available in log section

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
 added explorers for multisig events using blocknumber and index

## Related Issues
Closes #4699

## Screenshots/Recordings
image

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/multisig-operations/components/LogModal.tsx [hunk 1]
```diff
@@ -150,16 +151,20 @@ const LogModal = ({ isOpen, onClose, operation, account, connection, contacts }:
...
                           <BodyText className="text-text-tertiary">{formatDate(Number(event.timestamp), 'p')}</BodyText>
 
-                          {event.extrinsicHash && connection?.explorers && (
+                          {event.blockCreated && Number.isInteger(event.blockCreated) && connection?.explorers && (
                             <div>
                               <ContextMenu button={<IconButton name="info" size={16} />}>
                                 <ContextMenu.Group>
-                                  <ul className="flex flex-col gap-y-2">
+                                  <ul className="flex flex-col space-y-2">
                                     {connection.explorers.map(explorer => (
```
Comment (johnthecat) [inline src/renderer/features/multisig-operations/components/LogModal.tsx]: return null if getMultisigEventLink returns emply response

**Review by johnthecat — APPROVED** [review]
