### PR TITLE
fix: vested transfer starting block warning

### LINKED ISSUE #5206: Vested transfer. Start block tooltip shows wrong
## Description

For the PAH it shows wrong value in tooltip, also generally define that block in the past - wrong:

tooltip shows - 07.06.2022 at 22.28

Image

but actually it a few minutes in the past:

Image

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Update starting block warning message to tell the user that he must use the relay chain blocks.

## Related Issues
Closes https://github.com/novasamatech/nova-spektr/issues/5206

## Changes Made
- Update starting block warning message
- Override default table cell aligning
- Zod schema returns one error/warning per field, so render one issue

## Screenshots/Recordings
Screenshot 2025-11-26 at 1 30 02 PM

Screenshot 2025-11-26 at 1 30 18 PM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/entities/vesting/ui/VestingSchedulePreview.tsx [hunk 1]
```diff
@@ -197,7 +197,7 @@ export const VestingSchedulePreview = ({
       <Modal.Content>
         <div className="px-2 pb-3">
           <ScrollArea>
-            <Table columns={columns} data={tableData} className="w-full rounded-lg" />
+            <Table columns={columns} data={tableData} className="w-full rounded-lg [&_.table-cell]:!align-top" />
```
Comment (johnthecat) [inline src/renderer/entities/vesting/ui/VestingSchedulePreview.tsx]: wtf is this, we don't do that
