### PR TITLE
Fix: break transfer button after add to basket

### LINKED ISSUE #1801: Basket. Empty page appear on a second after adding an operation to the Basket.
## Description

1. When user click on "Save to basket" empty page appears on a second
2. After save to basket - can't interact with elements on the page

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/7c78d61d-2f4b-4e5f-9141-178ad3e13e10

</details>

## Environment
https://github.com/novasamatech/nova-spektr/commit/36f0e025b9dca5cdf7db66b521f9200584f39813

### PR DESCRIPTION
**Pull request by Asmadek**
fix: break transfer after add to basket
fix: sign button text when add to basket available

### CODE REVIEW

File: src/renderer/entities/operations/ui/SignButton.tsx [hunk 1]
```diff
@@ -21,18 +21,21 @@ const WalletText: Record<SignableWalletFamily, string> = {
...
   disabled?: boolean;
   className?: string;
   onClick?: () => void;
 };
 
-export const SignButton = ({ disabled, type, className, onClick }: Props) => {
+export const SignButton = ({ disabled, isDefault, type, className, onClick }: Props) => {
   const { t } = useI18n();
 
+  console.log('xcm', isDefault);
```
Comment (sokolova-an) [inline src/renderer/entities/operations/ui/SignButton.tsx]: do we need this `console.log`?

File: src/renderer/widgets/AddProxyModal/ui/Confirmation.tsx [hunk 2]
```diff
@@ -10,6 +10,7 @@ import { proxyUtils } from '@entities/proxy';
 import { confirmModel } from '../model/confirm-model';
 import { AssetBalance } from '@entities/asset';
 import { AssetFiatBalance } from '@entities/price/ui/AssetFiatBalance';
+import { isEmptyComponent } from '@/src/renderer/shared/lib/utils';
```
Comment (sokolova-an) [inline src/renderer/widgets/AddProxyModal/ui/Confirmation.tsx]: import name here and below

**Review by sokolova-an — APPROVED** [review]

File: src/renderer/features/operations/OperationsConfirm/ui/AddToBasketButton.tsx [hunk 3]
```diff
@@ -11,11 +11,11 @@ type Props = {
 export const AddToBasketButton = ({ wallet, onTxSaved }: Props) => {
   const { t } = useI18n();
 
-  if (wallet && !basketUtils.isBasketAvailable(wallet)) return <></>;
+  if (wallet && !basketUtils.isBasketAvailable(wallet)) return null;
```
Comment (tuul-wq) [inline src/renderer/features/operations/OperationsConfirm/ui/AddToBasketButton.tsx]: 👍

File: src/renderer/entities/operations/ui/SignButton.tsx [hunk 4]
```diff
@@ -42,7 +45,7 @@ export const SignButton = ({ disabled, type, className, onClick }: Props) => {
       }
       onClick={onClick}
     >
-      {t(type ? WalletText[type as SignableWalletFamily] : UnkownWalletText)}
+      {t(type && !isDefault ? WalletText[type as SignableWalletFamily] : DefaultSignButton)}
```
Comment (tuul-wq) [inline src/renderer/entities/operations/ui/SignButton.tsx:46]: As I understand if we have 2 buttons, `SignButton` must have simplified naming - "Sign", right?

File: src/renderer/widgets/AddProxyModal/ui/Confirmation.tsx [hunk 5]
```diff
@@ -170,6 +171,7 @@ export const Confirmation = ({ onGoBack, secondaryActionButton }: Props) => {
         <div className="flex gap-4">
           {secondaryActionButton}
           <SignButton
+            isDefault={!isEmptyComponent(secondaryActionButton)}
```
Comment (tuul-wq) [inline src/renderer/widgets/AddProxyModal/ui/Confirmation.tsx]: Why do we try to check inner content of a `secondaryActionButton`?

File: src/renderer/entities/operations/ui/SignButton.tsx (hunk 4 above)
Comment (Asmadek) [reply src/renderer/entities/operations/ui/SignButton.tsx:46]: Right

File: src/renderer/widgets/AddProxyModal/ui/Confirmation.tsx (hunk 5 above)
Comment (Asmadek) [reply src/renderer/widgets/AddProxyModal/ui/Confirmation.tsx]: Because for add to basket button we check availability inside of component and If component return null, it still be a component

**Review by Tbaut — APPROVED** [review]
Having this `{secondaryActionButton}` and the `isDefault={!isEmptyComponent(secondaryActionButton)}` everywhere sounds like a code smell to me. It'd be nice to have this integrated in the `SignButton` as a prop.

File: src/renderer/widgets/AddProxyModal/ui/AddProxy.tsx [hunk 6]
```diff
@@ -43,7 +43,12 @@ export const AddProxy = () => {
       {addProxyUtils.isConfirmStep(step) && (
         <Confirmation
           secondaryActionButton={
-            <AddToBasketButton wallet={initiatorWallet} onTxSaved={() => addProxyModel.events.txSaved()} />
+            initiatorWallet &&
+            !basketUtils.isBasketAvailable(initiatorWallet) && (
```
Comment (tuul-wq) [inline src/renderer/widgets/AddProxyModal/ui/AddProxy.tsx]: I suppose it's `initiatorWallet  && basketUtils.isBasketAvailable(initiatorWallet)` 🤔

**Review by tuul-wq — APPROVED** [review]
