### PR TITLE
fix: vote history identity

### LINKED ISSUE #3837: Governance. Vote history. There is no identity data for voters
## Description

When user opens referenda details there is no identities for voters.

https://github.com/user-attachments/assets/87918e9e-f432-4ae1-ab8a-210326bd031c

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Show identity sub name if present. Fix identity rendering in governance voting history.

## Related Issues
Closes https://github.com/novasamatech/nova-spektr/issues/3837

### CODE REVIEW

File: src/renderer/features/governance/aggregates/voteHistory.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ const $voteHistory = combine(
 
         return splitVotes.map((vote) => ({
           ...vote,
-          name: identities[chainId]?.[vote.voter as AccountId]?.name ?? null,
+          name: identityService.getFullName(identities[chainId]?.[vote.voter as AccountId] ?? {}),
```
Comment (johnthecat) [inline src/renderer/features/governance/aggregates/voteHistory.ts]: Should be a type error. Move `identities[chainId]?.[vote.voter]` to separated value and check it before passing to `identityService.getFullName`

Comment (johnthecat) [reply src/renderer/features/governance/aggregates/voteHistory.ts]: Also, you can move `identities[chainId]` to separated variable and declare it near result

Comment (savvyer) [reply src/renderer/features/governance/aggregates/voteHistory.ts]: @johnthecat pushed an update

File: src/renderer/features/governance/aggregates/voteHistory.ts [hunk 2]
```diff
@@ -38,15 +38,21 @@ const $voteHistory = combine(
...
     for (const [referendumId, historyList] of Object.entries(history)) {
       const aggregatedHistory = historyList.flatMap((vote) => {
         const splitVotes = votingListService.getDecoupledVotesFromVotingHistory(vote);
 
-        return splitVotes.map((vote) => ({
-          ...vote,
-          name: identities[chainId]?.[vote.voter as AccountId]?.name ?? null,
-        }));
+        return splitVotes.map((vote) => {
+          const identity = chainIdentities[vote.voter as AccountId];
```
Comment (johnthecat) [inline src/renderer/features/governance/aggregates/voteHistory.ts]: why do you need to type cast in the first place? In `DecoupledVote` this field has `Address` type, maybe we got error exactly here? IMO base fix here will be to change vote.voter to to AccountId and fix structure mapping inside transport

Comment (savvyer) [reply src/renderer/features/governance/aggregates/voteHistory.ts]: The initial problem was with react memoization, freshly fetched identities were not applied in the UI.
I fixed it already.

Comment (savvyer) [reply src/renderer/features/governance/aggregates/voteHistory.ts]: Typecasting reveals the hidden problem with `DecoupledVote` in which voter property is inconsistent, its either Address or AccountId.

It doesn't affect identities fetching, its seems the fetch works both with AccountId and an Address.

Comment (savvyer) [reply src/renderer/features/governance/aggregates/voteHistory.ts]: I have removed typecasting is the code segment above by updating `DecoupledVote` type and the related code.

**Review by johnthecat — APPROVED** [review]
