### PR TITLE
Fix: Realtime balance for proxy account

### LINKED ISSUE #1641: Proxied transfers. Does not subscribe on proxied balance.
## Description
When user got an error about balance:
Screenshot 2024-04-08 at 10 18 04

that won't be updated until select this account as an active

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/853cda15-b480-4283-a54b-e5cce1d461a5

</details>

## Steps to Reproduce

1. Select as active proxied wallet
2. Trigger an error about insufficient balance
3. Send a few tokens to this account in another app
4. Try to sign the operation after successful transfer

## Expected Behavior
The app get updated balances of proxied wallet

## Actual Behavior
Balance won't be updated until switch to the proxied wallet

## Environment
https://github.com/novasamatech/nova-spektr/commit/23ee363cc50fa75f156ee799eb31603b13a0eee2

### PR DESCRIPTION
**Pull request by tuul-wq**
- Updated balance subscription for proxied wallet
- Improved interaction between `balanceBucket` and `populateBalancesFx`
- All operations use live proxy balance

closes #1641

### CODE REVIEW

File: src/renderer/features/balances/subscription/lib/balance-sub-utils.ts [hunk 1]
```diff
@@ -41,15 +41,16 @@ function getAccountsToSubscribe(
...
+    return [firstAccount, ...getSiblingAccounts(proxyWallet, wallets, [proxyAccount], accounts)];
   }
 
   return walletAccounts;
 }
 
-function getNewAccounts(
-  subAccounts: SubAccounts,
+function formSubAccounts(
+  walletId: ID,
```
Comment (tuul-wq) [inline src/renderer/features/balances/subscription/lib/balance-sub-utils.ts:51]: This way all accounts are connected to one wallet
Otherwise we end up having 2 wallets for 1 proxied wallet (proxied wallet + proxy wallet)

**Review by Asmadek — APPROVED** [review]
