### PR TITLE
Fix: UI review

### LINKED ISSUE #2731: Multisigs. Design review layout issues
Fix multisig design review layout issues.

Fix according the [review](https://www.figma.com/design/eqaw6XqIm2Ox8nQ2QpUN36/Design-review?node-id=288-3615&t=2OJnVCgLSDIkrXpV-4) screens:
1. 1
2. 2
3. 3
4. 4
5. 5
6. 6
7. 8 (except 8.4)
8. 10.2, 10.3
9. 11
10. 13
11. 15.2
12. 16

### PR DESCRIPTION
**Pull request by tuul-wq**
- Multiple UI fixes for Multisig flow

closes #2731

### CODE REVIEW

File: src/renderer/entities/wallet/ui/Cards/WalletCardMd.tsx [hunk 1]
```diff
@@ -11,12 +11,17 @@ type Props = {
   description?: string | ReactNode;
   prefix?: ReactNode;
   hideIcon?: boolean;
-  className?: string;
   onClick?: () => void;
-  onInfoClick?: () => void;
 };
 
-export const WalletCardMd = ({ wallet, description, prefix, hideIcon, className, onClick, onInfoClick }: Props) => {
+export const WalletCardMd = ({
```
Comment (tuul-wq) [inline src/renderer/entities/wallet/ui/Cards/WalletCardMd.tsx]: This component update has been already done in `flex_msig`
To fix signatories modals this update has to be done

File: src/renderer/entities/wallet/ui/ContactItem/ContactItem.tsx [hunk 2]
```diff
@@ -1,67 +1,87 @@
...
   keyType?: KeyType;
-  size?: number;
+  iconSize?: number;
   className?: string;
   hideAddress?: boolean;
-  onInfoClick?: () => void;
-};
+}>;
+
 export const ContactItem = ({
```
Comment (tuul-wq) [inline src/renderer/entities/wallet/ui/ContactItem/ContactItem.tsx]: Same here

File: src/renderer/shared/lib/utils/address.ts [hunk 3]
```diff
@@ -99,31 +89,29 @@ export const isEthereumAccountId = (accountId?: AccountId): boolean => {
...
+ * @param chain Chain to operate
  *
  * @returns {Boolean}
  */
-export const validateSubstrateAddress = (address?: Address | AccountId): boolean => {
-  if (!address) return false;
-
-  if (isU8a(address) || isHex(address)) {
-    return PUBLIC_KEY_LENGTH_BYTES === u8aToU8a(address).length;
+export const validateAddress = (address: Address | AccountId, chain?: Chain): boolean => {
```
Comment (tuul-wq) [inline src/renderer/shared/lib/utils/address.ts:100]: Moved validation function from Telenova. We had almost the same but now can pass `chain` to be explicit

File: src/renderer/shared/ui-kit/Modal/Modal.tsx [hunk 4]
```diff
@@ -39,7 +39,9 @@ const Root = ({ isOpen, size = 'md', height = 'fit', children, onToggle }: Props
           <Dialog.Content
             aria-describedby={undefined}
             className={cnTw(
-              'ui-kit-modal-height flex min-w-32 max-w-full transform flex-col overflow-hidden rounded-lg bg-white text-left align-middle text-body shadow-modal transition-all',
+              'ui-kit-modal-height flex min-w-32 max-w-full flex-col overflow-hidden',
+              'text-left align-middle text-body',
+              'transform rounded-lg bg-white shadow-modal transition-transform',
```
Comment (tuul-wq) [inline src/renderer/shared/ui-kit/Modal/Modal.tsx:49]: `transition-transform` removed awkward modal resizing from step to step

File: src/renderer/pages/Onboarding/WatchOnly/WatchOnly.tsx [hunk 5]
```diff
@@ -142,7 +142,7 @@ const WatchOnly = ({ isOpen, onClose, onComplete }: Props) => {
           <Controller
             name="address"
             control={control}
-            rules={{ required: true, validate: validateAddress }}
+            rules={{ required: true, validate: (address) => validateAddress(address) }}
```
Comment (johnthecat) [inline src/renderer/pages/Onboarding/WatchOnly/WatchOnly.tsx:143]: Why?

File: src/renderer/shared/lib/utils/__tests__/address.test.ts [hunk 6]
```diff
@@ -1,7 +1,8 @@
+import { type Chain, ChainOptions } from '@/shared/core';
 import { toAddress, validateAddress } from '../address';
 import { TEST_ACCOUNTS, TEST_ADDRESS } from '../constants';
 
-describe('shared/lib/onChainUtils/address', () => {
+describe('shared/lib/address#toAddress', () => {
```
Comment (johnthecat) [inline src/renderer/shared/lib/utils/__tests__/address.test.ts]: just name it `toAddress`, why test names should be so complex?

File: src/renderer/shared/lib/utils/__tests__/address.test.ts [hunk 7]
```diff
@@ -21,44 +22,65 @@ describe('shared/lib/onChainUtils/address', () => {
     const address = toAddress(TEST_ADDRESS, { prefix: 0 });
     expect(address).toEqual(TEST_ADDRESS);
   });
+});
+
+describe('shared/lib/address#validateAddress', () => {
```
Comment (johnthecat) [inline src/renderer/shared/lib/utils/__tests__/address.test.ts]: Same here, `validateAddress`

File: src/renderer/shared/lib/utils/address.ts [hunk 8]
```diff
@@ -134,3 +122,13 @@ export const validateSubstrateAddress = (address?: Address | AccountId): boolean
...
   }
 };
+
+const validateEvmAddress = (address: Address | AccountId): boolean => {
+  try {
+    if (!isU8a(address) && !isHex(address)) return false;
+
+    return u8aToU8a(address).length === ETHEREUM_PUBLIC_KEY_LENGTH_BYTES;
+  } catch {
+    return false;
```
Comment (johnthecat) [inline src/renderer/shared/lib/utils/address.ts]: will `isU8a/isHex/u8aToU8a` functions even throw error?

File: src/renderer/shared/lib/utils/chains.ts [hunk 9]
```diff
@@ -60,3 +68,14 @@ export function getKnownChain(chainId: ChainId): WellKnownChain | undefined {
...
+
+/**
+ * Check whether chain is evm or not
+ *
+ * @param chain Value to check
+ *
+ * @returns {Boolean}
+ */
+export function isEvmChain(chain: Chain): boolean {
+  return Boolean(chain.options?.includes(ChainOptions.ETHEREUM_BASED));
```
Comment (johnthecat) [inline src/renderer/shared/lib/utils/chains.ts]:
```suggestion
  return chain.options?.includes(ChainOptions.ETHEREUM_BASED) ?? false;
```

File: src/renderer/shared/ui-entities/AccountExplorer/AccountExplorers.tsx [hunk 10]
```diff
@@ -1,14 +1,14 @@
...
+import { type AccountId, type Address, type Chain } from '@/shared/core';
 import { useI18n } from '@/shared/i18n';
 import { copyToClipboard, getAccountExplorer, toAddress } from '@/shared/lib/utils';
 import { ExplorerLink, FootnoteText, HelpText, IconButton, Separator } from '@/shared/ui';
 import { Box, Popover } from '@/shared/ui-kit';
 import { Hash } from '../Hash/Hash';
 
 type Props = PropsWithChildren<{
-  accountId: AccountId;
+  accountId: Address | AccountId;
```
Comment (johnthecat) [inline src/renderer/shared/ui-entities/AccountExplorer/AccountExplorers.tsx]: Why accountId can be an address?

File: src/renderer/shared/ui-kit/Combobox/Combobox.tsx [hunk 11]
```diff
@@ -41,14 +42,24 @@ type InputProps = Pick<
 >;
 
 type ControlledPopoverProps = {
-  value: string;
+  selectedValue: string;
```
Comment (johnthecat) [inline src/renderer/shared/ui-kit/Combobox/Combobox.tsx]: Why you need to differentiate selected value from value from input?

File: src/renderer/widgets/CreateWallet/model/form-model.ts [hunk 12]
```diff
@@ -132,6 +127,44 @@ const $availableAccounts = combine(
   },
 );
 
+const $invalidAddresses = combine(
+  {
+    chain: $chain,
+    signatories: signatoryModel.$signatories,
+  },
+  ({ chain, signatories }) => {
+    if (!chain) return new Set();
```
Comment (johnthecat) [inline src/renderer/widgets/CreateWallet/model/form-model.ts]: Don't use `Set`s and `Map`s in effector, you can dedupe values using our helper function

**Review by johnthecat — CHANGES_REQUESTED** [review]

File: src/renderer/pages/Onboarding/WatchOnly/WatchOnly.tsx (hunk 5 above)
Comment (tuul-wq) [reply src/renderer/pages/Onboarding/WatchOnly/WatchOnly.tsx:143]: `validateAddress` has 2 arguments, we can't use `validate: validateAddress` anymore
image

File: src/renderer/shared/ui-entities/AccountExplorer/AccountExplorers.tsx (hunk 10 above)
Comment (tuul-wq) [reply src/renderer/shared/ui-entities/AccountExplorer/AccountExplorers.tsx]: Actually we don't care what to pass `address` or `accountId`, few lines below we convert whatever we passed to `formattedAddress` using `toAddress` which works well with both data types. So the ability to pass `Address | AccountId` gives us more freedom
```javascript
const { explorers, addressPrefix } = chain;
const address = toAddress(accountId, { prefix: addressPrefix });
```

File: src/renderer/shared/ui-kit/Combobox/Combobox.tsx (hunk 11 above)
Comment (tuul-wq) [reply src/renderer/shared/ui-kit/Combobox/Combobox.tsx]: If we want to store compound selected value it will also be visible in `Combobox Input`
To avoid this we separate input's value and selected one
```javascript
inputValue={signatoryAddress}
selectedValue={`${signatoryAddress}_${selectedWalletId}`}
```

File: src/renderer/widgets/CreateWallet/model/form-model.ts [hunk 13]
```diff
@@ -132,6 +127,44 @@ const $availableAccounts = combine(
...
+    hasEmptySignatoryName: signatoryModel.$hasEmptySignatoryName,
+    hasDuplicateSignatories: signatoryModel.$hasDuplicateSignatories,
+    multisigAlreadyExists: $multisigAlreadyExists,
+    invalidAddresses: $invalidAddresses,
+    hiddenMultisig: $hiddenMultisig,
+    threshold: $createMultisigForm.fields.threshold.$value,
+  },
+  ({ invalidAddresses, threshold, ...params }) => {
+    if (invalidAddresses.size > 0) return false;
+    if (threshold < MIN_THRESHOLD) return false;
```
Comment (Asmadek) [inline src/renderer/widgets/CreateWallet/model/form-model.ts]: What is the reason to divide it? Maybe better create variables and use `||` as we do mostly?

**Review by Asmadek — APPROVED** [review]

File: src/renderer/shared/ui-entities/AccountExplorer/AccountExplorers.tsx (hunk 10 above)
Comment (johnthecat) [reply src/renderer/shared/ui-entities/AccountExplorer/AccountExplorers.tsx]: It's important for API shape and readability, revert this change please. Otherwise rename component to `AddressExplorers` and change it semantic meaning

File: src/renderer/shared/ui-kit/Combobox/Combobox.tsx (hunk 11 above)
Comment (tuul-wq) [reply src/renderer/shared/ui-kit/Combobox/Combobox.tsx]: Waiting for Sergey's UI decision

**Comment by pgolovkin** [comment]
@tuul-wq it has to be merged into `flexible multisig` branch as was stated in the task.

**Review by johnthecat — APPROVED** [review]
