### PR TITLE
fix: fork protection

### LINKED ISSUE #5106: Multisigs. Duplicates in operations
## Description

There is a possibility to create duplicates in multisig operations

Image

Test database:

[spektr-database (8).json](https://github.com/user-attachments/files/23601991/spektr-database.8.json)

## Steps to Reproduce

1. Create operation
2. Go to Operations page
3. Wait a bit

## Expected Behavior

There is no possibilities to have duplicates in operations

## Actual Behavior

There are duplications

## Additional info
That happens here:
https://github.com/novasamatech/nova-spektr/blob/5f8b6a3f7a13611a05a59e122a06aee4bdc8ffa0/src/renderer/domains/network/multisig-operation/resource.ts#L322-L323

due to the fact, that this data should be taken from the storage

Image

tested data - 

[spektr-database (8).json](https://github.com/user-attachments/files/23603009/spektr-database.8.json)

call hash:
0x4a394c0bf86ace58cbc2ba4bcfe6fe1ad1c2277f0ea9914205486f77640a5986

The bug is in subscribeEventsResource, the code incorrectly uses data.timepoint.height and data.timepoint.index to generate the operation ID. However, this timepoint refers to when the EVENT happened, NOT when the operation was originally created.

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Sometimes forks can happen, we want to rely on chain data, which is always true, so we override pending operations for given users/chains;

## Related Issues
Closes #5106

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/domains/network/multisig-operation/service.ts [hunk 1]
```diff
@@ -129,10 +129,23 @@ const mergeEvents = (oldEvents: MultisigEvent[], events: MultisigEvent[]) =>
...
+  operations: MultisigOperation[],
+): MultisigOperation[] => {
+  const newPendingOperations = operations.filter(operation => operation.status === 'pending');
+
+  const oldFilteredForPending = oldOperations.filter(
+    operation =>
+      operation.status !== 'pending' ||
+      !newPendingOperations.some(
+        newOperation => newOperation.chainId === operation.chainId && newOperation.accountId === operation.accountId,
+      ),
```
Comment (valentunn) [inline src/renderer/domains/network/multisig-operation/service.ts]: Why do we need this condition? Why not to simply merge all old-not-pending with all new pending?

File: src/renderer/domains/network/multisig-operation/service.ts [hunk 2]
```diff
@@ -129,10 +129,23 @@ const mergeEvents = (oldEvents: MultisigEvent[], events: MultisigEvent[]) =>
     sort: (a, b) => a.blockCreated - b.blockCreated,
   });
 
-const mergeMultisigOperations = (a: MultisigOperation[], b: MultisigOperation[]): MultisigOperation[] => {
+const mergeMultisigOperations = (
```
Comment (valentunn) [inline src/renderer/domains/network/multisig-operation/service.ts:145]: Overall its totally unclear how this function is supported to work: it does filtering two times, merging and sorting.
I think we should add tests or at least the comment that explains how this function is intended to work

File: src/renderer/domains/network/multisig-operation/store.ts [hunk 3]
```diff
@@ -40,6 +40,14 @@ const removeTransactionsFx = createEffect((operations: MultisigOperation[]) => {
 });
 
 const syncOperationsFx = createQueuedEffect(async (operations: MultisigOperation[]) => {
+  const dbOperations = await storageService.multisigOperations.readAll();
```
Comment (valentunn) [inline src/renderer/domains/network/multisig-operation/store.ts:48]: Are `operations` here a the result of `mergeMultisigOperations` from the other file?
The naming here is too generic, `operations` does not carry any insight about what is the content of the list

File: src/renderer/domains/network/multisig-operation/service.ts (hunk 1 above)
Comment (cuteWarmFrog) [reply src/renderer/domains/network/multisig-operation/service.ts]: In case of fork we can be in a case where there is an operation in our db/in memory which is no longer in the chain or in the indexer (was executed/canceled)

File: src/renderer/domains/network/multisig-operation/service.ts (hunk 2 above)
Comment (cuteWarmFrog) [reply src/renderer/domains/network/multisig-operation/service.ts:145]: Added a comment

File: src/renderer/domains/network/multisig-operation/store.ts (hunk 3 above)
Comment (cuteWarmFrog) [reply src/renderer/domains/network/multisig-operation/store.ts:48]: Added a comment as well + renamed var

File: src/renderer/domains/network/multisig-operation/service.ts [hunk 4]
```diff
@@ -129,10 +129,28 @@ const mergeEvents = (oldEvents: MultisigEvent[], events: MultisigEvent[]) =>
...
+  operations: MultisigOperation[],
+): MultisigOperation[] => {
+  /**
+   * Because we work with Events AT BEST, it may happen that our db has extra
+   * operations that are not on the chain anymore nor were executed. We want to
+   * filter them out.
+   *
+   * For example, if we have a fork and operation was executed in the different
+   * block than we first recevied event of.
+   */
```
Comment (valentunn) [inline src/renderer/domains/network/multisig-operation/service.ts]: This is not what I meant by a meaninfull comment.
Okay, just look at `mergeMultisigOperations`: how quickly can you infer what is the expected output of this function and which assumptions does it work with? This comment is useless as it gives no undestanding of why `mergeMultisigOperations` is implemented the way it is implemented. Please add a comment so an external reader (me) can fully understand all the context needed to evaluate correctness of the function

This will greatly help to maintin this code in the feature

File: src/renderer/domains/network/multisig-operation/store.ts (hunk 3 above)
Comment (valentunn) [reply src/renderer/domains/network/multisig-operation/store.ts:48]: `syncOperationsFx` is still too generic and confusing. `sync` can be anything. If we are syncing in-memory store to db, then the naming could be 

```ts
const syncInMemoryOperationsToDbFx = createQueuedEffect(async (inMemoryOperations: MultisigOperation[]) => {
```

File: src/renderer/domains/network/multisig-operation/store.ts [hunk 5]
```diff
@@ -39,8 +39,17 @@ const removeTransactionsFx = createEffect((operations: MultisigOperation[]) => {
...
+ * We want to sync operations between database and in-memory store. Its
+ * important to do so because operations can be deleted from the database
+ * without calling removeTransactionsFx (f.e. in case of fork).
+ */
+const syncOperationsFx = createQueuedEffect(async (allOperations: MultisigOperation[]) => {
+  const dbOperations = await storageService.multisigOperations.readAll();
+  const dbOperationIds = dbOperations.map(op => op.id);
+
+  await storageService.multisigOperations.deleteAll(dbOperationIds);
+  await storageService.multisigOperations.insertAll(allOperations.map(serializeOperation));
```
Comment (valentunn) [inline src/renderer/domains/network/multisig-operation/store.ts:52]: Do we subscribe to `multisigOperations` from our local db? Those two changes are not atomic and if we are subscribing, it might lead to flushing "empty state" or something similar

File: src/renderer/domains/network/multisig-operation/service.ts (hunk 1 above)
Comment (valentunn) [reply src/renderer/domains/network/multisig-operation/service.ts]: After the last commit it makes even less sense than before:

```
 const oldFilteredForPending = oldOperations.filter(
    oldOperation =>
      !operations.some(
        operation => operation.chainId === oldOperation.chainId && operation.accountId === oldOperation.accountId,
      ),
  );

```

Why is it needed? Why `oldFilteredForPending` is derived without even checking for pending?

File: src/renderer/domains/network/multisig-operation/service.ts [hunk 6]
```diff
@@ -129,10 +129,28 @@ const mergeEvents = (oldEvents: MultisigEvent[], events: MultisigEvent[]) =>
...
+  const oldFilteredForPending = oldOperations.filter(
```
Comment (johnthecat) [inline src/renderer/domains/network/multisig-operation/service.ts]: Looks like you're removing old operations for chains and accounts that are existed in new operations. let's put it that way in code (like what is `oldFilteredForPending`?) and optimize it. Now it's terribly unoptimized

File: src/renderer/domains/network/multisig-operation/resource.ts [hunk 7]
```diff
@@ -228,6 +228,8 @@ const fetchAllOnchainOperations = async (
   const requests = Object.values(apis).map(api => fetchOnchainOperations(api, accountId, chains));
   const operations = await Promise.allSettled(requests);
 
+  console.log('onchain operations', operations);
```
Comment (johnthecat) [inline src/renderer/domains/network/multisig-operation/resource.ts]: remove

**Review by johnthecat — DISMISSED** [review]

**Review by johnthecat — APPROVED** [review]
