### PR TITLE
Fix: Balance loading

### LINKED ISSUE #1573: Wallet creation. Infinity shimmering on Assets page.
## Description
After Multisig wallet creation - balances in infinity loading state, it fix if reload the app.
The same for all other wallets, if it does not have rows in the database

## Steps to Reproduce

1. Create Multisig
2. Go to Assets page

## Expected Behavior
Balances will be loaded for new account

## Actual Behavior
Infinity loading state

https://github.com/novasamatech/nova-spektr/assets/40560660/63c76962-a6b5-4e8e-8d1c-a6ca525e9d83

### PR DESCRIPTION
**Pull request by tuul-wq**
- Unload local balances to main balances buffer on timer
- Fixed `toBeInTheDocument()` type error 

closes #1573

### CODE REVIEW

**Review by Asmadek — APPROVED** [review]

File: src/renderer/features/balances/subscription/model/balance-sub-model.ts [hunk 1]
```diff
@@ -1,24 +1,25 @@
...
 import { isRejected } from '@shared/lib/utils';
 
-const balancesSubStarted = createEvent();
 const walletToUnsubSet = createEvent<Wallet>();
 const walletToSubSet = createEvent<Wallet>();
+const balancesUpdated = createEvent<Balance[]>();
 
 const $subscriptions = createStore<Subscriptions>({});
 const $subAccounts = createStore<SubAccounts>({});
+const $subBalances = createStore<Balance[]>([]);
```
Comment (Asmadek) [inline src/renderer/features/balances/subscription/model/balance-sub-model.ts:22]: But I am not sure about name for this variable. Maybe add comment to better understand what is it about?
