### PR TITLE
Fix: Proposer identity in governance

### LINKED ISSUE #2027: Governance. Referenda details. There is no proposer for referenda
## Description
There is no proposer in referenda details

Expected result:
image

Actual result:
Screenshot 2024-08-06 at 13 35 01

### LINKED ISSUE #2029: Governance. Votes. There is no Identity for votes history
## Description

When user opens votes - there is no identities

## Steps to Reproduce

1. Go to Governance page
2. Open Referenda
3. Click View Vote History

## Expected Behavior
All voters has his Identity

## Actual Behavior
For all voters only address is shown:
Screenshot 2024-08-06 at 13 38 05

## Environment
https://github.com/novasamatech/nova-spektr/commit/74fb677ee2dd26a02c67eeb6860265cc9bea9add

### PR DESCRIPTION
**Pull request by Tbaut**
closes #2027 
closes #2029 

It's back, now that we use the People chain.

image
image

### CODE REVIEW

**Review by pgolovkin — APPROVED** [review]

**Review by johnthecat — APPROVED** [review]

File: src/renderer/features/governance/components/ReferendumDetails/ProposerName.tsx [hunk 1]
```diff
@@ -1,18 +1,17 @@
...
 import { AccountAddress } from '@entities/wallet';
 import { detailsAggregate } from '../../aggregates/details';
 
 type Props = {
-  chainId: ChainId;
   referendum: Referendum;
 };
 
-export const ProposerName = ({ chainId, referendum }: Props) => {
+export const ProposerName = ({ referendum }: Props) => {
```
Comment (Asmadek) [inline src/renderer/features/governance/components/ReferendumDetails/ProposerName.tsx:14]: Not related to this PR, but I think we should discuss add explorers to the proposer. Now we have address, but we can't go fast to explorer as we have in most of places

**Review by Asmadek — APPROVED** [review]
