### PR TITLE
Fix/transfer address validation

### LINKED ISSUE #3087: Transfers. Can use not EVM address in EVM based networks.
## Description

User can put based substrate address in recipient field

Image

## Expected Behavior

Should be allowed only EVM

## Actual Behavior

Allowed substrate address, which may lead to send assets to wrong address

## Environment
https://github.com/novasamatech/nova-spektr/commit/84c0644447ad2a64f62582b3b27401b1c4363df0

### LINKED ISSUE #3090: Multisig. Can't set call data for xcm operation
## Description

User can't set call data to XCM operation, error:

```
Start parsing call data for section polkadotXcm and method limitedTeleportAssets
multisigTxService.ts:224 Error during update callData:  TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.parseXcmPalletExtrinsic (xcmService.ts:245:34)
    at polkadotxcm_limited_teleport_assets (callDataDecoder.ts:228:37)
    at getDecodedTransaction (callDataDecoder.ts:170:12)
    at parseSingle (callDataDecoder.ts:127:12)
    at decodeCallData (callDataDecoder.ts:66:12)
    at updateCallData (multisigTxService.ts:220:27)
    at setupCallData (OperationFullInfo.tsx:66:5)
    at submitHandler (CallDataModal.tsx:46:5)
    at react-hook-form.js?v=f13ddb07:1671:15
```

## Test data

[spektr-database.json](https://github.com/user-attachments/files/18621087/spektr-database.json)

## Steps to Reproduce

1. Import test data
2. Go to Operations
3. Try to set call data:
0x1f0904010100a10f04000101007a28037947ecebe0dd86dc0e910911cb33185fd0714b37b75943f67dcf9b6e7c04040000001300307ebabe0472020000000000

## Expected Behavior
Success parsed

## Actual Behavior
Failed

## Environment
https://github.com/novasamatech/nova-spektr/commit/1d871750621c741cf1e0a43f2889c37d1b2c83b8

### PR DESCRIPTION
**Pull request by sokolova-an**
Closes #3087  #3090

### CODE REVIEW

**Review by johnthecat — APPROVED** [review]

File: src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts [hunk 1]
```diff
@@ -56,12 +56,17 @@ export const TransferRules = {
...
       name: 'incorrectRecipient',
       errorText: 'transfer.incorrectRecipientError',
+      source,
       // Second argument for validator is form data, but we need chain
-      validator: (destination: string) => validateAddress(destination),
-    },
+      validator: (destination: string, _: any, chain: Chain) => {
+        if (!chain) return false;
+
+        return chain && validateAddress(destination, chain);
```
Comment (tuul-wq) [inline src/renderer/features/operations/OperationsValidation/lib/transfer-rules.ts]:
```suggestion
        return validateAddress(destination, chain);
```

**Review by tuul-wq — APPROVED** [review]
