### PR TITLE
Fix: Missing validation

### LINKED ISSUE #3095: Transfer confirm. Sign button is not available if validation fall with error.
## Description

Silent validation error on confirm:

https://github.com/novasamatech/nova-spektr/blob/v1.14.1/src/renderer/features/operations/OperationsConfirm/Transfer/model/confirm-model.ts#L69

## Expected Behavior

Error is shown

## Actual Behavior

Sign button is not available

## Environment
https://github.com/novasamatech/nova-spektr/commit/718ca6be2e2fd2455460acb1c72f51b04fd947b7

### PR DESCRIPTION
**Pull request by tuul-wq**
- Fixed missing fee validation

closes #3095

### CODE REVIEW

File: src/renderer/features/operations/OperationsValidation/lib/validation/balance.ts [hunk 1]
```diff
@@ -31,21 +31,17 @@ function insufficientBalanceForFee(
...
     isMultisig,
-    isXcm,
   }: TransferFeeStore,
   config: Config = { withFormatAmount: true },
 ) {
-  if (isXcm && !isNative) {
-    if (isLteThanBalance(fee, balance)) {
-      return true;
-    }
+  if (!isNative) {
```
Comment (tuul-wq) [inline src/renderer/features/operations/OperationsValidation/lib/validation/balance.ts:37]: Working with Polkadot asset hub involves Myth balance and Dot fee. So not only `xcm` cases must be validated with native balance.

File: src/renderer/widgets/Transfer/model/form-model.ts [hunk 2]
```diff
@@ -163,6 +163,18 @@ const $transferForm = createForm<FormParams>({
             balance: $accountBalance,
           }),
         ),
+        TransferRules.amount.insufficientBalanceForFee(
```
Comment (tuul-wq) [inline src/renderer/widgets/Transfer/model/form-model.ts:166]: Was completely missing 🥺

**Review by johnthecat — APPROVED** [review]

**Review by Asmadek — APPROVED** [review]
