### PR TITLE
fix: correct check for delegates in vote form

### LINKED ISSUE #2273: Governance. "The account is already delegating" verification for multishard wallet
## Description
Shows verification for all shards, if only one is delegating.

Screenshot 2024-09-03 at 13 42 32
Screenshot 2024-09-03 at 13 42 35

Main - hasn't delegations
Hot - has delegations

## Steps to Reproduce

1. Add Polkadot Vault with multiple shards (Main \ Hot)
2. Delegate from Hot account
3. Try to Vote as Main

## Expected Behavior
Shows verification, based on selected account

## Actual Behavior
Shows verification error for all accounts

## Environment
https://github.com/novasamatech/nova-spektr/commit/f47aca28a23082135af1ac02b24f02271c4e2b45

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #2273

### CODE REVIEW

**Review by Asmadek — APPROVED** [review]

File: src/renderer/widgets/VoteModal/aggregates/voteModal.ts [hunk 1]
```diff
@@ -27,9 +27,22 @@ const $redirectAfterSubmitPath = createStore<PathType | null>(null).reset(flow.o
...
-    return referendum ? tracks.includes(referendum.track) : false;
+  voteFormAggregate.transactionForm.form.fields.account.$value,
+  delegationAggregate.$activeTracks,
+  (referendum, account, tracks) => {
+    if (nullable(account) || nullable(referendum)) {
+      return false;
+    }
+
+    for (const dalagators of Object.values(tracks)) {
+      for (const [address, tracks] of Object.entries(dalagators)) {
```
Comment (sokolova-an) [inline src/renderer/widgets/VoteModal/aggregates/voteModal.ts]: dalagators?

Comment (johnthecat) [reply src/renderer/widgets/VoteModal/aggregates/voteModal.ts]:
```suggestion
    for (const dalegators of Object.values(tracks)) {
      for (const [address, tracks] of Object.entries(dalegators)) {
```
