### PR TITLE
fix: add signatory select on remove multisig vote

### LINKED ISSUE #2284: Governance. Vote. Remove votes for multisig
## Description
Wrong transaction for multisig remove votes

https://github.com/user-attachments/assets/c22734ad-f67d-429f-881f-58cff45c16ce

## Steps to Reproduce

1. Vote as a multisig
2. Go to Governance page
3. Remove votes via multisig wallet

## Expected Behavior
Multisig modal windows and transaction from signatory

## Actual Behavior
Regular modal windows and transaction from multisig itself

## Environment
https://github.com/novasamatech/nova-spektr/commit/5394425bbb2cb4cdcd9f2382363ad6e9393e9f1e

[accounts.json](https://github.com/user-attachments/files/16863062/accounts.json)
[wallets.json](https://github.com/user-attachments/files/16863063/wallets.json)

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #2284

### CODE REVIEW

File: src/renderer/widgets/RemoveVoteModal/ui/RemoveVoteModal.tsx [hunk 1]
```diff
@@ -1,35 +1,59 @@
...
+
+  const [isModalOpen, closeModal] = useModalClose(!isStep(step, Step.NONE), onClose);
+  const [isBasketModalOpen, closeBasketModal] = useModalClose(isStep(step, Step.BASKET), onClose);
+  const [isSelectSignatoryOpen, setIsSelectSignatoryOpen] = useState(shouldPickSignatory);
+  const [isSelectSignatoryClosed, setIsSelectSignatoryClosed] = useState(false);
+
+  const handleSelectSignatoryClose = () => {
+    setIsSelectSignatoryOpen(false);
+    setIsSelectSignatoryClosed(true);
+  };
```
Comment (sokolova-an) [inline src/renderer/widgets/RemoveVoteModal/ui/RemoveVoteModal.tsx:46]: maybe use `useToggle(shouldPickSignatory)` instead of it?

File: src/renderer/widgets/RemoveVoteModal/ui/RemoveVoteModal.tsx [hunk 2]
```diff
@@ -1,35 +1,59 @@
...
 import { BaseModal, Button } from '@shared/ui';
-import { OperationTitle } from '@entities/chain';
-import { OperationResult } from '@entities/transaction';
-import { OperationSign, OperationSubmit } from '@features/operations';
-import { RemoveVoteConfirmation, basketUtils } from '@features/operations/OperationsConfirm';
+import { OperationTitle } from '@/entities/chain';
+import { OperationResult } from '@/entities/transaction';
+import { OperationSign, OperationSubmit } from '@/features/operations';
+import { RemoveVoteConfirmation, basketUtils } from '@/features/operations/OperationsConfirm';
+import { SignatorySelectModal } from '@/pages/Operations/components/modals/SignatorySelectModal';
```
Comment (sokolova-an) [inline src/renderer/widgets/RemoveVoteModal/ui/RemoveVoteModal.tsx:14]: if we use `SignatorySelectModal` here from `pages/Operations` maybe it's better to move this component into feature?

File: src/renderer/widgets/RemoveVoteModal/ui/RemoveVoteModal.tsx (hunk 1 above)
Comment (johnthecat) [reply src/renderer/widgets/RemoveVoteModal/ui/RemoveVoteModal.tsx:46]: In this case we can't be sure, that modal closed state is caused by user interaction. `isSelectSignatoryClosed` tells effect to trigger modal close only if user closed select modal and didn't selected any signatory

File: src/renderer/widgets/RemoveVoteModal/ui/RemoveVoteModal.tsx (hunk 2 above)
Comment (johnthecat) [reply src/renderer/widgets/RemoveVoteModal/ui/RemoveVoteModal.tsx:14]: I think it will be great refactoring later :)

**Review by sokolova-an — APPROVED** [review]
