### PR TITLE
fix: focus on whole card

### LINKED ISSUE #2793: Portfolio. Token-centric. Focus state should be shown across whole component
## Description

Focus state should be shown across whole component.

## Expected Behavior

https://www.figma.com/design/IzDQl7uzHQVhdnf4tpzXVx/Spektr-Design-System?node-id=6115-21125&t=4AqpzQUb1lt5UZ4a-4

## Actual Behavior

Screenshot 2024-12-06 at 10 24 24

## Environment
https://github.com/novasamatech/nova-spektr/commit/1b7efc5e282ffc28d8a692e709eafa904f1bca07

### PR DESCRIPTION
**Pull request by aaa123eee**
**before**

image

image

**after**

image

image

closes #2793

### CODE REVIEW

File: src/renderer/shared/ui-kit/CardStack/CardStack.tsx [hunk 1]
```diff
@@ -45,13 +45,10 @@ const Trigger = ({ sticky, children }: TriggerProps) => {
   return (
     <RadixAccordion.Header asChild>
       <div className={cnTw('relative z-10 block w-full', sticky && open && 'sticky top-2 z-10')}>
-        {sticky && open && (
-          <div className="absolute -top-2 left-0 right-0 -z-10 h-4 w-full bg-top-nav-bar-background" />
-        )}
```
Comment (aaa123eee) [inline src/renderer/shared/ui-kit/CardStack/CardStack.tsx]: this change is questionable 

it overlaps outline 
image

File: src/renderer/shared/ui-kit/CardStack/CardStack.tsx [hunk 2]
```diff
@@ -45,13 +45,10 @@ const Trigger = ({ sticky, children }: TriggerProps) => {
...
         <RadixAccordion.Trigger
           className={cnTw(
-            'group flex w-full items-center gap-x-2 bg-row-background py-1 pl-3 pr-2',
-            'shadow-stack hover:shadow-stack-hover focus:shadow-stack-hover data-[state=open]:shadow-none',
+            'card-stack-trigger group flex w-full items-center gap-x-2 bg-row-background py-1 pl-3 pr-2',
+            'shadow-stack !outline-none hover:shadow-stack-hover focus:shadow-stack-hover data-[state=open]:shadow-none',
```
Comment (aaa123eee) [inline src/renderer/shared/ui-kit/CardStack/CardStack.tsx:54]: I don't like an exclamation mark but otherwise our focus styles for button applied on top of `outline-none`

(screen with `outline-none` instead of `!outline-none`)
image

**Review by johnthecat — APPROVED** [review]

File: src/renderer/shared/ui-kit/CardStack/CardStack.tsx (hunk 1 above)
Comment (johnthecat) [reply src/renderer/shared/ui-kit/CardStack/CardStack.tsx]: looks like we need another hack for top margin while header is sticky, research needed

**Review by tuul-wq — APPROVED** [review]

File: src/renderer/shared/ui-kit/CardStack/CardStack.tsx (hunk 1 above)
Comment (aaa123eee) [reply src/renderer/shared/ui-kit/CardStack/CardStack.tsx]: decided to have both

if focus-within then hide the hack with the stripe to not overlap with outline

if not then keep the old behaviour
