### PR TITLE
fix: votes impact and small UI fixes

### LINKED ISSUE #3440: Fellowship. Vote via likes - shouldn't shows impact if threshold one side
## Description

When user try to vote on one sided referenda - there is shouldn't be changes on threshold line

Image
Image

## Environment
https://github.com/novasamatech/nova-spektr/commit/1fc39d8371e7af52bf37caed02ed4967063301eb

### PR DESCRIPTION
**Pull request by sokolova-an**
## Description
Rework progress bar for voting
Small UI fixes along the way
## Related Issues
#3440
## Screenshots/Recordings
image
image

### CODE REVIEW

File: src/renderer/features/fellowship-tasks/components/tasks/RequestRetention.tsx [hunk 1]
```diff
@@ -1,31 +1,46 @@
...
   return (
     <Box direction="row" padding={4} gap={5} verticalAlign="flex-end">
       <Box gap={3} grow={1}>
         <SmallTitleText>{t('fellowship.tasks.task.retention.title')}</SmallTitleText>
         <FootnoteText>
           {t('fellowship.tasks.task.retention.description', { rank: toRomanNumeral(track?.id ?? 0) })}
         </FootnoteText>
+        <FootnoteText className="text-text-secondary">
+          {t('fellowship.tasks.task.retention.until', {
+            date: formatDate(periodEnd, 'dd.MM.yyyy'),
```
Comment (aaa123eee) [inline src/renderer/features/fellowship-tasks/components/tasks/RequestRetention.tsx:39]: can it improperly render current date when periodEnd has initial value `0`? maybe null as a pending state can help us to avoid

**Review by aaa123eee — APPROVED** [review]

**Review by johnthecat — APPROVED** [review]

File: src/renderer/features/fellowship-tasks/components/tasks/RequestRetention.tsx (hunk 1 above)
Comment (sokolova-an) [reply src/renderer/features/fellowship-tasks/components/tasks/RequestRetention.tsx:39]: it shouldn't since we take time from API but if there's no response - we can confirm with design what should we show in this case
