### PR TITLE
fix: signatory balance instead of initiator

### LINKED ISSUE #4024: CAS. Staking. Withdraw unstaked - wrong fee walidation
## Description

When user try to withdraw unstaked it triggers network fee validation. Looks like it connected to #3819 

Image

## Steps to Reproduce

1. Import database
2. Go to Staking
3. Try to withdraw unstaked

## Expected Behavior

Can withdraw

## Actual Behavior

Fee validation triggers

## Environment

https://github.com/novasamatech/nova-spektr/pull/3815/commits/16e305759a198292a24fed59f80a729ad31f257e

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
As a signatory is the one who signs, we should check its balance in validation and not inititator's

## Related Issues
Closes #4024

### CODE REVIEW

File: src/renderer/widgets/Staking/Withdraw/default/model/form-model.ts [hunk 1]
```diff
@@ -128,7 +127,9 @@ const form: Form<FormParams> = createForm<FormParams>({
             }
 
             if (isMultisig) {
-              const isEnough = new BN(fee).lte(new BN(initiatorBalance.balance));
+              const isEnough = new BN(signatoryBalance).gt(new BN(fee));
+
+              console.log({ isEnough, fee: fee.toString(), signatoryBalance: signatoryBalance.toString() });
```
Comment (johnthecat) [inline src/renderer/widgets/Staking/Withdraw/default/model/form-model.ts]: remove plz

**Review by johnthecat — APPROVED** [review]
