### PR TITLE
fix: add delegation to multiple delegates

### LINKED ISSUE #2165: Governance. Can't delegate to another delegate
### The scenario
1. Delegate to the 1st delegate
2. Select 2nd delegate
3. Try to delegate

### Expected result
1. Open 2nd delegate
2. Select tracks (that are not already delegated to the 1st delegate and not voted)
3. Sign transaction
4. Transaction executed

### Actual result
1. Open 2nd delegate
2. There is no button for delegate
3. The information about delegation to the 1st delegate is shown 

https://github.com/user-attachments/assets/65f5668e-9425-4690-a41f-cc3dff7b30e4

### PR DESCRIPTION
**Pull request by Asmadek**
* check active delegations for selected delegate

### CODE REVIEW

File: src/renderer/widgets/DelegateModal/model/select-tracks-model.ts [hunk 1]
```diff
@@ -46,13 +59,23 @@ const $availableAccounts = combine(
...
     return wallet.accounts
       .filter((a) => accountUtils.isNonBaseVaultAccount(a, wallet) && accountUtils.isChainIdMatch(a, chain.chainId))
-      .filter((account) => !delegations[toAddress(account.accountId, { prefix: chain.addressPrefix })]);
+      .filter((account) => {
+        console.log(
+          'xcm',
+          delegations,
+          delegate.accountId,
+          toAddress(account.accountId, { prefix: chain.addressPrefix }),
+        );
```
Comment (sokolova-an) [inline src/renderer/widgets/DelegateModal/model/select-tracks-model.ts]: don't forget to delete it

**Review by sokolova-an — APPROVED** [review]
