### PR TITLE
fix: remove some layout shifts

### LINKED ISSUE #2289: Info icon has wrong indent
## Actual Behavior
Screenshot 2024-09-05 at 16 09 22

https://github.com/user-attachments/assets/3c92a92c-7222-463f-b178-ebb20514c222

## Environment
https://github.com/novasamatech/nova-spektr/commit/023df867e4ea11596d331f02f572caada4bbeaf6

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #2289

### CODE REVIEW

File: src/renderer/shared/ui-entities/Hash/Hash.tsx [hunk 1]
```diff
@@ -4,14 +4,30 @@ import { Truncate } from './Truncate';
...
+  if (variant === 'full') {
+    return <span className="break-all">{value}</span>;
+  }
+
+  if (variant === 'truncate') {
+    return <Truncate text={value} />;
+  }
+
+  if (variant === 'short') {
+    return value.slice(0, 8) + '...' + value.slice(-8);
```
Comment (Asmadek) [inline src/renderer/shared/ui-entities/Hash/Hash.tsx]: Maybe use `truncate` from 'shared/lib/utils'?

**Review by Asmadek — APPROVED** [review]

**Review by tuul-wq — APPROVED** [review]
