### PR TITLE
fix: resolve wallet and account names

### LINKED ISSUE #5280: Address book. Name resolution. Some place in the app where name takes with old approach.
## Description

When user have a contact in address book, we would like to show that name in whole application.

## 1. Staking page

https://github.com/novasamatech/nova-spektr/blob/6bab19e5138fd282e63ba22c49eb2f822ef2ab37/src/renderer/entities/staking/ui/AccountsModal/AccountsModal.tsx#L50

Image

## 2. Signatory selector

[spektr-database (15).json](https://github.com/user-attachments/files/23900894/spektr-database.15.json)

Image
Image
Image

### Governance signatory selector
Image

## 3. Fellowship - edit beneficiary

https://github.com/novasamatech/nova-spektr/blob/6bab19e5138fd282e63ba22c49eb2f822ef2ab37/src/renderer/features/fellowship-salary/components/SalaryEditBeneficiaryModal.tsx#L101-L105

Image

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
Address book. Name resolution. Some place in the app where name takes with old approach.

## Related Issues
Closes #5280

## Changes Made
fixed named on Staking, Governance, Edit beneficiary modal

## Screenshots/Recordings
Снимок экрана 2025-12-04 в 10 58 24
Снимок экрана 2025-12-04 в 10 58 04
Снимок экрана 2025-12-04 в 10 58 58
Снимок экрана 2025-12-04 в 10 59 21

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/domains/network/account/service.ts [hunk 1]
```diff
@@ -285,7 +286,13 @@ function resolveAccountName({
       return accountChain?.addressPrefix;
     })();
 
-  return toShortAddress(toAddress(accountId, { prefix }), 5);
+  const isShardAccount =
+    relatedAccount &&
+    isChainAccount(relatedAccount) &&
+    'accountType' in relatedAccount &&
+    (relatedAccount as Record<string, unknown>)['accountType'] === AccountType.SHARD;
```
Comment (aaa123eee) [inline src/renderer/domains/network/account/service.ts:293]: looks like duplicate of `isVaultShardAccount`

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/domains/network/account/service.ts (hunk 1 above)
Comment (Yanaty) [reply src/renderer/domains/network/account/service.ts:293]: Yes, it's a duplicate. I can't import accountUtils due to circular dependency
