### PR TITLE
fix: display selected signatory wallet

### LINKED ISSUE #2623: Multisig. Uses wrong proxy to sign the operation
## Description

When create multisig the app may use wrong proxy to sign the operation. In that case I've tried to create Polkadot multisig, but proxy was used from Westend:

Screenshot 2024-11-12 at 09 00 02

Test accounts:
[accounts.json](https://github.com/user-attachments/files/17711783/accounts.json)
[wallets.json](https://github.com/user-attachments/files/17711785/wallets.json)

## Steps to Reproduce

1. Go to multisig creation flow
2. Select Polkadot
  a. First signatory - 13mAjFVjFDpfa42k2dLdSnUyrSzK8vAySsoudnxX2EKVtfaq
  b. Second - 152dNj968WxoqgBcwicY4KD6EVCK7qYUkJCx4edVhgJBxujt
  c. Third - 15G6kcqAygpk4TJGWVhUt7rTz7jQV3Dhd5KNK3jD2AwRiuAZ
  d. threshold - 2
3. Try to sign

## Expected Behavior
Sign with NovaWallet

## Actual Behavior
App try to sign the operation via westend proxy account

## Environment
https://github.com/novasamatech/nova-spektr/commit/029e2fcf5a0b879cc7bb291d7d0c2a8554aa04a6

### PR DESCRIPTION
**Pull request by sokolova-an**
Use the selected signatory wallet to sign create multisig operations

### CODE REVIEW

**Review by johnthecat — APPROVED** [review]

**Review by tuul-wq — APPROVED** [review]

File: src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/Signatory.tsx [hunk 1]
```diff
@@ -19,6 +19,7 @@ interface Props {
   signatoryName: string;
   signatoryAddress: string;
   signatoryIndex: number;
+  selectedWallet: string;
```
Comment (Asmadek) [inline src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/Signatory.tsx:22]: Maybe call it selectedWalletId?

**Review by Asmadek — APPROVED** [review]
