### PR TITLE
fix: made this shit actually work and look nicer fuck yeah

### LINKED ISSUE #5322: Revoke authority. Problem with revoke proxy
## Description

There is a problem with revoke authority.

Account:

13xSkb8xsHd6twCT5or1Pf3o424JbThrCorvRwYmXdREvvFn

## Actual result:
Continue button is not available

Image

## Expected result

Shows validation error or continue button is available

Tried to reproduce, but faced with error that can't open a flow at all

https://github.com/user-attachments/assets/40de1e0c-d7a4-4c5c-a613-dc0e4e410fb4

[spektr-database (17).json](https://github.com/user-attachments/files/24075587/spektr-database.17.json)

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Refactored some shit piss and fixed proxieds

## Related Issues
Closes #5322

## Screenshots/Recordings
https://assethub-kusama.subscan.io/account/16fMa8vMJBquKoEY6HqwrVjUBtJY1sQQySzfRpo5fY9W9Znz
Can't upload video from train. BELEIVE ME SER ITS GOOD PR

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/domains/network/account/hooks.ts [hunk 1]
```diff
@@ -20,12 +20,10 @@ type UseAccountNameParams = {
 };
 
 export const useAccountsNames = (accounts: AnyAccount[], chain?: Chain | null) => {
-  if (nullable(accounts) || accounts.length === 0) {
-    return [];
-  }
+  const isEmpty = nullable(accounts) || accounts.length === 0;
```
Comment (johnthecat) [inline src/renderer/domains/network/account/hooks.ts]: accounts are always an array

File: src/renderer/domains/network/account/resource.ts [hunk 2]
```diff
@@ -49,7 +49,8 @@ export const createAccountNameCacheKey = ({ accountId, chain, title }: AccountNa
 export const createWalletNameCacheKey = ({ wallet }: WalletNameParams): string => {
```
Comment (johnthecat) [inline src/renderer/domains/network/account/resource.ts:49]: Why there is a wallet in accounts service in the first place?

File: src/renderer/domains/network/account/service.ts [hunk 3]
```diff
@@ -152,7 +153,7 @@ function getAccountIdentity(accountId: AccountId, identities: IdentityMap) {
   return null;
 }
 
-function isCustomAccountName(account?: AnyAccount | null): account is AnyAccount {
+function isCustomAccountName(account?: AnyAccount | null) {
```
Comment (johnthecat) [inline src/renderer/domains/network/account/service.ts]: remove null and optional modifier

File: src/renderer/domains/network/account/service.ts [hunk 4]
```diff
@@ -163,12 +164,12 @@ function isCustomAccountName(account?: AnyAccount | null): account is AnyAccount
...
 
-  if ('chainId' in account && account.chainId) {
-    return account.chainId as ChainId;
+  if (accountService.isChainAccount(account)) {
+    return account.chainId;
   }
 
-  if ('remarkChainId' in account && account.remarkChainId) {
-    return account.remarkChainId as ChainId;
+  if (accountUtils.isMultisigAccount(account)) {
```
Comment (johnthecat) [inline src/renderer/domains/network/account/service.ts]: circular dependecy, account service should not know about multisig accounts

File: src/renderer/domains/network/account/resource.ts (hunk 2 above)
Comment (cuteWarmFrog) [reply src/renderer/domains/network/account/resource.ts:49]: hehehehe

**Review by johnthecat — APPROVED** [review]
