### PR TITLE
fix: moved evidence summary to separated model

### LINKED ISSUE #3425: Fellowship. PRs data disappear if open referenda details
## Description

Example:

https://github.com/user-attachments/assets/49717afe-9ed4-40cb-b5ed-c0f9d3de866f

Looks like it happens because when open details we send additional request without params for PRs:

```bash
curl 'https://opengov-backend-dev.novasama-tech.org/api/v1/evidence-summaries/single' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,ru;q=0.8' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'origin: https://localhost:3000' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: https://localhost:3000/' \
  -H 'sec-ch-ua: "Chromium";v="134", "Not:A-Brand";v="24", "Google Chrome";v="134"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36' \
  --data-raw '{"chainId":"x46ee89aa2eedd13e988962630ec9fb7565964cf5023bb351f2b6b25c1b68b0b2","evidenceId":"bafybeie4mw2oe3fnq4un7achzowu6cfucruy2q2zukxf6m4f65qoybr6f4","languageIsoCode":"en"}'
```

## Environment
https://github.com/novasamatech/nova-spektr/commit/ba2e57fbcd4e84646a192b518646cab64aa0a2bc

### PR DESCRIPTION
**Pull request by johnthecat**
## Description
Closes #3425

### CODE REVIEW

File: src/renderer/features/fellowship-tasks/model/evidence.ts [hunk 1]
```diff
@@ -10,25 +14,73 @@ import { memberProfile } from './memberProfile';
 // evidences
 
 const requestEvidenceFx = attach({ effect: evidence.request });
+const requestEvidenceSummaryFx = attach({
```
Comment (aaa123eee) [inline src/renderer/features/fellowship-tasks/model/evidence.ts:17]: do we still need `requestEvidenceFx` then?

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/features/fellowship-tasks/model/evidence.ts (hunk 1 above)
Comment (johnthecat) [reply src/renderer/features/fellowship-tasks/model/evidence.ts:17]: Yes, it's reused in tasks model
