### PR TITLE
basic ui-kit implementation, fixed storybook

### LINKED ISSUE #2306: Fellowship. Create UI KIt
Create a UI Kit of common components. 
That should help us build Fellowship faster and easier by reusing components from Governance

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #2306

Added `@/shared/ui-kit` and `@/shared/ui-entities` packages for better components organization. All components from `@/shared/ui` will be moved to kit and entities folder depending on component meaning.

Fixes storybook, upgraded packages and all stories to latest version.

### CODE REVIEW

File: src/renderer/shared/ui-entities/VoteChart/VoteChart.tsx [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+
+type Props = {
+  value: number;
+  threshold?: number;
+  disabled?: boolean;
+  thresholdIndicatorBorder?: string;
+};
+
+export const VoteChart = ({ value, threshold, disabled, thresholdIndicatorBorder = 'icon-button' }: Props) => {
+  console.log(4 - 4 / value);
```
Comment (sokolova-an) [inline src/renderer/shared/ui-entities/VoteChart/VoteChart.tsx]: remove it

File: src/renderer/shared/ui-kit/Dropdown/Dropdown.tsx [hunk 2]
```diff
@@ -0,0 +1,178 @@
...
+        },
+      )}
+      onCheckedChange={onChange}
+      onSelect={(event) => {
+        if (preventClosing) {
+          event.preventDefault();
+        }
+        onSelect?.();
+      }}
+    >
```
Comment (sokolova-an) [inline src/renderer/shared/ui-kit/Dropdown/Dropdown.tsx]: maybe move it to `handleSelect` function?

**Review by sokolova-an — APPROVED** [review]
