### PR TITLE
Fix/multisig callhash

### LINKED ISSUE #5522: Multisig operations list becomes inconsistent across sessions after rejecting an operation; operations disappear until reload
## Description

When working with the same multisig across multiple app instances (different browsers / ports / environments), rejecting an operation from one session can cause other operations to temporarily disappear in other sessions. The missing operations reappear only after a full page reload.

## Steps to Reproduce

Open two app instances:
Window 1: localhost — signer1 added
Window 2: spektr-dev — signer2 added

1. In Window 1, create several multisig operations using signer1.
2. Verify that all operations appear in Window 2.
3. In Window 2, add signer1 as well.
4. In Window 2, reject the most recent multisig operation using signer1.
5. Observe the operations list in all windows.

## Expected Behavior

In both windows only one operation (the rejected one) is moved to history

## Actual Behavior

In both windows one operation (the rejected one) is moved to history.
In window1 one extra operation disappeared. It reappears only after a reload.

## Screenshots

https://github.com/user-attachments/assets/685a7b62-0aa9-47a7-b4cb-265f241e0163

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
callhash by chainId

## Related Issues
Closes #5522

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

**Review by johnthecat — APPROVED** [review]

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/domains/network/multisig-operation/resource.ts [hunk 1]
```diff
@@ -415,86 +420,71 @@ export const subscribeOnchainResource = createSubscriptionResource<{
...
+
+        for (let index = 0; index < results.length; index++) {
+          const optionalMultisig = results[index]!;
+          const callHash = paths[index]!;
 
-      for (let index = 0; index < results.length; index++) {
-        const optionalMultisig = results[index]!;
-        const callHash = paths[index]!;
+          if (optionalMultisig.isNone) {
+            console.log('huy inside subscription optionalMultisig check', queries, optionalMultisig, callHash, index);
```
Comment (savvyer) [inline src/renderer/domains/network/multisig-operation/resource.ts:444]: remove console.log pls
