### PR TITLE
fix: polkadot vault single account groups

### LINKED ISSUE #4838: Consensuses title in EVM based single Polkadot Vault
## Description

There is no glue, why censuses is used for EVM based single wallet:

Image

[spektr-database (28).json](https://github.com/user-attachments/files/22724118/spektr-database.28.json)

### LINKED ISSUE #4850: Polkadot Vault. Onboarding flow. Change keys representation
There is a pages with onboarding flow, where we are using an old style page with all networks:

Image

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Fix ethereum accounts and other non-consensus accounts grouping

## Related Issues
Closes https://github.com/novasamatech/nova-spektr/issues/4838
Closes https://github.com/novasamatech/nova-spektr/issues/4850

## Changes Made
- Fixed/refactoed ConsensusAccountsList component
- Imported ethereum icon into the project
- Refactored VaultAccountsList. Use Ethereum icon instead of hardcoded link

## Screenshots/Recordings
Wallet details:
Screenshot 2025-10-20 at 3 34 30 PM
Screenshot 2025-10-20 at 3 34 43 PM

Onboarding screen:
Screenshot 2025-10-21 at 1 15 16 PM
Screenshot 2025-10-21 at 1 14 45 PM
Screenshot 2025-10-21 at 1 14 55 PM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

**Review by aaa123eee — APPROVED** [review]

**Review by kalininilya — APPROVED** [review]

File: src/renderer/features/wallet-details/ui/components/ConsensusAccountsList.tsx [hunk 1]
```diff
@@ -0,0 +1,166 @@
...
+
+type ChainAccountPair = readonly [chain: Chain, accountId: AccountId];
+
+type Props = {
+  accounts: ChainAccountPair[];
+};
+
+const EVM_CHAIN_CONFIG = {
+  chainId: 'evm',
+  icon: 'https://raw.githubusercontent.com/novasamatech/nova-spektr-utils/main/icons/v1/chains/Ethereum.svg',
```
Comment (johnthecat) [inline src/renderer/features/wallet-details/ui/components/ConsensusAccountsList.tsx]: Do we really want to hardcode this icon url like this? I'ts better to move it inside project

File: src/renderer/features/wallet-details/ui/components/ConsensusAccountsList.tsx [hunk 2]
```diff
@@ -0,0 +1,166 @@
...
+  const [evmAccounts, restAccounts] = partition(list, ([chain]) => networkUtils.isEthereumBased(chain.options));
+  const [consensusAccounts, otherAccounts] = partition(restAccounts, ([chain]) => isConsensusChain(chain));
+  const consensusGroups = buildConsensusGroups(consensusAccounts);
+
+  const shouldShowConsensusChains = consensusAccounts.length > 0;
+  const shouldShowOtherChains = evmAccounts.length > 0 || otherAccounts.length > 0;
+
+  return (
+    <div className="flex h-full min-h-0 flex-col">
+      <ScrollArea>
```
Comment (johnthecat) [inline src/renderer/features/wallet-details/ui/components/ConsensusAccountsList.tsx]: I think ScrollArea should be moved outside component

**Review by Yanaty — APPROVED** [review]
