### PR TITLE
fix: add correct referendum id to remove vote operation info

### LINKED ISSUE #2292: Governance. Multisig operations. Remove vote, wrong assign referenda
## Description
Wrong referenda is shown for remove vote operation, track and referenda is mixed up:
Screenshot 2024-09-05 at 17 12 53

Screenshot 2024-09-05 at 17 15 20

## Environment
https://github.com/novasamatech/nova-spektr/commit/023df867e4ea11596d331f02f572caada4bbeaf6

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #2292

### CODE REVIEW

File: src/renderer/entities/transaction/lib/transactionBuilder.ts [hunk 1]
```diff
@@ -437,15 +437,15 @@ function buildRevote({ chain, accountId, referendumId, trackId, vote }: RevotePa
...
 };
 
-function buildRemoveVote({ chain, accountId, trackId, referendumId }: RemoveVoteParams): Transaction {
+function buildRemoveVote({ chain, accountId, track, referendum }: RemoveVoteParams): Transaction {
   return {
     chainId: chain.chainId,
     address: toAddress(accountId, { prefix: chain.addressPrefix }),
     type: TransactionType.REMOVE_VOTE,
-    args: { trackId, referendumId },
+    args: { track: track, referendum: referendum },
```
Comment (Asmadek) [inline src/renderer/entities/transaction/lib/transactionBuilder.ts]: What is the reason to duplicate it?

**Review by Asmadek — APPROVED** [review]

File: src/renderer/entities/transaction/lib/transactionBuilder.ts [hunk 2]
```diff
@@ -437,15 +437,15 @@ function buildRevote({ chain, accountId, referendumId, trackId, vote }: RevotePa
 type RemoveVoteParams = {
   chain: Chain;
   accountId: AccountId;
-  referendumId: ReferendumId;
-  trackId: TrackId;
+  referendum: ReferendumId;
+  track: TrackId;
```
Comment (sokolova-an) [inline src/renderer/entities/transaction/lib/transactionBuilder.ts:441]: why rename it if it's actually referendumId and trackId?

Comment (johnthecat) [reply src/renderer/entities/transaction/lib/transactionBuilder.ts:441]: For consistency with VOTE operation, it's critical for integration into multisig operations
