### PR TITLE
fix: governance timers

### LINKED ISSUE #5150: Governance. Timers. Need to use timelineChain for timers
## Description

Need to use timelineChain from config - https://github.com/novasamatech/nova-spektr-utils/blob/main/chains/v1/chains.json#L483C14-L483C27
to estimate timeouts for Governance on Polkadot \ Kusama asset hubs

Image
Image

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Fixes timers on governance page. Use timeline(relay) api to calculate time until referendum end block.

## Related Issues
Closes #5150

## Screenshots/Recordings
Screenshot 2025-11-21 at 1 01 35 PM

Screenshot 2025-11-21 at 1 01 45 PM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/governance/model/networkSelector.ts [hunk 1]
```diff
@@ -37,22 +37,36 @@ const $governanceChainApi = combine(
...
 );
 
+const $timelineChainApi = combine(
+  {
+    chain: $governanceChain,
+    apis: networkModel.$apis,
+  },
+  ({ chain, apis }) => {
+    const timelineChainId = chain?.additional?.timelineChain;
+    return timelineChainId ? (apis[timelineChainId] ?? null) : null;
```
Comment (johnthecat) [inline src/renderer/features/governance/model/networkSelector.ts]: I think it's better to fallback to chain.chainId
```
apis[timelineChainId] ?? apis[chain.chainId] ?? null
```

**Review by kalininilya — DISMISSED** [review]

File: src/renderer/features/governance/model/networkSelector.ts (hunk 1 above)
Comment (savvyer) [reply src/renderer/features/governance/model/networkSelector.ts]: Updated the fallback

**Review by kalininilya — APPROVED** [review]
