### PR TITLE
fix: votes for ref

### LINKED ISSUE #5109: Fellowship. Promotion/Retention widget shows “No opinions have been submitted yet” despite existing votes
## Description

When a Promotion/Retention referendum already exists and has votes submitted, the corresponding widget still displays the message: “No opinions have been submitted yet”

## Steps to Reproduce

1. Select fellowship2 account from the attached db and go to Fellowship.
2. Open the profile where the Promotion/Retention widgets are displayed.
3. Observe the message shown in the promotion widget -> "No opinions have been submitted yet"
4. Click View referendum -> "Other members find the evidence to be Good"

## Expected Behavior

If there are any votes for the current Promotion/Retention referendum, the widget should:

- Show the correct state, e.g., count or summary of submitted votes,

## Actual Behavior

- The widget continues to display: “No opinions have been submitted yet”
- This happens even when the referendum already has votes recorded.

## Screenshots

Image
Image

## Database

[fellowship.json](https://github.com/user-attachments/files/23606266/fellowship.json)

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Using votes from all members

## Related Issues
Closes #5109

## Screenshots/Recordings

image

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

**Review by savvyer — APPROVED** [review]

File: src/renderer/features/fellowship-promotion/hooks/useVotes.ts [hunk 1]
```diff
@@ -1,19 +1,21 @@
 import { nonNullable } from '@/shared/lib/utils';
-import { useVotes as useVotesDomain } from '@/domains/collectives';
-import { useFellowshipAccount, useMemberPromotionReferendum } from '@/aggregates/fellowship-member';
+import { useMembers, useVotes as useVotesDomain } from '@/domains/collectives';
+import { useMemberPromotionReferendum } from '@/aggregates/fellowship-member';
 import { useFellowshipApi, useFellowshipChain } from '@/aggregates/fellowship-network';
 
 export const useVotes = () => {
```
Comment (johnthecat) [inline src/renderer/features/fellowship-promotion/hooks/useVotes.ts:6]: Rename to useMembersVotes
