### PR TITLE
Fix: edit contact button padding

### LINKED ISSUE #1802: Address book. Looks broken without matrixID.
## Description

without matrixID column, Address Book looks broken:
Screenshot 2024-05-27 at 13 21 08

### PR DESCRIPTION
**Pull request by Tbaut**
closes https://github.com/novasamatech/nova-spektr/issues/1802

Let me know what you think @stepanLav 

image

### CODE REVIEW

File: src/renderer/features/contacts/EditContactForm/ui/EditContactNavigation.tsx [hunk 1]
```diff
@@ -14,5 +14,5 @@ export const EditContactNavigation = ({ contactId }: Props) => {
     navigate(createLink(Paths.EDIT_CONTACT, {}, { id: [contactId] }));
   };
 
-  return <IconButton name="edit" className="m-3" onClick={navigateToEdit} />;
+  return <IconButton name="edit" className="m-3 p-2" onClick={navigateToEdit} />;
```
Comment (tuul-wq) [inline src/renderer/features/contacts/EditContactForm/ui/EditContactNavigation.tsx:17]: You could try this code with `shrink-0`:
```javascript
export const ContactRow = ({ contact, children }: PropsWithChildren<Props>) => {
  return (
    <Plate className="flex p-0">
      <div className="flex flex-1 gap-x-2 items-center p-3">
        <Identicon address={contact.address} size={20} background={false} />
        <div className="overflow-hidden">
          <BodyText className="truncate">{contact.name}</BodyText>
          <div className="flex items-center gap-1 text-text-tertiary">
            <Truncate className="text-help-text" ellipsis="..." start={4} end={4} text={contact.address} />
            <IconButton name="copy" onClick={() => copyToClipboard(contact.address)} />
          </div>
        </div>
      </div>
      <div className="shrink-0">{children}</div>
    </Plate>
  );
};
```

Comment (Tbaut) [reply src/renderer/features/contacts/EditContactForm/ui/EditContactNavigation.tsx:17]: you mean instead of my change right?

This is makes the hover state disappear, and misaligned. You'd need to add a flex, and probably some padding again then, otherwise it doesn't look good
image

**Comment by stepanLav** [comment]
> closes #1802
> 
> Let me know what you think @stepanLav
> 
> image

I'm fine with it, it matches the layout

**Review by tuul-wq — APPROVED** [review]
