### PR TITLE
fix: find correct pure proxy

### LINKED ISSUE #3956: Flexible Multisig. Subscribe on blocks to handle event - Pure created

### PR DESCRIPTION
**Pull request by sokolova-an**
## Description
Fix pure proxy subscription 
## Related Issues
Closes #3956

### CODE REVIEW

File: src/renderer/features/multisig-wallet-create/flexible-multisig/model/assign-model.ts [hunk 1]
```diff
@@ -31,10 +31,10 @@ const $proxyAddress = createStore<Address | null>(null).reset(flexibleMultisigMo
 
 type SubscribePureEvent = {
   api: ApiPromise;
-  accounts: AnyAccount[];
+  signer: AnyAccount;
 };
 
-const subscribePureEventFx = createEffect(({ api, accounts }: SubscribePureEvent): Promise<Address> => {
+const subscribePureEventFx = createEffect(({ api, signer }: SubscribePureEvent): Promise<Address> => {
```
Comment (johnthecat) [inline src/renderer/features/multisig-wallet-create/flexible-multisig/model/assign-model.ts]: we use `signatory` work everywhere

**Review by johnthecat — APPROVED** [review]
