### PR TITLE
fix: handle no activity and loading separately

### LINKED ISSUE #3818: Fellowship. Activity \ Agreement state for no data
## Description

There is no state for no data on Activity \ Agrteement

Image

### PR DESCRIPTION
**Pull request by aaa123eee**
## Description

Explicitly handle loading state and N/A

## Related Issues

closes #3818

## Changes Made

- Add dedicated loading state
- Do not fallback to empty arrays/records if data is loading/null/etc

### CODE REVIEW

File: src/renderer/domains/collectives/referendumMeta/service.ts [hunk 1]
```diff
@@ -22,15 +22,22 @@ function getReferendumsSinceLastProof(referendums: ReferendumMeta[], member: Cor
...
+
+  if (referendums.length === 0) return { activity: null, agreement: null, isLoading: false };
 
   const possibleReferendums = referendums.filter(r =>
     trackService.rankSatisfiesVotingThreshold(member.rank, maxRank, r.track),
   );
 
   if (referendums.length > 0 && possibleReferendums.length === 0) {
-    return { activity: 100, agreement: 100 };
+    return { activity: 100, agreement: 100, isLoading: false };
```
Comment (johnthecat) [inline src/renderer/domains/collectives/referendumMeta/service.ts]: It will stuck in loading state if member has rank lower than threshold on any given referendum. I think loading state should be derived from actual `referendumMeta.pending` + `voting.pending` states

File: src/renderer/features/fellowship-profile/model/profile.ts [hunk 2]
```diff
@@ -14,8 +14,8 @@ import { fellowship } from './fellowship';
 
 const requestIdentityFx = attach({ effect: identity.request });
 
-const $tracks = fellowship.$store.map(store => store?.tracks ?? []);
-const $referendumMeta = fellowship.$store.map(store => store?.referendumMeta ?? {});
+const $tracks = fellowship.$store.map(store => store?.tracks);
+const $referendumMeta = fellowship.$store.map(store => store?.referendumMeta);
 const $votes = fellowship.$store.map(store => store?.voting ?? []);
```
Comment (aaa123eee) [inline src/renderer/features/fellowship-profile/model/profile.ts:19]: this is the only annoying item that causes `0%` during an intermediate state

but we can't remove this `?? []` because sometimes we get only partial data

the only case is to refactor state reducers so they record an excessive `[]` to the proper store[palletType][chainId]

**Review by cuteWarmFrog — APPROVED** [review]
noice!

File: src/renderer/domains/collectives/referendumMeta/service.ts (hunk 1 above)
Comment (aaa123eee) [reply src/renderer/domains/collectives/referendumMeta/service.ts]: updated

no loading can stuck now but unfinished data can sneak now

File: src/renderer/domains/collectives/referendumMeta/service.ts [hunk 3]
```diff
@@ -22,8 +22,15 @@ function getReferendumsSinceLastProof(referendums: ReferendumMeta[], member: Cor
   return referendums.filter(r => r.created >= member.lastProof);
 }
 
-function getActivityInfo(referendums: ReferendumMeta[], member: Member, maxRank: number, votes: Vote[]) {
-  if (referendums.length === 0) return null;
+function getActivityInfo(
+  referendums: ReferendumMeta[] | undefined,
```
Comment (johnthecat) [inline src/renderer/domains/collectives/referendumMeta/service.ts]: I think it's better to use null everywhere instead of undefined

File: src/renderer/features/fellowship-profile/model/profile.ts [hunk 4]
```diff
@@ -14,8 +14,8 @@ import { fellowship } from './fellowship';
 
 const requestIdentityFx = attach({ effect: identity.request });
 
-const $tracks = fellowship.$store.map(store => store?.tracks ?? []);
-const $referendumMeta = fellowship.$store.map(store => store?.referendumMeta ?? {});
+const $tracks = fellowship.$store.map(store => store?.tracks);
```
Comment (johnthecat) [inline src/renderer/features/fellowship-profile/model/profile.ts]:
```suggestion
const $tracks = fellowship.$store.map(store => store?.tracks ?? null);
```
and so on

Comment (aaa123eee) [reply src/renderer/features/fellowship-profile/model/profile.ts]: kk!
