### PR TITLE
fix: create flexible proxy fee

### LINKED ISSUE #4357: Flexible multisig. Initial balance for flexible multisig calculates wrong
## Description

Balance for flexible multisig should be: ED + proxyDepositFactor
For test network it should be:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-test-network-1.novasama-tech.org#/chainstate/constants

Image

## Expected Behavior

**11 650 000 000** or, transferred to decimal - 0,01165

## Actual Behavior

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-test-network-1.novasama-tech.org#/explorer/query/0x64bb2aabfdb017c508887fbdd831ca92900a733a1a143315f1549ed7fce746bc

Image

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Using formula ED + proxyDepositFactor

## Related Issues
Closes #4357

### CODE REVIEW

File: src/renderer/features/multisig-wallet-create/flexible-multisig/model/flexible-multisig-create.ts [hunk 1]
```diff
@@ -119,7 +118,7 @@ sample({
   target: $existentialDeposit,
 });
 
-const $proxyDeposit = combine($api, api => (api && proxyService.getProxyDeposit(api, '0', 1)) ?? null);
+const $proxyDeposit = combine($api, api => (api && api.consts.proxy.proxyDepositFactor.toString()) ?? null);
```
Comment (aaa123eee) [inline src/renderer/features/multisig-wallet-create/flexible-multisig/model/flexible-multisig-create.ts]:
```suggestion
const $proxyDepositFactor = combine($api, api => (api && api.consts.proxy.proxyDepositFactor.toString()) ?? null);
```

**Review by aaa123eee — APPROVED** [review]
