### PR TITLE
fix(cas): evm crypto type matching

### LINKED ISSUE #4001: CAS Graph. EVM networks shows wrong
## Description

EVM networks built wrong for Nova Wallet

## Test database

[spektr-database (27).json](https://github.com/user-attachments/files/20886043/spektr-database.27.json)

## Steps to Reproduce

1. Import test data
2. Open wallet details
3. Open overview
4. Select Mythos\Moonbeam\Moonriver address

## Expected Behavior

Shows EVM address

## Actual Behavior

Empty screen

Image

## Environment
DEV

### PR DESCRIPTION
**Pull request by aaa123eee**
## Description

Set proper crypto type for EVM accounts

## Related Issues

closes #4001

## Changes Made

- set proper crypto type when connected
- add migration for connected accounts

## Screenshots/Recordings
image

### CODE REVIEW

File: src/renderer/shared/api/storage/migration/migration-7.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+
+/**
+ * Migration to fix cryptoType for connected EVM accounts
+ */
+export async function migrateEVMAccountsCryptoType(t: Transaction): Promise<void> {
+  const accounts = await t.table<AnyAccount>('accounts2').toArray();
+
+  console.log('migrateEVMAccountsCryptoType', { accounts });
+
+  const accountsToUpdate = accounts.map((account) => ({
```
Comment (johnthecat) [inline src/renderer/shared/api/storage/migration/migration-7.ts]: filter wallet connect accounts specifically pls

Comment (aaa123eee) [reply src/renderer/shared/api/storage/migration/migration-7.ts]: done https://github.com/novasamatech/nova-spektr/pull/4036/commits/a417704ff99de1cc73851ece438be6e67b0a4832

**Review by johnthecat — APPROVED** [review]
