### PR TITLE
fix: dev env cant get balances

### LINKED ISSUE #3717: DEV env - can't get balances
## Description

App on DEV env can't load balances
https://spektr-dev.novasama-tech.org/

## Steps to Reproduce

1. Open dev env
2. Switch to Portfolio view

## Expected Behavior
Balances will be loaded

## Actual Behavior
Balances in the loading state

## Environment
DEV

## Additional information
Subscriptions on balances won't create due to empty subAccounts object

Image

### PR DESCRIPTION
**Pull request by savvyer**
## Description
On the https://spektr-dev.novasama-tech.org/ and docker release build locally couldn't load balances.
There was a race condition. Effector waited for `networkModel.$chains.updates` when networkModel.$chains was already populated.

## Related Issues
Closes https://github.com/novasamatech/nova-spektr/issues/3717

## Changes Made
- initializes $subAccounts once $selectedWallet and $chains are available
- replaced a couple of `Boolean` checks with more appropriate `nonNullable`
- fixed one sample filter that checked wallet

### CODE REVIEW

**Review by cuteWarmFrog — APPROVED** [review]
lgtm! cool that you've found this!

File: src/renderer/features/assets-balances/subscription/model/balance-sub-model.ts [hunk 1]
```diff
@@ -134,10 +134,17 @@ sample({
...
+const $walletAndChains = combine({
+  wallet: walletSelect.$selectedWallet,
+  chains: networkModel.$chains,
+});
+
 sample({
-  clock: once(combineEvents([walletSelect.$selectedWallet.updates, networkModel.$chains.updates])),
-  filter: ([wallet]) => Boolean(wallet),
-  fn: ([wallet, chains]) => ({
+  clock: once($walletAndChains.map(({ wallet, chains }) =>
```
Comment (johnthecat) [inline src/renderer/features/assets-balances/subscription/model/balance-sub-model.ts:143]: remove map please

**Review by johnthecat — APPROVED** [review]

File: src/renderer/features/assets-balances/subscription/model/balance-sub-model.ts (hunk 1 above)
Comment (savvyer) [reply src/renderer/features/assets-balances/subscription/model/balance-sub-model.ts:143]: @johnthecat 
if I remove `map` how can I make sure that both wallet and chains stores are initialized and once($walletAndChains) does not run once with default values?

Comment (johnthecat) [reply src/renderer/features/assets-balances/subscription/model/balance-sub-model.ts:143]: oh, okay!
