### PR TITLE
fix: evm group

### LINKED ISSUE #4837: Consensus based view need separate EVM group
## Description

When user has EVM based wallet - it should be included in separate EVM group, otherwise it has no glue what is happening:

Image

## Steps to Reproduce

1. Add EVM based key, for example - moonbeam

## Expected Behavior

Shows separate group for EVM based keys

## Actual Behavior

EVM key put into relay group

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Show ethereum based accounts within the separate group in the Polkadot Vault wallet details.

## Related Issues
Closes https://github.com/novasamatech/nova-spektr/issues/4837

## Changes Made
- Group Ethereum accounts together
- Refactored grouping functionality

## Screenshots/Recordings
Screenshot 2025-10-16 at 3 43 27 PM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/entities/wallet/ui/VaultAccountsList/VaultAccountsList.tsx [hunk 1]
```diff
@@ -20,69 +21,96 @@ type Props = {
   onShardClick?: (shards: VaultShardAccount[]) => void;
 };
 
+const EVM_CHAIN_CONFIG = {
```
Comment (kalininilya) [inline src/renderer/entities/wallet/ui/VaultAccountsList/VaultAccountsList.tsx:24]: Do we really need this here? Isn’t there a way to fetch it dynamically instead?

**Review by kalininilya — APPROVED** [review]

File: src/renderer/entities/wallet/ui/VaultAccountsList/VaultAccountsList.tsx (hunk 1 above)
Comment (savvyer) [reply src/renderer/entities/wallet/ui/VaultAccountsList/VaultAccountsList.tsx:24]: I know its ugly, but ChainIcon doesn't support loading images by names like Icon component, only chain objects are supported.
