### PR TITLE
Fix: Mythos transfer

### LINKED ISSUE #2846: PAH. MYTH transfer from PAH to PAH address - Wrong extrinsic send to sign
## Description

Wen try to send extrinsic to the chain it always fall down with bad signature error.
Signed data is different with actually used in the transaction

Signed data:
```
0xa43508010100a53400000000000000000000000000000000000000000000000000000000000000000000b503c901000000fc4d0f000f00000068d56f15f85d3136970ec16946040bc1752654e906147f7e43e9d539d7c3de2fc07d9784e0f7cdf7eb0ca54fa0a1b730b8733dd0ba0a03c033f43f55721e3da400
```
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fasset-hub-polkadot-rpc.dwellir.com#/extrinsics/decode/0x3508010100a53400000000000000000000000000000000000000000000000000000000000000000000

Actually used in transaction:
```
{
    "address": "13mAjFVjFDpfa42k2dLdSnUyrSzK8vAySsoudnxX2EKVtfaq",
    "assetId: undefined
    "blockHash": "0xc07d9784e0f7cdf7eb0ca54fa0a1b730b8733dd0ba0a03c033f43f55721e3da4",
    "blockNumber": "0x007650fb",
    "era": "0xb503",
    "genesisHash": "0x68d56f15f85d3136970ec16946040bc1752654e906147f7e43e9d539d7c3de2f",
    "metadataHash": undefined
    "metadataRpc": "{metadata_rpc}",
    "method": "0x3508010100a53400000000000000000000000000000000000000000000000000000000000000000000",
    "mode": undefined
    "nonce": "0x00000072",
    "signedExtensions": [
        "CheckNonZeroSender",
        "CheckSpecVersion",
        "CheckTxVersion",
        "CheckGenesis",
        "CheckMortality",
        "CheckNonce",
        "CheckWeight",
        "ChargeAssetTxPayment",
        "CheckMetadataHash"
    ],
    "specVersion": "0x000f4dfc",
    "tip": "0x00000000000000000000000000000000",
    "transactionVersion": "0x0000000f",
    "version": 4
}
```

Screenshot 2024-12-12 at 09 41 45

## Environment
https://github.com/novasamatech/nova-spektr/commit/639f537c184ca4436a635fa87f43961474c4cb5d

### PR DESCRIPTION
**Pull request by tuul-wq**
- Fixed Statemine transfer (pah - pah > Mythos)

closes #2846

### CODE REVIEW

File: src/renderer/entities/transaction/lib/extrinsicService.ts [hunk 1]
```diff
@@ -64,20 +64,18 @@ export const getUnsignedTransaction: Record<
   [TransactionType.ASSET_TRANSFER]: (transaction, info, options, api) => {
     const palletName = transaction.args.palletName ?? 'assets';
     const methodArgs = api.tx[palletName].transfer.meta.args;
-    const rawArgs = [transaction.args.asset, transaction.args.target, transaction.args.amount];
+    const rawArgs = [transaction.args.asset, transaction.args.dest, transaction.args.value];
```
Comment (johnthecat) [inline src/renderer/entities/transaction/lib/extrinsicService.ts:67]: It will fail on simple transaction case

Comment (tuul-wq) [reply src/renderer/entities/transaction/lib/extrinsicService.ts:67]: According to the following methods, everything is fine
@Asmadek maybe you could tell us what we're missing?

```javascript
type TransferParams = {
  chain: Chain;
  asset: Asset;
  accountId: AccountId;
  destination: string;
  amount: string;
  xcmData?: {
    args: {
      xcmFee: string;
      xcmAsset?: NonNullable<unknown>;
      xcmWeight: string;
      xcmDest?: NonNullable<unknown>;
      xcmBeneficiary?: NonNullable<unknown>;
      destinationChain: ChainId;
    };
    transactionType: TransactionType;
  };
};
function buildTransfer({ chain, accountId, destination, asset, amount, xcmData }: TransferParams): Transaction {
  let transactionType = asset.type ? TransferType[asset.type] : TransactionType.TRANSFER;
  if (xcmData) {
    transactionType = xcmData.transactionType;
  }

  const palletName =
    asset.typeExtras && 'palletName' in asset.typeExtras ? camelCase(asset.typeExtras.palletName) : 'assets';

  return {
    chainId: chain.chainId,
    address: toAddress(accountId, { prefix: chain.addressPrefix }),
    type: transactionType,
    args: {
      palletName,
      dest: toAddress(destination || TEST_ACCOUNTS[0], { prefix: chain.addressPrefix }),
      value: formatAmount(amount, asset.precision) || '1',
      ...(Boolean(asset.type) && { asset: getAssetId(asset) }),
      ...xcmData?.args,
    },
  };
}
```

Comment (Asmadek) [reply src/renderer/entities/transaction/lib/extrinsicService.ts:67]: @johnthecat what's wrong with it? I didn't see any problems with transaction

**Review by johnthecat — APPROVED** [review]
