### PR TITLE
fix: remove walletConnect & nova wallet

### LINKED ISSUE #4572: WalletConnect. Send dissconnect event, when remove a wallet from Spektr
## Description

We would like to send disconnect event to WalletConnect when remove wallet from the app

## Steps to Reproduce

1. Pair Spektr with NovaWallet account
2. Remove that wallet from Spektr

## Expected Behavior

In NovaWallet session will disappear

## Actual Behavior

Session in NovaWallet still exist

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Wallet forget worked from wallet details modal, but didn't work if user removed a wallet from the dropdown list of actions.
This PR fixes dropdown remove action. Sends disconnect event to wallet connect & nova wallet on wallet removal from Spektr.

## Related Issues
Closes #4572

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/wallet-details/index.tsx [hunk 1]
```diff
@@ -119,9 +122,16 @@ walletDetailsFeature.inject(walletActionSlot, ({ wallet }) => {
       title = t('walletDetails.common.hideButton');
     }
 
+    let onForget;
```
Comment (johnthecat) [inline src/renderer/features/wallet-details/index.tsx:127]: This connection is forbidden because abstract wallet details feature shouldn't know about wallet connect. Add a comment about it here, please, we'll refactor it later

Comment (savvyer) [reply src/renderer/features/wallet-details/index.tsx:127]: yep

**Review by aaa123eee — APPROVED** [review]
