### PR TITLE
Fix: bugs after remove pure fixes

### LINKED ISSUE #1621: Add delegated authority. Remove wallet while creating new authority.
## Description
Current wallet may be deleted when add delegated authority for the wallet, which already has another delegated authority

## Steps to Reproduce

1. Add delegated authority for the wallet
2. Waiting update
3. Add second delegated authority for the wallet

## Expected Behavior
Added second delegated authority

## Actual Behavior
Current wallet was deleted

## Environment
https://github.com/novasamatech/nova-spektr/commit/432167ed6b6979d57bd411da75e199bf4d9e501a

## Screenshots

log - 
[nova-spektr.log](https://github.com/novasamatech/nova-spektr/files/14835144/nova-spektr.log)

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/dfaddf9b-6287-4485-a123-906a8c886ead

</details>

### LINKED ISSUE #1628: Revoke delegated authority (pure proxy). Is available for Proxied wallet
## Description
Revoke authority for the proxied account is not available - sign button is not available

## Steps to Reproduce

1. Connect NovaWallet wallet
2. Create pure proxy for it
3. Select created pure Proxied
4. Open Details for that wallet
5. Try to remove pure proxy

## Expected Behavior
Sign operation for remove the pure

## Actual Behavior
Button for sign is not available

## Environment
https://github.com/novasamatech/nova-spektr/commit/353084534671c39458b83465e007bc8e07559989

## Screenshots

Screenshot 2024-04-03 at 13 43 02

### LINKED ISSUE #1639: Remove pure. Undefined for proxy::killPure
## Description
When user try to remove pureProxy - got an error:
```
2024/04/08 08:55:06.837 [development#1.5.0]-renderer [warn] > Error: Method proxy::killPure expects argument {"name":"height","type":"Compact<u32>","typeName":"BlockNumberFor"}, but got undefined
```

Screenshot 2024-04-08 at 09 01 31

### LINKED ISSUE #1640: Remove proxy, as a proxied account. Reject when try to sign.
## Description
Get reject when try to sign via WalletConnect revoke authority as a proxied.

## Steps to Reproduce
Wallet setup:
- wallet_a with proxy on wallet_b
- proxied for wallet_c with All operations access

1. Try to remove proxied from wallet_b
-- successful removing
2. Try to remove proxy as a proxied wallet

## Expected Behavior
Successful signing as a proxied account

## Actual Behavior
Reject while signing

## Environment
https://github.com/novasamatech/nova-spektr/commit/23ee363cc50fa75f156ee799eb31603b13a0eee2

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/cba912e9-175a-4fda-b0ea-2dd1645a9a19

</details>

logs:
[nova-spektr.log](https://github.com/novasamatech/nova-spektr/files/14902110/nova-spektr.log)

### LINKED ISSUE #1654: Revoke autority from multisig. Invalid empty address passed
## Description
When user try to revoke access as a multisig - faced with error:
```
2024/04/09 12:14:09.948 [development#1.5.0]-main [error] > Unhandled Error: Invalid empty address passed
```

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/e0c7118f-0044-4226-8636-f4e6b14a5265

</details>

## Steps to Reproduce

1. Create delegated authority for the multisig wallet
2. Go to multisig wallet details
3. Try to revoke access

## Expected Behavior
Successful revoke

## Actual Behavior
Error

## Environment
https://github.com/novasamatech/nova-spektr/commit/3f055011f7232f86df35039f084938123d5e15c3

### PR DESCRIPTION
**Pull request by Asmadek**
fix: don't remove wallet after add second wallet
fix: fill data for block number and extIndex for pure

### CODE REVIEW

File: src/renderer/widgets/AddProxyModal/model/form-model.ts [hunk 1]
```diff
@@ -316,9 +316,9 @@ const $signatories = combine(
 
     const signers = dictionary(account.signatories, 'accountId', () => true);
 
-    return wallets.reduce<{ signer: Account; balance: string }[]>((acc, wallet) => {
+    const signatories = wallets.reduce<{ signer: Account; balance: string }[]>((acc, wallet) => {
```
Comment (tuul-wq) [inline src/renderer/widgets/AddProxyModal/model/form-model.ts]: We still can return this `reduce` without additional variable

File: src/renderer/widgets/AddPureProxiedModal/model/confirm-model.ts [hunk 2]
```diff
@@ -48,21 +62,28 @@ const $signerWallet = combine(
...
   ({ store, wallets }) => {
-    if (!store) return null;
+    if (!store) return undefined;
 
     return walletUtils.getWalletById(wallets, store.signatory?.walletId || store.account.walletId);
   },
+  { skipVoid: false },
 );
 
+sample({
```
Comment (tuul-wq) [inline src/renderer/widgets/AddPureProxiedModal/model/confirm-model.ts]: Could be safely deleted because of `restore`

File: src/renderer/widgets/AddPureProxiedModal/model/form-model.ts [hunk 3]
```diff
@@ -41,16 +58,17 @@ const feeChanged = createEvent<string>();
 const isFeeLoadingChanged = createEvent<boolean>();
 const isProxyDepositLoadingChanged = createEvent<boolean>();
 
-const $proxyDeposit = restore(proxyDepositChanged, '0');
-const $isProxyDepositLoading = restore(isProxyDepositLoadingChanged, false);
-const $multisigDeposit = restore(multisigDepositChanged, '0');
-const $fee = restore(feeChanged, '0');
-const $isFeeLoading = restore(isFeeLoadingChanged, false);
+const $fee = createStore<string>('0').reset(formSubmitted);
```
Comment (tuul-wq) [inline src/renderer/widgets/AddPureProxiedModal/model/form-model.ts]: If I return from confirm screen to the form screen, seems that I won't see previous data

File: src/renderer/widgets/AddPureProxiedModal/model/form-model.ts [hunk 4]
```diff
@@ -41,16 +58,17 @@ const feeChanged = createEvent<string>();
...
+const $oldProxyDeposit = createStore<string>('0').reset(formSubmitted);
```
Comment (tuul-wq) [inline src/renderer/widgets/AddPureProxiedModal/model/form-model.ts]: Nice to have `ZERO_BALANCE` for `'0'`

File: src/renderer/widgets/AddPureProxiedModal/ui/Confirm.tsx [hunk 5]
```diff
@@ -17,42 +15,83 @@ type Props = {
...
   if (!confirmStore || !api || !initiatorWallet) return null;
 
-  const [isFeeLoading, setIsFeeLoading] = useState(true);
-  const [isProxyDepositLoading, setIsProxyDepositLoading] = useState(true);
-
   return (
     <div className="flex flex-col items-center pt-4 gap-y-4 pb-4 px-5">
       <div className="flex flex-col items-center gap-y-3 mb-2">
-        <Icon name="proxyConfirm" size={60} />
+        <Icon className="text-icon-default" name={'proxyConfirm'} size={60} />
```
Comment (tuul-wq) [inline src/renderer/widgets/AddPureProxiedModal/ui/Confirm.tsx]:
```suggestion
        <Icon className="text-icon-default" name="proxyConfirm" size={60} />
```

File: src/renderer/widgets/RemoveProxyModal/model/remove-proxy-model.ts [hunk 6]
```diff
@@ -11,15 +19,20 @@ import { Step, RemoveProxyStore } from '../lib/types';
...
 import { confirmModel } from './confirm-model';
 import { walletProviderModel } from '../../WalletDetails/model/wallet-provider-model';
-import { Chain, ProxiedAccount, ProxyType, ProxyVariant } from '@shared/core';
+import { Account, Chain, ProxiedAccount, ProxyAccount, ProxyType, ProxyVariant } from '@shared/core';
 import { signModel } from '@features/operations/OperationSign/model/sign-model';
 import { submitModel } from '@features/operations/OperationSubmit';
-import { proxyModel } from '@/src/renderer/entities/proxy';
-import { toAccountId } from '@/src/renderer/features/proxies/lib/worker-utils';
+import { proxyModel } from '@entities/proxy';
+import { toAccountId } from '@features/proxies/lib/worker-utils';
```
Comment (tuul-wq) [inline src/renderer/widgets/RemoveProxyModal/model/remove-proxy-model.ts]: `shared/lib/utils`

File: src/renderer/widgets/WalletDetails/ui/components/ProxiesList.tsx [hunk 7]
```diff
@@ -95,7 +106,11 @@ export const ProxiesList = ({ className, canCreateProxy = true }: Props) => {
         onClose={toggleIsRemoveConfirmOpen}
         onConfirm={() => {
```
Comment (tuul-wq) [inline src/renderer/widgets/WalletDetails/ui/components/ProxiesList.tsx]: Let's write a dedicated handler function to make it readable

File: src/renderer/widgets/WalletDetails/ui/components/ProxiesList.tsx [hunk 8]
```diff
@@ -49,6 +49,15 @@ export const ProxiesList = ({ className, canCreateProxy = true }: Props) => {
     }
   };
 
+  const handleConfirm = () => {
+    toggleIsRemoveConfirmOpen();
+    proxyForRemoval &&
```
Comment (tuul-wq) [inline src/renderer/widgets/WalletDetails/ui/components/ProxiesList.tsx]:
```javascript
if (!proxyForRemoval) return;

const account = accounts.find((a) => accountUtils.isChainAndCryptoMatch(a, chains[proxyForRemoval.chainId]));
removeProxyModel.events.flowStarted({ account: account!, proxy: proxyForRemoval });
```

**Review by tuul-wq — APPROVED** [review]
