### PR TITLE
fix: proxy revoke delegate, remove proxy duplicates

### LINKED ISSUE #4355: Wallet details. Added proxy accounts are not displayed in the 'Delegated to' tab of the wallet details modal
## Description

In the wallet details modal, the 'Delegated to' tab does not list proxy accounts that have been delegated authority from the current wallet.

## Steps to Reproduce

1. Open the wallet details modal for any account.
2. Add one or more proxy accounts to this wallet (delegate authority).
3. Navigate to the “Delegated to” tab.

## Expected Behavior

The “Delegated to” tab should display all active proxy accounts that have been delegated authority from the wallet.

## Actual Behavior

The tab is empty, showing no proxy accounts, even when they are correctly set on-chain.

## Database

Can be checked on extension wallet in the attached db.

[spektr-database_1208.json](https://github.com/user-attachments/files/21739911/spektr-database_1208.json)

### PR DESCRIPTION
**Pull request by kalininilya**
Resolves #4355

## Description
This PR fixes issues with proxy revocation and delegation functionality by updating the proxy management system to work with the new account architecture. The changes address type compatibility issues between ProxiedAccount and AnyAccount types, improve proxy data fetching and display, and ensure proper account synchronization after proxy operations.
The main problem solved is the incompatibility between the legacy ProxiedAccount type and the new AnyAccount type system, which was causing issues in proxy removal operations and proxy list display. The solution involves updating type definitions, improving data fetching logic, and adding proper loading states.

Also enables text pasting in the Pure Proxy delegate revoke form

## Changes Made

- Fixed proxy removal model - Updated remove-proxy-model.ts to work with AnyAccount type and added proper account synchronization after successful proxy removal
- Enhanced proxy data fetching - Improved wallet-proxies-model.ts to deduplicate proxy entries
- Added loading states - Implemented skeleton loading states in ProxiesCount and ProxiesList components for better UX during data fetching
- Created new component - Added ChainProxyGroup.tsx component to better organize proxy display by chain
- Improved proxy list UI - Refactored ProxiesList.tsx to use the new component structure and handle loading states properly
- Fixed account synchronization - Added automatic account sync trigger after proxy operations complete successfully

## Screenshots/Recordings

Loading state
Screenshot 2025-09-24 at 11 43 45

Final state
Screenshot 2025-09-24 at 11 41 06

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable) *(It’s a pain to get the required init data)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts [hunk 1]
```diff
@@ -60,7 +71,9 @@ export const fetchWalletProxiesFx = createEffect(
 
 export const resetWalletProxies = createEvent();
 
-export const $walletProxies = createStore<Record<ChainId, Omit<ProxyAccount, 'id' | 'delay'>[]>>({});
+export const $walletProxies = createStore<
+  Record<ChainId, (Omit<ProxyAccount, 'id' | 'delay'> & { deposit: string })[]>
```
Comment (valentunn) [inline src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Embedding such type transformations adds way to much noise. I suggest to exract it to a separate type

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts [hunk 2]
```diff
@@ -48,7 +50,16 @@ export const fetchWalletProxiesFx = createEffect(
       });
 
       const accountsProxies = await Promise.all(accountProxiesPromises);
-      return [chainId, accountsProxies.flat()];
+      const allProxies = accountsProxies.flat();
+      const uniqueProxies = allProxies.reduce((acc, proxy) => {
+        const key = `${proxy.accountId}_${proxy.proxiedAccountId}`;
```
Comment (valentunn) [inline src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Why do we only deduplicate by proxy and proxied account ids? There can be multiple proxies with the same proxy and proxied, but with the different types.
You can test on this account:`127zarPDhVzmCXVQ7Kfr1yyaa9wsMuJ74GJW9Q7ezHfQEgh6`. It has Governance and Staking proxies to the same proxy account. Please add a screenshot demonstrating that this case works

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts [hunk 3]
```diff
@@ -96,53 +104,53 @@ sample({
...
-
-    const derivedGroups = [];
+    const groups = [];
     for (const [chainIdStr, proxyAccounts] of Object.entries(chainsProxies)) {
       if (proxyAccounts.length > 0) {
-        const proxiedAccount = accounts.find(
-          account => account.accountId === proxyAccounts[0].proxiedAccountId && accountUtils.isProxiedAccount(account),
-        );
+        const chainId = chainIdStr;
+        const totalDeposit = proxyAccounts[0].deposit || '0';
```
Comment (valentunn) [inline src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: We should never do this kind of "use zero in case something goes not as we expect". There should be a meaningful handling, either we hide/ignore the value we are unsure how to display, or show an entry depicting that the value is unexpected

File: src/renderer/features/wallet-details/ui/components/ProxiesList.tsx [hunk 4]
```diff
@@ -34,17 +31,13 @@ export const ProxiesList = ({ className, wallet, hasProxies, canCreateProxy = tr
...
-    store: accounts.$list,
-    keys: [wallet],
-    fn: (accounts, [wallet]) => {
-      return accountService.filterAccountsByWallet(accounts, wallet.id);
-    },
-  });
+  const allAccounts = useUnit(accounts.$list);
+  const isProxiesLoading = useUnit(walletProxiesModel.fetchWalletProxiesFx.pending);
+  const isAccountSyncPending = useUnit(accountSync.syncAccounts.pending);
+  const isLoading = isProxiesLoading || isAccountSyncPending;
```
Comment (valentunn) [inline src/renderer/features/wallet-details/ui/components/ProxiesList.tsx]: This code is dulbicated across two components. Might be worth a separate store

File: src/renderer/shared/core/types/proxy.ts [hunk 5]
```diff
@@ -10,6 +10,7 @@ export type ProxyAccount = {
   chainId: ChainId;
   proxyType: ProxyType;
   delay: number;
+  deposit?: string;
```
Comment (valentunn) [inline src/renderer/shared/core/types/proxy.ts]: Such modeling is wrong. Deposit, if we are talking about deposit received from the chain, belongs to the proxied account data, not an individual proxy
Otherwise this "deposit" will be dublicated for each proxy and we will do some strange things like `proxies[0].deposit` which I have actually seen above

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts [hunk 6]
```diff
@@ -48,7 +50,16 @@ export const fetchWalletProxiesFx = createEffect(
...
       const accountsProxies = await Promise.all(accountProxiesPromises);
-      return [chainId, accountsProxies.flat()];
+      const allProxies = accountsProxies.flat();
+      const uniqueProxies = allProxies.reduce((acc, proxy) => {
+        const key = `${proxy.accountId}_${proxy.proxiedAccountId}`;
+        if (!acc.has(key)) {
+          acc.set(key, proxy);
+        }
+        return acc;
+      }, new Map<string, (typeof allProxies)[0]>());
```
Comment (valentunn) [inline src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: If you extract the type I have marked in my other comment, you wont need to use this rather unreadable code to infer it

File: src/renderer/features/proxy-remove/model/remove-proxy-model.ts [hunk 7]
```diff
@@ -146,8 +147,8 @@ const $coreTx = combine(
         spawner: data.spawner,
         proxyType: data.proxyType,
         index: 0,
-        height: proxiedAccount.blockNumber!,
-        extIndex: proxiedAccount.extrinsicIndex!,
+        height: (proxiedAccount as any).blockNumber || 0,
+        extIndex: (proxiedAccount as any).extrinsicIndex || 0,
```
Comment (valentunn) [inline src/renderer/features/proxy-remove/model/remove-proxy-model.ts]: There is no way `|| 0` should ever be the case in normal conditions, why is it here? We know that `isPureProxiedNeedToBeKilled` imples that the `proxiedAccount` is actually `ProxiedAccount`. This should be asserted and then we should work with `ProxiedAccount`

File: src/renderer/features/proxy-remove/model/remove-proxy-model.ts [hunk 8]
```diff
@@ -271,7 +272,7 @@ sample({
     apis: networkModel.$apis,
   },
   fn: ({ chains, apis }, { proxy, proxied }) => {
-    const chain = chains[proxied.chainId || proxy.chainId];
+    const chain = chains[(proxied as any).chainId || proxy.chainId];
```
Comment (valentunn) [inline src/renderer/features/proxy-remove/model/remove-proxy-model.ts]: Just `proxy.chainId` is enough. No need to complicate

File: src/renderer/features/proxy-remove/ui/RemoveProxy.tsx [hunk 9]
```diff
@@ -27,7 +28,11 @@ export const RemoveProxy = ({ wallet }: Props) => {
   const { t } = useI18n();
 
   const step = useUnit(removeProxyModel.$step);
-  const chainId = useUnit(removeProxyModel.$proxiedAccount.map((account) => account?.chainId ?? null));
+  const chainId = useUnit(
+    removeProxyModel.$proxiedAccount.map((account) =>
+      account && accountService.isChainAccount(account) ? account.chainId : null,
+    ),
```
Comment (valentunn) [inline src/renderer/features/proxy-remove/ui/RemoveProxy.tsx]: You should use `chainId` derived from `$proxyAccount `. `$proxiedAccount ` is just some account we have in the app, it could be anything - wallet connect, extension, synced proxied... It is not guaranteed `chainId` is even there

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts [hunk 10]
```diff
@@ -19,10 +18,12 @@ export const fetchWalletProxiesFx = createEffect(
...
     chains: Record<ChainId, Chain>;
     apis: Record<ChainId, ApiPromise>;
-  }): Promise<Record<ChainId, Omit<ProxyAccount, 'id' | 'delay'>[]>> => {
+  }): Promise<Record<ChainId, (Omit<ProxyAccount, 'id' | 'delay'> & { deposit: string })[]>> => {
     const chainIds = keys(chains);
 
-    const fetchChainProxies = async (chainId: ChainId): Promise<[ChainId, Omit<ProxyAccount, 'id' | 'delay'>[]]> => {
+    const fetchChainProxies = async (
+      chainId: ChainId,
+    ): Promise<[ChainId, (Omit<ProxyAccount, 'id' | 'delay'> & { deposit: string })[]]> => {
```
Comment (valentunn) [inline src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: It should rather be something like
```ts
type Proxy = Omit<ProxyAccount, 'id' | 'delay'>
type OnChainProxies = { proxies:  Proxy[], deposit: string }
```

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts [hunk 11]
```diff
@@ -96,53 +104,53 @@ sample({
...
+  clock: accountSync.syncAccounts.doneData,
+  source: {
+    wallet: $wallet,
+    chains: networkModel.$chains,
+    apis: networkModel.$apis,
+  },
+  filter: ({ wallet }) => nonNullable(wallet),
+  fn: ({ wallet, chains, apis }) => ({ wallet: wallet!, chains, apis }),
+  target: fetchWalletProxiesFx,
+});
```
Comment (valentunn) [inline src/renderer/features/wallet-details/model/wallet-proxies-model.ts:171]: There is no need to bind proxies re-sync to anything. proxies can be subscribed to since it is a simple single-key request. This way we can always have up-to-date proxies here as well as lower loading times

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts (hunk 1 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Fixed, extracted the type into `type Proxy = Omit<ProxyAccount, 'id' | 'delay'> & { deposit: string };`

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts (hunk 2 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Oh, you are right, I forgot about the fact that proxies can have the same address but different type, added a proxyType check as well:

const key = `${proxy.accountId}_${proxy.proxiedAccountId}_${proxy.proxyType}`;

File: src/renderer/features/wallet-details/ui/components/ProxiesList.tsx (hunk 4 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/ui/components/ProxiesList.tsx]: FIxed, extracted isProxiesLoading, isAccountSyncPending into a single isLoading store

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts (hunk 6 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Fixed, yup, it made it way easier to read, `new Map<string, Proxy>());`

File: src/renderer/features/proxy-remove/model/remove-proxy-model.ts (hunk 7 above)
Comment (kalininilya) [reply src/renderer/features/proxy-remove/model/remove-proxy-model.ts]: Fixed the issue throughout the project, now blockNumber and extrinsicIndex are not optional in `ProxiedAccount` type

File: src/renderer/features/proxy-remove/ui/RemoveProxy.tsx (hunk 9 above)
Comment (kalininilya) [reply src/renderer/features/proxy-remove/ui/RemoveProxy.tsx]: Fixed
`const chainId = useUnit(removeProxyModel.$proxyAccount.map((proxy) => proxy?.chainId ?? null));`

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts (hunk 10 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Fixed,
`const fetchChainProxies = async (chainId: ChainId): Promise<[ChainId, Proxy[]]>`

File: src/renderer/shared/core/types/proxy.ts (hunk 5 above)
Comment (kalininilya) [reply src/renderer/shared/core/types/proxy.ts]: Removed

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts (hunk 3 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: After [this pr](https://github.com/novasamatech/nova-spektr/commit/b5b4a0357da064518ed46575467f358e59e10819) https://github.com/novasamatech/nova-spektr/blob/b5b4a0357da064518ed46575467f358e59e10819/src/renderer/shared/api/proxy/service/proxyService.ts#L29
we do not need it here anymore, removed `|| '0'`

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts (hunk 11 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts:171]: After adding `createStoreFromEffect` sync happens automatically, removed redundant refetch

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts (hunk 2 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Screenshot 2025-09-25 at 20 41 49

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts [hunk 12]
```diff
@@ -1,28 +1,34 @@
...
 import { createStoreFromEffect } from '@/shared/effector';
-import { entries, keys, nonNullable, nullable } from '@/shared/lib/utils';
-import { type AnyAccount, accountService, accounts } from '@/domains/network';
+import { keys, nonNullable } from '@/shared/lib/utils';
+import { type AnyAccount, accountService, accountSync, accounts } from '@/domains/network';
 import { networkModel, networkUtils } from '@/entities/network';
-import { accountUtils } from '@/entities/wallet';
+
+export type Proxy = Omit<ProxyAccount, 'id' | 'delay'> & { deposit: string };
+type WalletProxiesByChain = Record<ChainId, Proxy[]>;
```
Comment (valentunn) [inline src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Looks like one issue still remains:
Deposit is not something that belongs to an individual proxy but rather is a single value for all proxies for the given account on the given chain.
Thus, I suggest to define types like the following
``` ts
type Proxy = Omit<ProxyAccount, 'id' | 'delay'>;
type ChainProxies = { proxies: Proxy[], deposit: string }
type WalletProxiesByChain = Record<Chain, ChainProxies>
```

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts [hunk 13]
```diff
@@ -65,7 +72,16 @@ const { $: $walletProxies } = createStoreFromEffect<
...
+      const allProxies = accountsProxies.flat().filter(nonNullable);
+      const uniqueProxies = allProxies.reduce((acc, proxy) => {
+        const key = `${proxy.accountId}_${proxy.proxiedAccountId}_${proxy.proxyType}`;
+        if (!acc.has(key)) {
+          acc.set(key, proxy);
+        }
+        return acc;
+      }, new Map<string, Proxy>());
+
+      return [chainId, Array.from(uniqueProxies.values())];
```
Comment (valentunn) [inline src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: I suggest to extract this to a separate function to make this store easier to read as it is rather big now

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts [hunk 14]
```diff
@@ -1,28 +1,34 @@
...
 const flow = createGate<{ wallet: Wallet | null }>({ defaultState: { wallet: null } });
 
 const $wallet = flow.state.map(({ wallet }) => wallet);
 
-const { $: $walletProxies } = createStoreFromEffect<
+const {
+  $: $walletProxies,
+  fx: _fetchWalletProxiesFx,
+  $pending: $walletProxiesPending,
+} = createStoreFromEffect<
```
Comment (valentunn) [inline src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: This is still not a subscription. We should subscribe proxies on each chain instead of `getProxiesForAccount`. I suggest to ask @johnthecat how to achieve that.
If we dont do this, there will always be bugs about "proxy list is not up-to-date after X"

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts (hunk 12 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Moved deposit to a chain group level instead of individual proxy: 
```
export type Proxy = Omit<ProxyAccount, 'id' | 'delay'>;

type ChainProxies = { proxies: Proxy[]; deposit: string | null };

type WalletProxiesByChain = Record<ChainId, ChainProxies>;
```

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts (hunk 13 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Exctracted into `deduplicateProxies`

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts (hunk 14 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Spoke with @johnthecat and refactored it to `createSubscriptionResource` and `subscribeToChainsFx`

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts [hunk 15]
```diff
@@ -1,135 +1,221 @@
...
-          console.log(`Failed to fetch proxies for account ${account.accountId} on chain ${chainId}:`, error);
-          return [];
+          console.error(`Failed to fetch proxies for account ${account} on chain ${chain.chainId}:`, error);
         }
-      });
+      }
 
-      const accountsProxies = await Promise.all(accountProxiesPromises);
-      return [chainId, accountsProxies.flat().filter(nonNullable)];
+      const uniqueProxies = deduplicateProxies(allProxies);
```
Comment (valentunn) [inline src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Nit: I don't know how it is possible that proxies returned from the chain can be dublicated. Maybe dublicated was caused by some other issue we dont have anymire since we switched to subscription? In this case, we can drop dedublication entirely

**Review by valentunn — APPROVED** [review]

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts [hunk 16]
```diff
@@ -1,135 +1,208 @@
...
+          const mappedProxies = proxies.map(proxy => ({
+            accountId: proxy.delegate.toString() as AccountId,
+            proxiedAccountId: account,
+            chainId: chain.chainId,
+            proxyType: proxy.proxyType.toString() as ProxyType,
           }));
+
+          allProxies.push(...mappedProxies);
+
+          if (!deposit) {
```
Comment (johnthecat) [inline src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: sum deposit instead of overriding it every time

Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Fixed

File: src/renderer/features/wallet-details/model/wallet-proxies-model.ts (hunk 15 above)
Comment (kalininilya) [reply src/renderer/features/wallet-details/model/wallet-proxies-model.ts]: Yup, can't reproduce this case with deduplication anymore, removed
