### PR TITLE
fix: multishard revote

### LINKED ISSUE #2420: Governance. Multishard wallet. Revote flow contains all accounts
## Description

When user try to revote on multishard - the list of accounts contains all accounts. Technically there is no difference between vote and revote.

https://github.com/user-attachments/assets/431d55fe-9a58-4842-a3f3-60a47efd5c90

## Steps to Reproduce

1. Select multishard wallet
2. Vote as 1 of accounts
3. Click revote

## Expected Behavior
Revote flow contains only voted accounts

## Actual Behavior
Revote flow contains all available accounts

## Environment
https://github.com/novasamatech/nova-spektr/commit/f2b5fa27de10af054b2d8239bf5c8049eb7fb5c0

### LINKED ISSUE #2430: Governance. Voted via {address} does not shows any more
## Description

When user delegate his votes to someone it should show votes via delegate.

Screenshot 2024-10-09 at 10 59 13

test data:
[accounts.json](https://github.com/user-attachments/files/17304551/accounts.json)
[wallets.json](https://github.com/user-attachments/files/17304552/wallets.json)

## Steps to Reproduce

1. Select 123 wallet from test data
2. Go to Governance page
3. Select Polkadot

## Expected Behavior
Shows referenda for which voted by itself and voted via delegate

## Actual Behavior
Does not show voted via delegate

## Environment
https://github.com/novasamatech/nova-spektr/commit/d6565f11343c98b8c79ca63d8132292d199b1c6e

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #2420 
Closes #2430

### CODE REVIEW

File: src/renderer/widgets/VoteModal/ui/formFields/AccountsSelector.tsx [hunk 1]
```diff
@@ -34,15 +35,16 @@ export const AccountsSelector = ({ value, accounts, asset, chain, hasError, erro
...
-                type="short"
+            <div className="flex w-full items-center justify-between gap-2 text-start text-body" key={account.id}>
+              <Address
                 address={address}
-                name={isShard ? toShortAddress(address, 16) : account.name}
+                variant="truncate"
+                showIcon
+                iconSize={16}
                 canCopy={false}
+                title={isShard ? undefined : account.name}
```
Comment (sokolova-an) [inline src/renderer/widgets/VoteModal/ui/formFields/AccountsSelector.tsx]: why if `isShard` then undefined? Shards also can have names and now we usually try to show that names

**Review by sokolova-an — APPROVED** [review]
