### PR TITLE
fix: wallet details address

### LINKED ISSUE #2416: Wallet details. Address representation in different chains is broken
## Description

Screenshot 2024-10-07 at 17 31 56

## Expected Behavior

Shows address in chain format - 13mAjFVjFDpfa42k2dLdSnUyrSzK8vAySsoudnxX2EKVtfaq

## Actual Behavior

Shows in ss58=42

Found for:
- WalletConnect
- Watch only

## Environment
https://github.com/novasamatech/nova-spektr/commit/f2b5fa27de10af054b2d8239bf5c8049eb7fb5c0

### PR DESCRIPTION
**Pull request by sokolova-an**

### CODE REVIEW

File: src/renderer/shared/ui-entities/AccountExplorer/AccountExplorers.tsx [hunk 1]
```diff
@@ -8,14 +8,14 @@ import { Box, Popover } from '@/shared/ui-kit';
 import { Hash } from '../Hash/Hash';
 
 type Props = PropsWithChildren<{
-  account: AccountId;
+  accountId: AccountId;
   chain: Chain;
 }>;
 
-export const AccountExplorers = memo<Props>(({ account, chain, children }) => {
+export const AccountExplorers = memo(({ accountId, chain, children }: Props) => {
```
Comment (johnthecat) [inline src/renderer/shared/ui-entities/AccountExplorer/AccountExplorers.tsx:15]: Generic argument looks better imo

**Review by johnthecat — APPROVED** [review]

File: src/renderer/shared/ui-entities/AccountExplorer/AccountExplorers.tsx (hunk 1 above)
Comment (sokolova-an) [reply src/renderer/shared/ui-entities/AccountExplorer/AccountExplorers.tsx:15]: In this case, you can't see the required props directly, it looks like: `AccountExplorers: NamedExoticComponent<Props>`. It's more convenient to view the props upfront, as in `AccountExplorers: MemoExoticComponent<({ accountId, chain, children }: Props) => JSX.Element>`, without needing to look inside the component.
