### PR TITLE
Fix/salary fixes

### LINKED ISSUE #4793: My profile. Salary widget
Image

beneficiary - locally stored

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
Some salary fixes according to #4793

## Related Issues
Closes #4793 and #4899

## Changes Made
Fixed icons and margins
Fixed text content
Fixed button visibility conditions
Added rank sufficiency check

## Screenshots/Recordings
Снимок экрана 2025-10-24 в 18 53 07
Снимок экрана 2025-10-24 в 18 53 20

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

**Review by johnthecat — APPROVED** [review]

**Review by cuteWarmFrog — APPROVED** [review]

File: src/renderer/domains/collectives/salary/service.ts [hunk 1]
```diff
@@ -139,16 +139,12 @@ function isSalaryInductTransaction(transaction: Transaction): transaction is Sal
   return transaction.type === TransactionType.COLLECTIVE_SALARY_INDUCT;
 }
 
-function isClaimantActiveInCurrentCycle(claimStatus: ClaimStatus, period: SalaryCyclePeriod) {
-  return claimStatus.lastActive === period.cycleIndex;
+function isClaimantRequestedSalary(claimStatus: ClaimStatus) {
+  return claimStatus && claimStatus.type === 'registered';
 }
```
Comment (aaa123eee) [inline src/renderer/domains/collectives/salary/service.ts]: if it is nullable then we can maybe reflect it in the types here or handle the emptiness outside of this function

File: src/renderer/domains/collectives/salary/service.ts [hunk 2]
```diff
@@ -139,16 +139,12 @@ function isSalaryInductTransaction(transaction: Transaction): transaction is Sal
...
 
-function isClaimantRequestedSalary(claimStatus: ClaimStatus, period: SalaryCyclePeriod) {
-  return isClaimantActiveInCurrentCycle(claimStatus, period) && claimStatus && claimStatus.type === 'registered';
-}
-
-function isClaimantRequestedSalaryPayout(claimStatus: ClaimStatus, period: SalaryCyclePeriod) {
-  return isClaimantActiveInCurrentCycle(claimStatus, period) && claimStatus && claimStatus.type === 'payout';
+function isClaimantRequestedSalaryPayout(claimStatus: ClaimStatus) {
+  return claimStatus && claimStatus.type === 'payout';
```
Comment (aaa123eee) [inline src/renderer/domains/collectives/salary/service.ts]: same here

File: src/renderer/domains/collectives/salary/service.ts [hunk 3]
```diff
@@ -157,19 +153,18 @@ function isInducted(claimStatus: ClaimStatus) {
...
   );
 }
 
 function canRequestSalaryPayout(claimStatus: ClaimStatus, period: SalaryCyclePeriod) {
   return (
-    isClaimantActiveInCurrentCycle(claimStatus, period) &&
     period.type === 'payout' &&
-    claimStatus.type !== 'payout' &&
-    claimStatus.type !== 'none'
+    ((claimStatus.type === 'registered' && claimStatus.lastActive === period.cycleIndex) ||
```
Comment (aaa123eee) [inline src/renderer/domains/collectives/salary/service.ts:153]: is it the same as `isClaimantRequestedSalary`?

File: src/renderer/domains/collectives/salary/service.ts (hunk 1 above)
Comment (Yanaty) [reply src/renderer/domains/collectives/salary/service.ts]: deleted this function as unnecessary

File: src/renderer/domains/collectives/salary/service.ts (hunk 2 above)
Comment (Yanaty) [reply src/renderer/domains/collectives/salary/service.ts]: deleted this function as unnecessary

File: src/renderer/domains/collectives/salary/service.ts (hunk 3 above)
Comment (Yanaty) [reply src/renderer/domains/collectives/salary/service.ts:153]: deleted this function as unnecessary
