### PR TITLE
fix: completed referendum empty timeline

### LINKED ISSUE #2040: Governance. Timeline section does not show time-out time
## Description

Timeline section. Should not be empty, if there is no off-line data it should show data, based on on-chain data.

Screenshot 2024-08-07 at 09 52 56

on-chain data for this referenda:
Screenshot 2024-08-07 at 10 00 04

In Nova Wallet its shown:

IMAGE 2024-08-07 10:01:00

## Steps to Reproduce

1. Go to Governance page
2. Open Referenda without off-chain data

## Expected Behavior
Shows on-chain data

## Actual Behavior
Shows empty plate

## Environment
https://github.com/novasamatech/nova-spektr/commit/74fb677ee2dd26a02c67eeb6860265cc9bea9add

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #2040

### CODE REVIEW

File: src/renderer/features/governance/model/timeline.ts [hunk 1]
```diff
@@ -1,13 +1,40 @@
...
+  type Referendum,
+  type ReferendumId,
+  ReferendumType,
+} from '@shared/core';
+import { getCreatedDateFromApi, nonNullable, setNestedValue } from '@shared/lib/utils';
+import { governanceModel, referendumService } from '@entities/governance';
 
 import { networkSelectorModel } from './networkSelector';
 
+const mapReferendumToTimelineStatus = (referendum: CompletedReferendum): ReferendumTimelineRecordStatus => {
```
Comment (Asmadek) [inline src/renderer/features/governance/model/timeline.ts]: What about use object instead of switch?

**Review by Asmadek — APPROVED** [review]

**Review by pgolovkin — APPROVED** [review]

**Review by sokolova-an — APPROVED** [review]
