### PR TITLE
Fix: Remove vote

### LINKED ISSUE #3306: Governance. Multishard. Remove vote lead to crash
## Description

When user click "Remove vote" on test database state - app fall down with error. Wallet was added properly, via Polkadot Vault with erase database step.

## Test data

[spektr-database.json](https://github.com/user-attachments/files/19160261/spektr-database.json)

## Steps to Reproduce

1. Set test data
2. Go to referenda Polkadot referendum 1426
3. Click Remove vote

## Expected Behavior
Open remove vote flow

## Actual Behavior
App fall down

```
hook.js:608 TypeError: Cannot read properties of null (reading 'walletId')
    at combine.and (removeVotesModal.ts:71:57)
    at t2 (chunk-LB6HJBS6.js?v=35dd5861:251:18)
    at Oe (chunk-LB6HJBS6.js?v=35dd5861:661:30)
    at gt (chunk-LB6HJBS6.js?v=35dd5861:786:12)
    at o (chunk-LB6HJBS6.js?v=35dd5861:105:68)
    at Function.create (chunk-LB6HJBS6.js?v=35dd5861:186:169)
    at Object.i2 [as open] (chunk-LB6HJBS6.js?v=35dd5861:186:27)
    at chunk-63I4SB2U.js?v=35dd5861:102:15
    at commitHookEffectListMount (chunk-SLTJZ3ND.js?v=35dd5861:23841:34)
    at commitLayoutEffectOnFiber (chunk-SLTJZ3ND.js?v=35dd5861:23928:23) Error Component Stack
    at RemoveVotesModal (RemoveVotesModal.tsx:47:36)
    at GovernanceReferendumDetails (GovernanceReferendumDetails.tsx:17:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at div (<anonymous>)
    at Box.tsx:62:7
    at GovernanceReferendumList (GovernanceReferendumList.tsx:15:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at div (<anonymous>)
    at Box.tsx:62:7
    at div (<anonymous>)
    at Box.tsx:62:7
    at div (<anonymous>)
    at div (<anonymous>)
    at @radix-ui_react-scroll-area.js?v=35dd5861:176:13
    at @radix-ui_react-scroll-area.js?v=35dd5861:407:13
    at div (<anonymous>)
    at @radix-ui_react-scroll-area.js?v=35dd5861:176:13
    at Provider (chunk-YEPHIBGK.js?v=35dd5861:51:15)
    at @radix-ui_react-scroll-area.js?v=35dd5861:345:7
    at ScrollArea.tsx:25:35
    at div (<anonymous>)
    at Governance (Governance.tsx:29:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at main (<anonymous>)
    at div (<anonymous>)
    at _c (AppShell.tsx:11:9)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at ApolloProvider (@apollo_client.js?v=35dd5861:6485:19)
    at GraphqlProvider (GraphqlContext.tsx:48:35)
    at StatusModalProvider (StatusContext.tsx:34:39)
    at ConfirmDialogProvider (ConfirmContext.tsx:40:41)
    at MultisigChainProvider (MultisigChainContext.tsx:26:41)
    at App (App.tsx:19:20)
    at Wrapper (DelayedSuspense.tsx:10:24)
    at Suspense (<anonymous>)
    at ErrorBoundary (react-error-boundary.js?v=35dd5861:31:5)
    at I18Provider (I18nContext.tsx:35:31)
    at Router (react-router-dom.js?v=35dd5861:4484:15)
    at HashRouter (react-router-dom.js?v=35dd5861:5262:5)
    at div (<anonymous>)
    at ThemeProvider (ThemeProvider.tsx:11:33)
    at Root (index.tsx:57:55)
overrideMethod @ hook.js:608
gt @ chunk-LB6HJBS6.js?v=35dd5861:788
o @ chunk-LB6HJBS6.js?v=35dd5861:105
create @ chunk-LB6HJBS6.js?v=35dd5861:186
i2 @ chunk-LB6HJBS6.js?v=35dd5861:186
(anonymous) @ chunk-63I4SB2U.js?v=35dd5861:102
commitHookEffectListMount @ chunk-SLTJZ3ND.js?v=35dd5861:23841
commitLayoutEffectOnFiber @ chunk-SLTJZ3ND.js?v=35dd5861:23928
commitLayoutMountEffects_complete @ chunk-SLTJZ3ND.js?v=35dd5861:24908
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24897
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects @ chunk-SLTJZ3ND.js?v=35dd5861:24848
commitRootImpl @ chunk-SLTJZ3ND.js?v=35dd5861:26284
commitRoot @ chunk-SLTJZ3ND.js?v=35dd5861:26208
performSyncWorkOnRoot @ chunk-SLTJZ3ND.js?v=35dd5861:25826
flushSyncCallbacks @ chunk-SLTJZ3ND.js?v=35dd5861:16044
(anonymous) @ chunk-SLTJZ3ND.js?v=35dd5861:25555
Show 20 more frames
Show less
hook.js:608 TypeError: Cannot read properties of null (reading 'accountId')
    at removeVotesModal.ts:101:68
    at Array.filter (<anonymous>)
    at removeVotesModal.ts:101:18
    at Array.map (<anonymous>)
    at combine.and (removeVotesModal.ts:100:19)
    at t2 (chunk-LB6HJBS6.js?v=35dd5861:251:18)
    at Oe (chunk-LB6HJBS6.js?v=35dd5861:661:30)
    at gt (chunk-LB6HJBS6.js?v=35dd5861:786:12)
    at o (chunk-LB6HJBS6.js?v=35dd5861:105:68)
    at Function.create (chunk-LB6HJBS6.js?v=35dd5861:186:169) Error Component Stack
    at RemoveVotesModal (RemoveVotesModal.tsx:47:36)
    at GovernanceReferendumDetails (GovernanceReferendumDetails.tsx:17:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at div (<anonymous>)
    at Box.tsx:62:7
    at GovernanceReferendumList (GovernanceReferendumList.tsx:15:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at div (<anonymous>)
    at Box.tsx:62:7
    at div (<anonymous>)
    at Box.tsx:62:7
    at div (<anonymous>)
    at div (<anonymous>)
    at @radix-ui_react-scroll-area.js?v=35dd5861:176:13
    at @radix-ui_react-scroll-area.js?v=35dd5861:407:13
    at div (<anonymous>)
    at @radix-ui_react-scroll-area.js?v=35dd5861:176:13
    at Provider (chunk-YEPHIBGK.js?v=35dd5861:51:15)
    at @radix-ui_react-scroll-area.js?v=35dd5861:345:7
    at ScrollArea.tsx:25:35
    at div (<anonymous>)
    at Governance (Governance.tsx:29:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at main (<anonymous>)
    at div (<anonymous>)
    at _c (AppShell.tsx:11:9)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at ApolloProvider (@apollo_client.js?v=35dd5861:6485:19)
    at GraphqlProvider (GraphqlContext.tsx:48:35)
    at StatusModalProvider (StatusContext.tsx:34:39)
    at ConfirmDialogProvider (ConfirmContext.tsx:40:41)
    at MultisigChainProvider (MultisigChainContext.tsx:26:41)
    at App (App.tsx:19:20)
    at Wrapper (DelayedSuspense.tsx:10:24)
    at Suspense (<anonymous>)
    at ErrorBoundary (react-error-boundary.js?v=35dd5861:31:5)
    at I18Provider (I18nContext.tsx:35:31)
    at Router (react-router-dom.js?v=35dd5861:4484:15)
    at HashRouter (react-router-dom.js?v=35dd5861:5262:5)
    at div (<anonymous>)
    at ThemeProvider (ThemeProvider.tsx:11:33)
    at Root (index.tsx:57:55)
overrideMethod @ hook.js:608
gt @ chunk-LB6HJBS6.js?v=35dd5861:788
o @ chunk-LB6HJBS6.js?v=35dd5861:105
create @ chunk-LB6HJBS6.js?v=35dd5861:186
i2 @ chunk-LB6HJBS6.js?v=35dd5861:186
(anonymous) @ chunk-63I4SB2U.js?v=35dd5861:102
commitHookEffectListMount @ chunk-SLTJZ3ND.js?v=35dd5861:23841
commitLayoutEffectOnFiber @ chunk-SLTJZ3ND.js?v=35dd5861:23928
commitLayoutMountEffects_complete @ chunk-SLTJZ3ND.js?v=35dd5861:24908
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24897
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects @ chunk-SLTJZ3ND.js?v=35dd5861:24848
commitRootImpl @ chunk-SLTJZ3ND.js?v=35dd5861:26284
commitRoot @ chunk-SLTJZ3ND.js?v=35dd5861:26208
performSyncWorkOnRoot @ chunk-SLTJZ3ND.js?v=35dd5861:25826
flushSyncCallbacks @ chunk-SLTJZ3ND.js?v=35dd5861:16044
(anonymous) @ chunk-SLTJZ3ND.js?v=35dd5861:25555
Show 20 more frames
Show less
hook.js:608 TypeError: Cannot read properties of null (reading 'accountId')
    at removeVotesModal.ts:124:27
    at Array.map (<anonymous>)
    at combine.and (removeVotesModal.ts:122:19)
    at t2 (chunk-LB6HJBS6.js?v=35dd5861:251:18)
    at Oe (chunk-LB6HJBS6.js?v=35dd5861:661:30)
    at gt (chunk-LB6HJBS6.js?v=35dd5861:786:12)
    at o (chunk-LB6HJBS6.js?v=35dd5861:105:68)
    at Function.create (chunk-LB6HJBS6.js?v=35dd5861:186:169)
    at Object.i2 [as open] (chunk-LB6HJBS6.js?v=35dd5861:186:27)
    at chunk-63I4SB2U.js?v=35dd5861:102:15 Error Component Stack
    at RemoveVotesModal (RemoveVotesModal.tsx:47:36)
    at GovernanceReferendumDetails (GovernanceReferendumDetails.tsx:17:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at div (<anonymous>)
    at Box.tsx:62:7
    at GovernanceReferendumList (GovernanceReferendumList.tsx:15:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at div (<anonymous>)
    at Box.tsx:62:7
    at div (<anonymous>)
    at Box.tsx:62:7
    at div (<anonymous>)
    at div (<anonymous>)
    at @radix-ui_react-scroll-area.js?v=35dd5861:176:13
    at @radix-ui_react-scroll-area.js?v=35dd5861:407:13
    at div (<anonymous>)
    at @radix-ui_react-scroll-area.js?v=35dd5861:176:13
    at Provider (chunk-YEPHIBGK.js?v=35dd5861:51:15)
    at @radix-ui_react-scroll-area.js?v=35dd5861:345:7
    at ScrollArea.tsx:25:35
    at div (<anonymous>)
    at Governance (Governance.tsx:29:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at main (<anonymous>)
    at div (<anonymous>)
    at _c (AppShell.tsx:11:9)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at ApolloProvider (@apollo_client.js?v=35dd5861:6485:19)
    at GraphqlProvider (GraphqlContext.tsx:48:35)
    at StatusModalProvider (StatusContext.tsx:34:39)
    at ConfirmDialogProvider (ConfirmContext.tsx:40:41)
    at MultisigChainProvider (MultisigChainContext.tsx:26:41)
    at App (App.tsx:19:20)
    at Wrapper (DelayedSuspense.tsx:10:24)
    at Suspense (<anonymous>)
    at ErrorBoundary (react-error-boundary.js?v=35dd5861:31:5)
    at I18Provider (I18nContext.tsx:35:31)
    at Router (react-router-dom.js?v=35dd5861:4484:15)
    at HashRouter (react-router-dom.js?v=35dd5861:5262:5)
    at div (<anonymous>)
    at ThemeProvider (ThemeProvider.tsx:11:33)
    at Root (index.tsx:57:55)
overrideMethod @ hook.js:608
gt @ chunk-LB6HJBS6.js?v=35dd5861:788
o @ chunk-LB6HJBS6.js?v=35dd5861:105
create @ chunk-LB6HJBS6.js?v=35dd5861:186
i2 @ chunk-LB6HJBS6.js?v=35dd5861:186
(anonymous) @ chunk-63I4SB2U.js?v=35dd5861:102
commitHookEffectListMount @ chunk-SLTJZ3ND.js?v=35dd5861:23841
commitLayoutEffectOnFiber @ chunk-SLTJZ3ND.js?v=35dd5861:23928
commitLayoutMountEffects_complete @ chunk-SLTJZ3ND.js?v=35dd5861:24908
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24897
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects @ chunk-SLTJZ3ND.js?v=35dd5861:24848
commitRootImpl @ chunk-SLTJZ3ND.js?v=35dd5861:26284
commitRoot @ chunk-SLTJZ3ND.js?v=35dd5861:26208
performSyncWorkOnRoot @ chunk-SLTJZ3ND.js?v=35dd5861:25826
flushSyncCallbacks @ chunk-SLTJZ3ND.js?v=35dd5861:16044
(anonymous) @ chunk-SLTJZ3ND.js?v=35dd5861:25555
Show 20 more frames
Show less
hook.js:608 TypeError: Cannot read properties of null (reading 'accountId')
    at removeVotesModal.ts:237:70
    at Array.filter (<anonymous>)
    at removeVotesModal.ts:237:20
    at Array.map (<anonymous>)
    at fn (removeVotesModal.ts:230:21)
    at Re (chunk-LB6HJBS6.js?v=35dd5861:659:41)
    at gt (chunk-LB6HJBS6.js?v=35dd5861:786:12)
    at o (chunk-LB6HJBS6.js?v=35dd5861:105:68)
    at Function.create (chunk-LB6HJBS6.js?v=35dd5861:186:169)
    at Object.i2 [as open] (chunk-LB6HJBS6.js?v=35dd5861:186:27) Error Component Stack
    at RemoveVotesModal (RemoveVotesModal.tsx:47:36)
    at GovernanceReferendumDetails (GovernanceReferendumDetails.tsx:17:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at div (<anonymous>)
    at Box.tsx:62:7
    at GovernanceReferendumList (GovernanceReferendumList.tsx:15:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at div (<anonymous>)
    at Box.tsx:62:7
    at div (<anonymous>)
    at Box.tsx:62:7
    at div (<anonymous>)
    at div (<anonymous>)
    at @radix-ui_react-scroll-area.js?v=35dd5861:176:13
    at @radix-ui_react-scroll-area.js?v=35dd5861:407:13
    at div (<anonymous>)
    at @radix-ui_react-scroll-area.js?v=35dd5861:176:13
    at Provider (chunk-YEPHIBGK.js?v=35dd5861:51:15)
    at @radix-ui_react-scroll-area.js?v=35dd5861:345:7
    at ScrollArea.tsx:25:35
    at div (<anonymous>)
    at Governance (Governance.tsx:29:3)
    at Suspense (<anonymous>)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (react-router-dom.js?v=35dd5861:4477:26)
    at main (<anonymous>)
    at div (<anonymous>)
    at _c (AppShell.tsx:11:9)
    at RenderedRoute (react-router-dom.js?v=35dd5861:4102:5)
    at ApolloProvider (@apollo_client.js?v=35dd5861:6485:19)
    at GraphqlProvider (GraphqlContext.tsx:48:35)
    at StatusModalProvider (StatusContext.tsx:34:39)
    at ConfirmDialogProvider (ConfirmContext.tsx:40:41)
    at MultisigChainProvider (MultisigChainContext.tsx:26:41)
    at App (App.tsx:19:20)
    at Wrapper (DelayedSuspense.tsx:10:24)
    at Suspense (<anonymous>)
    at ErrorBoundary (react-error-boundary.js?v=35dd5861:31:5)
    at I18Provider (I18nContext.tsx:35:31)
    at Router (react-router-dom.js?v=35dd5861:4484:15)
    at HashRouter (react-router-dom.js?v=35dd5861:5262:5)
    at div (<anonymous>)
    at ThemeProvider (ThemeProvider.tsx:11:33)
    at Root (index.tsx:57:55)
overrideMethod @ hook.js:608
gt @ chunk-LB6HJBS6.js?v=35dd5861:788
o @ chunk-LB6HJBS6.js?v=35dd5861:105
create @ chunk-LB6HJBS6.js?v=35dd5861:186
i2 @ chunk-LB6HJBS6.js?v=35dd5861:186
(anonymous) @ chunk-63I4SB2U.js?v=35dd5861:102
commitHookEffectListMount @ chunk-SLTJZ3ND.js?v=35dd5861:23841
commitLayoutEffectOnFiber @ chunk-SLTJZ3ND.js?v=35dd5861:23928
commitLayoutMountEffects_complete @ chunk-SLTJZ3ND.js?v=35dd5861:24908
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24897
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24878
commitLayoutEffects @ chunk-SLTJZ3ND.js?v=35dd5861:24848
commitRootImpl @ chunk-SLTJZ3ND.js?v=35dd5861:26284
commitRoot @ chunk-SLTJZ3ND.js?v=35dd5861:26208
performSyncWorkOnRoot @ chunk-SLTJZ3ND.js?v=35dd5861:25826
flushSyncCallbacks @ chunk-SLTJZ3ND.js?v=35dd5861:16044
(anonymous) @ chunk-SLTJZ3ND.js?v=35dd5861:25555
Show 20 more frames
Show less
AccountSelectModal.tsx:46 Uncaught TypeError: Cannot read properties of null (reading 'name')
    at AccountSelectModal.tsx:46:39
    at Array.map (<anonymous>)
    at AccountSelectModal (AccountSelectModal.tsx:39:20)
    at renderWithHooks (chunk-SLTJZ3ND.js?v=35dd5861:18474:26)
    at updateFunctionComponent (chunk-SLTJZ3ND.js?v=35dd5861:21508:28)
    at beginWork (chunk-SLTJZ3ND.js?v=35dd5861:22850:22)
    at HTMLUnknownElement.callCallback2 (chunk-SLTJZ3ND.js?v=35dd5861:10558:22)
    at Object.invokeGuardedCallbackDev (chunk-SLTJZ3ND.js?v=35dd5861:10583:24)
    at invokeGuardedCallback (chunk-SLTJZ3ND.js?v=35dd5861:10617:39)
    at beginWork$1 (chunk-SLTJZ3ND.js?v=35dd5861:26696:15)
(anonymous) @ AccountSelectModal.tsx:46
AccountSelectModal @ AccountSelectModal.tsx:39
renderWithHooks @ chunk-SLTJZ3ND.js?v=35dd5861:18474
updateFunctionComponent @ chunk-SLTJZ3ND.js?v=35dd5861:21508
beginWork @ chunk-SLTJZ3ND.js?v=35dd5861:22850
callCallback2 @ chunk-SLTJZ3ND.js?v=35dd5861:10558
invokeGuardedCallbackDev @ chunk-SLTJZ3ND.js?v=35dd5861:10583
invokeGuardedCallback @ chunk-SLTJZ3ND.js?v=35dd5861:10617
beginWork$1 @ chunk-SLTJZ3ND.js?v=35dd5861:26696
performUnitOfWork @ chunk-SLTJZ3ND.js?v=35dd5861:26129
workLoopSync @ chunk-SLTJZ3ND.js?v=35dd5861:26068
renderRootSync @ chunk-SLTJZ3ND.js?v=35dd5861:26047
performSyncWorkOnRoot @ chunk-SLTJZ3ND.js?v=35dd5861:25805
flushSyncCallbacks @ chunk-SLTJZ3ND.js?v=35dd5861:16044
(anonymous) @ chunk-SLTJZ3ND.js?v=35dd5861:25555
Show 13 more frames
Show less
AccountSelectModal.tsx:46 Uncaught TypeError: Cannot read properties of null (reading 'name')
    at AccountSelectModal.tsx:46:39
    at Array.map (<anonymous>)
    at AccountSelectModal (AccountSelectModal.tsx:39:20)
    at renderWithHooks (chunk-SLTJZ3ND.js?v=35dd5861:18474:26)
    at updateFunctionComponent (chunk-SLTJZ3ND.js?v=35dd5861:21508:28)
    at beginWork (chunk-SLTJZ3ND.js?v=35dd5861:22850:22)
    at HTMLUnknownElement.callCallback2 (chunk-SLTJZ3ND.js?v=35dd5861:10558:22)
    at Object.invokeGuardedCallbackDev (chunk-SLTJZ3ND.js?v=35dd5861:10583:24)
    at invokeGuardedCallback (chunk-SLTJZ3ND.js?v=35dd5861:10617:39)
    at beginWork$1 (chunk-SLTJZ3ND.js?v=35dd5861:26696:15)
(anonymous) @ AccountSelectModal.tsx:46
AccountSelectModal @ AccountSelectModal.tsx:39
renderWithHooks @ chunk-SLTJZ3ND.js?v=35dd5861:18474
updateFunctionComponent @ chunk-SLTJZ3ND.js?v=35dd5861:21508
beginWork @ chunk-SLTJZ3ND.js?v=35dd5861:22850
callCallback2 @ chunk-SLTJZ3ND.js?v=35dd5861:10558
invokeGuardedCallbackDev @ chunk-SLTJZ3ND.js?v=35dd5861:10583
invokeGuardedCallback @ chunk-SLTJZ3ND.js?v=35dd5861:10617
beginWork$1 @ chunk-SLTJZ3ND.js?v=35dd5861:26696
performUnitOfWork @ chunk-SLTJZ3ND.js?v=35dd5861:26129
workLoopSync @ chunk-SLTJZ3ND.js?v=35dd5861:26068
renderRootSync @ chunk-SLTJZ3ND.js?v=35dd5861:26047
recoverFromConcurrentError @ chunk-SLTJZ3ND.js?v=35dd5861:25664
performSyncWorkOnRoot @ chunk-SLTJZ3ND.js?v=35dd5861:25810
flushSyncCallbacks @ chunk-SLTJZ3ND.js?v=35dd5861:16044
(anonymous) @ chunk-SLTJZ3ND.js?v=35dd5861:25555
Show 14 more frames
Show less
hook.js:608 The above error occurred in the <AccountSelectModal> component:

    at AccountSelectModal (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/shared/ui-entities/AccountSelectModal/AccountSelectModal.tsx:15:38)
    at VoteAccountSelect (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/widgets/RemoveVotesModal/ui/RemoveVotesModal.tsx:243:30)
    at RemoveVotesModal (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/widgets/RemoveVotesModal/ui/RemoveVotesModal.tsx:28:36)
    at GovernanceReferendumDetails (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/pages/Governance/ui/GovernanceReferendumDetails.tsx:26:5)
    at Suspense
    at RenderedRoute (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/react-router-dom.js?v=35dd5861:4477:26)
    at div
    at https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/shared/ui-kit/Box/Box.tsx:37:63
    at GovernanceReferendumList (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/pages/Governance/ui/GovernanceReferendumList.tsx:22:5)
    at Suspense
    at RenderedRoute (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/react-router-dom.js?v=35dd5861:4477:26)
    at div
    at https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/shared/ui-kit/Box/Box.tsx:37:63
    at div
    at https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/shared/ui-kit/Box/Box.tsx:37:63
    at div
    at div
    at https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/@radix-ui_react-scroll-area.js?v=35dd5861:176:13
    at https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/@radix-ui_react-scroll-area.js?v=35dd5861:407:13
    at div
    at https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/@radix-ui_react-scroll-area.js?v=35dd5861:176:13
    at Provider (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/chunk-YEPHIBGK.js?v=35dd5861:51:15)
    at https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/@radix-ui_react-scroll-area.js?v=35dd5861:345:7
    at https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/shared/ui-kit/ScrollArea/ScrollArea.tsx:16:60
    at div
    at Governance (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/pages/Governance/ui/Governance.tsx:30:5)
    at Suspense
    at RenderedRoute (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/react-router-dom.js?v=35dd5861:4102:5)
    at Outlet (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/react-router-dom.js?v=35dd5861:4477:26)
    at main
    at div
    at _c (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/features/app-shell/components/AppShell.tsx:28:25)
    at RenderedRoute (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/react-router-dom.js?v=35dd5861:4102:5)
    at ApolloProvider (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/@apollo_client.js?v=35dd5861:6485:19)
    at GraphqlProvider (https://localhost:3000/providers/context/GraphqlContext/GraphqlContext.tsx:33:35)
    at StatusModalProvider (https://localhost:3000/providers/context/StatusContext/StatusContext.tsx:20:39)
    at ConfirmDialogProvider (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/shared/providers/ConfirmContext/ConfirmContext.tsx:23:41)
    at MultisigChainProvider (https://localhost:3000/providers/context/MultisigChainContext/MultisigChainContext.tsx:25:41)
    at App (https://localhost:3000/App.tsx:26:22)
    at Wrapper (https://localhost:3000/DelayedSuspense.tsx:18:28)
    at Suspense
    at ErrorBoundary (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/react-error-boundary.js?v=35dd5861:31:5)
    at I18Provider (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/shared/i18n/I18nContext.tsx:24:31)
    at Router (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/react-router-dom.js?v=35dd5861:4484:15)
    at HashRouter (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/node_modules/.cache/vite-renderer/deps/react-router-dom.js?v=35dd5861:5262:5)
    at div
    at ThemeProvider (https://localhost:3000/@fs/Users/stepanlavrentev/nova-spektr/src/renderer/shared/ui-kit/Theme/ThemeProvider.tsx:13:33)
    at Root (https://localhost:3000/index.tsx:56:57)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
overrideMethod @ hook.js:608
logCapturedError @ chunk-SLTJZ3ND.js?v=35dd5861:20958
callback @ chunk-SLTJZ3ND.js?v=35dd5861:21004
callCallback @ chunk-SLTJZ3ND.js?v=35dd5861:18174
commitUpdateQueue @ chunk-SLTJZ3ND.js?v=35dd5861:18191
commitLayoutEffectOnFiber @ chunk-SLTJZ3ND.js?v=35dd5861:24001
commitLayoutMountEffects_complete @ chunk-SLTJZ3ND.js?v=35dd5861:24908
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24897
commitLayoutEffects @ chunk-SLTJZ3ND.js?v=35dd5861:24848
commitRootImpl @ chunk-SLTJZ3ND.js?v=35dd5861:26284
commitRoot @ chunk-SLTJZ3ND.js?v=35dd5861:26208
performSyncWorkOnRoot @ chunk-SLTJZ3ND.js?v=35dd5861:25826
flushSyncCallbacks @ chunk-SLTJZ3ND.js?v=35dd5861:16044
(anonymous) @ chunk-SLTJZ3ND.js?v=35dd5861:25555
Show 14 more frames
Show less
hook.js:608 TypeError: Cannot read properties of null (reading 'name')
    at AccountSelectModal.tsx:46:39
    at Array.map (<anonymous>)
    at AccountSelectModal (AccountSelectModal.tsx:39:20)
    at renderWithHooks (chunk-SLTJZ3ND.js?v=35dd5861:18474:26)
    at updateFunctionComponent (chunk-SLTJZ3ND.js?v=35dd5861:21508:28)
    at beginWork (chunk-SLTJZ3ND.js?v=35dd5861:22850:22)
    at beginWork$1 (chunk-SLTJZ3ND.js?v=35dd5861:26684:22)
    at performUnitOfWork (chunk-SLTJZ3ND.js?v=35dd5861:26129:20)
    at workLoopSync (chunk-SLTJZ3ND.js?v=35dd5861:26068:13)
    at renderRootSync (chunk-SLTJZ3ND.js?v=35dd5861:26047:15) {componentStack: '\n    at AccountSelectModal (https://localhost:3000… at Root (https://localhost:3000/index.tsx:56:57)'} Error Component Stack
    at ErrorBoundary (react-error-boundary.js?v=35dd5861:31:5)
    at I18Provider (I18nContext.tsx:35:31)
    at Router (react-router-dom.js?v=35dd5861:4484:15)
    at HashRouter (react-router-dom.js?v=35dd5861:5262:5)
    at div (<anonymous>)
    at ThemeProvider (ThemeProvider.tsx:11:33)
    at Root (index.tsx:57:55)
overrideMethod @ hook.js:608
componentDidCatch @ react-error-boundary.js?v=35dd5861:59
callback @ chunk-SLTJZ3ND.js?v=35dd5861:21010
callCallback @ chunk-SLTJZ3ND.js?v=35dd5861:18174
commitUpdateQueue @ chunk-SLTJZ3ND.js?v=35dd5861:18191
commitLayoutEffectOnFiber @ chunk-SLTJZ3ND.js?v=35dd5861:24001
commitLayoutMountEffects_complete @ chunk-SLTJZ3ND.js?v=35dd5861:24908
commitLayoutEffects_begin @ chunk-SLTJZ3ND.js?v=35dd5861:24897
commitLayoutEffects @ chunk-SLTJZ3ND.js?v=35dd5861:24848
commitRootImpl @ chunk-SLTJZ3ND.js?v=35dd5861:26284
commitRoot @ chunk-SLTJZ3ND.js?v=35dd5861:26208
performSyncWorkOnRoot @ chunk-SLTJZ3ND.js?v=35dd5861:25826
flushSyncCallbacks @ chunk-SLTJZ3ND.js?v=35dd5861:16044
(anonymous) @ chunk-SLTJZ3ND.js?v=35dd5861:25555
Show 14 more frames
Show less
chunk-XXNUTBCH.js?v=35dd5861:1238 WebSocket connection to 'wss://kusama.imbuenetwork.com/' failed: 
connect @ chunk-XXNUTBCH.js?v=35dd5861:1238
connectWithRetry @ chunk-XXNUTBCH.js?v=35dd5861:1260
(anonymous) @ chunk-XXNUTBCH.js?v=35dd5861:1050
Show 3 more frames
Show less
hook.js:608 2025-03-10 13:14:07          API-WS: disconnected from wss://kusama.imbuenetwork.com: 1006:: Abnormal Closure
overrideMethod @ hook.js:608
apply @ chunk-QQB3QV24.js?v=35dd5861:2059
error @ chunk-QQB3QV24.js?v=35dd5861:2091
(anonymous) @ chunk-XXNUTBCH.js?v=35dd5861:1024
Show 4 more frames
Show less
chunk-XXNUTBCH.js?v=35dd5861:1238 WebSocket connection to 'wss://kusama.imbuenetwork.com/' failed: 
connect @ chunk-XXNUTBCH.js?v=35dd5861:1238
connectWithRetry @ chunk-XXNUTBCH.js?v=35dd5861:1260
(anonymous) @ chunk-XXNUTBCH.js?v=35dd5861:1050
Show 3 more frames
Show less
hook.js:608 2025-03-10 13:14:14          API-WS: disconnected from wss://kusama.imbuenetwork.com: 1006:: Abnormal Closure
overrideMethod @ hook.js:608
apply @ chunk-QQB3QV24.js?v=35dd5861:2059
error @ chunk-QQB3QV24.js?v=35dd5861:2091
(anonymous) @ chunk-XXNUTBCH.js?v=35dd5861:1024
Show 4 more frames
Show less
chunk-XXNUTBCH.js?v=35dd5861:1238 WebSocket connection to 'wss://kusama.imbuenetwork.com/' failed: 
connect @ chunk-XXNUTBCH.js?v=35dd5861:1238
connectWithRetry @ chunk-XXNUTBCH.js?v=35dd5861:1260
(anonymous) @ chunk-XXNUTBCH.js?v=35dd5861:1050
Show 3 more frames
Show less
hook.js:608 2025-03-10 13:14:21          API-WS: disconnected from wss://kusama.imbuenetwork.com: 1006:: Abnormal Closure
overrideMethod @ hook.js:608
apply @ chunk-QQB3QV24.js?v=35dd5861:2059
error @ chunk-QQB3QV24.js?v=35dd5861:2091
(anonymous) @ chunk-XXNUTBCH.js?v=35dd5861:1024
Show 4 more frames
Show less
chunk-XXNUTBCH.js?v=35dd5861:1238 WebSocket connection to 'wss://kusama.imbuenetwork.com/' failed: 
connect @ chunk-XXNUTBCH.js?v=35dd5861:1238
connectWithRetry @ chunk-XXNUTBCH.js?v=35dd5861:1260
(anonymous) @ chunk-XXNUTBCH.js?v=35dd5861:1050
Show 3 more frames
Show less
hook.js:608 2025-03-10 13:14:28          API-WS: disconnected from wss://kusama.imbuenetwork.com: 1006:: Abnormal Closure
overrideMethod @ hook.js:608
apply @ chunk-QQB3QV24.js?v=35dd5861:2059
error @ chunk-QQB3QV24.js?v=35dd5861:2091
(anonymous) @ chunk-XXNUTBCH.js?v=35dd5861:1024
Show 4 more frames
Show less
```

## Environment
https://github.com/novasamatech/nova-spektr/commit/ff1c99c626c8021baac273f983986f9396416084

### PR DESCRIPTION
**Pull request by tuul-wq**
- Use `accountId` instead of address

closes #3306

### CODE REVIEW

File: src/renderer/pages/Governance/aggregates/governancePage.ts [hunk 1]
```diff
@@ -72,7 +72,7 @@ sample({
   filter: ({ network, wallet }) => nonNullable(network) && nonNullable(wallet),
   fn: ({ network, wallet }) => ({
     api: network!.api,
-    addresses: accountUtils.getAddressesForWallet(wallet!, network!.chain),
+    accounts: accountUtils.getAccountsIdsForWallet(wallet!, network!.chain),
```
Comment (tuul-wq) [inline src/renderer/pages/Governance/aggregates/governancePage.ts:75]: `votingAggregate.events.requestVoting` expects `accounts` not `addresses`

**Review by aaa123eee — APPROVED** [review]

**Review by sokolova-an — APPROVED** [review]
