### PR TITLE
fix: proxy identity timeout

### LINKED ISSUE #3529: Proxy. Won't create wallet when add a proxy
## Description

When user add proxy for PV wallet, the proxy won't be created as a wallet in the app

## Test data

[proxy_has_account.json](https://github.com/user-attachments/files/19649798/proxy_has_account.json)

Address: 5EbeYS2mBNszHcexgkCddZSSEfYP3QrM8goKaLF7ekoqvQnM

### Case:
1. go to https://spektr-dev.novasama-tech.org/
2. Add test data
3. Wait until proxy-worker will create a wallet
Expected result:
proxy-worker will be run and add proxy wallet to the app

Actual result:
Wallet won't be created, but database will be filled with proxies and proxyGroup data

## Environment
https://github.com/novasamatech/nova-spektr/commit/cf65d21a3b5cc2a370ccd8647e8b4bd9a7715179

## Additional info

Last changes for that code was done in that PR:
https://github.com/novasamatech/nova-spektr/pull/3130/files

In debug we found proxy and proxied accounts:

Image

But wallet won't be created:

Image

### PR DESCRIPTION
**Pull request by sokolova-an**
## Related Issues
Closes #3529

## Screenshots/Recordings
image

### CODE REVIEW

File: src/renderer/domains/network/identity/store.ts [hunk 1]
```diff
@@ -64,8 +64,12 @@ const requestFx = attach({
 
 const requestWithRetryFx = createEffect<Omit<FetchParams, 'api'>, Record<AccountId, AccountIdentity>>(
   ({ chainId, accounts }) => {
-    const binded = scopeBind(requestFx, { safe: true });
-    return fetchPool.call(() => binded({ chainId, accounts }));
+    try {
+      const binded = scopeBind(requestFx, { safe: true });
```
Comment (tuul-wq) [inline src/renderer/domains/network/identity/store.ts]: `bind` is irregular verb > `bind | bound | bound`
```suggestion
      const boundRequest = scopeBind(requestFx, { safe: true });
```

File: src/renderer/features/proxies/model/proxies-model.ts [hunk 2]
```diff
@@ -117,6 +122,19 @@ const fetchProxiesFx = createEffect(
     const proxyUrl =
       networkUtils.isPureProxySupported(chain.options) && chain.externalApi?.[ExternalType.PROXY]?.[0]?.url;
 
+    if (proxiedAccountsToAdd.length) {
+      const bindedRequestIdentities = scopeBind(requestIdentitiesFx, { safe: true });
```
Comment (tuul-wq) [inline src/renderer/features/proxies/model/proxies-model.ts]:
```suggestion
      const boundRequestIdentities = scopeBind(requestIdentitiesFx, { safe: true });
```

File: src/renderer/features/proxies/model/proxies-model.ts [hunk 3]
```diff
@@ -117,6 +122,19 @@ const fetchProxiesFx = createEffect(
...
+
+      await withTimeout(
+        bindedRequestIdentities({
+          accounts: proxiedAccountsToAdd.map((x) => x.accountId),
```
Comment (tuul-wq) [inline src/renderer/features/proxies/model/proxies-model.ts]:
```suggestion
          accounts: proxiedAccountsToAdd.map((a) => a.accountId),
```

**Review by tuul-wq — APPROVED** [review]
A few comments
