### PR TITLE
fix(portfolio): assets list & balances

### LINKED ISSUE #3389: Portfolio view. There is nothing to show for PJS extension wallet
## Description

When user select pjs extension - there is nothing on Portfolio view

Example:

https://github.com/user-attachments/assets/38686630-79d0-4215-8255-6d7e66cf6302

## Test data

[spektr-database (1).json](https://github.com/user-attachments/files/19363276/spektr-database.1.json)

## Steps to Reproduce

1. Import test database
2. Open Portfolio view

## Expected Behavior

Shows balances

## Actual Behavior

Empty page state

### PR DESCRIPTION
**Pull request by aaa123eee**
## Description

Fix issue with incorrect assets presentation

## Related Issues

closes #3389

## Changes Made

- use the most recent logic for network matching
- handle nullable balances
- fix alignment issues

## Screenshots/Recordings

**before**
image

**after**
image

### CODE REVIEW

File: src/renderer/features/assets/AssetsPortfolioView/model/portfolio-model.ts [hunk 1]
```diff
@@ -1,26 +1,33 @@
...
 const hideZeroBalancesChanged = createEvent<boolean>();
 const queryChanged = createEvent<string>();
 const transferStarted = createEvent<AssetByChains>();
 const receiveStarted = createEvent<AssetByChains>();
 
 const $hideZeroBalances = restore(hideZeroBalancesChanged, false);
-const $accounts = restore<Account[]>(accountsChanged, []);
+const $accounts = combine(
+  {
+    accountsList: accounts.$list,
```
Comment (johnthecat) [inline src/renderer/features/assets/AssetsPortfolioView/model/portfolio-model.ts]: U can use walletSelect.$selectedAccounts here

**Review by johnthecat — APPROVED** [review]
