### PR TITLE
Display account name in flexible multisig wallet details

### LINKED ISSUE #4638: Flex multisig wallet details. Regular multisig reference shows address instead of custom name
## Description

In the wallet details modal of a flex multisig, the reference to its underlying regular multisig is always displayed using its address, even when a custom name for that multisig exists in the local database.

## Steps to Reproduce

1. Import attached database
2. Open flex multisig 'flex sm/5' wallet details
3. Observe the reference to the underlying multisig (via...)

## Expected Behavior

- If a custom name exists → display the custom name (truncated if too long).
- If no custom name exists → display the truncated address.

## Actual Behavior

The reference always displays the address, ignoring the custom name.

## Screenshots

Image

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
In the wallet details modal of a flex multisig, the reference to its underlying regular multisig is always displayed using its address, even when a custom name for that multisig exists in the local database.

## Related Issues
Closes #4638

## Changes Made
Display account name in flexible multisig wallet details

## Screenshots/Recordings
Снимок экрана 2025-09-17 в 14 05 14

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

**Review by aaa123eee — APPROVED** [review]

File: src/renderer/features/wallet-details/ui/wallets/FlexibleWalletDetails.tsx [hunk 1]
```diff
@@ -222,7 +222,14 @@ export const FlexibleWalletDetails = ({ wallet, onClose }: Props) => {
...
                 <FootnoteText>{t('walletDetails.common.proxyVia')}</FootnoteText>
                 <WalletIcon type={WalletType.MULTISIG} size={16} />
-                <Account accountId={multisigAccount.multisigAccountId} chain={chain} hideIcon variant="short" />
+                <Account
+                  accountId={multisigAccount.multisigAccountId}
+                  chain={chain}
+                  hideIcon
+                  hideAddress
+                  variant="short"
+                  title={multisigAccount.name}
```
Comment (johnthecat) [inline src/renderer/features/wallet-details/ui/wallets/FlexibleWalletDetails.tsx]: If I understand correctly, that's not an actual fix for the issue. Name will always duplicate wallet name. @MaliDo Can you clarify what name do you expect here?

Comment (MaliDo) [reply src/renderer/features/wallet-details/ui/wallets/FlexibleWalletDetails.tsx]: I mean the name a user defines for a multisig in the list of wallets. This custom name, defined manually, should appear in the wallets details modal of its pure proxy / flex multisig.

Comment (MaliDo) [reply src/renderer/features/wallet-details/ui/wallets/FlexibleWalletDetails.tsx]: This one:
Снимок экрана 2025-09-17 в 14 51 58

Comment (Yanaty) [reply src/renderer/features/wallet-details/ui/wallets/FlexibleWalletDetails.tsx]: fixed

**Review by johnthecat — APPROVED** [review]
