### PR TITLE
Fix: Xcm destination

### LINKED ISSUE #1660: Multisig. Proxy operations. Wrong operation data for cross-chain transfer.
## Description
Multisig Operation with proxy and cross-chain transfer is parsed wrong.
Sender should be - proxy address
Recipient - should transfer to ss58 address

## Steps to Reproduce

1. Create multisig.asmulti(proxy.proxy(Xtokens.Transfer_multiasset()))
3. Go to Multisig Operations

## Expected Behavior
Parsed all data from transaction

## Actual Behavior
Wrong sender and recipient

## Environment
https://github.com/novasamatech/nova-spektr/commit/ca555571245870d28cad4cd0c3ea42cb09c3d98d

Screenshot 2024-04-09 at 17 54 55

Actually, sender is - 23dmKAum68Zw8e5P5x8sDo9EKJRFgkUBLHMDndPXenGNhhGE

operation:
https://acala.subscan.io/extrinsic/5937547-2

### PR DESCRIPTION
**Pull request by tuul-wq**
- Updated data parsing

closes #1660

### CODE REVIEW

File: src/renderer/pages/Operations/common/utils.ts [hunk 1]
```diff
@@ -266,14 +267,20 @@ export const getSignatoryAccounts = (
...
 
-export const getDestination = (tx: MultisigTransaction): Address | undefined => {
+export const getDestination = (
+  tx: MultisigTransaction,
+  chains: Record<ChainId, Chain>,
+  destinationChain?: ChainId,
+): Address | undefined => {
   if (!tx.transaction) return undefined;
 
+  const addressPrefix = (destinationChain ? chains[destinationChain] : chains[tx.transaction.chainId])?.addressPrefix;
```
Comment (Asmadek) [inline src/renderer/pages/Operations/common/utils.ts]: Maybe better to create variable for `(destinationChain ? chains[destinationChain] : chains[tx.transaction.chainId])` for better readability?

**Review by Asmadek — APPROVED** [review]

**Review by sokolova-an — APPROVED** [review]
