### PR TITLE
fix: redirect to operations page

### LINKED ISSUE #2229: Governance. Delegate. Multisig can't delegate due to broken GUI
## Description

"Add delegation on" modal window run out of screen, which makes delegation from multisig - impossible

Screenshot 2024-08-28 at 11 19 42

## Steps to Reproduce

1. Create Multisig wallet
2. Go to Governance page
3. Click Add delegation
4. Select any delegator and choose tracks

## Expected Behavior
Modal window fit the page or can be scrolled down

## Actual Behavior
Broken GUI which blocks the flow

## Environment
https://github.com/novasamatech/nova-spektr/commit/f7a2692393f448f894937ac31d2eb51284844ed6

### LINKED ISSUE #2231: Governance. Multisig. Does not lead to the Operations page after create the multisig operation
## Description
When user add multisig operation he will stay at the same state, but he should to go to the Operations page

https://github.com/user-attachments/assets/3977efe9-d0e2-4dbc-a285-808d26e8ee3b

## Environment
https://github.com/novasamatech/nova-spektr/commit/f7a2692393f448f894937ac31d2eb51284844ed6

### PR DESCRIPTION
**Pull request by Asmadek**
refactor: close operation result modal 
fix: redirect if multisig operation successfully created
fix: confirm screen for multisig delegate

### CODE REVIEW

File: src/renderer/widgets/VoteModal/aggregates/voteModal.ts [hunk 1]
```diff
@@ -202,6 +207,23 @@ sample({
   target: votingAggregate.events.requestVoting,
 });
 
+sample({
+  clock: voteConfirmModel.events.submitFinished,
+  source: {
+    wallet: walletModel.$activeWallet,
```
Comment (johnthecat) [inline src/renderer/widgets/VoteModal/aggregates/voteModal.ts]: use `transaction.$isMultisig` instead

**Review by johnthecat — CHANGES_REQUESTED** [review]

**Review by johnthecat — APPROVED** [review]

**Review by sokolova-an — APPROVED** [review]
