### PR TITLE
fix: polkadot vault file uploads

### LINKED ISSUE #4959: Polkadot Vault. Fix template import \ export flow
Since we have updated key management, new version for generated export file does not match with an old one template:

v1 Template:
```
0x387aed21a43ed189c8f0d14aab6f05f715f1adfe670efa6090208ddd4efe991f: #vault public address
  0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3: #polkadot genesis hash
    - key:
        derivation_path: "//polkadot"
        type: "main"
    - key:
        derivation_path: "//polkadot//pub"
        type: "pub"
  0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe: #kusama genesis hash
    - key:
        derivation_path: "//kusama"
        type: "main"
    - key:
        derivation_path: "//kusama//staking"
        type: "staking"
        sharded: 50
version: 1
```

Generated file:
```
version: 1
public address: 0x4a77d2656142fca2d1e6cbb9ee42e00e2518cfab216c15b1352dfad75c20b360
genesis: 0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3
//polkadot: Main [main]
//polkadot//pub: //polkadot//pub [custom]
genesis: 0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe
//kusama: //kusama [custom]
genesis: 0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e
//westend: //westend [custom]
```

There is some problems:
1. Generated file does not match with template
2. Template can't be used for adding a new keys
3. sharded param not read and not generated keys

### LINKED ISSUE #4961: Polkadot Vault. Update keys via Import flow won't update wallet details until reload the app
## Description

When user import their keys via template - it won't update the UI until reload the whole app.

Example:

https://github.com/user-attachments/assets/17ca3a10-d802-4d2b-8b60-cd56278b8e10

### PR DESCRIPTION
**Pull request by savvyer**
## Description
Fixes derivations import from file of both existing formats: yaml and plain text.

## Related Issues
Closes #4959
Closes [#4961](https://github.com/novasamatech/nova-spektr/issues/4961)

## Changes Made
- Ignore `type` and `name` fields from imported file, since we don't use them anymore
- Vault wallet accounts list failed to update because file import module return new keys + existing ones, we expect only new ones.

## Screenshots/Recordings
Screenshot 2025-10-29 at 5 28 49 PM

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [x] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [x] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/wallets/ImportKeys/lib/import-keys-utils.ts [hunk 1]
```diff
@@ -46,7 +47,7 @@ export const importKeysUtils = {
   getErrorsText,
 };
 
-function isFileStructureValid(result: unknown): result is ParsedImportFile {
+function isYamlStructureValid(result: unknown): result is ParsedImportFile {
```
Comment (johnthecat) [inline src/renderer/features/wallets/ImportKeys/lib/import-keys-utils.ts:50]: Maybe it's easier to write zod schema for this validation?

**Review by johnthecat — APPROVED** [review]

**Review by stepanLav — APPROVED** [review]

File: src/renderer/features/wallets/ImportKeys/lib/import-keys-utils.ts (hunk 1 above)
Comment (savvyer) [reply src/renderer/features/wallets/ImportKeys/lib/import-keys-utils.ts:50]: Could be, but I didn't touch original function
