### PR TITLE
fix: multiframe qr code check

### LINKED ISSUE #3748: Polkadot Vault. Can't add PV wallet, QR can't be scanned
## Description

Image

### PR DESCRIPTION
**Pull request by Yanaty**
## Description
Fixed multiframe QR code processing issue in Vault Reader component. 
Previously, when scanning an incorrect multiframe QR code, nothing happened.

## Related Issues
Closes #3748

## Changes Made
1. The bug was that the QR code contained more than 1 frame and due to the check nothing happened.
2. Removed blocking check if (resultMetadata.length > 1) return; in VaultQrReader decodeFrame function.
3. Added proper metadata validation to handle QR codes without metadata gracefully.

## Screenshots/Recordings
Снимок экрана 2025-09-04 в 12 26 31

### CODE REVIEW

File: src/renderer/entities/transaction/ui/QrCode/QrReader/VaultQrReader.tsx [hunk 1]
```diff
@@ -195,7 +195,10 @@ export const VaultQrReader = ({
       if (isSimpleQr) return;
 
       const resultMetadata = result.getResultMetadata().get(FRAME_KEY) as Uint8Array[];
-      if (resultMetadata.length > 1) return;
+      if (!resultMetadata || resultMetadata.length === 0) {
```
Comment (aaa123eee) [inline src/renderer/entities/transaction/ui/QrCode/QrReader/VaultQrReader.tsx]:
```suggestion
      if (!resultMetadata?.length) {
```

**Review by aaa123eee — APPROVED** [review]
🎉🎉🎉

File: src/renderer/entities/transaction/ui/QrCode/QrReader/VaultQrReader.tsx (hunk 1 above)
Comment (Yanaty) [reply src/renderer/entities/transaction/ui/QrCode/QrReader/VaultQrReader.tsx]: done )

**Review by cuteWarmFrog — APPROVED** [review]
