### PR TITLE
fix: comments after testing evm 

### LINKED ISSUE #1534: EVM transfers. XCM with "myself" button add EVM address, instead of chain address
## Description
When user try to make XCM in EVM chains (Moonbeam, Moonriver), Myself button will paste EVM address instead of chain Address

## Steps to Reproduce

1. Go to Assets page
2. Create transfer GLMR in Moonbeam
3. Select destination network as Acala
4. Click Myself

## Expected Behavior
Paste Acala address

## Actual Behavior
Paste Moonbeam address

## Environment
https://github.com/novasamatech/nova-spektr/commit/169243c16d6a18dd55fe9b981e5688a82af0498c

## Screenshots
Screenshot 2024-03-04 at 13 40 33

### LINKED ISSUE #1535: Assets page. Search works wrong, can't find Moonbeam network by name
## Description
User can't find Moonbeam network by name.

## Steps to Reproduce

1. Go to Assets page
2. In search field enter "Moonbeam"

## Expected Behavior
Show Moonbeam network

## Actual Behavior
Show only Moonbeam tokens

## Environment
https://github.com/novasamatech/nova-spektr/commit/169243c16d6a18dd55fe9b981e5688a82af0498c

## Screenshots
Screenshot 2024-03-04 at 13 45 54
Screenshot 2024-03-04 at 13 46 01

### LINKED ISSUE #1540: EVM Chains. Wrong crypto type for Single account PolkadotVault wallet.
## Description
Creating Single Polkadot Vault wallet lead to wrong crypto type for Moonbeam/Moonriver chains

## Steps to Reproduce

1. Add Polkadot Vault wallet
Screenshot 2024-03-05 at 13 06 21

2. Check created accounts

## Expected Behavior
Create accounts with appropriate account  and crypto type

## Actual Behavior
Create substrate accounts with sr25519 for Moonbeam and Moonriver
Screenshot 2024-03-05 at 13 07 59

### LINKED ISSUE #1549: Multi-chain multisig. Creation with EVM addresses lead to wrong multisig
## Description
When user create multi-chain multisig with EVM accounts - it will create wrong multisig account.

## Steps to Reproduce

1. User has 2 wallets with EVM accounts
2. Go to multisig creation flow
3. Select 2 wallets with EVM addreses
4. Create multisig wallet

## Expected Behavior
?
Multisig with different addresses for EVM and Substrate? Or ban to create that type of multisigs

## Actual Behavior
Was created broken multisig
Screenshot 2024-03-06 at 21 46 46

Screenshot 2024-03-06 at 21 46 52

### LINKED ISSUE #1551: Multisig. Click on menu item after multisig сreation is not available.
## Description
Immediatelly after creating multisig - the button from the menu is not available to click.

## Steps to Reproduce

1. Create multisig
2. Open wallet management
3. Try to click on "Multisig"

## Expected Behavior
Open Multisig creation menu

## Actual Behavior
Do nothing
Screenshot 2024-03-06 at 22 47 44

## Environment
https://github.com/novasamatech/nova-spektr/commit/db76ba3812a6bf3a4b3828f3aa06ba7fdfe93770

### PR DESCRIPTION
**Pull request by Asmadek**
fix: hide myself button if crypto type doesn't match
fix: exclude evm accounts from multichain multisig creation
fix: open create multisig modal after create multisig
fix: correct accounts list for wallet details (hide evm chains for substrate accounts)
fix: crypto type check (base on wallet type)
fix: show moonbeam assets on search (search on asset name, not only symbol)

### CODE REVIEW

File: src/renderer/pages/Assets/Assets/components/AssetsList/AssetsList.tsx [hunk 1]
```diff
@@ -65,7 +65,7 @@ export const AssetsList = () => {
   }, [balances, assetsPrices]);
 
   const searchSymbolOnly = sortedChains.some((chain) => {
-    return chain.assets.some((asset) => includes(asset.symbol, query));
+    return chain.assets.some((asset) => includes(asset.symbol, query) || includes(asset.name, query));
```
Comment (tuul-wq) [inline src/renderer/pages/Assets/Assets/components/AssetsList/AssetsList.tsx]: `isStringsMatchQuery` might be a better option

File: src/renderer/pages/Onboarding/Vault/ManageSingleshard/ManageSingleshard.tsx [hunk 2]
```diff
@@ -46,7 +46,11 @@ export const ManageSingleshard = ({ seedInfo, onBack, onClose, onComplete }: Pro
   useEffect(() => {
     const chainList = Object.values(allChains);
 
-    setChains(isEthereumBased ? chainList.filter((c) => networkUtils.isEthereumBased(c.options)) : chainList);
+    setChains(
+      chainList.filter((c) =>
+        isEthereumBased ? networkUtils.isEthereumBased(c.options) : !networkUtils.isEthereumBased(c.options),
+      ),
+    );
```
Comment (tuul-wq) [inline src/renderer/pages/Onboarding/Vault/ManageSingleshard/ManageSingleshard.tsx]:
```suggestion
const filteredChains = chainList.filter((c) => {
  return isEthereumBased ? networkUtils.isEthereumBased(c.options) : !networkUtils.isEthereumBased(c.options);
});
setChains(filteredChains);
```

File: src/renderer/widgets/SendAssetModal/ui/components/TransferForm.tsx [hunk 3]
```diff
@@ -23,6 +23,7 @@ import type { Chain, Account, MultisigAccount, Asset, Address, ChainId, HexStrin
 import { accountUtils } from '@entities/wallet';
 import { balanceModel, balanceUtils } from '@entities/balance';
 import { sendAssetModel } from '../../model/send-asset';
+import { networkModel, networkUtils } from '@/src/renderer/entities/network';
```
Comment (tuul-wq) [inline src/renderer/widgets/SendAssetModal/ui/components/TransferForm.tsx]:
```suggestion
import { networkModel, networkUtils } from '@entities/network';
```

**Review by tuul-wq — COMMENTED** [review]
Few comments

**Review by tuul-wq — APPROVED** [review]
