### PR TITLE
fix: governance voting

### LINKED ISSUE #4750: Governance. Vote flow. Is not reset previous voting while make revote
## Description

When user votes multiple times for the referenda, it may keep previous step data on voting page, while creating extrinsic for revote and use previous vote instead of selected parameters.

## Example:

In example I voted AYE, then reject operation, go to governance and try to revote on Abstain, but it creates AYE again.

https://github.com/user-attachments/assets/ec83583b-2b58-4f3e-ae2e-377fbd27155e

## Steps to Reproduce

1. User go to Governance flow
2. Votes for referenda AYE
3. Move to another page
4. Return to governance
5. Try to Revote and select another voting direction

## Expected Behavior

Operation always creates with selected voting direction

## Actual Behavior

Is used previous voting data

### PR DESCRIPTION
**Pull request by cuteWarmFrog**
## Description
Fix sync (blockNumber + ext_index) + vote calldata decoding + default vote if there is an error

## Related Issues
Closes #4750 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have tested the changes and verified the happy path works as expected
- [ ] I have provided screenshot of the working feature (if applicable)
- [x] I have provided description of the changes and any additional context that might help reviewers perform more accurate review
- [ ] I have added tests that cover the base logic (if applicable)
- [x] My code follows the project's coding standards and style guidelines

### CODE REVIEW

File: src/renderer/features/account-sync/model/sync.ts [hunk 1]
```diff
@@ -275,6 +277,7 @@ sample({
         });
       }
     }
+    console.log('proxiesToAdd', proxiesToAdd);
```
Comment (aaa123eee) [inline src/renderer/features/account-sync/model/sync.ts]:
```suggestion
```

File: src/renderer/features/multisig-operations/model/approve-model.ts [hunk 2]
```diff
@@ -108,13 +108,16 @@ type ExtrinsicSigningPayload = {
...
   try {
-    return await transactionService.getExtrinsicWeight(extrinsic);
-  } catch {
+    const weight = await transactionService.getTransactionWeight(
+      { type: 'encoded', callData: operation.callData },
+      api,
+    );
+    return weight;
+  } catch (error) {
+    console.log(error);
```
Comment (aaa123eee) [inline src/renderer/features/multisig-operations/model/approve-model.ts]:
```suggestion
```

**Review by aaa123eee — APPROVED** [review]

**Review by valentunn — APPROVED** [review]
