### PR TITLE
fix: clean up multisigs after deleting signatories

### LINKED ISSUE #3727: Remove complex wallets, when connected wallet was removed
We need to remove multisig and proxy wallets, when user remove connected wallets.

Remove multisig wallets:
- When any wallet was removed from the app (including proxied wallets) multisigs should be checked and removed if there is no signatories available in the app any more
- When proxy was removed by proxy-worker (for example remove access to the wallet) connected multisig should be removed too

Remove proxied wallets:
- When user delete wallet, connected to the proxy wallet, proxy should be removed too

### PR DESCRIPTION
**Pull request by sokolova-an**
## Description
Delete multisigs and proxies wallets related to the deleted wallet
## Related Issues
Closes #3727

### CODE REVIEW

File: src/renderer/features/wallets/ForgetWallet/model/forget-wallet-model.ts [hunk 1]
```diff
@@ -148,7 +173,7 @@ sample({
 
 // TODO this connection is dirty, we should decouple wallet delete logic and proxy manipulation.
 sample({
-  clock: [walletModel.events.walletRemovedSuccess, walletModel.events.walletHiddenSuccess],
+  clock: [walletModel.events.walletRemovedSuccess, walletModel.events.walletHiddenSuccess], //
```
Comment (savvyer) [inline src/renderer/features/wallets/ForgetWallet/model/forget-wallet-model.ts]: typo?

**Review by savvyer — APPROVED** [review]
looks good

**Review by johnthecat — APPROVED** [review]
