### PR TITLE
fix(cas): identities for all nodes

### LINKED ISSUE #4043: CAS. Request identities for signatories
Image

the signatory `15cf` has an identity which is not represented on the graph

### PR DESCRIPTION
**Pull request by aaa123eee**
## Description

Improve identity management

## Related Issues

closes #4043

## Changes Made

- Request identities for children nodes
- Handle `""` name correctly
- Avoid repetitions by using `accountId`

## Screenshots/Recordings

image

### CODE REVIEW

File: src/renderer/features/accounts-structure/model/accountsStructureModel.ts [hunk 1]
```diff
@@ -167,10 +167,13 @@ sample({
     chain: $selectedChain,
     graph: $graph,
   }),
-  filter: ({ chain, graph }) => !!chain && !!graph && graph.size > 0,
+  filter: ({ chain, graph }) => !!chain && !!graph,
```
Comment (savvyer) [inline src/renderer/features/accounts-structure/model/accountsStructureModel.ts]: Maybe we standardize usage of nonNullable?

**Review by savvyer — APPROVED** [review]
