### PR TITLE
fix: flex alerts and ui

### LINKED ISSUE #4232: Flexible multisig. Alert about already created multisig

### PR DESCRIPTION
**Pull request by sokolova-an**
## Description
Added creation flex multisig with an existing multisig;
Fixed minor ui  
## Related Issues
Closes #4232

### CODE REVIEW

File: src/renderer/entities/wallet/lib/account-utils.ts [hunk 1]
```diff
@@ -111,6 +112,10 @@ function isFlexibleMultisigAccount(account: Partial<AnyAccount>): account is Fle
   return 'accountType' in account && account.accountType === AccountType.FLEX_MULTISIG;
 }
 
+function isAnyMultisigAccount(account: Partial<AnyAccount>): account is MultisigAccount {
```
Comment (johnthecat) [inline src/renderer/entities/wallet/lib/account-utils.ts]: po kaifu

**Review by johnthecat — APPROVED** [review]
