### PR TITLE
fix: correct voting flow for proxied accounts

### LINKED ISSUE #2283: Governance. Vote. Vote via Proxy is broken
## Description
Revote/Vote flow is broken via Proxy

https://github.com/user-attachments/assets/1feaf45d-5371-4b15-b297-781064e449bb

## Steps to Reproduce

1. Add proxy for address_A via address_B
2. Select proxy
3. Try to vote

## Expected Behavior
Successfully voted

## Actual Behavior
Can't vote as a proxy

## Environment
https://github.com/novasamatech/nova-spektr/commit/5394425bbb2cb4cdcd9f2382363ad6e9393e9f1e

[accounts.json](https://github.com/user-attachments/files/16862776/accounts.json)
[wallets.json](https://github.com/user-attachments/files/16862777/wallets.json)

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #2283

### CODE REVIEW

File: src/renderer/features/operations/OperationsConfirm/Referendum/RemoveVote/ui/Confirmation.tsx [hunk 1]
```diff
@@ -40,6 +40,8 @@ export const Confirmation = ({ id = 0, secondaryActionButton, hideSignButton, on
   useGate(locksPeriodsAggregate.gates.flow, { chain: confirm?.meta.chain });
   useGate(locksAggregate.gates.flow, { chain: confirm?.meta.chain });
 
+  console.log({ confirm });
```
Comment (Asmadek) [inline src/renderer/features/operations/OperationsConfirm/Referendum/RemoveVote/ui/Confirmation.tsx]: remove

File: src/renderer/features/operations/OperationsConfirm/lib/createTransactionConfirmStore.ts [hunk 2]
```diff
@@ -46,36 +50,56 @@ export const createTransactionConfirmStore = <Input extends ConfirmInfo>({ $wall
...
+      const initiatorWallet = walletUtils.getWalletFilteredAccounts(wallets, {
+        walletFn: (wallet) => !isProxyTransaction(wrappedTx) || walletUtils.isProxied(wallet),
+        accountFn: (account) => initiatorAccount.accountId === account.accountId,
+      });
+      if (!initiatorWallet) return acc;
+
+      const signerAccount = walletUtils.getAccountBy(
+        wallets,
+        (account, wallet) =>
+          !walletUtils.isProxied(wallet) &&
```
Comment (Asmadek) [inline src/renderer/features/operations/OperationsConfirm/lib/createTransactionConfirmStore.ts]: I think `!walletUtils.isWatchOnly(wallet)` should be added too

**Review by Asmadek — APPROVED** [review]
