### PR TITLE
fix: correct multisig other signatories

### LINKED ISSUE #4071: CAS. Multisig. Sender in signatories
## Description

Sender added in signatories for multisig operations

Image

### PR DESCRIPTION
**Pull request by johnthecat**
Closes #4071

### CODE REVIEW

File: src/renderer/domains/network/transaction/service.ts [hunk 1]
```diff
@@ -40,8 +40,13 @@ function isDecodedTransaction(transaction: AnyTransaction): transaction is AnyDe
...
 async function wrapTransaction(transaction: EncodedTransaction, route: AnyAccount[], api: ApiPromise) {
   let wrapped: AnyTransaction = transaction;
-  for (const account of Array.from(route)) {
-    const result: AnyTransaction | null = await wrapTransactionTransformer(wrapped, { account, api });
+  const signatory = route.at(-1);
+  const path = route.slice(0, -1);
+
+  assert(signatory, 'Signatory not found in route');
+
+  for (const account of Array.from(path)) {
```
Comment (savvyer) [inline src/renderer/domains/network/transaction/service.ts]: hmm. isn't path an array already?

**Review by savvyer — APPROVED** [review]
