### PR TITLE
Fix: add Explorer icon and Popover

### LINKED ISSUE #2094: Governance. Delegates. There is no way to copy delegate address.
## Description
When user open Delegate page - there is no way to copy delegate address if it came from GitHub

## Steps to Reproduce

1. Go to Governance page
2. Click "Add delegate"
3. Click on any Delegate with off-chain data

## Expected Behavior

There is an info button which leads to explorers and provide an address

image
https://www.figma.com/design/4vjREBpvZK7M3m1GaoVptq/OpenGov-delegations?node-id=278-363334&t=WtpLmGDPS9zTE3fa-4

## Actual Behavior

There is no info button
Screenshot 2024-08-14 at 11 20 32

## Environment
https://github.com/novasamatech/nova-spektr/commit/733af1a94c903c8ed3dde4fb4ce25bd01f02ff97

### PR DESCRIPTION
**Pull request by Tbaut**
closes #2094 

image

### CODE REVIEW

File: src/renderer/features/governance/components/Delegations/DelegateTitle.tsx [hunk 1]
```diff
@@ -10,5 +11,20 @@ type Props = {
 export const DelegateTitle = ({ delegate, className }: Props) => {
   const delegateTitle = delegate.name || <Truncate ellipsis="..." start={4} end={4} text={delegate.accountId} />;
 
-  return <HeadlineText className={cnTw('w-full', className)}>{delegateTitle}</HeadlineText>;
+  return (
+    <HeadlineText className={cnTw('w-full', className)}>
+      <div className="inline-flex items-center">
```
Comment (johnthecat) [inline src/renderer/features/governance/components/Delegations/DelegateTitle.tsx]: use span instead, div will throw error about incorrect nesting

File: src/renderer/features/governance/components/Delegations/DelegateTitle.tsx [hunk 2]
```diff
@@ -10,5 +11,20 @@ type Props = {
...
+        {delegateTitle}{' '}
+        {delegate.address && (
+          <span>
```
Comment (johnthecat) [inline src/renderer/features/governance/components/Delegations/DelegateTitle.tsx:19]: can you remove this span w/o breaking layout?

Comment (Tbaut) [reply src/renderer/features/governance/components/Delegations/DelegateTitle.tsx:19]: This component is tricky. Removing the span, even with a `display: inline-block` on the `ExplorersPopover` makes such changes
Before:
image

After:
image

**Review by johnthecat — APPROVED** [review]

**Review by sokolova-an — APPROVED** [review]
