### PR TITLE
fix: proxy groups removed from list

### LINKED ISSUE #1622: Empty delegated authorities tab for new created wallets.
## Description
When user add new wallet to his Spektr app - delegated authorities tab for this wallet will be empty until restart the app.

## Steps to Reproduce

1. Create wallet with some proxies in polkadot.js
2. Add this wallet to the Spektr
3. Open wallet details
4. Switch to Delegated authorities tab

## Expected Behavior
All delegated authorities is shown for new added wallets

## Actual Behavior
Empty delegated authorities tab

## Environment
https://github.com/novasamatech/nova-spektr/commit/432167ed6b6979d57bd411da75e199bf4d9e501a

## Attachments

<details>
  <summary>Example</summary>

https://github.com/novasamatech/nova-spektr/assets/40560660/33666394-a12b-4f57-ae12-82304ea91e0f

</details>

### PR DESCRIPTION
**Pull request by sokolova-an**

### CODE REVIEW

**Review by Asmadek — APPROVED** [review]

File: src/renderer/widgets/RemoveProxyModal/ui/RemoveProxy.tsx [hunk 1]
```diff
@@ -17,7 +17,6 @@ export const RemoveProxy = () => {
 
   const step = useUnit(removeProxyModel.$step);
   const chain = useUnit(removeProxyModel.$chain);
-  const isMultisig = useUnit(removeProxyModel.$isMultisig);
```
Comment (tuul-wq) [inline src/renderer/widgets/RemoveProxyModal/ui/RemoveProxy.tsx:20]: 👍

File: src/renderer/features/proxies/model/proxies-model.ts [hunk 2]
```diff
@@ -376,7 +376,6 @@ sample({
   target: spread({
     toAdd: proxyModel.events.proxyGroupsAdded,
     toUpdate: proxyModel.events.proxyGroupsUpdated,
-    toRemove: proxyModel.events.proxyGroupsRemoved,
```
Comment (tuul-wq) [inline src/renderer/features/proxies/model/proxies-model.ts:379]: I suppose we don't need `toRemove` inside most recent `reduce`

**Review by tuul-wq — APPROVED** [review]
